### ISSUE TITLE
The staging instance is running out of disk space - clean it up after a build

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#1003]
The staging instance is running out of disk space a couple of days after cleaning it up. We should automatically remove all the build outputs, except for the docker image and logs

**Comment by jkondrat** [comment]
@kkaczmarczyk The build is now outputting a single log file which can be found at ~/deployment/deployments
Could you please confirm?

**Comment by jkondrat** [comment]
@awalkowiak : since Krzysztof is OOO, could you please have a look?

**Comment by awalkowiak** [comment]
Yup, logs are there.
