### ISSUE TITLE
Daily Update on single record view is returning ALL daily updates, no datetime

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1004]
So two issues here:

Issue 1: Steps to reproduce:
* Create a new provider records
* Add a daily update
* Add a second daily update
* View that record's single-record view

Result:
ALL daily updates are returned

It seems the API returns all the results and the frontend displays all of them as well. It should only display the most recent, non-expired daily update. I'll leave it up to you whether this should be enforced at the API level of at the frontend.

Issue 2: Creation Datetime Not displayed for daily update

On the single record view, the creation datetime of the displayed daily update should be displayed next to the 'Daily Updates' heading as it is on the edit view

**Comment by abaranowska1** [comment]
@awalkowiak 
1. Split a text into two lines ( on smaller screens and mobile devices it doesn't look good )
![image](https://user-images.githubusercontent.com/61964176/82535528-43298800-9b47-11ea-85a9-b8657a9d38be.png)
2. The second issue, in my opinion, was resolved, I can see only last update, not all updates.
![up](https://user-images.githubusercontent.com/61964176/82536062-2e99bf80-9b48-11ea-80a8-90f3e3d1e0fc.gif)

**Comment by abaranowska1** [comment]
**Tested with success**
- Creation Datetime is displayed for Daily Update 
![image](https://user-images.githubusercontent.com/61964176/82546441-601a8700-9b58-11ea-94f8-d7c98d1a22bf.png)
- Only last update is visible 
![up](https://user-images.githubusercontent.com/61964176/82546711-d5865780-9b58-11ea-8104-f89b34a33e12.gif)
