### ISSUE TITLE
Hook up search in service provider view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1006]
This task's purpose is to make the search bar on mobile and desktop functional.

I believe the top "your records" should NOT be affected by the search i.e. all of your records should always show regardless of search/filter settings.

To start lets just have it search Org Name, Org Description, and Service Name by default. We will likely have which fields to search to be set by the user at some point - but this default will do for now.

We will also need to move the 'search' icon to the left side of the input, and then have an 'X' to clear the search on the right side when text is entered. Search action will be tied to enter/submit browser action. It would be good to set the input attributes accurately so that mobile keyboards recognize it as a search and changes the enter key accordingly.

**Comment by abaranowska1** [comment]
@jkondrat 
1. Plz delete one of this "x" 
![image](https://user-images.githubusercontent.com/61964176/82807232-a5f08b80-9e87-11ea-8bfe-875d040633ec.png)
2. On mobile devices, the placeholder is too long, maybe we can add "..." when it is going to the end of the field 
![image](https://user-images.githubusercontent.com/61964176/82807407-fd8ef700-9e87-11ea-95a4-d0f12516cbab.png)
![7C93D523-E4DD-4C8E-8E5C-3B3AB140512A](https://user-images.githubusercontent.com/61964176/82807513-2f07c280-9e88-11ea-93be-71efa0a41b13.jpg)

**Comment by abaranowska1** [comment]
**Tested with success**
**Verified cases:**

- one "x" was deleted
- "..." is added to the placeholder
-  the top "your records" are not affected by the search
-  search Org Name, Org Description, and Service Name by default.
-  'search' icon was moved to the left side of the input
-  'x' icon was added on the right side to clear the search

**Verified on:**

- Google Chrome v. 83.0.4103.61
- Firefox v. 76.0.1
- Mobile device 360 x 640
- iPhone X 375 x 812
