### ISSUE TITLE
Hook up Service Provider records to matching process on both record creation and update

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1009]
Service Provider records should run through the matching algorithm upon creation and edit.

We will not surface any information from these matches in the Service Provider view.

These matches should show up to the other partners in classic SN

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:**

- Service Provider records run through the matching algorithm upon creation and edit.
![image](https://user-images.githubusercontent.com/61964176/82642139-c1e8f880-9c0d-11ea-8871-795c3f7e1f73.png)
- We do not surface any information from these matches in the Service Provider view.
![image](https://user-images.githubusercontent.com/61964176/82642163-c8777000-9c0d-11ea-9c3b-d4d255095efe.png)
- These matches show up to the other partners in classic SN
![image](https://user-images.githubusercontent.com/61964176/82642130-be557180-9c0d-11ea-8784-922ff194f448.png)
