### ISSUE TITLE
Visually distinguish matches from Service Provider on classic SN view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1010]
In #1009, if a match exists in classic SN view - we should visually distinguish when a matching record is from a Service Provider record. The organization title should appear with a star next to it everywhere it's displayed.

**Comment by kdondziak** [comment]
@johnhbenetech How it should look. Our suggestions are:
- star icon: https://fontawesome.com/icons/star?style=solid
- asterisk '*'
- asterisk icon: https://fontawesome.com/icons/asterisk?style=solid

**Comment by johnhbenetech** [comment]
@kdondziak gold start icon

**Comment by kdondziak** [comment]
@johnhbenetech Regarding comparing view (all-record, multi-record) should I add start to org name in details? See picture below:
![image](https://user-images.githubusercontent.com/52406204/82679973-f11e5a80-9c4b-11ea-9b39-81fb7fc27b4b.png)

**Comment by kdondziak** [comment]
@johnhbenetech I think that star may by a little confusing. What do you think about adding tooltip?

**Comment by johnhbenetech** [comment]
@kdondziak What do you think about either of these? We can have tooltip that says "This record is maintained by the service provider".

![image](https://user-images.githubusercontent.com/12927553/82691565-bef90280-9c23-11ea-8175-c8b4cfdab9cd.png)

![image](https://user-images.githubusercontent.com/12927553/82692189-dedcf600-9c24-11ea-8c7d-4ce10284be18.png)

![image](https://user-images.githubusercontent.com/12927553/82693585-6a578680-9c27-11ea-9858-624db27d749c.png)

**Comment by johnhbenetech** [comment]
I'm leaning towards the checkbox personally

**Comment by kdondziak** [comment]
@johnhbenetech I think green icon with two people would be best.

**Comment by abaranowska1** [comment]
@kdondziak 
Few changes to the new icon will be needed : 
1. The new tooltip should be a little bit smaller on the home page and a little bigger and a few pixels higher in details view, in my opinion, it should be similar to the mock.
![image](https://user-images.githubusercontent.com/61964176/82821373-4a80c680-9ea4-11ea-8f77-0410868b48e6.png)
![image](https://user-images.githubusercontent.com/61964176/82821398-540a2e80-9ea4-11ea-8f71-595fa40004b0.png)
![image](https://user-images.githubusercontent.com/61964176/82821460-73a15700-9ea4-11ea-9baa-04a14b8ab66a.png)
2. I think we should move the icon before the Organization Name
![image](https://user-images.githubusercontent.com/61964176/82821575-a8ada980-9ea4-11ea-897a-d2d22b560821.png)
like here: 
![image](https://user-images.githubusercontent.com/61964176/82821671-c975ff00-9ea4-11ea-9987-90ad223fd5e4.png)

**Comment by abaranowska1** [comment]
**Tested with success**

Verified cases:
- Service Provider Organization are marked with a tooltip
- Visually distinguish is done when a matching record is from a Service Provider record
- UI issues were fixed 
![image](https://user-images.githubusercontent.com/61964176/82895893-482a7500-9f55-11ea-8333-f264f4093a33.png)

![image](https://user-images.githubusercontent.com/61964176/82895896-4bbdfc00-9f55-11ea-8f72-4813fe7f512b.png)

![Screenshot from 2020-05-26 12-41-54](https://user-images.githubusercontent.com/61964176/82895908-524c7380-9f55-11ea-8f57-fb5d3c0f9972.png)

Verified on:

- Google Chrome v. 83.0.4103.61
- Firefox v. 76.0.1
