### ISSUE TITLE
Adjust last updated by info on Service Provider records to reflect user first+last name

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1011]
Once #1012 is completed we should change the 'last updated by information' to display the following

1. First Name Last Name (if not null)
2. Email if names are null

In the case where names are available, hovering on the name should display the email in a tooltip

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on staging env

**Verified cases**
- Creating an organization as
-- user with first and/or last name
-- user without first/last name
- Checking for mail tooltip if name not provided

**Summary**
This feature works as expected.

**Attachment**
![sn 1011](https://user-images.githubusercontent.com/51324797/83019767-c8210f80-a027-11ea-9c06-112b508b5e3e.gif)
