### ISSUE TITLE
Add First/Last Name to user registration page

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1012]
I'm pretty sure the user model already supports this on the backend, so we should add these fields as a non-required fields on the registration page (is it a required field in the database?)

This will be used in #1011

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on staging env

**Verified cases**
- Registering a new user from the register page
- Registering a new user from the admin user management view
- Editing an existing account

**Summary**
First/Last name fields are added to all of the mentioned pages. I was able to register and edit accounts without interruptions.

**Attachments**
![sn 1012 1](https://user-images.githubusercontent.com/51324797/82899821-e4f01100-9f5b-11ea-91b3-3aab00e84c35.png)

![sn 1012 2](https://user-images.githubusercontent.com/51324797/82899827-e6213e00-9f5b-11ea-81ca-aa3aa117b038.png)

![sn 1012 3](https://user-images.githubusercontent.com/51324797/82899829-e6b9d480-9f5b-11ea-95f2-28f5e1352684.png)
