### ISSUE TITLE
Hook up account menu links on Service Provider view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1013]
Connect settings and password links on Service Provider view

**Comment by abaranowska1** [comment]
**Tested with success**

**Tested on:**
- Chrome Browser v. 81.0.4044.92
- Firefox v. 75.0

**Verified cases:** 
- Connect settings and password links on Service Provider view

![Peek 2020-05-21 12-58](https://user-images.githubusercontent.com/61964176/82554704-bc84a300-9b66-11ea-9a54-e0582ee255f4.gif)
