### ISSUE TITLE
Change button fonts on buttons in new/edit views to match fonts and camel case

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1014]
Buttons on new/edit pages should match the font used everywhere else. Should also not be uppercase but rather camel case i.e. Discard Changes

**Comment by abaranowska1** [comment]
**Tested with success**
- Button fonts on buttons in new/edit view is changed to camel case 
![image](https://user-images.githubusercontent.com/61964176/82910543-09071e80-9f6b-11ea-94e1-ebfbab52743b.png)
![image](https://user-images.githubusercontent.com/61964176/82910560-0efcff80-9f6b-11ea-8a5f-7b40549bc640.png)
![image](https://user-images.githubusercontent.com/61964176/82910575-13c1b380-9f6b-11ea-9789-d143c9da5c73.png)
