### ISSUE TITLE
UI issue when displaying long service names

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#1015]
I met UI issues with displaying long service names:

1. Once I met such view 
![image](https://user-images.githubusercontent.com/61964176/82537841-ff388200-9b4a-11ea-84a8-1a0c6939ebe9.png)
2. The same organization with a long Service Name.
![image](https://user-images.githubusercontent.com/61964176/82537960-3ad34c00-9b4b-11ea-88a3-663db121495c.png)
![image](https://user-images.githubusercontent.com/61964176/82537966-3eff6980-9b4b-11ea-8e53-7709f6b632c3.png)
![image](https://user-images.githubusercontent.com/61964176/82538045-67876380-9b4b-11ea-9523-125a31944727.png)
3. Still the same Organization but on mobile and smaller screens view:
![image](https://user-images.githubusercontent.com/61964176/82538284-d1a00880-9b4b-11ea-8a68-df5eb652f37d.png)
![image](https://user-images.githubusercontent.com/61964176/82538319-debcf780-9b4b-11ea-9c7e-61a8fafe02d3.png)
![image](https://user-images.githubusercontent.com/61964176/82539705-280e4680-9b4e-11ea-903e-a3d0bb92666c.png)

4. Service Details View - same organization with long service name. In my opinion it could be split into two lines
![image](https://user-images.githubusercontent.com/61964176/82539017-fe085480-9b4c-11ea-8537-fe8b29330c7f.png)

Tested on:
- Chrome Browser v. 81.0.4044.92
- Firefox v. 75.0
- Mobile device 360x640
- 13,3" 1024x768
- Real mobile iPhone X 375x812

**Comment by bognasoldev89** [comment]
@abaranowska1 I spotted this on staging env:

![Screenshot from 2020-05-27 14-32-32](https://user-images.githubusercontent.com/51324797/83023399-269cbc80-a02d-11ea-9b5d-641207816e66.png)

I don't think it looks good.

Chrome v80.0.3987.149
1920 x 1080

**Comment by abaranowska1** [comment]
@bognasoldev89 @jkondrat 
Verified on Google Chrome v. 83.0.4103.61
![image](https://user-images.githubusercontent.com/61964176/83024247-63b57e80-a02e-11ea-93d9-33e60013f8f4.png)

1. I found one thing on Single Record View : 
![image](https://user-images.githubusercontent.com/61964176/83024357-91022c80-a02e-11ea-93b5-23b403d0cca6.png)
![image](https://user-images.githubusercontent.com/61964176/83024615-f0603c80-a02e-11ea-95f8-058a7d0e20b9.png)
This service has more than 2 service types, plz add "+1,+5,+15" when is more than display
2. I'm not sure if it is related to your changes but buttons are smaller and "Load more" is not centered
![image](https://user-images.githubusercontent.com/61964176/83024962-20a7db00-a02f-11ea-8408-6dc7489fe565.png)
![image](https://user-images.githubusercontent.com/61964176/83025031-26052580-a02f-11ea-9685-7418277c0179.png)

**Comment by jkondrat** [comment]
@abaranowska1 : You're right, it turned out that buttons were using pills' css - I separated them

**Comment by abaranowska1** [comment]
**Tested with success**
- Long service names are displayed correctly
- Buttons are fixed
- "+..." feature is added to Single Record View
- UI looks good on Chrome, Firefox and mobile device
