### ISSUE TITLE
Add 'compare' section to the single record view

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#102]
See https://user-images.githubusercontent.com/12927553/48446723-9b681880-e75f-11e8-867b-4ffe6760ca4c.png
The section should contain all records that seem to be matched organizations. The list of matched organizations to compare could be visible in the section, as it shouldn't be too long. Each element should be a link to the side-by-side view (which should be done in a separate issue: https://github.com/benetech/ServiceNet/issues/113)

**Comment by kcissewski** [comment]
Tested with success.
