### ISSUE TITLE
'Unsaved updates' error on leaving edit page if changes not saved/discarded

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1025]
On new/edit view, if user attempts to navigate away from page with unsaved data, they should be prompted with alert.

"You have unsaved data, are you sure you want to leave?" 

Discard Changes/Save Changes

**Comment by jkondrat** [comment]
@johnhbenetech is it okay for the alert to have the standard "cancel" and "ok" options? I'm using the standard react-router's Prompt to show it, and it's only possible to customize the message - no callbacks or button names

**Comment by johnhbenetech** [comment]
@jkondrat yes that's fine

**Comment by abaranowska1** [comment]
**Tested with success**
- "You have unsaved data, are you sure you want to leave?" alert is displayed on new/edit view if the user attempts to navigate away from the page with unsaved data
![Selection_012](https://user-images.githubusercontent.com/61964176/83137063-ca976e00-a0e8-11ea-8e3c-d2237a400e7b.png)
![Selection_013](https://user-images.githubusercontent.com/61964176/83137064-cb300480-a0e8-11ea-83e3-b0cdf703b9d9.png)
- Alert has standard "Cancel", "Ok" options 
- It works also on mobile devices
