### ISSUE TITLE
Allow for reactivation of records

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1026]
A new option should appear under the user menu 'Deactivated Records'. It should bring the user to a simple page where it lists any deactivated records (org Name, last updated date, deactivated date) and then a button 'Activate'

Clicking activate should allow record to appear again on main view

**Comment by kdondziak** [comment]
@johnhbenetech On desktop link be there: 
![image](https://user-images.githubusercontent.com/52406204/82993837-85e4d780-a001-11ea-90dc-2fb62f9ed45f.png) And on mobile view in side menu. Am I right?

**Comment by johnhbenetech** [comment]
@kdondziak yes that's right. Let's use the font awesome clipboard-list icon

**Comment by abaranowska1** [comment]
@kdondziak I found a few minor issues:
1. After click "Activate" button nothing happened, I saw only 500 error in the console
![image](https://user-images.githubusercontent.com/61964176/83114567-687b4080-a0c9-11ea-9560-7116b83cae65.png)
![Peek 2020-05-28 09-35](https://user-images.githubusercontent.com/61964176/83114574-6ca75e00-a0c9-11ea-97c0-5d8012fb47d2.gif)
@johnhbenetech 
2. I noticed that Organizations from the Deactivation list are displayed in all records view, is it the expected result? 
![image](https://user-images.githubusercontent.com/61964176/83115469-af1d6a80-a0ca-11ea-9f45-6ba2e68db2be.png)
![image](https://user-images.githubusercontent.com/61964176/83115554-cf4d2980-a0ca-11ea-98d0-dfd0105df040.png)

**Comment by johnhbenetech** [comment]
Deactivated records should NOT show to other users.

**Comment by kdondziak** [comment]
@johnhbenetech On deactivated page, should there be any deactivated records even those that not belong to current user? If yes, then should user have ability to reactivate records that not belong to current user?

**Comment by johnhbenetech** [comment]
@kdondziak Only the logged in user's deactivated records should show.

Basically this flow allows a record creator to remobe a record for when they no longer want others to see it (and reactivate if they change their mind)

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:**
- A new option appears under the user menu 'Deactivated Records'
- After clicking 'Deactivated Records' it brings the user to a simple page where it lists any deactivated records (org Name, last updated date, deactivated date) and then a button 'Activate'
- Deactivated records are not shown to other users
- Only the logged in user's deactivated records are displayed

![Peek 2020-05-29 11-52](https://user-images.githubusercontent.com/61964176/83246882-0727a000-a1a3-11ea-8847-743570faab0d.gif)


**Verified on:**
- staging instance
- Ubuntu 18.04.4 OS
- mobile device 360x640
- Google Chrome Browser v. 83.0.4103.61
