### ISSUE TITLE
Filter choices should only list options with corresponding records

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1027]
Similar to on classic view, the filter options that populate (service type, zip county, etc) should only reflect options that actually exist in the record collection.

For instance, if a Service Provider record doesnt exist eith a location in Albany - Albany shouldnt appear in the filter dropdown

**Comment by abaranowska1** [comment]
@johnhbenetech @awalkowiak 
I have one doubt regarding filters. On the filtering feature, the user can choose one of the options available in the record collection. Now we have Silo, so shouldn't it be better for the user to see only options that actually exist in the silo?

**Comment by johnhbenetech** [comment]
@abaranowska1 yes that's correct, the options should reflect the records that user has access to

**Comment by abaranowska1** [comment]
**Tested with success**

- Users associated with the same silo see records from other users in their silo
- On the filters, we only have what is on the list of other providers from my silo. Also, only real data will be displayed
![Peek 2020-06-17 15-52](https://user-images.githubusercontent.com/61964176/84906701-934a2a80-b0b2-11ea-91c6-5eeeae9a32d1.gif)
