### ISSUE TITLE
Investigate issues with ShelterTech Job not creating locations

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1031]
Steps:

I was creating a new ServiceNet instance from scratch (empty database)

Upon starting I launched the ShelterTech data job and waited until it was complete. After the job completed, organization, services, etc were created - but locations were NOT created.

Please investigate what might have caused this and necessary remediations.

**Comment by kdondziak** [comment]
@johnhbenetech This is my guess but there is possibility that you haven't set GOOGLE_API_KEY

**Comment by johnhbenetech** [comment]
@kdondziak I believe I have. Other providers add their locations fine, just sheltertech doesn't work.

Also this isn't just the geocode results, but the actually Location entity doesn't get created

**Comment by jkondrat** [comment]
@johnhbenetech it turned out that the response from ShelterTech has changed - we now have a list of addresses instead of a single address

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on local env

**Verified cases**
- Firing ShelterTech update job on empty db

**Summary**
Location entity was populated after firing ShelterTech job on empty db

**Attachment**
![sn 1031](https://user-images.githubusercontent.com/51324797/83850055-a18e6300-a710-11ea-9cfc-bcb606c84a5a.png)
