### ISSUE TITLE
Research/recommend approaches for a multi tenant system

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1032]
Please split this out into related tasks as needed based on recommended approach.

Goal: Allow for creation of separate silos of the ServiceProvider view (for different regions as an example). 

* A user entity should be associated with a specific silo
* When a user creates/edits a record, it should be associated with the silo
* Any users on that silo should only see records from other users in their silo

* Admin users should be able to create new named silos, that can later be used to assign users

Future considerations:
* Is it possible to (automatically?) create registration pages that pre-associates that user to a specific silo? for example: servicenet.benetech.org/#/register?tenant=chicago

* If we ever wanted to create a public facing (read only) version of a silo's resources - is there anyway to (automatically?) create an endpoint for a silo, for example: chicago.servicenet.benetech.org/#/ or servicenet.benetech.org/#/chicago/

**Comment by kkaczmarczyk** [comment]
@johnhbenetech I've extracted 4 bullet points from the Goal as they are clear and I put them into #1034 and #1033. We can use this task for research on future considerations topics. In short: both are doable. We've also story-pointed all of the issues.
I might have messed up the order of priority in Up next column though - let me know or feel free to change the priorities
