### ISSUE TITLE
Allow for creation of separate silos of the ServiceProvider view (for different regions as an example).

### ISSUE THREAD

**Issue by kkaczmarczyk** [benetech/ServiceNet#1033]
* A user entity should be associated with a specific silo
* Admin users should be able to create new named silos, that can later be used to assign users

dev note: consider using jhipster auto-generated views

**Comment by abaranowska1** [comment]
@kdondziak 
Please verify and fix these cases:

1. Missing translations in Silo Entity: 
Create, Update, Delete 

![image](https://user-images.githubusercontent.com/61964176/84007906-58891980-a971-11ea-9356-2132d40f17d6.png)
![image](https://user-images.githubusercontent.com/61964176/84007916-5b840a00-a971-11ea-9e87-ac2a6fc52852.png)e
![image](https://user-images.githubusercontent.com/61964176/84007928-5fb02780-a971-11ea-9659-777e99090a0c.png)

2. After removing the silo we are moving to the HomePage, but in the other Entity's we stay on the opened Entity page.
![image](https://user-images.githubusercontent.com/61964176/84008345-0a284a80-a972-11ea-804a-5270ef5bb6cf.png)

I checked also assigning users to the Silo and here from my side all works fine. For example user: **provider** and user: **bognaprov** are in the same silo. Both users have access to see records only from the same silo.
![image](https://user-images.githubusercontent.com/61964176/84009179-31334c00-a973-11ea-901d-f997babe0c60.png)
![image](https://user-images.githubusercontent.com/61964176/84009201-37c1c380-a973-11ea-9f30-42593ad4910c.png)

**Comment by abaranowska1** [comment]
**Tested with success**

- Missing translations in Silo Entity: Create, Update, Delete were fixed
- After removing the silo we are staying on the opened Entity page.
