### ISSUE TITLE
Associate silos with Service Provider records

### ISSUE THREAD

**Issue by kkaczmarczyk** [benetech/ServiceNet#1034]
* When a user creates/edits a record, it should be associated with the silo
* Any users on that silo should only see records from other users in their silo

**Comment by kdondziak** [comment]
@johnhbenetech What should happen when user doesn't have silo?

**Comment by johnhbenetech** [comment]
Can we display something like. "Your account has not been configured. Please contact servicenet@benetech.org to complete set-up"

**Comment by kdondziak** [comment]
@johnhbenetech Team suggested that user might be assigned to default silo. Would you like to do it?

**Comment by johnhbenetech** [comment]
I would still like a message to display and them.not to have the ability to add records per my previous column. Is that difficult to do?

So either they don't get added to a solo and unsiloed users see that message or they get assigned to default silo but anyone on default silo sees only that message

**Comment by abaranowska1** [comment]
**Tested with success**
- If the user is not associated with the silo, the alert message is displayed.
![image](https://user-images.githubusercontent.com/61964176/84901516-e1a7fb00-b0ab-11ea-8536-65f8a978ee23.png)
- When a user creates/edits a record, it should be associated with the silo
- Users associated with the same silo see records from other users in their silo
![image](https://user-images.githubusercontent.com/61964176/84902509-313af680-b0ad-11ea-96b1-c0380fac4d9a.png)
![image](https://user-images.githubusercontent.com/61964176/84902539-39933180-b0ad-11ea-8335-f04a7e66f795.png)
