### ISSUE TITLE
Update classic view to show first and last name for matching records instead of ServiceProvider

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1036]
Similar to the new view, wherever a ServiceProvider record appears (side by side, compare, single record,  main page) on the classic page - First Name Last Name should appear instead of "ServiceProvider"

**Comment by kdondziak** [comment]
@johnhbenetech I guess that it should works same as on new view. I mean if there is no first name and last name then it should show email. And if there is first name or last name then mail should be inside tooltip. Am I right?

**Comment by johnhbenetech** [comment]
Yes

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on staging env

**Verified cases**
- checking organizations provided by service providers on the "classic" view
-- Service Provider with first and/or last name
-- Service Provider without first and last name

**Summary**
First and/or last name is displayed if provided. While hovering over it, the e-mail is displayed. If name is not provided, the e-mail is displayed.

**Attachments**
- with a name
![sn 1036 1](https://user-images.githubusercontent.com/51324797/83867925-79abf900-a72a-11ea-877b-b272b727c157.gif)

![sn 1036 2](https://user-images.githubusercontent.com/51324797/83867928-7a448f80-a72a-11ea-8a47-22b8e8ddb133.gif)

- without a name
![sn 1036 3](https://user-images.githubusercontent.com/51324797/83868067-90525000-a72a-11ea-817b-cb008863d415.png)

![sn 1036 4](https://user-images.githubusercontent.com/51324797/83868228-d3acbe80-a72a-11ea-8029-0a5be041f946.png)
