### ISSUE TITLE
Regression testing 06-01-2020

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#1037]
After one month from previous regression testing, it is important to check thoroughly if every functionality and feature works as expected.

The regression test suite contains all tests designed for this moment.

**Link to the test suite:**
https://docs.google.com/spreadsheets/d/1Lw_bDDwgaEAQXLUHMQ4bn2homCGbVMqEH3e3nPq8dYQ/edit?usp=sharing

**ACC**
- All test cases from the list are performed
- Report is created
- Tickets for found bugs are created and linked in the report and this issue

**Comment by abaranowska1** [comment]
Regression testing status report

Regression testing on 4 browsers (Google Chrome, Mozilla Firefox, MS Edge, Safari), and the mobile device was finished. 

List of reported issues:

https://github.com/benetech/ServiceNet/issues/1039

https://github.com/benetech/ServiceNet/issues/1041

https://github.com/benetech/ServiceNet/issues/1042

https://github.com/benetech/ServiceNet/issues/1048

All issues are in Up Next column so they will be fixed soon.

Summary:

Executed: 163 test cases 

159 test cases pass

4 test cases failed

Used time resources: We spent 3 days for regression testing.

There were no critical bugs, most of the issues were related to the Shelter project.

Link to report: https://docs.google.com/spreadsheets/d/1Lw_bDDwgaEAQXLUHMQ4bn2homCGbVMqEH3e3nPq8dYQ/edit#gid=0
![image](https://user-images.githubusercontent.com/61964176/83649314-56147180-a5b7-11ea-819f-2adc232773c0.png)
