### ISSUE TITLE
Add Notes tab to the single record view

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#104]

**Comment by NeilMBenetech** [comment]
@johnhbenetech I don't understand what this one is but you moved it around a bit in January. Can you add detail please and/or disposition it?

**Comment by johnhbenetech** [comment]
@NeilMBenetech this was something from an early prototype. 

It actually was an input where someone could add some ephemeral notes (possibly with auto expiration). I think iCarol has this concept?

Something like "Organization X is hosting a job fair  March 4th! 123 Main Street 1pm-4pm" 

I have no reason to believe this would be used, and I dont believe iCarol makes these available over API

**Comment by NeilMBenetech** [comment]
Yep, I think this is a duplicate to: https://github.com/benetech/ServiceNet/issues/313.

So I'll close this one.
