### ISSUE TITLE
Filtering feature on Shelter view is disabled after viewing shelter's details page

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#1041]
**Reproduction**
- Log in as a sacramentouser
- Apply filters
- View details page of one of the shelters
- Go back to Shelter's view

**Expected result**
- Filtering feature works

**Actual result**
- Filtering feature is disabled (user has to refresh the page)

**Attachments**
![shelter filtering feature disabled](https://user-images.githubusercontent.com/51324797/83513064-7964f100-a4d1-11ea-9567-894dd36891c6.gif)

**Comment by bognasoldev89** [comment]
@kdondziak the filtering feature is enabled but it doesn't work quite right.

Is it possible for filters to stay, as on the homepage with organizations?
Moreover, after reproducing this bug and applying the new filters, Bad request is sometimes thrown.

![sn 1041 sacramento](https://user-images.githubusercontent.com/51324797/87017304-1cdfaa80-c1d0-11ea-98dc-2818c0f60485.gif)

The other issue that could be related is that RESET button after applying filters clears out filters, but the record list is not reloaded.
![sn 1041 reset](https://user-images.githubusercontent.com/51324797/87017503-59aba180-c1d0-11ea-9776-40fc6e93385b.gif)

The homepage example to compare:
![sn 1041 classic view](https://user-images.githubusercontent.com/51324797/87017570-6fb96200-c1d0-11ea-9720-d3e491dc771b.gif)

**Comment by kdondziak** [comment]
@bognasoldev89 I've investigated and non of these above mentioned are related to this bug, but I'll fix it here

**Comment by bognasoldev89** [comment]
@kdondziak 
"Only show beds currently available" checkbox is not retained after going back from shelter details page. Moreover, RESET button should be enabled after going back from shelter details page. Please compare it with the filtering feature on the homepage.
![sn 1041](https://user-images.githubusercontent.com/51324797/87132095-ab6a2f80-c295-11ea-9090-9dabdba70055.gif)

**Comment by bognasoldev89** [comment]
**Tested with success**

**Environment**
- Staging env
- Browsers
-- Chrome 83.0.4103.116

**Verified cases**
- Applying filters
- Opening shelters details page
- Going back to shelter view and checking filtering feature

**Summary**
All found issues are resolved and the user can successfully use filtering feature.

**Attachment**
![sn 1041 working](https://user-images.githubusercontent.com/51324797/87547076-dcd66700-c6aa-11ea-90bc-46c9f3f49ce1.gif)
