### ISSUE TITLE
Filtering on Shelter view shows doubled records

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#1042]
Despite of doubling records on the shelter view I noticed strange behavior of the progress bar: though the list filtered 0 records, progress bar showed 0/1. 
I have to mention that filters set by me should show at least one shelter on the list.

**Reproduction**
- Log in as a sacramentouser
- Set filters. I used:
-- County: Yolo, Solano
-- Only show shelters that: Accessible
- Apply them

**Expected result**
- Applicable shelters are filtered and displayed

**Actual result**
- The filtered shelter is doubled on the list
- Once I got 0 records on the list and 0/1 progress bar

**Attachments**
- doubled record
![shelter doubled records](https://user-images.githubusercontent.com/51324797/83513718-9221d680-a4d2-11ea-800a-2b268e5ab38a.gif)

- progress bar
![shelter filtering progress bar](https://user-images.githubusercontent.com/51324797/83513730-9948e480-a4d2-11ea-803c-ab641c1ed541.gif)

**Comment by abaranowska1** [comment]
@kdondziak Still I can see doubled records, plz verify this issue once again 
![image](https://user-images.githubusercontent.com/61964176/83646495-fe283b80-a5b3-11ea-8e5b-956ba05faa19.png)

**Comment by abaranowska1** [comment]
**Tested with success**
**Verified cases:** 

- Applicable shelters are filtered and displayed
- The filtered shelter is doubled on the list - now it is displayed correctly 
![image](https://user-images.githubusercontent.com/61964176/83872480-60a74600-a732-11ea-8b49-b006375c36f3.png)
- The issue with 0/1 on the progress bar - I can't reproduce this issue anymore 
![image](https://user-images.githubusercontent.com/61964176/83872534-79176080-a732-11ea-9d1d-96eefb243655.png)
