### ISSUE TITLE
Auto-generate separate registration pages per each silo created

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1043]
Ideal Workflow:

1. Admin creates a new silo, let's call it "Chicago" for example

2. Our app automatically generates the required configuration to support a custom registration endpoint that automatically associates that user with the intended endpoint.
 
3. A prospective user visits this new endpoint, let's say:
https://servicenet.benetech.org/#/register/Chicago
or maybe
https://servicenet.benetech.org/#/register&group=Chicago

or whatever is best approach

4. User registers and is automatically added to the Chicago silo. For now they will still need to be activated by an admin, but we may allow for email auth in the future

**Comment by abaranowska1** [comment]
@awalkowiak 
I created a new Silo named Chicago and then I go to https://benetechservicenet.org/#/register/Chicago and I try to register new user, but I met Internal Server Error, plz check what's wrong here 
![image](https://user-images.githubusercontent.com/61964176/84997429-dd80e980-b14e-11ea-9734-2b226ea2f5d6.png)
Second thing is that error message: 
![image](https://user-images.githubusercontent.com/61964176/84997468-ed003280-b14e-11ea-8f22-a4531278445f.png)
It is thrown when I want to register user without firstly created Silo

**Comment by awalkowiak** [comment]
@abaranowska1 turned out, that we had not merged code-freeze branch on auth service. After build everything should be fine.

**Comment by abaranowska1** [comment]
**Tested with success**
Flow from the description works as expected : 

1. Admin creates a new silo, let's call it "Chicago" for example
2. Our app automatically generates the required configuration to support a custom registration endpoint that automatically associates that user with the intended endpoint.
3. A prospective user visits this new endpoint, let's say:
https://servicenet.benetech.org/#/register/Chicago
4. User registers and is automatically added to the Chicago silo. For now they still need to be activated by an admin.

![ServiceNet - Google Chrome_472](https://user-images.githubusercontent.com/61964176/85113931-61eb6f00-b218-11ea-981a-7183524bf73f.png)

![ServiceNet - Google Chrome_473](https://user-images.githubusercontent.com/61964176/85113928-60ba4200-b218-11ea-9c0b-4c2ecc310136.png)

Also when I want to register user without firstly created Silo error message with correct error is displayed 
![image](https://user-images.githubusercontent.com/61964176/85114065-9bbc7580-b218-11ea-9c66-00288b87e019.png)
