### ISSUE TITLE
Change bookmark icon color based on age of Daily Update

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1044]
This is regarding the bookmark icon to the left of the org name

* If daily update within last 24h, color = 6AB9A4

* If daily update within last 48h, color = FAB28C

* If daily update older - current grey color - 808080

* If no daily update - no icon (still keep org name in current location)

**Comment by kdondziak** [comment]
@johnhbenetech Do you mean bookmark on record card?
![image](https://user-images.githubusercontent.com/52406204/83770091-f1bde480-a680-11ea-9ee2-d9821f073c75.png)

**Comment by johnhbenetech** [comment]
Yes the grey icon in the upper left

**Comment by abaranowska1** [comment]
**Tested with success**

- If daily update within last 24h, color = 6AB9A4 
![image](https://user-images.githubusercontent.com/61964176/84892271-8ec74700-b09d-11ea-9878-6ca7ff53dd8f.png)

- If daily update within last 48h, color = FAB28C
![image](https://user-images.githubusercontent.com/61964176/84892196-6dfef180-b09d-11ea-9dd1-7e4c59568e41.png)

- If daily update older - current grey color - 808080
![image](https://user-images.githubusercontent.com/61964176/84892241-7fe09480-b09d-11ea-89f5-7cbefd0a55fb.png)

- If no daily update - no icon (still keep org name in current location)
![image](https://user-images.githubusercontent.com/61964176/84892302-9c7ccc80-b09d-11ea-94d7-f9b6164b55b5.png)
