### ISSUE TITLE
Create a setting that allows certain silos to expose a public facing list of records

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1045]
In the silo admin page, create a setting that allows for a public (unauthenticated) view of the records. There will be silos with this setting off, and off should be the default.

This view will be very similar to the current page, but just will not have the 'Your record' section at the top (therefore no ability to add records). Once again this is a 'read-only' view.

If possible this should automatically create the endpoint for this as well. Let me know what's possible here, for instance:

chicago.servicenet.benetech.org
or
servicenet.benetech.org/#/chicago
or
whatever else might be best approach

**Comment by kdondziak** [comment]
Creating public option will be handled in https://github.com/benetech/ServiceNet/issues/1054

**Comment by kdondziak** [comment]
@johnhbenetech Should unauthorized user have access to single record view (when clicking on link on record card)?

**Comment by johnhbenetech** [comment]
Yes


________________________________

**Comment by kdondziak** [comment]
How to test:
1. Set some silo as public.
2. Log out and got to /public/"Name of the silo"

**Comment by abaranowska1** [comment]
@kdondziak Please take a look for a small UI issue: 
- Mobile: Logo is not centered and I think we can move the whole section up or do the same bar as on web view 
![image](https://user-images.githubusercontent.com/61964176/88279908-20515680-cce5-11ea-85a5-50d8a144e96c.png)
![image](https://user-images.githubusercontent.com/61964176/88280061-758d6800-cce5-11ea-8f16-fb1a87b22855.png)
- Firefox issue: I don't know why we have doubled scroll bar, could you check it? 
![Peek 2020-07-23 12-49](https://user-images.githubusercontent.com/61964176/88280268-c8671f80-cce5-11ea-8731-20f9f8475221.gif)

@johnhbenetech URL address is sensitive to small and capital letter in the name of Silo, is it ok for you?

**Comment by johnhbenetech** [comment]
Case-sensitive url is fine

**Comment by abaranowska1** [comment]
@kdondziak 
Please take a look at the mobile view. If you can, center benetech logo and I think we can move the whole section up or do the same bar as on web view.
![Selection_534](https://user-images.githubusercontent.com/61964176/88377425-6f5bc200-cd9f-11ea-98f4-65fac632afa7.png)

Firefox issue was fixed. There is no doubled scroll bar. 
![image](https://user-images.githubusercontent.com/61964176/88377386-5c48f200-cd9f-11ea-9f6c-d45ded68d231.png)

**Comment by abaranowska1** [comment]
**Tested with success**
It looks good for me 
![image](https://user-images.githubusercontent.com/61964176/88392311-0cc4ef00-cdbc-11ea-9f4f-0a6abe9da599.png)
**Verified cases:** 

- New endpoint: for example https://benetechservicenet.org/#/public/Silo1
- Whole organization from the same Silo are displayed when the Silo is public
- When Silo doesn't exist or is not public, error message is thrown
- Map view, sorting and filtering works without issues
- New page and new design for the bar with the pills button was created
- New page works on two browsers and mobile
