### ISSUE TITLE
Add 'public' option to silo and allow admin to set it

### ISSUE THREAD

**Issue by kdondziak** [benetech/ServiceNet#1054]

**Comment by bognasoldev89** [comment]
**Tested with success**

**Environment**
Staging env

**Verified cases**
- Creating public silo
- Creating not public silo
- Changing silo from public to not public
- Changing silo from not public to public

**Summary**
A public option for silo is available in the Silos entity.

**Attachment**
![sn 1054](https://user-images.githubusercontent.com/51324797/87047249-896f9f00-c1fa-11ea-9163-7e0ff2a77260.gif)
