### ISSUE TITLE
Offer 'row' display of records in addition to card view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1056]
Mockup:
![image](https://user-images.githubusercontent.com/12927553/84075489-dcef9280-a999-11ea-8be2-a29c8751f385.png)

I'm imagining we would hide this control at the responsive breakpoint to disable on mobile/small screen

**Comment by kdondziak** [comment]
@johnhbenetech  Should this apply to 'my records' as well?

**Comment by johnhbenetech** [comment]
@kdondziak just the below records for now.

**Comment by bognasoldev89** [comment]
@kdondziak It seems like the UI needs some adjusting. On the mock-up the organization name is in the one line:

![sn 1056](https://user-images.githubusercontent.com/51324797/87133873-3c420a80-c298-11ea-8214-f0ca1f00e286.png)

**Comment by bognasoldev89** [comment]
@kdondziak can you restrain those super long organization names similar to the card view?

![Screenshot from 2020-07-13 09-09-56](https://user-images.githubusercontent.com/51324797/87281610-ae625b80-c4f3-11ea-81e3-2d35fe45543a.png)
![Screenshot from 2020-07-13 09-10-10](https://user-images.githubusercontent.com/51324797/87281612-aefaf200-c4f3-11ea-8de3-2476ee9101f6.png)

**Comment by bognasoldev89** [comment]
**Tested with success**

**Environment**
- Staging env
- Browsers
-- Chrome 83.0.4103.116
-- Firefox 78.0.2

**Verified cases**
- Changing displaying records method to "row"
- Applying long organizations names
- Scrolling back and forth
- Checking on mobiles

**Summary**
"Row" records displaying method looks good, the organizations' names don't overlap cards borders. This feature is not available on mobiles.

**Attachment**
![sn 1056 work](https://user-images.githubusercontent.com/51324797/87546140-58cfaf80-c6a9-11ea-9b75-a7184cd6bfc1.png)
