### ISSUE TITLE
Filtering on Provider View QA generates errors

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1060]
Steps to reproduce:

* Open Provider View on current dev
* open the filter shade

Result:
* three errors are thrown

The geo filter boxes seem to be empty on QA for some reason, so my assumption is we might need error handling when that's the case so user doesnt see those errors.

The second point is why are those boxes empty, but I realize that could be a result of something weird with the dev DB or the unmerged code. Let me know

**Comment by abaranowska1** [comment]
**Tested with success**
I didn't notice any error messages during filtering.
