### ISSUE TITLE
Add latest daily update (if available) to card/row view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1061]
When a daily update is available, the latest daily update should appear on the main card view. We may want to increase the card height a bit to accommodate 2 lines of text - and truncate the updates longer than that (with an ellipses). We should also include the date time ahead of the update e.g.:

Update (6/30/2020 1:24pm): Lorem ipsem

![image](https://user-images.githubusercontent.com/12927553/84960510-6a806000-b0c7-11ea-8bcc-372b43992b9b.png)

**Comment by awalkowiak** [comment]
@johnhbenetech is it ok if I break the two lines like on the screenshot below? 
![Selection_231](https://user-images.githubusercontent.com/12113312/85291280-9706f400-b49a-11ea-9b06-8c807832238f.png)

The ellipsis for two lines of text is harder to achieve than what I already have? Are you ok with that version or rather you prefer to have the update starting right after the date in the first line?

**Comment by johnhbenetech** [comment]
Two lines is fine

**Comment by abaranowska1** [comment]
**Tested with success**
**Verified cases:** 
- When a daily update is available, the latest daily update appears on the main card view
- Add 2 lines of text 
" 
 Update (6/30/2020 1:24pm):
 Lorem ipsem
"
![image](https://user-images.githubusercontent.com/61964176/85381286-1d284680-b53e-11ea-83a4-f518e03f9da8.png)
**Verified on:**
- Google Chrome Version 83.0.4103.61 
- Mozilla Firefox Version 77.0.1
- Mobile Device 360x640
