### ISSUE TITLE
Remove notification and view switcher elements

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1063]
Until we implement these features let's remove them for now.

![image](https://user-images.githubusercontent.com/12927553/84960599-b59a7300-b0c7-11ea-955c-4b52fcc370f1.png)

![image](https://user-images.githubusercontent.com/12927553/84960594-b0d5bf00-b0c7-11ea-83df-05e558e8dc54.png)

**Comment by abaranowska1** [comment]
**Tested with success**
Notification and view switcher elements were removed.
![image](https://user-images.githubusercontent.com/61964176/85125855-a5e86f00-b22c-11ea-9c28-6596f3fa1839.png)
