### ISSUE TITLE
Add map view for records

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1064]
Add a button to the left of the Sort and Filter buttons that says 'Map View' with the map-o fa icon to the left of the text (within the button.

When clicked this renders the new view. The button then changes to 'Grid View' with the 'th' grid fa icon to the left of the text.

The main interaction allows a user to see all the filtered records (with locations) as pins on the map. When a pin is clicked, the card for that resource should appear and if clicked the user would be brought to the single record view for that record.

Let me know if you have suggestions on how viable 'display all the pins' is in google maps. I'm not sure if they impose a limit on number of pins. I'm also not sure if anything like dynamic loading based on user map navigation is available in the embedded map. Or like a user scrolling to a different area of the map and hitting 'search in this area'.

Web (tapping a pin brings up the selected card):
![image](https://user-images.githubusercontent.com/12927553/84963333-b256b580-b0ce-11ea-92f8-f2042d4be4c7.png)

Mobile (no pin selected):
![image](https://user-images.githubusercontent.com/12927553/84963904-4ecd8780-b0d0-11ea-90d5-3f09098ad932.png)

Mobile (pin selected):
![image](https://user-images.githubusercontent.com/12927553/84964185-10849800-b0d1-11ea-8b7b-f271cf6dafce.png)

**Comment by abaranowska1** [comment]
@awalkowiak I found a few minor issues: 

1. After going back to the grid view all records are displayed. It could be a problem when we will have for example 1000 + records. 
![Peek 2020-06-30 13-09](https://user-images.githubusercontent.com/61964176/86120539-cb029a80-bad4-11ea-9281-e752251851d1.gif)
2. In my opinion cards should have the same size.
![image](https://user-images.githubusercontent.com/61964176/86121414-3bf68200-bad6-11ea-9028-0b0038776af2.png)
![image](https://user-images.githubusercontent.com/61964176/86121895-2170d880-bad7-11ea-801e-cfcd854a2d18.png)
3. Mobile View UI issues - buttons are out of the page and also card is too small.
![Selection_483](https://user-images.githubusercontent.com/61964176/86122004-4e24f000-bad7-11ea-9152-4f13d27d3bac.png)
![Selection_482](https://user-images.githubusercontent.com/61964176/86122007-4f561d00-bad7-11ea-9305-2e36cda7ee6a.png)
4. Also, I look into the mobile photos from the description and I see that the card is on the map, not under the map. @johnhbenetech is it ok for you? 
![image](https://user-images.githubusercontent.com/61964176/86122335-f63ab900-bad7-11ea-96d7-0bc6c1fc92a3.png)

**Comment by awalkowiak** [comment]
@abaranowska1 Here are my responses to your points:
1. When I am entering map view I am pulling all records, so there is no point of going back to previous page / records amount. That's why there are all records displayed. I think we could improve / split records loading for map view and grid view for the case when we will have huge amount of records (I'll make an issue for that improvement).
2. Fixed
3. Fixed
4. @johnhbenetech let us know what do you think about that verison.

**Comment by johnhbenetech** [comment]
@awalkowiak 

Yes, please make a task for point 1. If when you leave the grid view it is only showing 6 records, when you return it should still be showing 6. Let me know if separating the views is a massive amount of work.

Let's also make a task for the forth point. I think it's fine for a first version, but we can revisit later to see if we cant get it closer to the mockups. Thanks

**Comment by awalkowiak** [comment]
@johnhbenetech ok I'll create both tasks. Reg. 1st. The views won't be separated, but I think there will be separate API endpoint for getting records for map view probably.

**Comment by awalkowiak** [comment]
@johnhbenetech here are two new tasks for it: https://github.com/benetech/ServiceNet/issues/1074, https://github.com/benetech/ServiceNet/issues/1073. I put these in the "Service Provider View" column.

**Comment by abaranowska1** [comment]
**Tested with success**
It seems like the UI issue doesn't occur anymore. Cards have the correct size and buttons are well positioned on the mobile view. 
![image](https://user-images.githubusercontent.com/61964176/86352241-c28d9980-bc65-11ea-8a1b-a3e1e66d177e.png)
![image](https://user-images.githubusercontent.com/61964176/86352249-c7524d80-bc65-11ea-8c46-9554af6053fb.png)
