### ISSUE TITLE
Pull out common CSS classes from the new SP view

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#1065]
Many of the css classes could be common for the newly added components (for example buttons, pills). Change div with button style class to component created in #1056

**Comment by awalkowiak** [comment]
reg button-pill, use ButtonPill component

**Comment by awalkowiak** [comment]
@johnhbenetech
current version: 
![Selection_294](https://user-images.githubusercontent.com/12113312/88933726-15b43580-d280-11ea-8030-19b208b0fb15.png)
button pill version:
![Selection_293](https://user-images.githubusercontent.com/12113312/88933768-1f3d9d80-d280-11ea-85df-19e912a117f8.png)

There could be option to apply different coloring styling to button-pill too (if we want it). What do you think about it?

**Comment by johnhbenetech** [comment]
Thanks. The pill version with coloring would be nice.

* "I'm finished" can use the blue from the current square button
* "Discard" can use the grey from the current square button
* 'Deactivate' can use the grey from the current square button

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:**
- All buttons are changed to the pill version
![Przechwytywanie10](https://user-images.githubusercontent.com/61964176/89779736-4d3ca080-db10-11ea-8534-c54d3b64b87c.PNG)
![Przechwytywanie11](https://user-images.githubusercontent.com/61964176/89779744-4f9efa80-db10-11ea-8a1c-ca502b1f294b.PNG)
![Przechwytywanie8](https://user-images.githubusercontent.com/61964176/89779761-5b8abc80-db10-11ea-936c-3551e9428f6d.PNG)
![Przechwytywanie9](https://user-images.githubusercontent.com/61964176/89779766-5ded1680-db10-11ea-8fd4-68464ceb8477.PNG)

**Tested on:**

- Windows 10 OS
- Chrome v. Wersja 84.0.4147.105
- Firefox v. 79.0
- Mobile 360x640 and iPhone X
