### ISSUE TITLE
Add additional info to user registration / user setttngs page

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1071]
Add the following fields to the user profile available in both the initial user registration page as well as the user settings page:

* Organization Name (required, free text)
* Organization URL (not required, URL validation)
* Phone Number (not required, styled as (XXX)-XXX-XXXX input with validation)

**Comment by abaranowska1** [comment]
@awalkowiak 
Internal Server Error is thrown when I want to register a new user without Organization URL or Phone Number 

![ServiceNet - Google Chrome_504](https://user-images.githubusercontent.com/61964176/86353464-8bb88300-bc67-11ea-820e-ea849fe739d8.png)
![ServiceNet - Google Chrome_502](https://user-images.githubusercontent.com/61964176/86353468-8d824680-bc67-11ea-8ca4-e94f5cfc9ded.png)
![ServiceNet - Google Chrome_501](https://user-images.githubusercontent.com/61964176/86353472-8e1add00-bc67-11ea-8c0d-cd0635018d10.png)

**Comment by johnhbenetech** [comment]
In addition to @abaranowska1 issues, I have broken out an additional issue #1079

**Comment by johnhbenetech** [comment]
Also @awalkowiak as per the original task description this info is meant to be available in the user settings page for a logged in user as well as on the registration page (in case they need to update the info). I will break out another task for that

**Comment by awalkowiak** [comment]
@johnhbenetech
1. I was thinking about that QoL improvement for the phone number at the beginning, but it was not in initial requirements hence I wanted to suggest it at today's meeting.
2. I am not sure why, but when I read user settings I thought about admin - user management (and that where I added those fields). I can add these to the settings page too. This should be quick and easy.

**Comment by johnhbenetech** [comment]
@awalkowiak 
Great!
I've broken out #1081 for that.

**Comment by abaranowska1** [comment]
@awalkowiak 
Internal Server Error doesn't occur anymore, but now also there is no error message when I want to register a user with the same email/login. Data are overwritten and the page stays on the registration page, not come back to the homepage.
![Peek 2020-07-03 09-44](https://user-images.githubusercontent.com/61964176/86445043-0047fc00-bd12-11ea-8672-8c1801ce3e05.gif)

**Comment by awalkowiak** [comment]
@abaranowska1 please make sure that the user is active. If user is active you will get red notification about login/email being used, otherwise, it will be accepted.

**Comment by abaranowska1** [comment]
Confirmed that for active user I get the notification.
