### ISSUE TITLE
An unexpected error has occurred after create a new user account and click Edit button

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#1075]
During regression tests I noticed an issue. An unexpected error has occurred after create a new user account and click Edit button. After refresh the page issue doesn't occur.
![image](https://user-images.githubusercontent.com/61964176/86260000-01b3e000-bbbd-11ea-82c1-9264a387b1d0.png)
![Peek 2020-07-01 16-55](https://user-images.githubusercontent.com/61964176/86260063-14c6b000-bbbd-11ea-8560-89a26b476c84.gif)
**Steps:**
1. Go to user management
2. Create user, for example, Sacramento user without System Account
3. Save
4. Click Edit button 

**Verified on:** 
- Google Chrome Version 83.0.4103.116

**Comment by bognasoldev89** [comment]
**Tested with success**

**Environment**
Staging env.

**Verified cases**
- Creating a new account and clicking edit button
- Creating a new account and clicking create a new account button

**Summary**
After creating a new account I could successfully edit this and different accounts and go to create a new account page. I checked with different profiles and system accounts. Not once the unexpected error occurred.

**Attachment**
Example:
![sn 1075](https://user-images.githubusercontent.com/51324797/87041867-275f6b80-c1f3-11ea-9017-6678e78e0d2e.gif)
