### ISSUE TITLE
Internal Server Error is thrown during filtering on the Shelter View

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#1077]
Internal Server Error is thrown during filtering on the Shelter View. During regression testing after pick a few liters, for example, Location, Audience Men, Audience Women and Audience Families error message is thrown.

![Peek 2020-07-01 20-41](https://user-images.githubusercontent.com/61964176/86280332-dee4f400-bbdb-11ea-9e96-02c0cefa7559.gif)

**Steps:**
1. Log in as Sacramento User 
2. Pick some filter 
3. Add location and pick "Search near selected location" checkbox
4. Apply 

**Actual result:** 
Internal Server Error 
![ServiceNet - Google Chrome_491](https://user-images.githubusercontent.com/61964176/86280342-e1dfe480-bbdb-11ea-8dff-206d70c89169.png)

**Expected result:**
No error message, filters should work without issues. 

**Verified on:**
Google Chrome Version 83.0.4103.116

**Comment by abaranowska1** [comment]
@awalkowiak 
The issue still occur, there is no one reproduction, I clicked some checkboxes and I met Internal Server Error. You can see it on gif 
![Peek 2020-07-03 10-09](https://user-images.githubusercontent.com/61964176/86447579-da245b00-bd15-11ea-828b-779eab95911d.gif)
![Untitled window_512](https://user-images.githubusercontent.com/61964176/86447727-1061da80-bd16-11ea-8760-97ca3a095540.png)

**Comment by bognasoldev89** [comment]
**Tested with success**

**Environment**
Staging env

**Verified cases**
- Applying filters
-- County
-- Beds/Options
-- Locations

**Summary**
I tried different combinations of filters and Internal server error was not thrown in any case.

**Attachments**
![sn 1077](https://user-images.githubusercontent.com/51324797/87011884-cc188380-c1c8-11ea-8d32-a3e5e8c56488.gif)
