### ISSUE TITLE
Phone number input on user settings/registration page should assist user in formatting

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1079]
While the ultimate data should be formatted as (xxx)-xxx-xxxx we shouldn't expect the user to type it in that exact way (typing the parentheses and dashes for example).

We should use a common phone input that does this for the user. We dont have to use this specific component, but an example of the interactions would be:

https://catamphetamine.github.io/react-phone-number-input/

Specifically the "without country select" since we are only working with US based users right now

**Comment by abaranowska1** [comment]
@awalkowiak 
I saw that phone number auto formatting works fine, we have two patterns  1 (XXX) XXX-XXXX or (XXX) XXX-XXXX, but I cannot register a user. Plz take a look for this error message 
![image](https://user-images.githubusercontent.com/61964176/86475257-a3b20480-bd44-11ea-9991-c6c6ec017882.png)

**Comment by awalkowiak** [comment]
@abaranowska1 the http error was because the core service was down. It is working now (cc @bognasoldev89)

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on staging env

**Verified cases**
- User registration with phone numbers in both requested formats
- Phone number edit from:
-- user administration page
-- user settings page

**Summary**
In all mentioned cases the phone number is formated and saved correctly. The error spotted by Alicja no longer occurs.

**Attachments**
![sn 1079](https://user-images.githubusercontent.com/51324797/86484808-58edb800-bd57-11ea-8f50-03073a2be5ea.gif)

![sn 1079 2](https://user-images.githubusercontent.com/51324797/86484809-5ab77b80-bd57-11ea-8856-9c71b85bd0d1.gif)

![sn 1079 3](https://user-images.githubusercontent.com/51324797/86484811-5be8a880-bd57-11ea-872e-1cdbde813851.gif)
