### ISSUE TITLE
Investigate double pin on the map view in fact when we have a general address

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#1084]
When I added location with the address to the Organization and this address has only street without any number then on the map view I can see 2 pins next to each other,  but when I add the number to the street all works and I see only one pin.
It could be related to the geocoding.
For example : 
Olszewskiego, Pruszcz Gdański
![Selection_507](https://user-images.githubusercontent.com/61964176/86439273-8eb78000-bd08-11ea-849c-a6724b912d6b.png)
Olszewskiego 4D, Pruszcz Gdański 
![Selection_508](https://user-images.githubusercontent.com/61964176/86439277-90814380-bd08-11ea-8450-ca4264a9357d.png)

Steps: 
1. Log in as Provider
2. Add general address to the Organization ( without number )
3. Open this Organization in the Map View

**Comment by kdondziak** [comment]
@abaranowska1 I can't reproduce. Probably there is more steps to reproduce

**Comment by abaranowska1** [comment]
@kdondziak After these one month, I cannot reproduce it too. Maybe it was an issue with Google Maps.

**Comment by awalkowiak** [comment]
@abaranowska1 it is not issue with Google Maps. We had both records (locations) in database. We just can't reproduce the case when in geocoding results we have more records than one.

**Comment by kkaczmarczyk** [comment]
@abaranowska1 Could you once again try to reproduce it? If it won't happen I think we can close this, and keep an eye for this issue during regression tests.

**Comment by abaranowska1** [comment]
@kkaczmarczyk  I cannot reproduce it. I will keep an eye on this issue during regression tests.
