### ISSUE TITLE
Allow ServiceProvider records to be managed by multiple users

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1088]
Use case:

In ServiceProvider view, we want to allow multiple users to edit the same collection of records.

This will likely be a more significant rearchitecture/migration so definitely looking for some input on the best approach to achieve it.

Option 1:
Does the user_profile_organizations table currently support multiple rows for the same record? Would it work as expected (either user sees the same record to edit when they log in)?

The gap here is that if User A makes additional records, User B wouldn't see them by default until they are manually associated

Option 2:
We need a way to group users within the ServiceProvider system account. This can get a little clunky but not sure if there is another option. Basically it could work like this:

* Create 'UserGroup' entity with name and silo columns
* Add UserGroup to the user admin page and surface when ServiceProvider system account is selected
* Change the  user_profile_organizations table to use UserGroupID instead of UserID
* Change all ServiceProvider logic to use UserGroup in loading/saving records (to load logged in user's records, associate new records on creation, load deactivated accounts, etc).

At this point I don't want to worry about race conditions/simultaneous edits/etc - so we can assume any edit can fully overwrite the data regardless of if there were intermediate changes

Option 2:

**Comment by kdondziak** [comment]
We decided to go on with option 2

**Comment by johnhbenetech** [comment]
@kdondziak so we would get rid of 'user_profile_organization' table?

One thing I'm curious if we could handle is a user being in multiple groups. So when they log in they would be able to edit all records from both Group A and Group B?

**Comment by bognasoldev89** [comment]
@kdondziak a few remarks

1.
On staging env I created a group with Silo 1
To this group, I added 4 accounts, assigned to Silo 1: provider, bognabogna, bognaprov and bognaprov22
When I logged in as each of those 4 users, on the carousel I saw organizations only from bognabogna. After a while organizations from bognaprov22 appeared.

2.
I changed silo for the group to Silo 3
The carousel was empty for all of the accounts. Is that a correct behavior?
I changed silo for the group back to Silo 1
The carousel was still empty for all the mentioned accounts.

3.
On user management page, can you change the field name to for example "Groups" and enable "unclicking"?
![Screenshot from 2020-07-16 10-33-50](https://user-images.githubusercontent.com/51324797/87651961-e536ac80-c753-11ea-9953-91018a856610.png)

**Comment by bognasoldev89** [comment]
The issues mentioned worked fine on the user group I created last week.

1. I was not able to create a new group - Internal Server Error occured.
2. I deleted group created last week and now Internal Server Error is thrown on every place, where organizations from group members are available.
3. Admin -> User management is throwing Internal Server Error as well.

Please, improve error handling within this issue and allow creating and deleting groups smoothly.

**Comment by bognasoldev89** [comment]
**Tested with success**

**Environment**
- Staging env
- Browsers
-- Chrome 83.0.4103.116
-- Firefox 78.0.2

**Verified cases**
- Creating a few groups
- Deleting a group with users in it
- Changing group's silos
- Adding users to one group
- Adding a user to a few groups
- Removing a user from a group
- Editing organization records from the other account in a group
- Changing user's silos
- Comparing displayed organizations by silos

**Summary**
It seems like users are allowed to successfully edit other users' organizations within the group. The error is not thrown anymore. I was able to cross groups and remove users from groups.
The last update information is consistent with the account that provided changes.
Group's silo doesn't have an impact on this feature at this moment.

**Attachments**
![Peek 2020-07-21 10-01](https://user-images.githubusercontent.com/51324797/88028798-68cc1100-cb39-11ea-9f16-6f3afaea7658.gif)

![Peek 2020-07-21 10-05](https://user-images.githubusercontent.com/51324797/88029162-eb54d080-cb39-11ea-9fc3-de04623b5d91.gif)
