### ISSUE TITLE
Error on Service Provider record creation when Service is linked to location, then unlinked

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1092]
Steps to reproduce:

* Log-in to ServiceProvider account and create a new record
* Add org details and some locations
* Add some services
* On one of the services, pick a location in the 'Which locations offer this service' section
* Use the x to remove that location you just added
* Click I'm Finished

Result: Error is thrown and record isn't committed

Cause: 
The affected endpoint: https://servicenet.benetech.org/services/servicenet/api/organizations/user-owned

If you never link a location to a service, the index gets sent as:
"locationIndexes":[]

However, if you linked one then removed it, the index gets sent as:
"locationIndexes":""

Which throws the following errors since it's a string and not an array:

{"type":"https://www.jhipster.tech/problem/problemwithmessage","title":"Bad Request","status":400,"detail":"Failed to convert value of type 'java.lang.String' to required type 'java.util.UUID'; nested exception is java.lang.IllegalArgumentException: Invalid UUID string: user-owned","path":"/api/organizations/user-owned","message":"error.http.400"}

detail: "JSON parse error: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value (''); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('')↵ at [Source: (PushbackInputStream); line: 1, column: 2837] (through reference chain: org.benetech.servicenet.service.dto.provider.SimpleOrganizationDTO["services"]->java.util.ArrayList[1]->org.benetech.servicenet.service.dto.provider.SimpleServiceDTO["locationIndexes"])"

**Comment by johnhbenetech** [comment]
![image](https://user-images.githubusercontent.com/12927553/87177101-b5ddf680-c2a0-11ea-94d1-a5aa115a5457.png)

**Comment by kdondziak** [comment]
@johnhbenetech It is just UI error related to tooltip. I'll look on it but it is not dangerous.

**Comment by kdondziak** [comment]
@johnhbenetech Can you check if issue still occurs on production?

**Comment by johnhbenetech** [comment]
@kdondziak I have not released the latest code to prod as I am waiting on the new deployment approach to be ready

**Comment by awalkowiak** [comment]
@johnhbenetech Your case seems to be easy to fix. But I found one more bug:
When the user is not in any User Group, then he can't edit, delete, deactivate and reactivate his own records. I think this is very important to get fixed. I bumped up the estimate to 3 points to cover this fix too.

**Comment by awalkowiak** [comment]
And the same happens on the 'Deactivated records' table.

**Comment by awalkowiak** [comment]
@bognasoldev89 or @awalkowiak please test also the issue I mentioned in the comments above.

**Comment by abaranowska1** [comment]
**Tested with success** 

**Verified cases:** 
- I try to reproduce steps from the description and any error message don't exist, user can use the x to remove just added location and click I'm Finished
![Peek 2020-07-24 14-56](https://user-images.githubusercontent.com/61964176/88393484-fcae0f00-cdbd-11ea-9ac9-2a5192354f3f.gif)

- When the user is not in any User Group, then he can edit, delete, deactivate and reactivate his own records.
![image](https://user-images.githubusercontent.com/61964176/88393229-94f7c400-cdbd-11ea-9dfa-a1711a251932.png)
![Peek 2020-07-24 14-47](https://user-images.githubusercontent.com/61964176/88393264-a345e000-cdbd-11ea-8abb-0cec18a37dea.gif)

**Verified on:**
- Google Chrome Version 84.0.4147.89
