### ISSUE TITLE
Hitting the 'Register' link from a silo's public view should brring you to the registration page for that silo

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1104]
For example:

/public/Demo should bring you to /register/Demo

**Comment by abaranowska1** [comment]
**Tested with success**
**Verified cases:**
- Hitting the 'Register' link from a silo's public view bring you to the registration page for that silo
- /public/Demo brings you to /register/Demo
- It is possible to register a new user to the Silo 

![Peek 2020-07-28 11-31](https://user-images.githubusercontent.com/61964176/88647778-a515e900-d0c6-11ea-95e7-ca3865152cb5.gif)

**Verified on:**
- QA environment
- Google Chrome Version 84.0.4147.89
- Mobile Device 360x640
