### ISSUE TITLE
Frequent JS Console error "a.split not a function"

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1105]
Happens frequently. I'll leave it up to you all if it's worth fixing. It often comes with a 401 to the /account endpoint. So I assume it's something with a call being made when unauthenticated.

**Comment by johnhbenetech** [comment]
![image](https://user-images.githubusercontent.com/12927553/88438792-202d8580-cdcf-11ea-8e70-3a019e025bcd.png)

**Comment by abaranowska1** [comment]
**Tested with success**
JS Console error "a.split not a function" does not occur anymore 
Verified cases: 
- Checked if error exists during log in / log out
- Checked if error exists during adding new Organization and moving from one page to another
- Checked if errror exist on pages with error pop-ups 
![image](https://user-images.githubusercontent.com/61964176/89294361-b5e2d380-d65f-11ea-9efc-fcf98668b2d8.png)
![image](https://user-images.githubusercontent.com/61964176/89294374-baa78780-d65f-11ea-9dc2-cb72bee88bbc.png)
![image](https://user-images.githubusercontent.com/61964176/89294387-bf6c3b80-d65f-11ea-83bd-e76f1fa360e8.png)

Now only such error is displayd 
![image](https://user-images.githubusercontent.com/61964176/89294549-f2aeca80-d65f-11ea-9d53-52df4bf7512c.png)

**Verified on:**

- Ubuntu 16.04
- Firefox v.79.0
- Chrome v. 84.0.4147.105
