### ISSUE TITLE
Weird font rendering in Firefox

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1106]
On my firefox the font on the ServiceProvider view is not rendering as clearly as on Chrome. I'd like to see if it's happening for other people. The lower case 'y' is particularily noticeable.

I think it's related to : https://www.lockedownseo.com/firefox-font-weight-too-bold/

**Comment by awalkowiak** [comment]
@johnhbenetech the only thing I can notice is that font on FF is less bold than on chrome but other than that it looks the same.
Here are the screenshots.
1. ON the top is firefox, on the bottom is chrome
![Selection_289](https://user-images.githubusercontent.com/12113312/88785221-38b3ec00-d191-11ea-8a96-bba980e3f0c3.png)
2. On the left is ff, on the right is chrome
![Selection_290](https://user-images.githubusercontent.com/12113312/88785321-4cf7e900-d191-11ea-8ee6-402e6b8d7024.png)

What version of Firefox and Chrome do you have? Are you using Linux or Windows?

**Comment by johnhbenetech** [comment]
I'm on Windows and FF 78.0.2

Example:
![image](https://user-images.githubusercontent.com/12927553/89078622-5c6e6200-d34a-11ea-9a26-a6150176a136.png)

**Comment by kdondziak** [comment]
@johnhbenetech Seem like the font name has changed (Muli -> Mulish https://github.com/benetech/ServiceNet/issues/943#issuecomment-619065138). Can you review if this is what should be displayed -> https://fonts.google.com/specimen/Mulish?preview.text=Sacred+Heart+Community+Service&preview.text_type=custom&sidebar.open=true&selection.family=Mulish:wght@400;700

**Comment by johnhbenetech** [comment]
@kdondziak yes that's correct.

**Comment by abaranowska1** [comment]
**Tested with success**
In my opinion, now it looks fine. I checked it also on Windows machine and here I didn't notice any weird font regarding Firefox.

1. Ubuntu 16.04 OS, on the left, is Chrome v. 84.0.4147.105, on the right is Firefox v.79.0
![image](https://user-images.githubusercontent.com/61964176/89406982-4b449d00-d71e-11ea-8a85-efa402c8be55.png)
![image](https://user-images.githubusercontent.com/61964176/89406986-4ed82400-d71e-11ea-9c49-1a2e9f843275.png)

2. Windows 10, on the left, is Chrome v. 80.0.39.87.149, on the right is Firefox v.79.0
![Przechwytywanie](https://user-images.githubusercontent.com/61964176/89407151-8f37a200-d71e-11ea-8227-a78621b2c712.PNG)
![Przechwytywanie1](https://user-images.githubusercontent.com/61964176/89407154-9068cf00-d71e-11ea-8faf-b383676080e6.PNG)
