### ISSUE TITLE
Add 'Required Documents' to ServiceProvider views

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1107]
It should be made present on the services section of all views: new record, edit record, view only, and public.

It can be displayed below the eligibility and application process fields.

**Comment by jkondrat** [comment]
@johnhbenetech Should we allow adding multiple required documents and display it like a list, or a single input/textbox would suffice?

**Comment by johnhbenetech** [comment]
@jkondrat single box should be good

**Comment by abaranowska1** [comment]
**Tested with success**
**Verified cases:**

- Required Documents field is displayed below the eligibility and application process fields,
- It is available on all views: new record, view only, edit record, and public.

![Selection_019](https://user-images.githubusercontent.com/61964176/90744810-60016300-e2d0-11ea-9f26-7cd0b8d757a7.png)
![Selection_020](https://user-images.githubusercontent.com/61964176/90744821-61329000-e2d0-11ea-87df-5da523b836ba.png)
![Selection_021](https://user-images.githubusercontent.com/61964176/90744827-61329000-e2d0-11ea-9f4a-8948745cd94a.png)
![Selection_022](https://user-images.githubusercontent.com/61964176/90744831-61cb2680-e2d0-11ea-820b-a71784eac2f6.png)

**Verified on:**
- Ubuntu 18.04
- Google Chrome v.84.0.4147.125
