### ISSUE TITLE
SPRING_PROFILES_ACTIVE should be set based on SN_VERSION_TAG

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1109]
Currently the swarm deployment always deploys with SPRING_PROFILES_ACTIVE=dev,swagger

If SN_VERSION_TAG=latest then SPRING_PROFILES_ACTIVE should be set to prod,swagger

**Comment by kkaczmarczyk** [comment]
I've added instruction of the SPRING_PROFILES_ACTIVE setup to the to https://github.com/benetech/ServiceNet/wiki/Production-environment. For prod it is one time manual action (change it to _'prod,swagger'_  in .env)

**Comment by kkaczmarczyk** [comment]
@johnhbenetech just checking in if you were able to set the SPRING_PROFILES_ACTIVE env variable on prod?

**Comment by johnhbenetech** [comment]
Yes this worked! Closing task
