### ISSUE TITLE
Possible issue with new taxonomy not showing in ServiceProvider filter

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1110]
Hi could be missing something here, but steps to reproduce:

* Log in as admin and add a new taxonomy term to the ServiceProvider system account
* Log in as a ServiceProvider and start to add/edit a record
* On a service, choose the newly created taxonomy for your service - then save the change
* Note: taxonomy appears as options and is saved sucessfully
* Log in as a different ServiceProvider in the same silo
* Attempt to filter records by ServiceType

Result:
* New taxonomy doesnt appear in the filter options

Not sure if I'm missing some other join table or something I need to modify when i add a new taxonomy term

**Comment by bognasoldev89** [comment]
@kdondziak I was able to follow John's steps but when I tried to create more taxonomies, Internal Server Error was thrown and the console showed 500. Can you look at this?

![ServiceNet - Google Chrome_002](https://user-images.githubusercontent.com/51324797/89541519-c7161680-d7fe-11ea-954c-b531fdc0491c.png)

**Comment by pmuchowski** [comment]
@bognasoldev89 it was unique constraint violation exception, the combination of External Database Id and Provider Name is unique and one Taxonomy with empty External Database Id and ServiceProvider Provider Name already exist.

**Comment by bognasoldev89** [comment]
@pmuchowski thanks for the clarification.

**Tested with success**

**Environment**
- staging env

**Verified cases**
- creating a new taxonomy for provider
- using this taxonomy while creating a new organization
- using this taxonomy while editing existing organization
- filtering by this taxonomy

**Summary**
New taxonomies, created in taxonomies entity by admin user, are usable in every intended way.

**Attachment**
![sn 1110](https://user-images.githubusercontent.com/51324797/90125692-bae00b00-dd62-11ea-8210-016e0ab08252.png)
