### ISSUE TITLE
Add transit layer to ServiceProvider map

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1111]
By default, the ServiceProvider map view should include the google 'transit' map layer

**Comment by kdondziak** [comment]
QA note: This should work as here: https://developers.google.com/maps/documentation/javascript/trafficlayer#transit_layer
Also note that not every city supports this feature.

**Comment by abaranowska1** [comment]
**Tested with success:**
The transit layer was added to ServiceProvider map, not every city supports this feature, but this is the expected result. 
![Przechwytywanie2](https://user-images.githubusercontent.com/61964176/89619831-f2e0dd00-d88e-11ea-9b66-895f416235f3.jpg)
![Przechwytywanie3](https://user-images.githubusercontent.com/61964176/89619832-f4120a00-d88e-11ea-90f9-c439fa5016a5.jpg)
