### ISSUE TITLE
When on ServiceProvider Public view, home link should bring you back to that Silo's main view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1113]
If a user clicks 'home' in a public serviceprovider view - it should bring them back to the main public view

**Comment by abaranowska1** [comment]
**Verified cases: **
- If a user clicks 'home' in a public serviceprovider view - it brings them back to the main public view
- If a user clicks 'home' in a single record public serviceprovider view - it brings them back to the main public view
- If a user clicks 'home' in a map public serviceprovider view - it doesn't bring them back to the main public view
![gif1](https://user-images.githubusercontent.com/61964176/89537754-0c841500-d7fa-11ea-89a5-42275d9aed01.gif)

@johnhbenetech If a user clicks Benetech Logo in a public serviceprovider view it should bring them to the main public view too or to our normal login page ?

**Tested on:**
- Windows 10 OS
- Google Chrome v. 84.0.4147.105

**Comment by johnhbenetech** [comment]
@abaranowska1 the logo should also bring back to main ServiceProvider view. Thanks for pointing that out

**Comment by abaranowska1** [comment]
@jkondrat In summary, these cases need to be fixed:
- If a user clicks 'home' in a map public serviceprovider view - it doesn't bring them back to the main public view
- If a user clicks Benetech Logo in a public serviceprovider view it should bring them to the main public view too

**Comment by abaranowska1** [comment]
**Tested with success**

- If a user clicks 'home' in a public serviceprovider view - it brings them back to the main public view,
- If a user clicks 'home' in a single record public serviceprovider view - it brings them back to the main public view,
- If a user clicks Benetech Logo in a public serviceprovider view - it brings them back to the main public view too.

![Peek 2020-08-20 08-10](https://user-images.githubusercontent.com/61964176/90723530-312dc180-e2bd-11ea-9582-4c779120ee52.gif)

**Verified on:**
- Ubuntu 18.04
- Google Chrome v. 84.0.4147.125 
- Firefox v. 79.0
