### ISSUE TITLE
When on ServiceProvider public view, log in should surface modal over the public view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1114]
If user clicks sign in on SP public view, the sign in modal should appear over the main SP view and not bring you back to homepage

**Comment by bognasoldev89** [comment]
**Tested with success**

**Environment**
- staging env
- browsers
-- Chrome 83.0.4103.116
-- Firefox 79.0

**Verified cases**
- Log in from the public silo main page
- Log in from the public silo organization card
- Log in from the non-public silo main page
- Canceling log in modal

**Summary**
In any of the above cases, the user wasn't sent to the welcome page. In the background was always the main page of service provider view. Logging in was correct.

**Attachments**
![sn 1114 1](https://user-images.githubusercontent.com/51324797/89542779-6c7dba00-d800-11ea-81d4-10f2318b4ab7.gif)

![sn 1114 2](https://user-images.githubusercontent.com/51324797/89542784-6ee01400-d800-11ea-99f0-31e0dd73cf40.gif)
