### ISSUE TITLE
i've found location with 200 geolocations, but only 3 different.

### ISSUE THREAD

**Issue by kdondziak** [benetech/ServiceNet#1116]
See location_geocoding_results.location_id='891340fb-fe4f-46e6-9eac-e92f9f3c3186'. Probablty geocodings are saved on update with previous ones.

**Comment by awalkowiak** [comment]
@kdondziak the physical address connected to this location is "Dmowskiego 12" which I guess is a testing location. @abaranowska1 perhaps you know why there are so many geocoding results connected to this location. The organization connected is "Regression testing organization1". Did you notice something unusual regarding that during testing?

**Comment by abaranowska1** [comment]
@kdondziak @awalkowiak Yes, "Regression testing organization1" is a testing record, but I didn't notice anything unusual, maybe @bognasoldev89 noticed something while testing geocoding in regression testing

**Comment by bognasoldev89** [comment]
@kdondziak @awalkowiak @abaranowska1indeed, I was testing geolocation, but the map was ok and I didn't look into this one particular organization. I didn't notice any changes in the geolocations on the entity page.
I recall creating and testing issue #1021 (may be helpful)

**Comment by abaranowska1** [comment]
Together with @kdondziak we checked that there is no location with duplicated geocoding results
