### ISSUE TITLE
Refactor Map View endpoint

### ISSUE THREAD

**Issue by pmuchowski** [benetech/ServiceNet#1121]
The map view endpoint is using existing method to fetch the organizations and it's getting the locations and geocoding results from the organizations.
Fetching the geocoding results directly should improve the performance and fix the issue with displaying wrong locations when filtering by city.
When writing new method for this we need to remember about the location exclusions, because not all of the locations should be displayed on the map.

**Comment by johnhbenetech** [comment]
@jkondrat Can we also cover general performance in this task? In loading 100+ locations the response time is quite long. Would it be possible to include pagination/result limits or is there another recommendation here?

We also may want this endpoint to allow for GPS coordinates parameter/filtering. The user interaction we want to handle is reloading results as the user drag/zooms the map based on the boundaries

**Comment by jkondrat** [comment]
@johnhbenetech the map view endpoint is a couple of times faster after the refactor - loading 50 locations takes around 200ms and the response is 13.4kB in size. Do you think we need to further improve it? I don't think that pagination/limiting results would work on map view. If we wanted to cluster them, we would still need to make the same query to get the count, we would be just reducing the response size

**Comment by johnhbenetech** [comment]
@jkondrat we can test it out in QA and then give feedback. 

I guess my thought (which may not be a good one) was to create a new endpoint specifically for the map where the major parameters are GPS coordinates. In that way you could send the API a set of coordinates and a distance and the endpoint returns our locations within that distance.

In this interaction we would only fetch the locations that are within the user's chosen map viewpoint (aka those that would display within the boundaries of where the user navigated to within the map frame).

The pagination would occur within that request to by default only return the first X locations in that distance (where X is determined through testing). That way a user would have to add filters or zoom in to see ALL the locations if they set a condition where it would return 100s of locations.

**Comment by abaranowska1** [comment]
I can only confirm that as @jkondrat  said loading near 50 locations now takes around 200 ms and response is near 13kB in size. In my opinion, it works better now than it was before the fix.
![image](https://user-images.githubusercontent.com/61964176/91847976-e025b200-ec5a-11ea-99e8-24c98f6d03ff.png)
