### ISSUE TITLE
Sorting shelters by beds available doesn't work

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#1126]
Shelters are not sorted by the number of available beds

**Reproduction**
1. Log in as a sacramentouser
2. Click "Sort" button
3. Choose "Beds available" from the dropdown

**Expected result**
4. Shelters are sorted by the number of available beds in the ascending or descending order

**Actual result**
4. Shelters are not sorted by the number of available beds at all

**Attachment**
![Peek 2020-08-21 14-39](https://user-images.githubusercontent.com/51324797/90891803-94524d80-e3bc-11ea-8968-26482386a7f6.gif)

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:**
- Sorting shelters by beds available ( ascending and descending )
- Sorting filtered shelters by beds available

![Peek 2020-08-28 11-29](https://user-images.githubusercontent.com/61964176/91546341-94a19a00-e922-11ea-9a1d-bc119c79e5dd.gif)

**Tested on:**
- Ubuntu 18.04
- Google Chrome v. 84.0.4147.135 
- Firefox v. 79.0
