### ISSUE TITLE
Allow for cascade delete of organizations and all related entities

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1128]
We need to create a function for an admin to delete a SP record and all related entities (at the database).

This can be tied to the 'delete' button in the admin org entities page or wherever you find it easiest to include.

**Comment by pmuchowski** [comment]
@johnhbenetech I think we can safely delete most of the entities related to the organization (locations, services and all child entities), but I'm not sure about the taxonomies. Is it possible that one Taxonomy can be shared between services from different organizations?

**Comment by pmuchowski** [comment]
Also do we want to remove the Conflicts and OrganizationMatches related the to deleted organization?

**Comment by johnhbenetech** [comment]
@pmuchowski definitely do NOT want to delete the taxonomy, but we should removed the service->taxonomy ties

I think we have to remove the conflicts/matches, right?

**Comment by pmuchowski** [comment]
Yes, I think it will be better to remove the conflicts and matches, to avoid any potential issues when match has reference to removed organization.

**Comment by pmuchowski** [comment]
@johnhbenetech there are also LocationMatch and ServiceMatch, from what I can see the ServiceMatch is not used right now, but the LocationMatch is.
We will need to remove those too and MatchSimilarity.

**Comment by abaranowska1** [comment]
@pmuchowski plz check this issue 
- I opened Entity -> Organizations and wanted to delete the organization "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ... "(it's one with a service provider account) after clicking delete it was ok, the green popup was displayed, but this organization stayed on the list. After refreshing the page Internal Server Error is displayed and Organization are not loaded 
![image](https://user-images.githubusercontent.com/61964176/92460838-b9222f80-f1c8-11ea-92e3-7ad65c3b19b2.png)

**Comment by abaranowska1** [comment]
@pmuchowski 
Still, I cannot delete an Organization with success. I tried to remove Organization Test1 
![image](https://user-images.githubusercontent.com/61964176/92566015-e380f500-f27b-11ea-8edb-c44dc0ba5a60.png)
and I met Internal Server Error, also I observed that the bottom scroll bar does not show at the bottom of the page and this prevents the page from scrolling sideways when scrolling from top to bottom, but I'm not sure if it is related to your changes
![Peek 2020-09-09 09-01](https://user-images.githubusercontent.com/61964176/92566536-ae28d700-f27c-11ea-84bd-af9d189cf4da.gif)

**Comment by abaranowska1** [comment]
**Tested with success**
Finally, I can remove an Organization without issue. The green popup is displayed after click the Delete button and the record is removed from the list. 
![Peek 2020-09-11 09-52](https://user-images.githubusercontent.com/61964176/92887966-304c0380-f415-11ea-8e04-e9ffccf85ce8.gif)
**Verified on:**
- Ubuntu 20.04 
- Google Chrome v. 85.0.4183.83
