### ISSUE TITLE
Improve performance of loading 'owned records'

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1129]
Currently with many 'owned' records in the SP view, it takes a while to load the records to populate the top section.

Is it possible to increase the performance here possibly by adding pagination / lazy loading tied to the carousel navigation?

**Comment by abaranowska1** [comment]
**Tested with success**
Paginations were added to the carousel - ' owned records'. Now it is loading quicker and during moving the carousel cards are loaded with the spinner. 
![Peek 2020-09-14 15-05](https://user-images.githubusercontent.com/61964176/93089587-cbeea580-f69b-11ea-9d36-217b06a4869b.gif)
**Verified on:**
- Dev instance
- Ubuntu 20.04
- Google Chrome v. 85.0.4183.83
