### ISSUE TITLE
Add side-by-side view

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#113]
There should be available view to compare two organizations. Mock is available here:
![screenshot from 2019-01-14 12-00-02](https://user-images.githubusercontent.com/19305104/51109040-3af36700-17f4-11e9-8d5a-ecadaf792b43.png)
The view should be accesible from "compare" section (https://github.com/benetech/ServiceNet/issues/102)
Selecting either this is similiar record or not should be read-only for now, so it should be disabled to avoid confusions.

**Comment by johnhbenetech** [comment]
See #25 for how to present on single page view

**Comment by oskarhinc** [comment]
Thanks, I think we'll finish the view as a part of this issue, and add logic for removing matches in the mentioned #25

**Comment by kcissewski** [comment]
Ok, so I'm closing this one as it's working properly.
