### ISSUE TITLE
SP Search bar should search additional fields

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1130]
We should open the SP search bar to searching on
* Organization name
* Service name
* Service description
* Eligibility

**Comment by abaranowska1** [comment]
**Tested with success**
- SP Search bar search additional fields : 

-- Organization name
-- Service name
--Service description
-- Eligibility

**Tested on:** 

- Ubuntu 18.04
- Google Chrome v. 84.0.4147.135
- Firefox v. 79.0
