### ISSUE TITLE
Accordions should start expanded on SP single record view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1131]
When a user clicks into the 'view' version of a single SP record all accordions should start expanded (org details, locations, services)

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:**
- When a user clicks into the 'view' version of a single SP record all accordions are expanded by default (org details, locations, services)
- Verified on public view and regular SP view

![image](https://user-images.githubusercontent.com/61964176/91536229-b136d580-e914-11ea-889c-88c7aab0ae13.png)

**Tested on:**
- Ubuntu 18.04
- Google Chrome v. 84.0.4147.135 
- Firefox v. 79.0
