### ISSUE TITLE
Add 'directions' button to map and location card

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1132]
A user should be able to open a google maps link (in a new tab) with the destination pre-populated to an address from the SP view. This button should be in two place:

* Map card view
- Added to any card displayed from clicking a pin, prepopulates with the location from the clicked pin
![image](https://user-images.githubusercontent.com/12927553/90920677-59491d80-e3ae-11ea-8776-53400ad38f11.png)

* Location card on single record view
- Added to each location card, prepopulates location from that card 
![image](https://user-images.githubusercontent.com/12927553/90920478-fa83a400-e3ad-11ea-8e36-0ed05bfc1cbb.png)

**Comment by pmuchowski** [comment]
@johnhbenetech on the map view I'm using the coordinates in the link to google maps, but on single records view the coordinates are not available, so I'm using the address is it fine or should I add the coordinates to the single record endpoint?

**Comment by johnhbenetech** [comment]
@pmuchowski the address is fine - it's probably better for the user to see something they are familiar with rather than coords

**Comment by abaranowska1** [comment]
- "Directions" button was added to the map and location card and after click on the button a google maps link (in a new tab) is opened with the destination pre-populated to an address from the SP view
![image](https://user-images.githubusercontent.com/61964176/91717160-36c6b980-eb91-11ea-872a-350864b2b58d.png)
- Button was added to every card displayed from clicking a pin and to every card with address on Single Record view
- Button was added to each location card, pre-populated location from that card
![Peek 2020-08-31 13-37](https://user-images.githubusercontent.com/61964176/91717135-2e6e7e80-eb91-11ea-8111-6add672b701e.gif)

@pmuchowski One issue: 
1. If you can please fix the UI on the location card. Directions button should be in the bottom right corner like it looks on mock and in my opinion the City name  ![image](https://user-images.githubusercontent.com/61964176/91717656-38dd4800-eb92-11ea-8a2e-43022b91b020.png) should be at the same high as the title on Service Details card
![image](https://user-images.githubusercontent.com/61964176/91717181-434b1200-eb91-11ea-892b-5f00ed9a8ce4.png)

**Comment by abaranowska1** [comment]
Confirmed that issue with Locations card on single record view is fixed. It look great now.
![image](https://user-images.githubusercontent.com/61964176/91814645-beb1cf80-ec34-11ea-8772-eca62276fafb.png)
![image](https://user-images.githubusercontent.com/61964176/91814650-c1142980-ec34-11ea-877d-a27158f692a4.png)
![image](https://user-images.githubusercontent.com/61964176/91817015-7810a500-ec35-11ea-9536-816e6f2f3e94.png)


@pmuchowski 
I also checked the second issue and it still needs to be fixed. The Direction button is smaller, but the text at the bottom of the card is off the card, just like before. 
![image](https://user-images.githubusercontent.com/61964176/91817486-970f3700-ec35-11ea-90b8-7b356702a360.png)

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:**

- "Directions" button was added to the map and location card and after click on the button a google maps link (in a new tab) is opened with the destination pre-populated to an address from the SP view
- Button was added to every card displayed from clicking a pin and to every card with address on Single Record view
- Button was added to each location card, pre-populated location from that card
- It works on both public and authenticated view
- On mobile view "Directions" button was changed to button with icon 

![image](https://user-images.githubusercontent.com/61964176/91957001-becdd000-ed05-11ea-83e6-8ba0e27fc627.png)


**Tested on:**

- Ubuntu 18.04
- Google Chrome v. 84.0.4147.135
- Firefox v. 79.0
- Mobile 360x640
