### ISSUE TITLE
ServiceProvider Feedback link

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1133]
Add 'Feedback' link to header next to 'Contact' in SP view. Available on both public and authenticated view

This can be a near duplicate of the Sacramento feedback modal (using the same feedback email, etc). #832

**Comment by abaranowska1** [comment]
@pmuchowski 
Feedback functionality works without any issues, but please change:
- "Send feedback" button to the pill button. Buttons should look the same in the whole SP View ( buttons were changed in this ticket #1065 )
- Add bigger padding above the word "Feedback", this page should be similar to Settings / Password pages
![image](https://user-images.githubusercontent.com/61964176/91714990-23195400-eb8d-11ea-9473-26df9e67f3e9.png)

For comparison:
![image](https://user-images.githubusercontent.com/61964176/91715036-37f5e780-eb8d-11ea-96b0-6f23fb790265.png)
![image](https://user-images.githubusercontent.com/61964176/91715045-3fb58c00-eb8d-11ea-98a5-b48d7c143396.png)

**Comment by abaranowska1** [comment]
- "Send feedback" button was changed to the pill button
- Page looks the same as Settings or Password page
- Feedback functionality works without any issues
- Feedback link was added to the header on both public and authenticated view

Chrome:
![image](https://user-images.githubusercontent.com/61964176/91822353-f9693700-ec37-11ea-97d7-661c4c86b9bc.png)
Firefox:
![image](https://user-images.githubusercontent.com/61964176/91822359-fbcb9100-ec37-11ea-9e69-4b2318cce96e.png)

@johnhbenetech In this ticket we talked about adding Feedback link to the header on both public and authenticated view. What about the mobile view ? Should the link to the feedback also be added to the hamburger menu?

**Tested on:**

- Ubuntu 18.04
- Google Chrome v. 84.0.4147.135
- Firefox v. 79.0

**Comment by johnhbenetech** [comment]
@abaranowska1 yes add to hamburger as well

**Comment by abaranowska1** [comment]
@pmuchowski 
Please add Feedback link to the hamburger menu.
![image](https://user-images.githubusercontent.com/61964176/91845503-938da700-ec59-11ea-893c-985c20a649dc.png)

**Comment by abaranowska1** [comment]
**Tested with success**

- "Send feedback" button was changed to the pill button
- Page looks the same as Settings or Password page
- Feedback functionality works without any issues
- Feedback link was added to the header on both public and authenticated view
- Feedback link was added also to the mobile view

| ---      | ---       |
| ![image](https://user-images.githubusercontent.com/61964176/91975603-f34e8580-ed1f-11ea-841a-1400f71dc73e.png) | ![image](https://user-images.githubusercontent.com/61964176/91975638-006b7480-ed20-11ea-97c9-08da2d67f22f.png) |

**Tested on:**

- Ubuntu 18.04
- Google Chrome v. 84.0.4147.135
- Firefox v. 79.0
- Mobile 360x640
