### ISSUE TITLE
Add 'my location' button to SP map view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1134]
clicking this button should launch the HTML5 geolocation function and center the map to your location (and refresh results once performance improvements made to map endpoint).

https://developers.google.com/maps/documentation/javascript/geolocation

Button should be similar to:
![image](https://user-images.githubusercontent.com/12927553/90925293-96191280-e3b6-11ea-832e-b0e1b46aca9d.png)

**Comment by pmuchowski** [comment]
@johnhbenetech the location icon is in the paid version of font awesome: https://fontawesome.com/icons/location?style=solid
Can I use something else like: https://fontawesome.com/icons/compass?style=regular or https://fontawesome.com/icons/map-marker?style=solid?
Or maybe you have an icon file you want to be used here?

**Comment by johnhbenetech** [comment]
@pmuchowski Let's go with compass right now as I explore other options

**Comment by johnhbenetech** [comment]
@pmuchowski sorry let's actually go with map marker for now

**Comment by pmuchowski** [comment]
@johnhbenetech it should be placed in the bottom right corner of the map, on the left side of the + and - buttons, right?

**Comment by johnhbenetech** [comment]
@pmuchowski yes that's fine

**Comment by abaranowska1** [comment]
@johnhbenetech 
In our old view after clicking "My current location" button the map is centered to your location and the location is marked by a pin 
![image](https://user-images.githubusercontent.com/61964176/91834640-9c29b180-ec48-11ea-9b4a-8433d1e4ae70.png)

Now in SP View after clicking location button the map is only centered to your location, but without any pin or blue circle like in the description.
What do you think about it ? Should we add a pin or circle ?

**Comment by johnhbenetech** [comment]
@abaranowska1 I guess the blue circle is a 'nice to have'. If it's something trivial to add then yes, if it would take more than an hour or two wee can forget it for now

**Comment by abaranowska1** [comment]
@pmuchowski Please investigate if adding a blue circle will take more than one hour or it is something quick

**Comment by abaranowska1** [comment]
**Tested with success**
According to the last meeting, blue pin was added to the map view. After clicking "My location" button, your current location is marked with a blue pin.
![image](https://user-images.githubusercontent.com/61964176/91974042-80dca600-ed1d-11ea-81e7-0586c6a55f32.png)

**Tested on:**

- Ubuntu 18.04
- Google Chrome v. 84.0.4147.135
- Firefox v. 79.0
