### ISSUE TITLE
UI issue on ServiceProvider data entry Page for new record creation

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#1135]
UI issue on ServiceProvider data entry Page for new record creation. One tab is too narrow on mobile view ( 360x640 )
![image](https://user-images.githubusercontent.com/61964176/91046247-5c474680-e618-11ea-995f-a1a6ea2c7d75.png)

**Verified on:**
- Ubuntu 18.04
- Google Chrome 84.0.4147.125
- Mobile 360x640

**Comment by awalkowiak** [comment]
Dev note: `white-space: nowrap` on this should be enough

**Comment by abaranowska1** [comment]
**Tested with success**
ServiceProvider data entry Page for new record creation looks fine on mobile now

![image](https://user-images.githubusercontent.com/61964176/91726244-3681ea80-eba0-11ea-9bcd-ebe194562aee.png)

**Tested on:**
- Mobile iPhone X
- Mobile 360x640
