### ISSUE TITLE
Edge UI issue - cards size

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#1140]
On the Edge browser, while opening card with filtering feature, it's not as high as two organizations cards.

**Reproduction**
- Open Edge and log in as service provider
- Click "Filter" pill

**Expected result**
- Card with filtering feature is twice high as organization card

**Environment**
- Edge browser
-- v83.0.478.58
-- v84.0.522.63 on Windows 10

**Attachments**
- Edge
![Screenshot from 2020-08-25 16-06-40](https://user-images.githubusercontent.com/51324797/91186272-24f79900-e6ef-11ea-9286-f0a9caace656.png)

- Chrome (for comparison)
![Screenshot from 2020-08-25 16-08-59](https://user-images.githubusercontent.com/51324797/91186286-29bc4d00-e6ef-11ea-811d-abc9fca5f51c.png)

**Comment by abaranowska1** [comment]
Screenshot from Edge v 84.0.522.63, Windows 10 OS
![1](https://user-images.githubusercontent.com/61964176/91310908-bbd95980-e7b2-11ea-9fd1-5102ca52bc4e.PNG)

**Comment by bognasoldev89** [comment]
@johnhbenetech I revisited this page on both of my Edge browsers and this issue doesn't occur anymore - it looks like on Alicja's screenshot.
I propose to close this issue.

**Comment by johnhbenetech** [comment]
Confirmed on my side
