### ISSUE TITLE
UI issue - empty space in the middle of the Service Provide main page with filter card on

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#1141]
Cards arrangement is improper when the filter card is displayed.

**Reproduction**
- Log in as a service provider
- Click "Filter" pill

**Expected result**
- On the left of the filter card, 6 organizations cards should be put

**Environment**
- Chrome 83.0.4103.116
- Firefox 79.0
- Edge
-- 83.0.478.58
-- 84.0.522.63 on WIndows 10

**Attachment**
![Screenshot from 2020-08-25 16-08-59](https://user-images.githubusercontent.com/51324797/91186965-eca48a80-e6ef-11ea-9a28-d7ba2b00871f.png)

**Comment by abaranowska1** [comment]
**Tested with success**
There is no empty space in the middle of the Service Provider main view with filter modal on. Filter card is two lines high.
![image](https://user-images.githubusercontent.com/61964176/91561558-2073f000-e93c-11ea-8f02-4739114ecec0.png)
![image](https://user-images.githubusercontent.com/61964176/91561567-22d64a00-e93c-11ea-8b4b-f42710893618.png)

**Tested on:**

- Ubuntu 18.04
- Google Chrome v. 84.0.4147.135
- Firefox v. 79.0
