### ISSUE TITLE
UI issue - "x" icons on the filtering card became too small

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#1143]
While using filtering feature on the Service Provider view, on pills with chosen options "x" icon is available. Those get much smaller though and look like dots.

![ServiceNet - Google Chrome_001](https://user-images.githubusercontent.com/51324797/91273971-50759480-e77e-11ea-9977-dbc729836d72.png)

For example, compare those to gifs available in #1007

**Comment by abaranowska1** [comment]
**Tested with success**
The "X" icon on the filtering card now is in the perfect size.
![image](https://user-images.githubusercontent.com/61964176/91562219-1f8f8e00-e93d-11ea-82f5-5d13c9d3fa22.png)

**Tested on:**

- Ubuntu 18.04
- Google Chrome v. 84.0.4147.135
- Firefox v. 79.0
