### ISSUE TITLE
While using filters a double scroll bar appears

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#1144]
While using filters on the Map View ( City and Zip Code ) a double scroll bar appears.

Chrome v. 84.0.4147.135 - City and Zip Code filters
![Peek 2020-08-26 09-43](https://user-images.githubusercontent.com/61964176/91276438-d6dfa580-e781-11ea-84a5-b8c00a4dd61b.gif)
![Screenshot from 2020-08-26 09-55-59](https://user-images.githubusercontent.com/61964176/91276983-87e64000-e782-11ea-9ea0-9df8ca6f2dae.png)

Firefox v 79.0 - only Zip Code filter
![Peek 2020-08-26 09-44](https://user-images.githubusercontent.com/61964176/91277018-93396b80-e782-11ea-85dd-cccfe3d6a2d9.gif)

**Expected result:** 
It should be only one scroll bar

**Comment by awalkowiak** [comment]
Dev note: The `overflow: hidden` on div with css class .background fixes this issue, but this has to be tested.

**Comment by abaranowska1** [comment]
**Testes with success:**
Confirmed that issue with doubled scroll bar is fixed. 
I checked filters on: 
-- Grid View
-- Map View 
-- Public View

![Peek 2020-08-27 14-23](https://user-images.githubusercontent.com/61964176/91441702-f7d2f400-e870-11ea-9862-e60459508a2d.gif)

**Verified on:**
- Ubuntu 18.04 OS
- Google Chrome v.  84.0.4147.135
- Firefox v 79.0
