### ISSUE TITLE
Evaluate browser performance improvements from Lighthouse report

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1154]
Evaluate the 'performance' recommendations that are generated from running Chrome's [lighthouse tool](https://developers.google.com/web/tools/lighthouse).

Depending on the complexity of performance improvements, feel free to break larger efforts into separate tasks. Please let me know if there is anything I can help with like providing smaller images, etc.

**Comment by kdondziak** [comment]
@johnhbenetech I've used the lighthouse tool on the production server (SP view) (login, home, mapview, single record view, record create pages). I've gathered performance issues from reports: 
Performance:
	critical lever issues:

		Defer offscreen images
		Consider lazy-loading offscreen and hidden images after all critical resources have finished loading to lower time to interactive

		Serve images in next-gen formats
		Image formats like JPEG 2000, JPEG XR, and WebP often provide better compression than PNG or JPEG, which means faster downloads and less data consumption.

		Properly size images
		Serve images that are appropriately-sized to save cellular data and improve load time.

		Minify JavaScript
		Minifying JavaScript files can reduce payload sizes and script parse time

		Ensure text remains visible during webfont load 
		Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading

		Minimize main-thread work
		Consider reducing the time spent parsing, compiling and executing JS. You may find delivering smaller JS payloads helps with this. 

	medium-level issues:

		Remove unused CSS
		Remove dead rules from stylesheets and defer the loading of CSS not used for above-the-fold content to reduce unnecessary bytes consumed by network activity.

		Defer offscreen images
		Consider lazy-loading offscreen and hidden images after all critical resources have finished loading to lower time to interactive

Non-performance:

	Ensure text remains visible during webfont load
	Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading

	Background and foreground colors do not have a sufficient contrast ratio. 
	Low-contrast text is difficult or impossible for many users to read.

	Form elements do not have associated labels. 
	These are opportunities to improve the semantics of the controls in your application. This may enhance the experience for users of assistive technology, like a screen reader.
Here are the original reports:
[lhreports.zip](https://github.com/benetech/ServiceNet/files/5161007/lhreports.zip)

**Comment by kdondziak** [comment]
@abaranowska1 QA note: Pay attention to all images on the app and fonts.

**Comment by kdondziak** [comment]
@johnhbenetech I've managed to reduce/optimize images/SVGs size. Also, I made some initial scripts asynchronous and made images loading lazily. This should decrease the loading time significantly.

**Comment by abaranowska1** [comment]
@kdondziak 
I noticed that the font on service provider view is slightly different. Look for example for the letter "a" 
Before changes: 
![image](https://user-images.githubusercontent.com/61964176/92119314-edc46e80-edf7-11ea-899a-9ba081b95530.png)
After changes: 
![image](https://user-images.githubusercontent.com/61964176/92119168-bfdf2a00-edf7-11ea-8d8a-5ced45ecd81e.png)
