### ISSUE TITLE
Explore further performance improvements for pin loading on map

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1155]
Building off of #1121, come up with technical recommendation and scoping for possible future improvements to pin loading.

I guess my thought (which may not be a good one) was to create a new endpoint specifically for the map where the major parameters are GPS coordinates. In that way you could send the API a set of coordinates and a distance and the endpoint returns our locations within that distance.

In this interaction we would only fetch the locations that are within the user's chosen map viewpoint (aka those that would display within the boundaries of where the user navigated to within the map frame). My question repeated below:

The pagination would occur within that request to by default only return the first X locations in that distance (where X is determined through testing). That way a user would have to add filters or zoom in to see ALL the locations if they set a condition where it would return 100s of locations.

**Comment by jkondrat** [comment]
@johnhbenetech
1. I think that having location limit might be misleading, we would have to inform the user that we are displaying X of N locations. We would still have to count these, so it would mainly reduce response size, not the database load. 
2. Perhaps we could divide the map into sectors so we avoid fetching the same locations repeatedly.
3. Should we also add a spinner indicating that the pins are loading?

**Comment by johnhbenetech** [comment]
@jkondrat I guess we should test this endpoint/performance as part of the greater performance testing tasks and maybe use that data to make a more informed decision.

I just dont understand how the system will perform if there 1000s of location pins (but maybe testing will show that I'm wrong). Best case the response takes a super long time to return, worst case attempting to render the pins crashes the browser. Additionally, a map showing 1000 pins in a small area is probably unusable as the map will be obscured by pins and the user may not be able to click on specific pins since there are so many.

We could do #3 as a band-aid until we have a better answer.

I guess i don't understand how #2 would work or how it is different than loading pins based on map view boundary? Can you give more details on that @jkondrat ?

As far as #1 goes, when i look at how other map-based sites approach the problem (yelp, google maps, trulia) it seems to be somewhat common to limit the pins per view (obviously i acknowledge these sites have insanely higher cost infrastructure and graph-DBs etc). Based on performance testing we can limit the results to the first X results (possibly using pagination where we only get the first page) and if there are more than that we also include something like 'only the first X records are shown'. The other common paradigm i see is the 'redo search in this area' type button - whereby you arent thrashing the DB constantly, but rather doing some initial load - then when the user moves the map offering them to hit the DB again for updated view of records.

What do you think? We could take part of this task to research the current performance and go from there?

**Comment by jkondrat** [comment]
@johnhbenetech 
#1 I agree, it makes sense to paginate if we inform user that there are more records and make it possible to redo search

About #2: We could divide the world map into grid (use sth like https://en.wikipedia.org/wiki/Geohash) We could then cache the cells and only request the ones that were not loaded yet when the user moves the map. We could implement this if pagination and general performance improvements are not enough.

**Comment by jkondrat** [comment]
note for QA: I have set the pin limit to 50, so you'll probably have to add a couple of records to Silo1

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:**

- "Search this area" button was added to the map view
- The spinner icon is displayed during loading the pins
- After click "Search this area" button max 50 pins are shown on the map in the current approximate area, when it is more than 50 records, notification is displayed and you should zoom in the area. 

![Peek 2020-09-08 13-16-min](https://user-images.githubusercontent.com/61964176/92477207-7ec48c80-f1e0-11ea-9564-a524cf43139e.gif)


**Verified on:**

- Ubuntu 20.04
- Google Chrome 85.0.4183.83
- Firefox 80.0
