### ISSUE TITLE
Implement accessibility improvements from Lighthouse report

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1156]
Evaluate the 'accessibility' recommendations that are generated from running Chrome's [lighthouse](https://developers.google.com/web/tools/lighthouse) tool.

Depending on the complexity of performance improvements, feel free to break larger efforts into separate tasks.

**Comment by kdondziak** [comment]
@johnhbenetech Lighthouse pointed out that some background colors have insufficient contrast and suggest to change them. In most cases, it is enough to change gray color to a little darker gray, but in one case there is a need to change #67bba4. I found that #3b7b65 is acceptable. Are you good wi that? See how it would look like.
Old:
![image](https://user-images.githubusercontent.com/52406204/92370793-1059ce80-f0fb-11ea-8c07-16f1fc144001.png)

New:
![image](https://user-images.githubusercontent.com/52406204/92370746-fe782b80-f0fa-11ea-9fa4-996c1d971988.png)

**Comment by johnhbenetech** [comment]
@kdondziak yes that's great

**Comment by kdondziak** [comment]
@abaranowska1 Things that have changed:
* Some labels color changed from light gray to darker gray
* Background of the apply pill on filter card. 
* Text on the home page (old view)

**Comment by abaranowska1** [comment]
**Tested with success**
Labels, background, buttons, and text look fine. Some labels color changed from light gray to darker gray, background of the apply and add new record pill buttons were changed. 
![image](https://user-images.githubusercontent.com/61964176/92599721-ee9f4980-f2aa-11ea-86e8-beca3d0ad854.png)

**Verified on:**
- Ubuntu 20.04
- Chrome v. 85.0.4183.83 
- Firefox v. 80.0
