### ISSUE TITLE
Handle common JS console errors

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1157]
Every time a user visits the homepage, the following JS errors are logged:
![image](https://user-images.githubusercontent.com/12927553/91617051-b879d580-e94c-11ea-89af-2d08f654686a.png)

Especially as we implement Sentry - we should try to prevent/catch these errors (even though they aren't detrimental)

**Comment by kdondziak** [comment]
Estimated also for other places where 401 happens. Consider fixing key prop error.

**Comment by abaranowska1** [comment]
@pmuchowski 
I met JS console error during logging out from Service Net App 
![Peek 2020-09-09 09-51](https://user-images.githubusercontent.com/61964176/92575008-1f21bc00-f288-11ea-9977-b7d1cb365ea8.gif)
![Selection_008](https://user-images.githubusercontent.com/61964176/92575000-1c26cb80-f288-11ea-8e21-6452ce2053b9.png)

**Comment by abaranowska1** [comment]
@pmuchowski 
I met JS console error during logging out from Service Net App
![image](https://user-images.githubusercontent.com/61964176/92737335-54f39d00-f37b-11ea-84c1-8695572b3730.png)

**Comment by awalkowiak** [comment]
@abaranowska1 seems like we can't handle that one on our end. See: https://stackoverflow.com/a/42986081

**Comment by abaranowska1** [comment]
@awalkowiak Ok, so I will close this issue.
