### ISSUE TITLE
Enable password field for browser autofill

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1158]
Log:

[DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: ![https://goo.gl/9p2vKq](https://goo.gl/9p2vKq) 

<input name=​"password" placeholder=​"Your password" required id=​"password" type=​"password" class=​"is-touched is-dirty av-valid form-control" value=​"XXXXXX>​

**Comment by abaranowska1** [comment]
**Tested with success**
"Current Password" input element have autocomplete attributes
![image](https://user-images.githubusercontent.com/61964176/91984808-93aaa700-ed2c-11ea-84f7-0265e4eacac4.png)
Autofill depends on browser, for example it is not working on Chrome, but it is available on Firefox. 
![image](https://user-images.githubusercontent.com/61964176/91987098-e20c7580-ed2d-11ea-8231-6898f1777b0a.png)
![image](https://user-images.githubusercontent.com/61964176/91987122-eb95dd80-ed2d-11ea-9e8b-2f1b456b6b46.png)
