### ISSUE TITLE
Add admin page for user_profile_organizations

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1159]
Open to recommendations here. Basically i'd like the admin interaction to be the following:

* All existing ServiceProvider organizations will show as rows in this admin page along with the current username of the owner

* Is there any support for adding searching or filtering within an admin page? Ideally an admin would be able to enter an organization name in order to assist in finding the right row to change

* I dont think there should be the ability to delete nor add a new record - since that has lots of ramifications that break cascading elements, silos, usergroups, etc.

* Admin can select username from a single select dropdown (so we need to make the user_profile_id>user_profile>username translation for the user)

**Comment by jkondrat** [comment]
@johnhbenetech : Does this look good?
![Screenshot from 2020-09-01 19-10-05](https://user-images.githubusercontent.com/5969801/91884689-cdc16d80-ec86-11ea-81e2-fb90ad3953bb.png)
![Screenshot from 2020-09-01 19-09-31](https://user-images.githubusercontent.com/5969801/91884694-cef29a80-ec86-11ea-82c9-bd9a0e46e2f5.png)
![Screenshot from 2020-09-01 19-09-57](https://user-images.githubusercontent.com/5969801/91884696-d0bc5e00-ec86-11ea-839c-f2440578cb77.png)

**Comment by jkondrat** [comment]
Perhaps we could keep the name consistent and stay with 'Organization owners'

**Comment by johnhbenetech** [comment]
@jkondrat looks good. Let's go with organization owner

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:**
- All existing ServiceProvider organizations show as rows in the organization owner admin page along with the current username of the owner
![Screenshot_2020-09-04_16-49-08](https://user-images.githubusercontent.com/61964176/92252494-993ff280-eece-11ea-9004-c79a037eb901.png)
- Search bar was added to this page and it is possible to search organizations by name 
- There is no Delete option , but Edit is enabled and works without issues
- After changing the Owner, the Organization automatically is moved from Your Own record to another Owner 
- Admin can select username from a single select dropdown 

**Verified on:**
- Ubuntu 20.04 OS
- Google Chrome Version 85.0.4183.83
