### ISSUE TITLE
Fix issues with css classes bleeding out between different components

### ISSUE THREAD

**Issue by pmuchowski** [benetech/ServiceNet#1167]
The classes used in multiple components should be moved to a separate, shared file.
Each view should have a unique class at the top component which would be a root for all its classes.

**Comment by abaranowska1** [comment]
**Tested with success**
Thanks, @jkondrat for all the fixes. I caught some UI issues after css classes changes. 
- Scroll bar is working fine now 
![image](https://user-images.githubusercontent.com/61964176/92924685-a6faf800-f439-11ea-86e8-1643f14a35c1.png)

- Video on the homepage display in the bigger window 
![Selection_026](https://user-images.githubusercontent.com/61964176/92924775-c42fc680-f439-11ea-9de9-6c51b8c8f352.png)

- Mobile View was fixed. All buttons and headers on traditional and public view looks better 
![Selection_035](https://user-images.githubusercontent.com/61964176/92925079-402a0e80-f43a-11ea-9735-e5d5d99416d4.png)
![Selection_036](https://user-images.githubusercontent.com/61964176/92925082-40c2a500-f43a-11ea-86c7-a81e96e10a55.png)
![Selection_037](https://user-images.githubusercontent.com/61964176/92925084-415b3b80-f43a-11ea-8ff0-24ba7f2b488c.png)
![Selection_038](https://user-images.githubusercontent.com/61964176/92925087-41f3d200-f43a-11ea-9893-b53ed1854a8d.png)
![Selection_039](https://user-images.githubusercontent.com/61964176/92925089-41f3d200-f43a-11ea-802d-17e0739fcfe5.png)
![Selection_040](https://user-images.githubusercontent.com/61964176/92925090-428c6880-f43a-11ea-934f-7d9bbe1a62f7.png)
![Selection_041](https://user-images.githubusercontent.com/61964176/92925091-428c6880-f43a-11ea-9fd7-da17762b89f0.png)
