### ISSUE TITLE
CBO Interface: MOVE “About” and “Contact” to the bottom of the page

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1170]
MOVE “About” and “Contact” to the bottom of the page 

**Computer View**
- Always at the bottom right (as you scroll down "About" and "Contact" should be floating on the bottom right) 
- Keep same font, size, color (black), as it had on the header (next to the benetech logo)
- highlight Hex #89cff0 when you hover over it

<img width="1526" alt="Annotation 2020-09-02 091301" src="https://user-images.githubusercontent.com/65787629/92008829-82e23d00-ecfc-11ea-9b7d-6e51809daaa6.png">

**Mobile View**
- As you scroll down, About and Contact should be next to "Load More"
- Half the font as the dropdown from the hamburger menu
- Black letter color 
- highlight Hex #89cff0 when you hover over it

<img width="247" alt="Annotation 2020-09-02 091751" src="https://user-images.githubusercontent.com/65787629/92009341-39deb880-ecfd-11ea-88ab-acc82b3ef649.png">

**Comment by johnhbenetech** [comment]
I don't think we would do this for a few reasons. Generally speaking 'floating' elements are bad practice from an accessibility standpoint so we try to avoid when possible. When a user is using their tab key/swipe to navigate it helps to have the order of elements in a fixed order. floating elements are difficult to do that right and it seems like a hassle for a relatively unimportant change.

 I would rather remove these items entirely (if they aren't important enough to be in the nav, we prob don't need them at all). Please make sure that this task and #1169 reflect the same design if you update it. For instance where would 'Feedback' go? We can't do this piecemeal - I'd rather have one task that reflects the final intended design.

One place to consider is that there is also the user drop down in the top right where we can put less important/less used links

**Comment by johnhbenetech** [comment]
@EnriqueCorado im closing this as it has been replaced by #1197
