### ISSUE TITLE
CBO Interface: Adding a refer button to each record 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1173]
- To each record on the CBO interface that is not theirs (the one they are at and referring from) 
- Add the black (Hex color Code #000000)  “Refer” click on 
- When you hover over it it will turn Aqua (Hex color code #00FFFF) 
- Once it has been clicked it will turn green (Hex color #0B6623) and add a checkmark next to it 

<img width="470" alt="Annotation 2020-09-02 100050" src="https://user-images.githubusercontent.com/65787629/92013862-30584f00-ed03-11ea-9b3b-d2e1b602c1c5.png">

- Once clicked Item gets added to the referral page
**when you click on the website below, click on the referral tab on the top menu bar, then click on referral, that is where items are added to the referral pafe**
https://e34vsd.axshare.com
- User can continue adding items to cart

**Comment by EnriqueCorado** [comment]
@johnhbenetech any more detail on this task?

**Comment by johnhbenetech** [comment]
@EnriqueCorado what happens when you click the button besides the color change?

**Comment by EnriqueCorado** [comment]
- To each record on the CBO interface that is not theirs, basically not the records the logged CBO logged on owns
- Add the black (Hex color Code #000000)  “Refer” click on 
- When you hover over it it will turn Aqua (Hex color code #00FFFF) 
- Once it has been clicked it will turn green (Hex color #0B6623) and add a checkmark next to it 

<img width="470" alt="Annotation 2020-09-02 100050" src="https://user-images.githubusercontent.com/65787629/92013862-30584f00-ed03-11ea-9b3b-d2e1b602c1c5.png">

- Once clicked Item gets added to the referral page
**when you click on the website below, click on the referral tab on the top menu bar, then click on referral, that is where items are added to the referral page**
https://e34vsd.axshare.com
- User can continue adding items to cart

**Comment by johnhbenetech** [comment]
This should also be added to the card when clicking a map pin on desktop/mobile

**Comment by kkaczmarczyk** [comment]
@johnhbenetech @EnriqueCorado I am considering the caching mechanism for this behavior - whether data should be cached locally in the browser or kept in DB at this point. Should the referrals created on this page be saved across logins/sessions of users on different PCs?

**Comment by EnriqueCorado** [comment]
Cached locally in the browser. Referrals should be saved across logins/sessions of users on different PCs. Thank you!

**Comment by johnhbenetech** [comment]
@EnriqueCorado if you want them saved across logins I believe you want them written to the DB

**Comment by EnriqueCorado** [comment]
@johnhbenetech only saved when they send the referral/check out

**Comment by johnhbenetech** [comment]
@EnriqueCorado understood. So using the e-commerce metaphor:

* Things in the cart will be cached in browser user session
* Completed orders (referrals) saved to DB

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:**
- Refer button was added to the card
![image](https://user-images.githubusercontent.com/61964176/95075429-6dec3580-0710-11eb-9ee8-c3100d1112ee.png)
- When we hover over it it will turn to blue
- Once it has been clicked it  turns green and a checkmark icon is displayed next to it
- It is possible to unclick the button
