### ISSUE TITLE
CBO Interface: Indication for recently updated records

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1179]
Current: The record/cards for services currently has a bookmark icon for indicating recently updated record.
Problem: The bookmark icon is generally associated with saving things for later use. This might create a wrong impression of what it does on our website.
Solution: The icon for recently updated could be change to a small circle and the color indication could follow the following logic:
for any card updated in the last 7 days: green circle
for any card updated in the last 7 to 30 days: orange circle
for any card updated before the last 30 days: gray circle. 

![Frame 1Benetech_last update indication](https://user-images.githubusercontent.com/12637929/92166357-7cd88300-ee06-11ea-93c6-16b8c223d9aa.png)

**Comment by abaranowska1** [comment]
**Tested with success**
The icon for recently updated records changed to the circles

![image](https://user-images.githubusercontent.com/61964176/95073182-ad188780-070c-11eb-9a64-a753c4c29795.png)

- for any card updated in the last 7 days: green circle
- for any card updated in the last 7 to 30 days: orange circle
- for any card updated before the last 30 days: gray circle

@johnhbenetech @sidmundhra @EnriqueCorado 
I can see that on the mockup in the description this green circle has a light green color, but I'm not sure if it matches our app and the 'Add a New Record ' button. We recently had this color = 6AB9A4 # 1044. What do you think?
![image](https://user-images.githubusercontent.com/61964176/95073975-046b2780-070e-11eb-9141-70f27acd7476.png)

**Comment by johnhbenetech** [comment]
Use the same green

**Comment by sidmundhra** [comment]
Thanks @johnhbenetech . @abaranowska1 : as John mentioned, please use the same green.

**Comment by abaranowska1** [comment]
**Tested with success**
Color of recently update records has been changed
![image](https://user-images.githubusercontent.com/61964176/95315623-03173780-0893-11eb-8094-076d8cd8140d.png)
![image](https://user-images.githubusercontent.com/61964176/95315631-06aabe80-0893-11eb-8ac6-31f86f1031a5.png)

**Comment by sidmundhra** [comment]
This looks good. Works as intended. Confirm for release.
