### ISSUE TITLE
Add location to confllict detection

### ISSUE THREAD

**Issue by wojtekbu** [benetech/ServiceNet#118]
Add a location conflict detector and include it in the workflow. Also, make sure that detecting works properly for more than one entity type.

UPDATE:
Since #79 we store multiple locations in Organization. LocationEquivalent will have to be created in the scope of this ticket.

UPDATE 01/22/19:
We have to handle situations in which there is more than one location assigned to an organization. At first, we can create a conflict for every pair of location that we cannot match, but in the future, we should find a way to match them e.g. using a distance to decrease the number of conflicts.

**Comment by johnhbenetech** [comment]
out of date
