### ISSUE TITLE
CBO Interface: Sort by Descending order of updates

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1180]
On the CBO interface, cards that are most recently updated should appear first when looking from left to right.
Currently: Cards are sorted from left to right based on the creation date/time.
Problem: Cards that are most recently updated may not be visible to users as they may flow out of screen based on their creation date. 
Solution: Sort by last updated date/time. Card which are most recently updated should appear before cards updated earlier when looking from left to right.

![Frame 5Benetech_last updated card](https://user-images.githubusercontent.com/12637929/92169247-db066580-ee08-11ea-9595-5a09ccca4622.png)

**Comment by abaranowska1** [comment]
**Tested with success**
Cards that are most recently updated sort by descending order of updates from left to right.
![Peek 2020-10-02 15-27](https://user-images.githubusercontent.com/61964176/94928352-d7c3cf80-04c3-11eb-88c3-3c982e13dd8f.gif)

**Verified on:**

- Ubuntu 20.04
- Google Chrome v. 85.0.4183.83
- Firefox v. 80.0

**Comment by sidmundhra** [comment]
This looks good. Works as intended. Confirm for release.
