### ISSUE TITLE
CBO Interface: Map view ends abruptly.

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1181]
On the CBO interface: When on Map view, there's are large part of the top updates part that takes up space which feels like the page ends abruptly. 

One solution is to add more details in the footer so there's ample space for the map to be centralized on the page.

![Frame 3Benetech_Servicenet](https://user-images.githubusercontent.com/12637929/92173827-19505480-ee0a-11ea-91b2-ac3040988e59.png)

**Comment by abaranowska1** [comment]
**Verified cases:**
- ' Your records ' are not displayed anymore on the map view
- Map is centered
- More space is added to the footer
- Map looks the same on public and traditional sp view
![image](https://user-images.githubusercontent.com/61964176/95071839-94a76d80-070a-11eb-9165-c22efa40657f.png)
![image](https://user-images.githubusercontent.com/61964176/95071861-9cffa880-070a-11eb-8a37-50a4ff726d31.png)

I checked also if something has changed on mobile and I met one UI issue on mobile public view, @jkondrat it is related to this issue? 
![image](https://user-images.githubusercontent.com/61964176/95071819-8ce7c900-070a-11eb-8d37-c1ebdb7b217c.png)

**Verified on:**
- Ubuntu 20.04
- Google Chrome Version 85.0.4183.83 
- Firefox Version 80.0

**Comment by abaranowska1** [comment]
**Tested with success**

- ' Your records ' are not displayed anymore on the map view
- Map is centered
- More space is added to the footer
- Map looks the same on public and traditional sp view
- Mobile view was fixed 

![image](https://user-images.githubusercontent.com/61964176/95320639-08c44b80-089a-11eb-87d8-9b6a841c4622.png)
![image](https://user-images.githubusercontent.com/61964176/95320672-1548a400-089a-11eb-84ff-eb01494c3d85.png)

**Verified on:**

- Ubuntu 20.04
- Google Chrome Version 85.0.4183.83
- Firefox Version 80.0
- Mobile 360x640
