### ISSUE TITLE
Map view ideas

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1182]
It is better practice if users could see a list on the side with map view to get an idea of where each service is located. The idea is to give users information on how close the service they seek is and when was it last updated. 

The service list will be sorted by most recently updated on the top.

![2020-09-03 17_16_28-File Explorer](https://user-images.githubusercontent.com/12637929/92175459-a5fb1280-ee0a-11ea-91f9-69bc4d4d7ac7.png)

![image](https://user-images.githubusercontent.com/12637929/92175513-bb703c80-ee0a-11ea-91b6-d97e1cc0ac9f.png)

**Comment by johnhbenetech** [comment]
@sidmundhra how would this change the mobile view?

**Comment by sidmundhra** [comment]
@johnhbenetech - apologies for the delay here. 

In developing the map view, I'm currently assuming that the user would primarily use a browser to access ServiceNet and not through an app.(Apps have more flexibility, though)

This is how I envision our mobile map view should look like, with toggles for list and map view. This screen currently is clicked on a restaurant to show how it would look if we picked a service on the map.

![X - 2ServiceNet Map view](https://user-images.githubusercontent.com/12637929/93942299-258b4b80-fcfe-11ea-9eab-66697d6ac19f.png)

The next screen is for how filters would look on the map view.
![X - 3Map View Filters](https://user-images.githubusercontent.com/12637929/93942303-27550f00-fcfe-11ea-8a79-56d509475bcf.png)

P.S- yes, I've used Yelp again. I researched Google Maps on chrome on phone as well. Every company does almost the same version of map view, except the design for the card if sth is selected. I went with the quickest/easiest one to develop.

**Comment by johnhbenetech** [comment]
I'm not passing #1182 or #1213 through to dev. They aren't clearly defined and overlap/contradict each other at times.

If you want a change, please provide mobile and desktop mockups that actually use the SN interface and describe all interactions. We are setting ourselves up for failure by providing mockups with entirely different design systems.

**Comment by johnhbenetech** [comment]
@sidmundhra @EnriqueCorado can we close these out if they no longer relevant?
