### ISSUE TITLE
"My Location" improvement after pin loading improvement

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1186]
After the pin loading improvement (i believe) the 'my location' button no longer navigates the map to your location (the blue pin is still added).

Can we change the 'my location' button to do both of the following:

1. Change the map view to be centered around the blue pin

2. Perform the 'search in this area' call to load pins within 5 miles lets say.

5 Miles doesnt need to be perfect or anything, so whatever is easiest to implement with a square frame is fine

**Comment by johnhbenetech** [comment]
@jkondrat I'll let QA chime in, but one thing I'm noticing is that now the 'Search in this Area' button now often recenters you somewhere weird.

So for example i hit 'my location' and get centered around my location (chicago) - great. Now i move the map over to the SF area and hit the Search in this area button - the map is recentered back to chicago and loses where i was focused

**Comment by abaranowska1** [comment]
@johnhbenetech You're right, something weird is happening.  I tried to reproduce this issue: 
@jkondrat 
1. Go to the map view
2. Click "My location" icon - blue circle icon should display near your current location 
3. Move to map for example near Chicago 
4. Click "Search this area" button

**Actual Result:** The map is centered around your current location, the blue icon is still displayed
**Expected Result:** The map should not be centered around your location, but should remain in the search area, for example Chicago.

![Peek 2020-09-10 10-44-min](https://user-images.githubusercontent.com/61964176/92707536-a8eb8b00-f355-11ea-81b3-a1cac40ae124.gif)


Second issue which I found is also interesting. I remember a gif from #1155 and "Search this area" button works without issue, but now I noticed that when I didn't use "My location" button, but only move the map for example near Chicago, and click "Search this area" button, the map is centered to Sacramento/SanFrancisco area.

1. Go to the map view
2. Zoom the map near Chicago 
3. Click "Search this area" button

**Actual Result:** The map is centered to Sacramento/SanFrancisco area, but pins are displayed near Chicago. 

![Peek 2020-09-10 10-45-min](https://user-images.githubusercontent.com/61964176/92707506-a38e4080-f355-11ea-9496-a9986309670d.gif)

Third one: 
@johnhbenetech The first time we go to the map view and click "My Location" the map is centered and zoomed in to your location, but when we zoom out and click "My Location" again, the map is only centered, not zoomed in. Should it also be zoomed each time the button is clicked?
![Peek 2020-09-10 11-27-min](https://user-images.githubusercontent.com/61964176/92712411-e520ea80-f359-11ea-8666-b3cded45fd92.gif)

**Comment by abaranowska1** [comment]
**Tested with success**
- The map is centered and zoomed near your current location ( blue circle ) only after clicking "My location" button 
- The map is not centered to Sacramento/SanFrancisco area when pins are displayed near Chicago
- "Search in this area" button call to load pins from zoomed area 
- When we go to the map view and click "My Location" the map is centered and zoomed in to your location every time after click the button 

![Peek 2020-09-11 13-42-min](https://user-images.githubusercontent.com/61964176/92921777-fbe83f80-f434-11ea-963d-c84b655f0d60.gif)

**Verified on:**
- Ubuntu 20.04
- Google Chrome v. 85.0.4183.83
