### ISSUE TITLE
Change out my location icon and size

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1187]
After doing a few user tests of the map feature, the following changes surfaced:

1. Please change out the blue pin to a blue circle (similar to google maps)

2. As far as the size goes, the feedback was the pin was too large. I guess the goal would to be to emulate the google map circle as close as possible (especially as the user zooms the map, the circle should change in size accordingly).

**Comment by abaranowska1** [comment]
**Tested with success**
- blue pin is changed to a blue circle
- as the user zooms the map, the circle change in size accordingly
![Peek 2020-09-10 11-45-min](https://user-images.githubusercontent.com/61964176/92714062-008cf500-f35c-11ea-9a2a-6b4f734752ee.gif)
**Verified on:**
- Ubuntu 20.04
- Google Chrome v.85.0.4183.83
