### ISSUE TITLE
Service Net Referral SMS Number 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1190]
From KP: "A short number may be preferable. For example, I get a reminder for prescription refills or AAA from numbers that have the format 123-456 or 123-45. These do not look like a phone number and will not confuse people."

- From Twilio, a unique phone number that doesn't resemble a normal phone number in order for the number to be easily recognizable that is from service net

**Comment by johnhbenetech** [comment]
Just as a note, a short-code is ~$11,500/year compared to $10/year for a regular number.

**Comment by EnriqueCorado** [comment]
Is there an option for a number, for example, 123-111-111? Some number that's not so ordinary so people can recognize quick it's from Service Net then

**Comment by johnhbenetech** [comment]
@EnriqueCorado It's just somewhat random what's available. But Twilio allows you to search for an available numbers if you make a free account. Keep in mind there aren't very many 'vanity' area codes besides maybe '321' - and then almost all the groups of 4 same numbers are gone. Groups of 3 are available as well as like 404-0403

**Comment by EnriqueCorado** [comment]
@johnhbenetech a number like 321 404-0403 will work. Seems unique enough

**Comment by johnhbenetech** [comment]
closing this as a number has been acquired
