### ISSUE TITLE
Service Net CBO Interface: The 'Add a New Record view' should hide when the search bar for referrals is engaged.

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1191]
When an employee from a CBO is trying to refer somebody to other CBOs, they will use the search bar for finding services to refer to. The screen should have a clear indication of where to search and what the section's purpose is. It should have a search text field and zip code field. The window should look something like the following. 
![Frame 2Benetech_Refer](https://user-images.githubusercontent.com/12637929/92525519-023aa980-f1f2-11ea-973e-232d5f885ec7.png)

When the search bar under 'Refer Elsewhere' is interacted with, the above section of 'Add a new Record' should be hidden. The window would probably look something like the following. 
![Frame 7Benetech_Refer2](https://user-images.githubusercontent.com/12637929/92525631-301fee00-f1f2-11ea-9497-909329b3bd3b.png)

**Comment by johnhbenetech** [comment]
@sidmundhra Why are there two search bars, how are they different?

Why are we surfacing zip code filter when the rest of the filters are under the 'filter' section? Why do we think zip code is so important, have we talked to users about this? Why not city? 

How would this look on mobile?

Once the top section is hidden, how does a user unhide it?

**Comment by sidmundhra** [comment]
@johnhbenetech The two search bars are different because the first one will be used by the CBOs to search through their updates and the second one for specifically searching for CBOs to refer to. We can also choose to have only one bar for search, keeping the bar below and removing the bar on top. Happy to discuss more.

Zip Code filter is more useful than the city filter because cities can have a very large radius for e.g. San Francisco city is large but with zip codes we can narrow it down to a specific location in the city. While I agree that having cities as a filter will provide more results for each service, but they may not be viable for a user if the services are much farther for the user when travelling on foot. We are currently talking to users regarding the usefulness of cities vs zip codes.

The mobile view is being designed keeping in mind the feedback from the above requirement.

The top section can easily be accessed by scrolling back to top. It'll be a nav section(like in HTML).

**Comment by johnhbenetech** [comment]
My vote is for one search bar. 

I don't agree with the zip code box, so I'd like to discuss that more. We don't know the density of services we will have and a single zipcode may be too specific and would frequently result in no matching records. Regardless I don't understand why we would take it out of the filter section where all the other filters are.

Ok so when you said "When the search bar under 'Refer Elsewhere' is interacted with, the above section of 'Add a new Record' should be hidden" it just means automatically scrolling down?

**Comment by johnhbenetech** [comment]
Not sure of the status of this or if it should be closed as irrelevant now. i just noticed it wasnt on the product board so im adding it back

**Comment by sidmundhra** [comment]
@johnhbenetech : 

I believe we'll only have one search bar.

re: zip code box- Yeah. We should do a city level filter unless specified.

re: automatic scrolling down - yes. An automatic scroll would help to inform the user that while their main focus currently lies on searching for other CBOs, their records are easily accessible by scrolling to the top.

**Comment by sidmundhra** [comment]
@johnhbenetech : There are two parts to this task. 

1. The search bar should move to the bottom part underneath refer elsewhere on the CBO interface. This will give us more real estate to show the filters being used.

2. When the search bar is engaged the page should do an automatic scroll to the part of the page that only shows all service cards that the CBO can refer to. Essentially, hiding the 'add a new record' section.

The zip code box part was for filters that we should ask for. But that has been solved by @EnriqueCorado on how the location will be picked on the backend when a CBO is trying to refer people to other CBOs. (Filter the results by location of the CBO user on the backend)

**Comment by johnhbenetech** [comment]
@sidmundhra can we get a mobile mockup for the search bar location?

**Comment by sidmundhra** [comment]
@johnhbenetech : #1327 and #1328 define the mobile mockup and layout.

**Comment by johnhbenetech** [comment]
Dev note: ignore zip code / find button in mockup

**Comment by abaranowska1** [comment]
@jkondrat 
I met an interesting issue with the search bar, could you take a look at it? 
![Peek 2020-10-29 09-52](https://user-images.githubusercontent.com/61964176/97546600-f470fb80-19cc-11eb-8fc1-5bf62adb6c6a.gif)
My steps: 
1. Log in as provider
2. Click load more button
3. Search for an organization that I know is not here for example VOLUNTEER INCOME TAX ASSISTANCE (VITA)
4. Click "x" icon and remove the search bar
5. Click load more button ( now I see less records )
6. Search by keyword "test" 
7. No Organization are displayed, but I know that we have such Organizations 
8. Click "x" icon and remove the search bar
9. Only 4 Organizations are displayed

**Comment by abaranowska1** [comment]
- The page is scrolled to the search bar position after click the search field 
- Issue with displaying wrong Organizations was fixed 
- Now we have only one search bar below the Refer Elsewhere section
![Peek 2020-10-30 13-11](https://user-images.githubusercontent.com/61964176/97703814-8d794280-1ab1-11eb-9e46-faa82f61e13c.gif)

**Comment by sidmundhra** [comment]
This looks good. Works as intended. Good for release.
