### ISSUE TITLE
Each time a filter is opened, 5 requests are sent

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#1195]
We should limit the number of requests by keeping the postal codes, regions, cities, system accounts and taxonomies after closing the filter

**Comment by abaranowska1** [comment]
I checked filters on traditional admin, traditional user, service provider, service provider public, and service provider mobile view. Filters work as expected without issue, but I cannot open a detail page of the organization on our traditional view - an unexpected error has occurred @jkondrat plz check it. 
![image](https://user-images.githubusercontent.com/61964176/94108556-d1888000-fe3f-11ea-819f-becb18fb0ddb.png)
![Peek 2020-09-24 08-21](https://user-images.githubusercontent.com/61964176/94108629-ee24b800-fe3f-11ea-876d-5c6cfa1b9095.gif)

![Peek 2020-09-24 08-20](https://user-images.githubusercontent.com/61964176/94108684-072d6900-fe40-11ea-8323-361ea172c2a8.gif)
![Peek 2020-09-24 08-23](https://user-images.githubusercontent.com/61964176/94108688-085e9600-fe40-11ea-95ec-df9b4a279187.gif)

**Verified on:**
- Ubuntu 20.04
- Google Chrome v. 85.0.4183.83
- Mobile 360x640

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:**
- filters on traditional admin, traditional user, service provider, service provider public, and service provider mobile view work as expected without issue,
- an unexpected error doesn't occur anymore 

![image](https://user-images.githubusercontent.com/61964176/94145763-550f9480-fe73-11ea-9616-bfde228839ed.png)


**Verified on:**
- Ubuntu 20.04
- Google Chrome v. 85.0.4183.83
- Mobile 360x640
