### ISSUE TITLE
Service Net System Wide Remove "About" and "Contact" From header 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1197]
**System-wide remove "About" and "Contact" from header from desktop and mobile view**
<img width="957" alt="Annotation 2020-09-09 133332" src="https://user-images.githubusercontent.com/65787629/92650255-17badc80-f2a1-11ea-8917-a942ef8bde91.png">

**System-Wide add "About" and "Contact" to bottom of page**
**Desktop View**
- same font, color
- scroll all the way down to find the "About" and "Contact" menu options 

<img width="956" alt="Annotation 2020-09-09 133500" src="https://user-images.githubusercontent.com/65787629/92650387-48027b00-f2a1-11ea-9b74-e3911ee4ad19.png">

**Mobile View**
- same font, color
- scroll all the way down to find the "About" and "Contact" menu options 

<img width="196" alt="Annotation 2020-09-09 133823" src="https://user-images.githubusercontent.com/65787629/92651564-c19a6900-f2a1-11ea-9a93-10d9107d5349.png">

remove from hamburger-menu "About" and "Contact"

<img width="218" alt="Annotation 2020-09-09 134430" src="https://user-images.githubusercontent.com/65787629/92653015-9b28fd80-f2a2-11ea-8443-e84808255161.png">

**Comment by johnhbenetech** [comment]
@EnriqueCorado what happens in map view on mobile?

I guess my vote is to just get rid of these entirely since feedback=contact essentially and the About link hasnt been updated so I don't see a reason to keep it until it is

**Comment by EnriqueCorado** [comment]
**System-wide remove "About" and "Contact" from header from desktop and mobile view**
<img width="957" alt="Annotation 2020-09-09 133332" src="https://user-images.githubusercontent.com/65787629/92650255-17badc80-f2a1-11ea-8917-a942ef8bde91.png">

remove from hamburger-menu "About" and "Contact"

<img width="218" alt="Annotation 2020-09-09 134430" src="https://user-images.githubusercontent.com/65787629/92653015-9b28fd80-f2a2-11ea-8443-e84808255161.png">

**Comment by kkaczmarczyk** [comment]
@EnriqueCorado @johnhbenetech should we remove Contact from the footer on the home page (before login) as well? Feedback is visible for logged-in users only.

![image](https://user-images.githubusercontent.com/3207119/93320791-c5823a00-f811-11ea-9fbc-61922e78aaa4.png)

**Comment by EnriqueCorado** [comment]
@kkaczmarczyk yes, please remove

**Comment by awalkowiak** [comment]
@johnhbenetech @EnriqueCorado 
For the desktop view I added the footer that is visible on the landing page and on old views:
![Selection_370](https://user-images.githubusercontent.com/12113312/94163800-8cd50700-fe88-11ea-960f-2e8ea4a1ea61.png)

Right now I also this always visible, because I feel like this looks better (only the content between the header and the footer is scrollable).

Regarding the mobile view. I feel like this `about us` link is better suiting in the hamburger menu instead of the footer or at the bottom of the page/view. See the two screenshots below and let me know how do you feel about this:
![Selection_371](https://user-images.githubusercontent.com/12113312/94164559-78ddd500-fe89-11ea-9b9a-49666abd855a.png)
![Selection_373](https://user-images.githubusercontent.com/12113312/94164566-7bd8c580-fe89-11ea-8637-c73fe8fc7b4f.png)

**Comment by EnriqueCorado** [comment]
@awalkowiak Thank you!

**Comment by awalkowiak** [comment]
@EnriqueCorado these are screenshots from my local instance, if it looks good, then I'll make a PR for it. However, let me know what do you think about it on mobile devices.

**Comment by EnriqueCorado** [comment]
@awalkowiak 
On the desktop view, it makes sense to have it there, and looks great. 
However, on the mobile view since the screen size is already limited, can we move about us to the hamburger menu on the top left? Possibly under Password?

**Comment by awalkowiak** [comment]
@EnriqueCorado yup will do it.

**Comment by abaranowska1** [comment]
**Tested with success**
Contact was removed from the header and About as was added to the footer on desktop view and to the hamburger on mobile. 

![Selection_108](https://user-images.githubusercontent.com/61964176/94924158-50735d80-04bd-11eb-9e10-4c646b57c024.png)
![Selection_109](https://user-images.githubusercontent.com/61964176/94924159-51a48a80-04bd-11eb-944f-abfab8c9207a.png)
![Selection_110](https://user-images.githubusercontent.com/61964176/94924161-51a48a80-04bd-11eb-80bd-5b5cf15e810f.png)
