### ISSUE TITLE
Service Net CBO Beneficiary Check In Menu Option in the Referral Header 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1200]
**Mobile View**

<img width="204" alt="Annotation 2020-09-09 151059" src="https://user-images.githubusercontent.com/65787629/92660132-b00b8e00-f2ae-11ea-8a77-7c046756a9e0.png">

**Desktop View**

when you click the referral page it loads any unsent referrals active on the cart

add the Beneficiary Check-In green button to emphasize that you are at the Beneficiary Check-In page

add the two other options under it as menu options that can pop in a new menu

look at this link for reference under the hamburger menu, service net referral page, and click on the different three menu buttons which hide and show different menus
https://e34vsd.axshare.com

add another title, 5 pixels bigger, black, bold

add the box to enter a 10 digit phone number

add the box to enter a unique identifier linked to the phone number in the database if it exists

add a box to be able to send an SMS with a thank you note (just add the button with the functionality to be able to send items in the above section)

<img width="1277" alt="Annotation 2020-09-09 151144" src="https://user-images.githubusercontent.com/65787629/92660180-c87ba880-f2ae-11ea-9410-e0703f02851c.png">

**Comment by EnriqueCorado** [comment]
as the user clicks send backend, we will check if the phone number or unique ID exists, if it does, add it to their log record of where they have gone (which CBO's) they have gone to along with their timestamp

if the number is new, make a new record (with a new unique identifier) on the database with that phone number and add the timestamp alongside it

**Comment by EnriqueCorado** [comment]
- Once the user clicks "Send" 
- a pop up of "Congratulations, referral sent!" will appear 
- add a "Close" button pop up to close referral 
- add a button for "Go to home page" 
- once the "Close" button gets pressed, send the user to the "Beneficiary Check-In" page


<img width="275" alt="Screenshot 2020-09-10 090948" src="https://user-images.githubusercontent.com/65787629/92760330-67eb7a80-f345-11ea-9063-d025d1442b9e.png">

**Comment by jkondrat** [comment]
A header tab will be added in another issue: https://github.com/benetech/ServiceNet/issues/1206

**Comment by johnhbenetech** [comment]
@EnriqueCorado A few questions came up regarding the check-in process. I guess the main question is do you imagine:
1. requiring the user to check-in EVERY beneficiary that walks in (regardless of referral), or

2. will they ask EVERY beneficiary if they've been referred by a servicenet partner and only check in those who have been? Let the system look for an existing open referral and close it out. If one doesn't exist leave the check-in object orphaned

**Comment by EnriqueCorado** [comment]
@johnhbenetech 

Ideally, yes, so we can see how many beneficiaries just show up to a specific CBOs without referrals and have a complete picture

**Comment by abaranowska1** [comment]
@awalkowiak I found similar issues which I met during testing @jkondrat ticket

1. Only 5 organizations are displayed in the drop-down list, but all organizations owned by the user should be there
![Screenshot_2020-10-12_11-58-55](https://user-images.githubusercontent.com/61964176/95733369-57029180-0c82-11eb-944e-f519a4a492be.png)

2. In Referral Entity the fields "From and To" are empty.
![image](https://user-images.githubusercontent.com/61964176/95733487-82857c00-0c82-11eb-98f7-aeaa30415661.png)

**Comment by awalkowiak** [comment]
@abaranowska1 the first point is fixed and the second point is a known bug (already reported as a seperate issue)

**Comment by jkondrat** [comment]
@awalkowiak actually, the second point is also fixed for the referral entity

**Comment by abaranowska1** [comment]
Confirmed that both issues were fixed
![Peek 2020-10-15 12-56](https://user-images.githubusercontent.com/61964176/96114628-2a4eb400-0ee6-11eb-8d62-bde7ae2242d6.gif)
![Peek 2020-10-15 12-568](https://user-images.githubusercontent.com/61964176/96114630-2c187780-0ee6-11eb-89ce-f843769cceb4.gif)

Verified cases:
- Beneficiary check in page is created 
- Two buttons and communicate about success is displayed after send check in 
![image](https://user-images.githubusercontent.com/61964176/96119051-b06df900-0eec-11eb-9da6-b4199e488b31.png)
- If someone previously made a referral from his organization to the one selected in the check-in for the beneficiary, the fulfilled date is set
- when there are no selected organizations, the organization you refer to and from is also set up

**Comment by EnriqueCorado** [comment]
good. release
