### ISSUE TITLE
add https to public website

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1204]
- Need SSL certificate for the public website
- as well as SSL certificate for Service Net for all other interfaces (Public and CBO)

**Comment by EnriqueCorado** [comment]
@johnhbenetech can this be added to this week's release?

**Comment by johnhbenetech** [comment]
@EnriqueCorado Isn't this already there?

![image](https://user-images.githubusercontent.com/12927553/92759914-d5070c00-f355-11ea-9821-0eaa64d64a99.png)

**Comment by EnriqueCorado** [comment]
@johnhbenetech For KP and I it shows this

<img width="332" alt="Screenshot 2020-09-10 091255" src="https://user-images.githubusercontent.com/65787629/92760770-d6303d00-f345-11ea-9651-ccadd2edf59e.png">


<img width="427" alt="Screenshot 2020-09-10 091356" src="https://user-images.githubusercontent.com/65787629/92760897-f8c25600-f345-11ea-896a-21a129e27695.png">

**Comment by johnhbenetech** [comment]
Closing as I have reconfigured routing to force everyone to HTTPS
