### ISSUE TITLE
CBO Referral Page Navigation to Page when Items in Cart and when Empty 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1206]
**For Desktop and Mobile**

- when a user clicks on the referral tab

<img width="395" alt="Screenshot 2020-09-10 092726" src="https://user-images.githubusercontent.com/65787629/92762872-df220e00-f347-11ea-8c4f-f2d292d173f8.png">

- if there is nothing in the "Cart" or in the "Referrals" page 
- when the user click on referral it will take you to the "Beneficiary Check-In" page
<img width="287" alt="Screenshot 2020-09-10 093029" src="https://user-images.githubusercontent.com/65787629/92763345-46d85900-f348-11ea-8ac0-0c9864ccb043.png">

-if there are items in the cart, then when you click on referral, it will take the user to the "Referral" page and show what's on the cart

![image](https://user-images.githubusercontent.com/3207119/93463439-0d739080-f8e8-11ea-8196-1c4ce70469cb.png)

**Mobile View**

<img width="203" alt="Screenshot 2020-09-16 113058" src="https://user-images.githubusercontent.com/65787629/93377654-2872d180-f810-11ea-84bf-e8730cc5a1a7.png">

<img width="191" alt="Screenshot 2020-09-16 113150" src="https://user-images.githubusercontent.com/65787629/93377700-3cb6ce80-f810-11ea-97b7-6c512fb31d07.png">

**if only one record keep this layout on referral page ** 
<img width="206" alt="Screenshot 2020-09-16 113508" src="https://user-images.githubusercontent.com/65787629/93378120-d3838b00-f810-11ea-87c5-cad4778f6e62.png">

<img width="727" alt="Screenshot 2020-09-16 113703" src="https://user-images.githubusercontent.com/65787629/93378219-fb72ee80-f810-11ea-9209-b95a5ffe2b17.png">

**Comment by kkaczmarczyk** [comment]
@EnriqueCorado @johnhbenetech would there be any value in changing the 'Referral' button label in the header to 'Check-in' in the case when 'cart' is empty'? Unsure if this may be misleading or helpful to the user.

**Comment by kkaczmarczyk** [comment]
update: I have updated the description to include the latest mock-ups from #1176

**Comment by awalkowiak** [comment]
@abaranowska1 in this ticket I added the referral page structure. There are 3 tabs with a bit improved layout as it is in the create new record view. Depending on if you have any referrals selected it will open the proper tab (0 referrals = beneficiary check in, referrals  > 0 = referral tab). 
Note: The content of each tab is not the part of this ticket (Check-in tab content will be added in #1200, Referral tab content will be added in #1198 and Bulk upload tab content will be added in #1205)

**Comment by abaranowska1** [comment]
**Tested with success**
**Verified cases:**
- Referral page structure with 3 tabs was added to sp view
- Depending on if you have any referrals selected it to open the proper tab (0 referrals = beneficiary check-in, referrals > 0 = referral tab).
![Peek 2020-10-08 14-59](https://user-images.githubusercontent.com/61964176/95461941-1ef40980-0977-11eb-8e37-650103c8ad54.gif)
**Verified on:**
- Ubuntu 20.04
- Google Chrome Version 85.0.4183.83
- Mobile 360x640

**Comment by EnriqueCorado** [comment]
good. release
