### ISSUE TITLE
Add search bar to public view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1207]
At some point the search bar got removed from the 'public' SP view.

Please add it and ensure it functions.

**Comment by abaranowska1** [comment]
**Tested with success**
A search bar with all search function was added to the Public Service Provider View.
![Peek 2020-09-15 13-38](https://user-images.githubusercontent.com/61964176/93205927-e470c580-f758-11ea-9e48-21339c054d5f.gif)
**Verified on: **
- Ubuntu 20.04
- Google Chrome v. 85.0.4183.83
