### ISSUE TITLE
CBO SMS Content for Referral, Check In, and Bulk Upload

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1208]
1. On the "Beneficiary Check-In" Page, once you press send after entering phone number or unique identifier 

<img width="179" alt="Screenshot 2020-09-10 112724" src="https://user-images.githubusercontent.com/65787629/92781042-9d4d9380-f358-11ea-9e6c-45a255c8380d.png">

- if the number exists, it will send an SMS to the Beneficiary saying, "Thank you for coming to __(CBO they are at)__. Here is your unique identifier in case you forgot and the number you can provide instead of your phone number at any service provider you go to to ensure our services are being used and can improve."
- if the number does not exist, it will send an SMS to the Beneficiary saying. "Thank you for coming to __(CBO they are at)__. Here is your unique identifier for you to provide at every community organization you go to to ensure our services are being used and can improve."

2.  On the Referral Page

<img width="269" alt="Screenshot 2020-09-10 113111" src="https://user-images.githubusercontent.com/65787629/92781630-25cc3400-f359-11ea-9224-4ba798484faf.png">

- user can enter either the phone number or unique identifier and clicks "Send" backend we will send an SMS saying, "Here are the places we discussed you wanted a referral to (list of referrals from above ). Here is your unique identifier for you to provide at every community organization you go to to ensure our services are being used and can improve."

3. On the bulk transaction upload page 

<img width="213" alt="Screenshot 2020-09-10 113428" src="https://user-images.githubusercontent.com/65787629/92782159-996e4100-f359-11ea-8f5d-cfe930e66af3.png">

- Once all numbers from the CBO's log is inputted in and they click Finished
- back end we will send an SMS saying, "Thank you for coming to __(CBO they went to)_on (date from timestamp inputted into the log)_. Here is your unique identifier for you to provide at every community organization you go to to ensure our services are being used and can improve."

**Comment by kkaczmarczyk** [comment]
hi @EnriqueCorado @johnhbenetech should we consider creating a simple SMS log entity to keep the history of SMS being sent to the user in case of check-ins?

**Comment by EnriqueCorado** [comment]
@kkaczmarczyk create a simple log entity to keep history. thank you

**Comment by jkondrat** [comment]
@johnhbenetech It would be nice to create an account on Twilio (or any other provider) so we can test sending out messages

**Comment by abaranowska1** [comment]
@jkondrat 
1. When the number is invalid the Internal Server Error is thrown, plz change the notification 
![Peek 2020-10-23 13-29](https://user-images.githubusercontent.com/61964176/97002805-cad25300-153a-11eb-9bfe-17f77f41f4bb.gif)
![Peek 2020-10-23 13-28](https://user-images.githubusercontent.com/61964176/97002810-cc038000-153a-11eb-92f1-ff744cc0b324.gif)

**Verified cases:**
- I made a check in for our twilio testing number and without issue I get a sms message 
 
![image](https://user-images.githubusercontent.com/61964176/97003962-9495d300-153c-11eb-97c7-ca3136f35be8.png)
![image](https://user-images.githubusercontent.com/61964176/97004636-a6c44100-153d-11eb-88f0-df6a3a9b7b36.png)

- I guess that a bulk transaction upload page will be created in another ticket

**Comment by abaranowska1** [comment]
**Tested with success**
Pop up message was changed from Internal Server Error to " The phone number is invalid "
![image](https://user-images.githubusercontent.com/61964176/97317896-9973c300-186b-11eb-8724-77c1e3f9c1e7.png)

**Comment by johnhbenetech** [comment]
Possibly related to #1385, the check in form seems to be broken. Regardless of entry on phone or unique ID, the send button never seems to become active for submission

**Comment by johnhbenetech** [comment]
I think both #1208 and #1385 are caused by the case where a user only owns 1 record

The dropdown for organization selection doesnt render (which makes sense since there would only be one option) but that also seems to prevent the send button from being enabled

**Comment by awalkowiak** [comment]
@johnhbenetech I'll investigate it together with #1385

**Comment by abaranowska1** [comment]
Tested together with #1385
