### ISSUE TITLE
CBO Interface Paper Stack "Cart" Icon

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1210]
Here are two potential ideas for the replacement of the cart icon

![62188149-stack-of-paper-icon](https://user-images.githubusercontent.com/65787629/92801872-db53b300-f36a-11ea-91bd-0eb86c706c74.jpg)

![paper_plain-512](https://user-images.githubusercontent.com/65787629/92801879-dc84e000-f36a-11ea-8bf2-a94e5c76f909.png)

**Comment by johnhbenetech** [comment]
@EnriqueCorado is this ok: https://fontawesome.com/icons/layer-group?style=solid

Generally speaking we should use open source/free licensed icons. Fontawesome is already integrated into the system so something from their free collection works great. If not, please pick an option and find a FOSS asset.

**Comment by EnriqueCorado** [comment]
- add cart PNG next to the referral menu option alongside the number of referrals added to the cart

https://fontawesome.com/icons/layer-group?style=solid

<img width="500" alt="Annotation 2020-09-09 150422" src="https://user-images.githubusercontent.com/65787629/92659718-c82edd80-f2ad-11ea-9924-254e42843d15.png">

Should look something like this, if no items in the cart then just have the icon from above
- if an item gets added to the "cart" have the number show up next to the cart
- keep the same font from the header menu on the number

**Comment by johnhbenetech** [comment]
@EnriqueCorado I'm confused due to the mockup still having the cart - can you provide a final mockup on intended final desing

**Comment by EnriqueCorado** [comment]
<img width="385" alt="Screenshot 2020-09-14 150954" src="https://user-images.githubusercontent.com/65787629/93143235-5fc07180-f69c-11ea-8bbf-4311d7b16121.png">

- keep same, font, color, as Home and Feedback

**Comment by awalkowiak** [comment]
@abaranowska1 I added this icon: https://fontawesome.com/icons/layer-group?style=solid. The number of referrals appears in the lower right-hand corner of the icon.

**Comment by abaranowska1** [comment]
**Tested with success**
The paper stack icon was added to the header near the Referral tab.
The number of referrals appears in the lower right-hand corner of the icon and increase when we click the Refer button on the cards.

![Selection_133](https://user-images.githubusercontent.com/61964176/95454891-552c8b80-096d-11eb-9ba9-0e0dcbd0b143.png)
![Selection_134](https://user-images.githubusercontent.com/61964176/95454892-55c52200-096d-11eb-898f-c974131de214.png)
![Selection_135](https://user-images.githubusercontent.com/61964176/95454893-55c52200-096d-11eb-85b7-69cd969e2422.png)

**Comment by EnriqueCorado** [comment]
good. release
