### ISSUE TITLE
ServiceNet Map View for Mobile

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1211]
Map view for ServiceNet does not show search bar, sort and filter buttons correctly. 
![IMG_8248](https://user-images.githubusercontent.com/12637929/92810975-07336080-f38c-11ea-8645-229c42cf47dd.PNG)

We can have the buttons a white fill and black text. 
something similar to this can be looked at for our purposes. 
![IMG_8247](https://user-images.githubusercontent.com/12637929/92811035-14e8e600-f38c-11ea-947a-03db5157b868.PNG)

**Comment by johnhbenetech** [comment]
For this task we will just fill the current buttons with blue and have the text/icons in white

**Comment by sidmundhra** [comment]
@johnhbenetech please delete this from the project board. This has been defined clearly in #1331
