### ISSUE TITLE
ServiceNet Map View for mobile and Desktop

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1213]
ServiceNet Map view should have different pins/markers on map for different types of services. This will help in visually identifying service types on map and have a uniform design system around them. 

This could be similar to the following image. Yelp does numbering for how the services are shown on the list. 

**For Web.** 
![2020-09-10 17_54_32-Siddharth Mundhra_resume docx - Word](https://user-images.githubusercontent.com/12637929/92813223-cee15180-f38e-11ea-8479-c46f584f6344.png)

**For Mobile.**
![IMG_8250](https://user-images.githubusercontent.com/12637929/92813076-845fd500-f38e-11ea-8894-07a8e7a73d75.PNG)

For icons I found the following resources that can be used: 
https://templatic.com/newsblog/100-free-templatic-map-icons/
https://impress.org/top-google-maps-marker-icon-collections-2015/

**Comment by johnhbenetech** [comment]
@EnriqueCorado what's the user story for this? What's the value?

Currently the map doesnt show a record until you click it so I dont understand what adding numbers would help unless we were embedding the map on the grid view. And if that's the case we need to slot this after this work.

**Comment by EnriqueCorado** [comment]
@sidmundhra check John's comment

**Comment by sidmundhra** [comment]
@johnhbenetech - it isn't supposed to be a numbered pin but a different color marker for different types of services. Say food pantry could be indicated by a green pin on the map, shelters with purple pin, medical with a red pin. I think it could help with a visual cue to the users when they open the map view without searching for anything specific. This isn't super important though. Could sit on low priority.

**Comment by johnhbenetech** [comment]
@sidmundhra gotcha, that could be cool. There are like 1,000s of different 'service type' categories so we will need to come up with some amount of grouping. Additionally, more likely than not a single location will have multiple services or different types

**Comment by sidmundhra** [comment]
@johnhbenetech: @EnriqueCorado and I literally were just discussing the same possibility of have one location with multiple services and how to solve that. We'll have some ideas soon for you. :)

**Comment by sidmundhra** [comment]
@johnhbenetech : We've both come to consensus that we should have a unique colored pin for any CBOs that have multiple service types. Say Gray for all CBOs that have more than one service type. Let us know if this makes sense. Thanks!

**Comment by johnhbenetech** [comment]
I'm not passing #1182 or #1213 through to dev. They aren't clearly defined and overlap/contradict each other at times.

If you want a change, please provide mobile and desktop mockups that actually use the SN interface and describe all interactions. We are setting ourselves up for failure by providing mockups with entirely different design systems.

**Comment by johnhbenetech** [comment]
These two issues should probably be deleted at this point and a new simpler, clearer one created

**Comment by sidmundhra** [comment]
Will create a new task for this.

**Comment by johnhbenetech** [comment]
@sidmundhra @EnriqueCorado can we close these out if they no longer relevant?

**Comment by sidmundhra** [comment]
yes. closing this.
