### ISSUE TITLE
Public Interface Remove "last update.. By: Bay Area Unclaimed"

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1217]
**Desktop and Mobile Public Interface**

- remove the top left section from every record if they say what's below 
<img width="148" alt="Screenshot 2020-09-11 110849" src="https://user-images.githubusercontent.com/65787629/92958612-5f677280-f41f-11ea-8cf9-2d536b99644b.png">

- only show the Last Updated date and By if it's an update from that organization

**Comment by johnhbenetech** [comment]
@EnriqueCorado what's the user story for this? What's the value?

**Comment by EnriqueCorado** [comment]
@johnhbenetech to let the users know the organization from the record are updating the record and not some random "Bay Area View" 
- clean up of what doesn't add up essentially

**Comment by johnhbenetech** [comment]
Bay Area Unclaimed is replaced with the CBO User's name once they 'claim' the record and start actively managing it (to indicate that it is being actively maintained by the CBO'

I think it's important to some how indicate that a record isn't 'claimed' yet. Is there a different text we could put there that can help make that clearer? Can we do something better visually to differentiate managed from unmanaged records? I would hate to remove this until we can replace it with something.

**Comment by EnriqueCorado** [comment]
@johnhbenetech We could as a play holder right now, "Last Update 08/21/20 10:10 By: Benetech" 
I think it's more intuitive 
- then once claimed like you said, replaced with the CBO User's name once they 'claim' the record and start actively managing it (to indicate that it is being actively maintained by the CBO)

**Comment by johnhbenetech** [comment]
@EnriqueCorado makes sense!

**Comment by johnhbenetech** [comment]
Closing as this is completed without code change
