### ISSUE TITLE
The wrong header is displayed while moving from admin old view to SP public view

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#1227]
The wrong header is displayed while moving from admin old view to SP public view.

![Peek 2020-09-15 13-42](https://user-images.githubusercontent.com/61964176/93206721-264e3b80-f75a-11ea-90d3-8e7eeec1ac02.gif)
![Selection_049](https://user-images.githubusercontent.com/61964176/93206801-4251dd00-f75a-11ea-96f6-0887fdef6c4a.png)

**Steps:** 
1. Go to ServiceNet app and log in as Admin
2. Change the URL address to for example https://benetechservicenet.org/#/public/Silo1 

**Actual result:** 
The wrong header is displayed while moving from admin old view to SP public view.

**Expected result:** 
Header from public view should display
![image](https://user-images.githubusercontent.com/61964176/98661706-18c2c580-2347-11eb-86e9-024e6b10909b.png)

Additional work:  Let's use this ticket to also unify headers for each user because we have two components for the header. After this ticket, we should have one header component with unified styling for all pages (public or not) and users. Also do this ticket together with it: #1373 and look into #1370

**Comment by awalkowiak** [comment]
@jkondrat @awalkowiak Dev notes: Let's use this ticket to also unify headers for each user because we have two components for the header. After this ticket, we should have one header component with unified styling for all pages (public or not) and users.

@sidmundhra @EnriqueCorado @johnhbenetech if admin user goes from his home page to the public view, what items in the header should he see? The items that he can currently see (look at the first screenshot that @abaranowska1 shared) or the items that are suggested in the screenshot of the expected result?

**Comment by johnhbenetech** [comment]
@awalkowiak I think they should see the generic header that everyone else sees on public view (like in #1370)

**Comment by awalkowiak** [comment]
@EnriqueCorado @johnhbenetech @meenupant 

Currently, Header for Service Provider view and for Admin (non-public ones) looks like this:
![benetechservicenet_service_provider_view](https://user-images.githubusercontent.com/12113312/100775110-1bbf4c00-3403-11eb-9fc4-19248cd1a031.png)
![benetechservicenet_admin_view](https://user-images.githubusercontent.com/12113312/100775119-1f52d300-3403-11eb-843c-60eb4b1cc271.png)
The left-hand side menu items are bold, and the right-hand side menu items are a bit thinner.

What I suggest (I did it locally) we could have all the header menu items bold. Plus on each user's header 'Home' and 'Feedback' (and 'Referral' for Service Provider) menu items are on the left-hand side and all other menu items are on the right-hand side. Additionally, each user has the same avatar circle next to the 'Account' menu item (the one with the user name displayed), only for not logged users it would be a user icon (as it is currently on the landing page). Here are the screenshots of how it looks for each case:
1. Admin user view:
![admin_view](https://user-images.githubusercontent.com/12113312/100775915-30501400-3404-11eb-8aa2-764458a15c06.png)
2. Admin user public view:
![admin_public_view](https://user-images.githubusercontent.com/12113312/100775997-465dd480-3404-11eb-86c8-7b26ba9207cd.png)
3. Sacrament user view:
![sacramento_user_view](https://user-images.githubusercontent.com/12113312/100776053-58d80e00-3404-11eb-89f2-e10033306a55.png)
4. Sacrament user public view:
![sacrament_user_public_view](https://user-images.githubusercontent.com/12113312/100776092-642b3980-3404-11eb-8acd-855e54b4805a.png)
5. Non admin, non service provider user view:
![non_admin_non_service_provider_user_view](https://user-images.githubusercontent.com/12113312/100776161-7e651780-3404-11eb-870a-4fa9d41b047d.png)
6. Non admin, non service provider user public view:
![non_admin_non_service_provider_user_public_view](https://user-images.githubusercontent.com/12113312/100776201-89b84300-3404-11eb-8fbe-0b8f01c9dd49.png)
7. Service Provider user view (with referrals enabled):
![service_provider_view](https://user-images.githubusercontent.com/12113312/100776251-9b99e600-3404-11eb-955e-6fd7fa8ffcd6.png)
8. Service Provider user public view (with referrals enabled):
![service_provider_public_view](https://user-images.githubusercontent.com/12113312/100776296-a6547b00-3404-11eb-9286-4e270226616f.png)

Let me know what do you think about it.

**Comment by EnriqueCorado** [comment]
@meenupant

**Comment by awalkowiak** [comment]
@EnriqueCorado @meenupant this one was merged, you can check it out on the dev server and if there will be something you'd like to change, let me know.

**Comment by meenupant** [comment]
@awalkowiak Looks good for now

**Comment by abaranowska1** [comment]
**Tested with success**
It looks good to me too. All headers look similar now.
