### ISSUE TITLE
Service Net Wide Change Military Time to 12-hour am-pm clock

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1229]
<img width="1915" alt="Screenshot 2020-09-15 112546" src="https://user-images.githubusercontent.com/65787629/93249725-98b52080-f746-11ea-94af-cfa460630760.png">

- change to 12-hour am-pm clock on all records system-wide

**Comment by awalkowiak** [comment]
@EnriqueCorado, @johnhbenetech  Should this only affect Service Provider (CBO) View or also the admin/entities view?

**Comment by johnhbenetech** [comment]
Service Provider view.

**Comment by abaranowska1** [comment]
**Tested with success**
Time is changed to 12-hour am-pm clock on all records system-wide (Provider View)
![Selection_241](https://user-images.githubusercontent.com/61964176/97183022-8eeaf800-179d-11eb-889f-f4a551589c85.png)
![Selection_240](https://user-images.githubusercontent.com/61964176/97183027-8f838e80-179d-11eb-95fe-bbaab03f7a5e.png)
![Selection_239](https://user-images.githubusercontent.com/61964176/97183029-901c2500-179d-11eb-9506-70e92018087f.png)
![Selection_238](https://user-images.githubusercontent.com/61964176/97183031-901c2500-179d-11eb-97c9-d63ce0e80417.png)

**Comment by EnriqueCorado** [comment]
good. release
