### ISSUE TITLE
ServiceNet Sitewide Filter Buttons with cross to remove filters

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1230]
@johnhbenetech - ServiceNet should have filter buttons like other ecommerce sites which can be used indicate that there are filters that have been applied and can be removed. 

I researched through a lot of websites and came with an understanding that these help a user understand the filters that have been applied to get the results. Currently, the filters sit under the dropdown for filters and even to remove the filter applied a user has to go through 2 clicks to get there. 

Here's an example of how it would look :-
![Frame 2Benetech filters](https://user-images.githubusercontent.com/12637929/93260169-fe1d0780-f76e-11ea-8398-2e38cf94221e.png)

Notice how the Food Pantry filter button shows up near find when food pantry filter is applied. 
Alternatively, we could also do an airtable like filters where each type of filter has a dropdown to select multiple filters. 
Let me know your thoughts on this.

**Comment by johnhbenetech** [comment]
@sidmundhra I think it makes sense. Maybe we could color code them to distinguish between service type, zip, and city filters.

How do you think this could look on mobile? I think it prob makes sense to keep it in some kind of filter modal since we dont want to take up too much of the main screen

**Comment by sidmundhra** [comment]
Also, from a recent discussion with KP, we (@EnriqueCorado and I) were told that the map view button should move to the rightmost place(or merge with the list view/grid view, if possible) and filter button should take the leftmost place. Should I add a new issue for that or can we consider this as a part of this issue?

**Comment by sidmundhra** [comment]
> 
> 
> @sidmundhra I think it makes sense. Maybe we could color code them to distinguish between service type, zip, and city filters.
> 
> How do you think this could look on mobile? I think it prob makes sense to keep it in some kind of filter modal since we dont want to take up too much of the main screen

Yeah. a filter modal on mobile sounds good. will develop designs for that as well.

**Comment by johnhbenetech** [comment]
@sidmundhra break out the other stuff into a new task

**Comment by sidmundhra** [comment]
Also, I like the idea of color coding different filters. Can see it help visually.

**Comment by sidmundhra** [comment]
Hey @johnhbenetech noticed that you mentioned this issue on 1244 and you make a great point of having a 'clear all filters' button with this task. It totally makes sense to have it. 

Can we also add 'clear all filters' button as part of this issue, given this issue deals with the filters mechanism sitewide? Or should I add a new issue for it?

**Comment by johnhbenetech** [comment]
@sidmundhra you can keep it here

**Comment by johnhbenetech** [comment]
@sidmundhra this needs more scoping

I dont see any details/mockups for the 'clear all filters' action.

I don't see any details on how the filters should be color coded

I dont see any mobile mockups for this task

I dont understand why the mockups have two search bars
