### ISSUE TITLE
ServiceNet Sitewide: Merge Map View into Grid View/List View Button and move filter button to the leftmost place

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1232]
@johnhbenetech : If possible, we should merge the map view button into the list view/grid view button as both the buttons serve the same function of switching views and we can get more space for filter buttons if they're merged.

Additionally, we should move the Filter button dropdown to the leftmost place, so it's almost at the centre and the first thing a user notices when moving left-to-right on the screen. This also means that the map view/grid view/list view button should move to the rightmost place(where the filter button is currently.).

**Comment by johnhbenetech** [comment]
@sidmundhra how does this affect the mobile view while you are within the map-view (since the interface changes)

**Comment by sidmundhra** [comment]
@johnhbenetech : this has been taken care of in the last comment in #1213. Does that work?

**Comment by johnhbenetech** [comment]
@sidmundhra I dont see anything relevant to my question. We need mockups for this task for the ServiceNet mobile/desktop interface.  Yelp screenshots don't help

**Comment by sidmundhra** [comment]
@johnhbenetech : Apologies for the mix up. I meant to write #1182 where the toggle is for list and map on the top right and filter on the top left.

Here's the updated mockup:

![X - 5Benetech_map_view](https://user-images.githubusercontent.com/12637929/94070014-83339c80-fdbf-11ea-8f5b-63f1eb1effd5.png)

**Comment by abaranowska1** [comment]
**Tested with success**
The Map View, Grid View, List View buttons were merged into one big button on web and mobile.
![image](https://user-images.githubusercontent.com/61964176/98120805-bb45f900-1eae-11eb-9d80-5d240de11021.png)
![image](https://user-images.githubusercontent.com/61964176/98121261-5b9c1d80-1eaf-11eb-92fc-ba5e4224a07c.png)

**Comment by sidmundhra** [comment]
this looks good. Confirm for release.
