### ISSUE TITLE
CSV download of Referral History

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#1238]
Scope:
* Possibility to download a csv report of "Referral History", "Referrals Made From", "Referrals Made To"
* Directions for download?

**Comment by jkondrat** [comment]
@johnhbenetech I wonder if we should still add "Directions for download", I can't find them on any mockup

**Comment by johnhbenetech** [comment]
@EnriqueCorado what do you think?

**Comment by EnriqueCorado** [comment]
@jkondrat @johnhbenetech Let's leave directions out for now

**Comment by abaranowska1** [comment]
**Verified cases:**
- CSV download function and button was added
- After click CSV button, the whole referral history download as a csv file
- @jkondrat please change the CSV button to the pill 
![image](https://user-images.githubusercontent.com/61964176/96445102-a3fcdf80-120f-11eb-8494-da3c8447f43c.png)
![image](https://user-images.githubusercontent.com/61964176/96445116-a7906680-120f-11eb-9bcf-ee1417f816ba.png)

**Verified on:**
- Ubuntu 20.04
- Google Chrome Version 85.0.4183.83
- Mobile 360x640

**Comment by abaranowska1** [comment]
**Tested with success**
- CSV button was changed to the pill
![image](https://user-images.githubusercontent.com/61964176/96683204-1c7faf80-137a-11eb-8eb0-ebbb2c82b5ec.png)
- After click CSV button, the whole referral history download as a CSV file

**Verified on:**

- Ubuntu 20.04
- Google Chrome Version 85.0.4183.83
- Mobile 360x640

**Comment by EnriqueCorado** [comment]
changes to CSV download names have been tasked on #1371
