### ISSUE TITLE
Bulk transaction upload page

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#1239]
![image](https://user-images.githubusercontent.com/5969801/93460072-01390480-f8e3-11ea-8304-00b8ab2c2316.png)

Scope:
* Propose UI design for the page
* Possibility to enter a list of dates/phone numbers manually 
* Add/remove rows

CSV upload and sending SMS messages will be done in other tasks

**Comment by jkondrat** [comment]
@johnhbenetech @EnriqueCorado When the user clicks 'Finished', should we create beneficiaries for each phone number?

**Comment by johnhbenetech** [comment]
@jkondrat I think all 'bulk' action related tasks will be pulled back for additional scoping considerations.

**Comment by johnhbenetech** [comment]
possible duplicate of #1209
