### ISSUE TITLE
Track info about dates of accepting changes

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#124]
When conflict entity is updated (another matched organization has the same value for a field), it's system account is added to "acceptedThisChange" array. However, a timestamp of this event is not tracked, which results in a lack of information about conflict on the single record view page. According to the mock: https://user-images.githubusercontent.com/12927553/48446723-9b681880-e75f-11e8-867b-4ffe6760ca4c.png each conflicting value should have a date when it was imported.

**Comment by kkaczmarczyk** [comment]
closing this as outdated
