### ISSUE TITLE
Public View Make Benetech logo take the user to the home page 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1244]
- currently, website whenever any filters are applied there's no option to "start fresh"
- make the benetech logo a simple way to go back to the first page when a user enters the website url

**Comment by johnhbenetech** [comment]
I'm not sure i understand this task @EnriqueCorado can you explain a bit more?

**Comment by johnhbenetech** [comment]
What does 'from the start mean'?

If you are on the single record view for instance, the home and logo already behaves as I believe it should (brings you back home to all records view)

I think maybe what you are talking about is like clearing filter and sort? Take a look at #1230 and see if there's some synergy there.

I think the use case I'm worried about is like when you actually WANT to keep your filters. I'm imagining this is actually the more common use case. Like I filter for shelters in Oakland, click on one to see if it's a good fit, it's not a good fit, so I want to go back to find a different shelter in Oakland. So when I go back it would be annoying to have to redo that filter.

Take a look at #1230 and let me know what you think. I think more surfacing of what filters are active and the ability to clear individual filters or clear all filters could go a long way.

**Comment by EnriqueCorado** [comment]
#1230 will take care of clearing filters but will look into it further once we can see how it works

**Comment by johnhbenetech** [comment]
#1230 doesnt handle clear all which i do think is important
