### ISSUE TITLE
Public View Remove Header and just leave Feedback 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1245]
- on public view remove the "0.0.1-Snapshot"
- remove the "About" header

**Comment by abaranowska1** [comment]
**Tested with success**

- on public view the "0.0.1-Snapshot" was removed
- the "About" header is also removed

![image](https://user-images.githubusercontent.com/61964176/96978290-7ae59300-151e-11eb-8fe3-6355a9717dcd.png)

**Comment by EnriqueCorado** [comment]
good. release
