### ISSUE TITLE
Public View add home button

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1246]
- on the header pf public view add the home button where it shows the initial page
- same font, style, size, color as feedback

<img width="949" alt="Screenshot 2020-09-18 102127" src="https://user-images.githubusercontent.com/65787629/93626746-bd083b80-f998-11ea-80d7-226082927d7b.png">

**Comment by abaranowska1** [comment]
**Tested with success**
Home button was added to the header on public view
![image](https://user-images.githubusercontent.com/61964176/96728495-78ffc080-13b4-11eb-82a6-d23044174a79.png)

**Comment by EnriqueCorado** [comment]
change tasked on #1370
