### ISSUE TITLE
Public view automatically load more as they scroll down

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1247]
- user feedback that is annoying to keep loading the upcoming records

**Comment by abaranowska1** [comment]
@awalkowiak Plz check why after load the public view homepage, we cannot scroll the page. 
![Peek 2020-11-04 14-48](https://user-images.githubusercontent.com/61964176/98119841-75d4fc00-1ead-11eb-965a-c93d5fa6786e.gif)
When I change the grid view to list view and map view the whole functionality works as expected.

**Comment by abaranowska1** [comment]
**Tested with success**
Public home page and Standard Service Provider View load automatically after scroll. 
![Peek 2020-11-06 12-50](https://user-images.githubusercontent.com/61964176/98363137-c58f0100-202e-11eb-8b17-004d3bd56e65.gif)
**Verivied on:**
- Ubuntu 20.04
- Google Chrome Version 85.0.4183.83

**Comment by EnriqueCorado** [comment]
good. release
