### ISSUE TITLE
Assist with data re-architecture scoping regarding record<->silo<->SystemAccount relation

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1269]
So there's been a change to some of the business requirements behind how we want records and silos associated. It's a bit tricky so it might warrant a discussion.

So here's where we eventually want to get to:

* Let's say we have a Silo called 'Bay Area'
* We still want to have users that associate with that silo
* We still want a user to have the ability to create a records from scratch and edit records they have previously created
* We still want the idea of a user group, allowing for multiple users to edit a set of records
* We still want the above records to appear to all other users in that silo with search/sort/filter/map/etc functionality

Example of what's changed?
* We would now like the ability to populate the 'Bay Area' silo with a SUBSET of records from the 'Eden' system account, in addition to the records created by the users in that silo
* These Eden records would work with the same search/sort/filter/map/etc functions and would mix with the user records from the silo
* These Eden records would always reflect the most up to date information available via the iCarol API job

* A serviceprovider user can log in to the silo and for an Eden record, is afforded an option to 'Claim this Record'

* When a user 'claims' a record, the following happens:
** The 'Eden' version of the record is detached from the Silo. It will no longer appear in search/filter/sort/map/etc
** The record is copied as a new record which is a snapshot of how the record existed at the time it was claimed. This record is part of the claiming user's silo and is now owned by the claiming user

This copied record is now entirely detached from the original. Future iCarol API jobs dont affect this records. Data changes will only come via edits by a ServiceProvider user

Please advise on architecture changes you think may help accomplish this.

Keep in mind we only want CERTAIN Eden records and not all Eden records. The logic for which records we want to include can be quite complex - so I think the easiest way to accomplish this at first will to have some table where I can inject the OrganizationIDs I want to be included in the Silo.

**Comment by jkondrat** [comment]
@johnhbenetech the most straightforward way to accomplish this would be to add a relation between the silo and the records. The question is - should it be one to many or many to many? Could a record be associated to multiple silos in the future?

**Comment by johnhbenetech** [comment]
I think many-to-many would be safest option.

So basically a rough sketch of the logic would be:

* Within a silo show any org created within that silo or any org having a row in the new table with matching silo_id 
* If a record was not created within the silo (is not owned by a serviceprovider user) allow the record to be claimed
* Once a record is claimed, the record will be copied to a new record owned by the claiming user. The source record will be removed from the new table with matching silo_id (so that only the claimed version will appear).

Does that all sound correct?

**Comment by jkondrat** [comment]
That sounds right @johnhbenetech
