### ISSUE TITLE
Improve the performance of get-taxonomies and other endpoints used by the filters

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#1273]
When opening a filter on SN view, the get-taxonomies request takes about a second. We should only fetch taxonomies from service provider. 

dev note: we could either create a new get-taxonomies endpoint for service providers, or add 'systemAccount' parameter to the endpoint. With the latter, we could also improve performance of the classic view (we would then have to load taxonomies for selected providers on the fly when changing 'partner sources')

**Comment by abaranowska1** [comment]
**Tested with success**
The performance of get-taxonomies is changed from more than 1s to 400-500 ms. 
![image](https://user-images.githubusercontent.com/61964176/97859712-4a151300-1d01-11eb-9485-8647a1ccb274.png)
