### ISSUE TITLE
Map data from UWBA to a common structure

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#129]
An adapter for data from partner UWBA should be implemented, with a wiki page, describing how it's mapped.

**Comment by johnhbenetech** [comment]
@oskarhinc please review #137 for this task. These changes should also be implemented in the Eden mapping.

**Comment by oskarhinc** [comment]
@johnhbenetech ok, we will prioritize this

**Comment by kcissewski** [comment]
Tested with success.
