### ISSUE TITLE
Sign in process for CBO's

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1301]
**for CBOs/orgs with multiple locations**

![Screenshot 2020-10-07 111409](https://user-images.githubusercontent.com/65787629/95370855-402cfb00-088e-11eb-8aea-732c963dc75a.png)

As shown above, add a second pop up after sign-in credentials have been inputted 
and show a classic menu horizontal 
(https://e34vsd.axshare.com) link to prototype to see how it flows (type anything for username and password)

![Screenshot 2020-10-07 111626_LI (2)](https://user-images.githubusercontent.com/65787629/95371481-1c1de980-088f-11eb-9e23-d8b5f3e3460f.jpg)

*save the city where they are referring from for later usage*

this login credentials page alongside the location picker will only be for new/first time users. every time after that, the place they are "working" at will be stored. the ability to change that saved location will be in task #1310 

**if they are logging in from a cbo with one location void this whole process and let them sign in**
**as well as "cbo/orgs" that have no locations, null in process, virtual service, toll-free number  **

**Comment by johnhbenetech** [comment]
@EnriqueCorado I need you to think through this from the absolute beginning.

* When a user signs in for the first time they will not have any orgs associated with their account (as they have not claimed any records as they have not logged in). What should happen in this case?

* A user may own/claim multiple organizations each having multiple locations - I do not see this scenario handled in the mockup

* A user sets their location, but later that location or entire organization record is deleted. What happens in this case?
