### ISSUE TITLE
CBO Interface: Referral to org/cbo with multiple locations

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1311]
![Screenshot 2020-10-07 121044](https://user-images.githubusercontent.com/65787629/95376662-4a52f780-0896-11eb-9511-36a58c7c2235.png)

- add the dropdown option
- If the referral is made from Richmond, CA (based on input from task #1301) then the dropdown will pre-populate the first options with Richmond locations

![Screenshot 2020-10-07 121053](https://user-images.githubusercontent.com/65787629/95376713-5fc82180-0896-11eb-9cf1-cd7d87e93d07.png)

**If the user signs in from a CBO that has only one location we will assume they will filter the city during the referral process**
![Screenshot 2020-10-07 121412](https://user-images.githubusercontent.com/65787629/95376921-a9b10780-0896-11eb-88bf-8d454aca6024.png)

- use the location filters (city, zip code) to determine how to organize data on the dropdown menu in the referral dropdown as above

**if the user signs in from a CBO that's based online, it will be the same process as above when they are asked for a CBO in a specific city or zip**

**Comment by johnhbenetech** [comment]
@EnriqueCorado can you provide an example when there are multiple referrals in the cart? I assume there will need to be a dropdown per org. It would be super helpful if you can make a mockup using the current design in the dev environment

**Comment by EnriqueCorado** [comment]
@johnhbenetech 

Here is an example with multiple referrals in the cart as well as a classic menu horizontal so you can see what's under (the next organization you will be referring from)

<img width="917" alt="Screenshot 2020-10-15 083848" src="https://user-images.githubusercontent.com/65787629/96152875-ddf17d00-0ec1-11eb-8dca-197a3a380285.png">

<img width="919" alt="Screenshot 2020-10-15 083910" src="https://user-images.githubusercontent.com/65787629/96152922-eb0e6c00-0ec1-11eb-8367-73838e6d82bb.png">

The different initial referral options are to the organization the referrals belong to, and the "dropdown" corresponds to the locations of where these are

**Comment by johnhbenetech** [comment]
@EnriqueCorado can you show how it looks on mobile (where the righthand popout may not fit)

Also can you show what the selector looks like when a location is selected. I assume we want to change   the text to reflect the selected location

**Comment by EnriqueCorado** [comment]
@johnhbenetech changed design for sake of simplicity and match other dropdowns currently in beneficiary history 
**desktop view**
<img width="917" alt="Screenshot 2020-10-15 094421" src="https://user-images.githubusercontent.com/65787629/96160657-19dd1000-0ecb-11eb-902f-6c4d81610339.png">

<img width="938" alt="Screenshot 2020-10-15 094436" src="https://user-images.githubusercontent.com/65787629/96160672-1ea1c400-0ecb-11eb-946a-e3ce68d6ba87.png">

<img width="925" alt="Screenshot 2020-10-15 094452" src="https://user-images.githubusercontent.com/65787629/96160680-219cb480-0ecb-11eb-906f-3ef394b7faca.png">

**mobile view**
<img width="134" alt="Screenshot 2020-10-15 094545" src="https://user-images.githubusercontent.com/65787629/96160735-37aa7500-0ecb-11eb-869c-d061211fb651.png">

<img width="131" alt="Screenshot 2020-10-15 094607" src="https://user-images.githubusercontent.com/65787629/96160781-455ffa80-0ecb-11eb-8054-3124c4c060fc.png">

<img width="130" alt="Screenshot 2020-10-15 094634" src="https://user-images.githubusercontent.com/65787629/96160835-54df4380-0ecb-11eb-8cbf-8242fbe83bbe.png">

can we eliminate the amount of space around the "referral" title, please

**Comment by johnhbenetech** [comment]
sounds good

**Comment by abaranowska1** [comment]
**Tested**
- Dropdowns with multiple locations were added to the referral page
![image](https://user-images.githubusercontent.com/61964176/97688565-91e63100-1a9a-11eb-88c0-d93a3c6f4be6.png)
- It is a chance to pick the proper location when the Organization has more than one address
- From Location and To Location  fields are filled on the Entity Referral Page
![image](https://user-images.githubusercontent.com/61964176/97688523-87c43280-1a9a-11eb-9cda-f63728046cbd.png)
- @jkondrat I met one UI issue on mobile view, I think there is too much space above and below the Referrals title and location dropdowns are too narrow, maybe Remove buttons should be smaller.
![image](https://user-images.githubusercontent.com/61964176/97689356-b7c00580-1a9b-11eb-9fa6-62b5a7c8fa38.png)
**Verified on:**
- Ubuntu 20.04
- Mobile 360x640
- Google Chrome Version 85.0.4183.83

**Comment by abaranowska1** [comment]
**Tested with success**

- Dropdowns with multiple locations were added to the referral page
- It is a chance to pick the proper location when the Organization has more than one address
- From Location and To Location fields are filled on the Entity Referral Page
- Mobile issues were fixed, now the remove button is smaller, and mostly the whole content is on the one page 
![image](https://user-images.githubusercontent.com/61964176/97857070-7af34900-1cfd-11eb-95d4-8231a6bae200.png)

**Verified on:**

- Ubuntu 20.04
- Mobile 360x640
- Google Chrome Version 85.0.4183.83

**Comment by EnriqueCorado** [comment]
good, release
