### ISSUE TITLE
Fix issues discovered by CodeQL

### ISSUE THREAD

**Issue by kkaczmarczyk** [benetech/ServiceNet#1316]
CodeQL runs well now and its checks discovered a few issues, which need investigation.
Note: these issues may be introduced by initial JHipster configuration and/or be false-positives

TODOs:
* investigate issues on Gateway/Core/Auth
* fix them as needed

**Comment by jkondrat** [comment]
@kkaczmarczyk @johnhbenetech I don't see any issues in these 3 repos - am I missing something?
