### ISSUE TITLE
Mobile: ServiceNet CBO Interface Homepage layout

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1327]
Use Case: Homepage for Servicenet CBO Interface for Mobile

## Full Mockup
![X - 10SN_Mobile_Homepage](https://user-images.githubusercontent.com/12637929/96177591-1746de80-0efc-11eb-9f10-776b14f05998.png)

The Above mockup shows the CBO ServiceNet Homepage in context

## UI/UX details
For 'Refer Elsewhere' text: 
   -  font: Roboto, 
   -  font size: 24
   - Alignment: Centrally aligned to the width of the screen

### Changes from the past
- Search bar moves from top of the page to underneath 'Refer Elsewhere' section
- the 'All records' progress bar("showing 6 of 10 records") does not show on the page. 

### Acceptance Criteria
When a user from CBO logs in to ServiceNet, the user should see that the homepage has 'add a record' section on the top followed by the Refer Elsewhere section. The Refer Elsewhere section should have a search bar, sort and filter buttons and toggle to map view buttons.

**Comment by abaranowska1** [comment]
**Tested with success**
- The new homepage layout looks similar to the mockup.
- The search bar moved from the top of the page to underneath 'Refer Elsewhere' section
- The progress bar was removed from the homepage
![image](https://user-images.githubusercontent.com/61964176/97541264-24b49c00-19c5-11eb-87e3-83f3464def72.png)
**Verified on:**
- Ubuntu 20.04
- Mobile 360x640
- iPhone X

**Comment by sidmundhra** [comment]
This looks good. Works as intended. Confirm for release.
