### ISSUE TITLE
Mobile: Servicenet CBO interface: Search Bar activation. 

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1328]
Use Case: This task defines the homepage layout for ServiceNet CBO interface when Search Bar is activated/interacted with.

## Full Mockup
![X - 11SN_Mobile_Search Bar](https://user-images.githubusercontent.com/12637929/96179555-0481d900-0eff-11eb-87ff-1511ca90b86c.png)

The Above mockup shows the CBO ServiceNet Homepage in context

## UI/UX details
For 'Refer Elsewhere' text: 
   -  font: Roboto, 
   -  font size: 24
   - Alignment: Centrally aligned to the width of the screen

For Black overlay on the screen
  - Color: #000000
  - Opacity: 65%

### Changes from the past
- 'Refer Elsewhere' section moves to the top of the page by auto scroll. Hiding 'Add a new record section'.
- the 'All records' progress bar("showing 6 of 10 records") does not show on the page. 
- The screen has a black overlay with 65% opacity when the search bar is clicked

### Acceptance Criteria
When a user from CBO logs in to ServiceNet and taps the search bar to search for services, the page should auto scroll to select to the refer elsewhere section and page would be overlaid by a black tint highlighting only the search bar.

**Comment by abaranowska1** [comment]
**Tested with success**
When a user from CBO logs in to ServiceNet and taps the search bar to search for services, the page is auto scrolled to the refer elsewhere section and the page is overlaid by a black tint highlighting only the search bar.

![image](https://user-images.githubusercontent.com/61964176/97544003-49ab0e00-19c9-11eb-8b21-7b8c9af3ceba.png)


**Verified on:**
- Ubuntu 20.04
- Mobile 360x640
- iPhone X
