### ISSUE TITLE
Mobile: ServiceNet Public Homepage Layout

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1329]
Use Case: This task defines the homepage layout for ServiceNet Public interface.

## Full Mockup
![X - 6ServiceNet_Mobile- Public Homepage](https://user-images.githubusercontent.com/12637929/96183480-ed45ea00-0f04-11eb-94ed-89decb3ed5f6.png)

The Above mockup shows the CBO ServiceNet Homepage in context

### Changes from the past
- the 'All records' progress bar("showing 6 of 10 records") does not show on the page. 
Search bar moves below and centrally aligned.

### Acceptance Criteria
When a public user lands on ServiceNet on mobile, the user should see that the homepage with a search bar, map toggle, and sort and filter buttons to interact with the service.

**Comment by sidmundhra** [comment]
@johnhbenetech: There are a few changes on this layout.

##full mockup
![X - 6ServiceNet_Mobile- Public Homepage](https://user-images.githubusercontent.com/12637929/96183480-ed45ea00-0f04-11eb-94ed-89decb3ed5f6.png)

Notable changes from the previous version
- Search bar moves below and centrally aligned.

**Comment by abaranowska1** [comment]
**Tested with success**
- The new homepage layout looks similar to the mockup.
- The search bar moved from the top of the page to the big pill button
- The progress bar was removed from the homepage
![image](https://user-images.githubusercontent.com/61964176/97542855-bfae7580-19c7-11eb-8ef9-d16df9de15bf.png)

**Verified on:**
- Ubuntu 20.04
- Mobile 360x640
- iPhone X

**Comment by sidmundhra** [comment]
This looks good. Works as intended. Confirm for release.
