### ISSUE TITLE
Mobile: ServiceNet Public Interface: Search Bar activation

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1330]
Use Case: This task defines the homepage layout for ServiceNet Public interface when Search Bar is activated/interacted with.

## Full Mockup
![X - 6ServiceNet_Mobile- Public search bar activation](https://user-images.githubusercontent.com/12637929/96183734-53cb0800-0f05-11eb-953e-0fea94221c8a.png)

The Above mockup shows the ServiceNet Homepage in context

## UI/UX details
For Black overlay on the screen
  - Color: #000000
  - Opacity: 65%

### Changes from the past
- the 'All records' progress bar("showing 6 of 10 records") does not show on the page. 
- The screen has a black overlay with 65% opacity when the search bar is clicked
-  Search bar has moved below and centrally alinged in the rounded rectangle.

### Acceptance Criteria
When a user interacts with ServiceNet on Mobile and taps the search bar to search for services, the page should be overlaid by a black tint highlighting only the search bar.

**Comment by sidmundhra** [comment]
@johnhbenetech : There are few changes to this version.

## full mockup
![X - 6ServiceNet_Mobile- Public search bar activation](https://user-images.githubusercontent.com/12637929/96183734-53cb0800-0f05-11eb-953e-0fea94221c8a.png)

Notable changes to the previous version:
-  Search bar has moved below and centrally alinged in the rounded rectangle.

**Comment by abaranowska1** [comment]
**Tested with success**
When a user interacts with ServiceNet on Mobile and taps the search bar to search for services, the page is overlaid by a black tint highlighting only the search bar.

![image](https://user-images.githubusercontent.com/61964176/97544424-df469d80-19c9-11eb-8e27-0a7fe495fd70.png)

**Verified on:**
- Ubuntu 20.04
- Mobile 360x640
- iPhone X

**Comment by sidmundhra** [comment]
this looks good. Works as intended. Confirm for release.
