### ISSUE TITLE
Mobile: ServiceNet Map view layout for both public and CBO interface.

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1331]
Use Case: This task defines the map page layout of Servicenet public and CBO interface.

## Full Mockup
![X - 15SN_Map View Mobile](https://user-images.githubusercontent.com/12637929/96186194-17011000-0f09-11eb-9d56-dba4fe4f5f29.png)

The Above mockup shows the ServiceNet Map View in context

### Notable Changes from the mockup
- The 'Search This Area' button on the top needs to be moved below and needs to have a white background with drop shadow.

### Notable Changes from the current version
- The initial map view loads at San Francisco.
- The map can be moved by one-finger interaction. (Currently, the map requires two fingers to move). The scaling function will continue to use the two-finger interaction.
- The sort, filter and list view toggle buttons are separated from the map and are part of the search bar section.

### Acceptance Criteria
When a user interacts with ServiceNet on Mobile and toggles to map view. The map view should initially load at San Francisco and display all the services in the area. The user should be able to move the map around with one finger and should require two fingers for zooming in or out of the map. The search bar in this layout should be at the top and underneath it, the buttons for toggle to list view, sort and filter. The user should be able to see the 'search this area' button at the bottom of the page approximately 1/4 of the distance from the bottom.

**Comment by johnhbenetech** [comment]
dev note: need to investigate greedy gestureHandling
https://cloud.google.com/blog/products/maps-platform/smart-scrolling-comes-to-mobile-web-maps

**Comment by abaranowska1** [comment]
- The initial map view loads at San Francisco
- The map can be moved by one-finger interaction
- The 'search this area' button was moved to the bottom 
- @jkondrat The sort, filter, and list view toggle buttons are not part of the search bar section, there are not visible
![image](https://user-images.githubusercontent.com/61964176/97966461-282c9680-1dbc-11eb-86fa-de6c8725ef9d.png)

**Comment by abaranowska1** [comment]
@johnhbenetech @sidmundhra 
Which button view do you prefer and should the buttons stay while scrolling or not?
| ![image](https://user-images.githubusercontent.com/61964176/97972092-4e563480-1dc4-11eb-9717-0171f625ee6b.png) | ![image](https://user-images.githubusercontent.com/61964176/97972099-51512500-1dc4-11eb-90e4-1b43aaeb6320.png) |
| ---      | ---       |

**Comment by johnhbenetech** [comment]
@sidmundhra can you answer

**Comment by johnhbenetech** [comment]
@jkondrat @abaranowska1 Lets go with the rounded corner approach.

The top section should remain static at the top and should not scroll with the page

**Comment by abaranowska1** [comment]
**Tested with success**
The top section stays static and is not scrolled with the page. 
![image](https://user-images.githubusercontent.com/61964176/98356141-6ecffa00-2023-11eb-99ef-cd4bb3771544.png)

**Comment by sidmundhra** [comment]
@johnhbenetech @jkondrat : tested this on Safari. iPhone 11. iOS 14.2

The map view doesn't load the map. Screenshots below.

![IMG_8863](https://user-images.githubusercontent.com/12637929/98563926-bea7fe80-2279-11eb-97b4-2df4efee09f8.PNG)
![IMG_8862](https://user-images.githubusercontent.com/12637929/98563930-bfd92b80-2279-11eb-8672-d9402742dbaf.PNG)

**Comment by johnhbenetech** [comment]
@jkondrat seems to be okay on desktop Safari, but i confirm not working on mobile safari

**Comment by johnhbenetech** [comment]
@jkondrat alright, nevermind it randomly started working again - who knows

@abaranowska1 I guess maybe check on mobile safari again to see if it works for you as well. I also notice a few responsiveness issues on public view, map view card - so maybe you can break those out into tasks with the regression

**Comment by abaranowska1** [comment]
@jkondrat It also doesn't work on my iPhone X, iOS 14.1, Safari browser.
@johnhbenetech Sure, I will check it and break into tasks during regression

**Comment by abaranowska1** [comment]
It will be tested together with #1378
