### ISSUE TITLE
Duplicating a record

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1332]
when you click duplicate record then it saves everything from the current record edit and duplicates it, shows up on the screen
- add a button that allows this capability, "Duplicate Record" on the bottom of the record editing 
- also add a feature in order to make sure they changed at least their location, service details, or name of their record 
- if nothing was changed, when they click finish show an alert that the same duplicate record can't be saved

<img width="725" alt="Screenshot 2020-10-15 154539" src="https://user-images.githubusercontent.com/65787629/96193665-7f49f480-0efd-11eb-891b-27b6bc2356de.png">

**Comment by johnhbenetech** [comment]
@EnriqueCorado What's the user story for this? what's the value
