### ISSUE TITLE
Unclaiming a record 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1333]
This will throw out any user-provided info and just re-add the original Eden record to the collection
- make sure we add this to the schema in case we don't add this feature immediately, but have the functionality ready to go 
- add button at the bottom, same font, size, color 

<img width="729" alt="Screenshot 2020-10-15 154756" src="https://user-images.githubusercontent.com/65787629/96193785-d18b1580-0efd-11eb-8824-0eaa00820816.png">

**Comment by meenupant** [comment]
How is Unclaim Record different than Deactivate Record? I want to understand the process when someone clicks one of these buttons then what happens to the record. The user may get confused and this may delay any action taken by him. The CTA must be absolutely clear to the user.

**Comment by EnriqueCorado** [comment]
@meenupant unclaim breaks ties from the user updating the record and would go back to the algorithm updating the record 
Deactivate record is for users who created their own record which did not exist in service net so they can essentially delete it

**Comment by meenupant** [comment]
@EnriqueCorado Do they really care if it exists in our records? It is up to us to decide whether we should just revert back to the old record that already exists in our database or just remove it if it does not exist. I think let's brainstorm this further to make the process more clear and not confuse the user.

**Comment by kkaczmarczyk** [comment]
@EnriqueCorado @meenupant should some pop-up appear after clicking on "Unclaim Record" button? Also, are there any new findings coming from the brainstorm?

**Comment by EnriqueCorado** [comment]
@kkaczmarczyk 
- have a pop up saying "Record successfully unclaimed" 
- no new findings from brainstorm

**Comment by abaranowska1** [comment]
@awalkowiak 
The unclaim button disappear after I did any update and click the I'm Finished button 
![Peek 2020-12-16 14-10](https://user-images.githubusercontent.com/61964176/102352824-8ac2a600-3fa8-11eb-93ef-bcd03023ea4c.gif)

**Comment by abaranowska1** [comment]
**Tested with success**
- The unclaim button stays after update record 
![image](https://user-images.githubusercontent.com/61964176/102371304-5659e480-3fbe-11eb-86fb-f1ec741f59ad.png)
