### ISSUE TITLE
Allow for enabling referral functionality at the silo level

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1337]
Similar to the "public" setting, each silo should have an allow referral setting.

If false, it should hide the referral UI elements from the user. I'm fine with this being a relatively dumb front end only restriction (basically just dont render the 'refer' and referral cart UI elements)

**Comment by abaranowska1** [comment]
The possibility to turning on/off referral functionality at the silo level was added to the admin page and works fine in Service Provider View. There is a chance to turn off the referral functionality. 
![image](https://user-images.githubusercontent.com/61964176/96988688-f0ecf880-1524-11eb-92bd-e5b703cad882.png)
![image](https://user-images.githubusercontent.com/61964176/96988696-f5b1ac80-1524-11eb-819e-aa20dfdf77c2.png)
![image](https://user-images.githubusercontent.com/61964176/96988716-fba78d80-1524-11eb-919c-cf9f20746177.png)
