### ISSUE TITLE
Registration 500 error

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1338]
Currently I am getting a 500 error on registration on dev

This should be a priority task

**Comment by johnhbenetech** [comment]
The registration appears to go through, but the user is afforded an ISE message (as well as in the JS Console) which leads one to believe it failed

**Comment by abaranowska1** [comment]
**Tested with success**
Internal Server Error doesn't occur anymore. 
![Peek 2020-10-21 14-38](https://user-images.githubusercontent.com/61964176/96720565-3685b600-13ab-11eb-8041-8c1c9647f689.gif)
