### ISSUE TITLE
admin users can't load taxonomy

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1339]
When logged in as admin user and viewing a public view of SP page, the taxonomy API errors

**Comment by johnhbenetech** [comment]
@awalkowiak maybe you can poke at #1348 while you are in this part of the code

**Comment by awalkowiak** [comment]
@johnhbenetech sure. I'll look into it.

**Comment by abaranowska1** [comment]
**Tested with success**
No errors are generated when you are logged in as adminuser and view the public view of the SP page.
![image](https://user-images.githubusercontent.com/61964176/97310852-03886a00-1864-11eb-86a6-f9841a6e684d.png)
