### ISSUE TITLE
Map Healthleads x_schedule correctly

### ISSUE THREAD

**Issue by kcissewski** [benetech/ServiceNet#134]
There is no simple pattern for locations.x_schedule column that could be used to map to RegularSchedule entity.
Example values:
Monday - Friday: 8 am - 4 pm 
Saturday: 8 am - 3 pm 
Sunday: CLOSED 

Community Produce Program: 
1st and 3rd Thursday of each month, 12pm-1 pm 
Food Assistance Program: 
3rd Tuesday of each month, 10am-12pm 

9 am- 5pm

We need to find a way to map it correctly.

**Comment by bognasoldev89** [comment]
Confirmed that x_schedule content is mapped correctly to ServiceNet.

![Screenshot from 2019-07-31 11-48-45](https://user-images.githubusercontent.com/51324797/62202325-63564380-b389-11e9-87ab-3191fe3434a0.png)

![Screenshot from 2019-07-31 11-54-11](https://user-images.githubusercontent.com/51324797/62202646-f2635b80-b389-11e9-9a91-169210415936.png)
