### ISSUE TITLE
Beneficiary unique identifier

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1342]
Currently the UUID (unique ID) looks like this d8e5d573-cd57-4eec-8a34-af93b6e2b194 for Beneficiaries 

<img width="335" alt="Screenshot 2020-10-20 123334" src="https://user-images.githubusercontent.com/65787629/96635292-86437f00-12d0-11eb-8e85-38325da40ee1.png">

We want something more user friendly in order for beneficiaries to use this code to check-in for example

As every phone number gets checked in or gets entered in order to receive a referral, a simple unique identifier will be provided with the initial structure of 

letter, letter, digit, digit, digit

combining both upper and lower case. It will be calculated in "increasing order" for example, once aa000 is used, aa001 will be used, and so on for digits. For letters, aa000 then use all numbers, then ab000

Once, these options get exhausted, add another digit at the end and use the same method as above 

These short unique identifiers will stick with a beneficiary for all time so we can monitor the complete picture of when the code was used 

<img width="758" alt="Screenshot 2020-10-20 124644" src="https://user-images.githubusercontent.com/65787629/96636577-54cbb300-12d2-11eb-9b24-b5711a69080c.png">

**Comment by jkondrat** [comment]
@EnriqueCorado @johnhbenetech I think it would be better to ignore the casing of characters - users might get confused with AA000 and Aa001 being different ids. With two letters and three numbers, we get 676.000 unique combinations, if we use lower and uppercase letters it's 2.704.000 ids.

What do you think about alphanumeric ids? It's much easier to generate and handle these ids, this would be basically a base-36 representation of an integer.
With 4 characters there would be 1.679.616 combinations, with 5 characters it's 6.0466.176 unique ids.
Example identifiers (numeric and lowercase letters);
`0000, 0001, 0002, ... 000a, 000b, 000c, ... 000z, 0010, 0011, 0012, 
... 001a, etc.`

**Comment by EnriqueCorado** [comment]
@jkondrat 

let's go with alphanumeric so it is easier to generate and handle ids. Thank you

**Comment by abaranowska1** [comment]
**Tested with success**
- Now Unique ID's were created. 
- There is a chance to see the new ID in the Beneficiary History table.
- If the Phone Number and ID are valid the Referral functionality works without issue.
![image](https://user-images.githubusercontent.com/61964176/98396022-65638380-205d-11eb-81ab-6e48e16c8770.png)
