### ISSUE TITLE
Investigate loading of taxonomy and geofilter dropdowns

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1348]
In investigating the network traffic on opening the filter pane - I'm noticing that the taxonomy and geo API calls often have an empty 'SiloName' parameter. The taxonomy also sometimes has SiloId parameter empty

It appears that sometimes the blank parameter still yields results sometimes - but I'm not sure what's going on specifically

**Comment by abaranowska1** [comment]
**Tested with success**
- I see that now location and taxonomy dropdowns display also data from Eden Organizations
- Filters works without issue, it is possible to filter data also from Eden Organization 
- Eden Organizations are displayed on the Map view as well 
![Screenshot_2020-10-27_15-48-40](https://user-images.githubusercontent.com/61964176/97319626-59addb00-186d-11eb-8a64-9282046d61c7.png)
![Selection_249](https://user-images.githubusercontent.com/61964176/97319633-5c103500-186d-11eb-83b4-0bca291dbb81.png)
![Screenshot_2020-10-27_15-50-35](https://user-images.githubusercontent.com/61964176/97319650-5f0b2580-186d-11eb-9005-2e1e4816b8b9.png)
**Verified on:**
- Ubuntu 20.04
- Google Chrome Version 85.0.4183.83
