### ISSUE TITLE
ServiceNet Web Platform: Initial loading of Map View on Web platform. 

### ISSUE THREAD

**Issue by sidmundhra** [benetech/ServiceNet#1351]
Use Case: This task defines the initial loading of Map view on the Web platform of ServiceNet

## Full Mockup
![Desktop - 1SN_Public_map_view_cropped](https://user-images.githubusercontent.com/12637929/97229254-6fa89680-17ae-11eb-8bd8-c4b9a2dc6191.png)

The Above mockup shows the ServiceNet Map View for web platform for public view in context.

### Notable Changes from the mockup
- The 'Search This Area' button on the top needs to be moved below and needs to have a white background with drop shadow.

### Notable Changes from the current version
- The initial map view loads at San Francisco.

### Acceptance Criteria
When a user interacts with ServiceNet on web and toggles to map view. The map view should initially load at San Francisco and display all the services in the area. The user should be able to see the 'search this area' button at the bottom of the page approximately 1/4 of the distance from the bottom.

**Comment by abaranowska1** [comment]
**Tested with success**
When we changed the view to the map view the map is automatically zoomed to San Francisco and services near this area are displayed. 
![image](https://user-images.githubusercontent.com/61964176/99241342-07bdfc80-27fe-11eb-926f-d916110c6ef3.png)
![image](https://user-images.githubusercontent.com/61964176/99241360-0e4c7400-27fe-11eb-8501-db5c57deaa20.png)

**Comment by sidmundhra** [comment]
looks good. Works as intended.
