### ISSUE TITLE
Remove Double Header of Home on Public SN

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1354]
Remove Double Header of Home on Public SN
- Just keep the Home option near the benetech logo and use the same font and style as the CBO interface header look 

<img width="958" alt="Screenshot 2020-10-27 075834" src="https://user-images.githubusercontent.com/65787629/97319600-4594ba00-182a-11eb-884d-3ebe554a445e.png">

**Comment by abaranowska1** [comment]
**Tested with success**
- Double Header of Home on Public SN View was removed
- The font was changed and now public and standard SP View look the same
![image](https://user-images.githubusercontent.com/61964176/99235839-a8102300-27f6-11eb-8432-c5a906904668.png)
