### ISSUE TITLE
Investigate 'Untyped' taxonomy terms in SP view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1355]
On some records from linked partner sets (UWBA for instance) services will sometimes display 'Untyped' for service type.

examples on this record:
https://servicenet.benetech.org/#/public/OCOF/single-record-view/7888135e-b4a8-4ff1-858b-95ac65695ae5

In the database it seems to be driven by having no records in service_taxonomy for those services.

Instead of showing a pill with untyped. Can we display text 'No service type found'

**Comment by abaranowska1** [comment]
I check it on staging instance and now I see that the untyped pill is changed to the text: "No service type found" and after 1-2 sec all service types are displayed. 
![Peek 2020-10-29 13-43](https://user-images.githubusercontent.com/61964176/97575880-b1735000-19ed-11eb-9451-bb83d3c042c6.gif)
