### ISSUE TITLE
Reevaluate taxonomy filter loading method on ServiceProvider views

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1356]
Currently in a ServiceProvider view with linked records from a partner dataset (UWBA, Eden, etc) the taxonomy filter only loads the terms for the ServiceProvider taxonomy. As a result there is no way to filter linked records.

Ideally my desired end state is as follows:

As a user on ServiceProvider view (authenticated or public view) I want the taxonomy filter dropdown to be populated by taxonomy terms for ANY service in that silo - both user created and linked from partners.

Taxonomy terms that would yield no results (due to no matching service being included in the silo) should not be displayed.

I understand this reducer may be complicated or has performance issues - so please make me aware of limitations that may exist

**Comment by awalkowiak** [comment]
@johnhbenetech could you give an example of a linked organization for which you are having this issue? For the organization from Eden (MidPen Housing) we can see its taxonomy on the filter list.

**Comment by johnhbenetech** [comment]
https://servicenet.benetech.org/#/public/OCOF/single-record-view/7888135e-b4a8-4ff1-858b-95ac65695ae5

See the services with type 'VITA Programs'

This do any appear in the filter @awalkowiak

**Comment by awalkowiak** [comment]
@johnhbenetech thanks

**Comment by johnhbenetech** [comment]
@awalkowiak and that's running the latest code and everything, so hopefully you can look at the API requests/responses and.see if anything looks off

**Comment by abaranowska1** [comment]
It is hard to reproduce it for me, but when I check it on my Silo with Eden Organizations I can see all taxonomies in the drop-downs 
![Peek 2020-10-29 14-20](https://user-images.githubusercontent.com/61964176/97579215-13ce4f80-19f2-11eb-8989-38c5ebdc975a.gif)
