### ISSUE TITLE
SN Registrations/Logins must go through captcha

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1359]
Please add a captcha pop up after a user registers and logs in

- one place where we can get this is from https://developers.google.com/recaptcha/intro
- the documentation and code snippets are there

<img width="1292" alt="Screenshot 2020-10-28 120917" src="https://user-images.githubusercontent.com/65787629/97484761-6c301f00-1916-11eb-8c30-36a77091b4c9.png">

**Comment by johnhbenetech** [comment]
Looking for recommendation from dev team on v3 vs v2 captcha. My understanding is v3 can be made invisible to the user, but not sure of how that might work within the context our site specifically

**Comment by abaranowska1** [comment]
**Tested with success**
Captcha algorithm was added to the SN Registrations/Logins pages 
![image](https://user-images.githubusercontent.com/61964176/99264322-980d3900-2820-11eb-99ba-b507cc26cc4e.png)

Example from my phone:
![image](https://user-images.githubusercontent.com/61964176/99264211-71e79900-2820-11eb-8e7a-952bf72c7084.png)

**Comment by EnriqueCorado** [comment]
on the sign-in popup, if you refresh the page the captcha icon loads on top of the sign-in button. potential bug on website reload

**Comment by abaranowska1** [comment]
**Tested**
The captcha icon now is displayed only in the bottom right corner, there is one weird situation when the captcha icon is not displayed but it will be investigated together with #1398
