### ISSUE TITLE
Ensure data for each provider has proper relationships

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#136]
The mapping of the providers' data might be a complex process, and it is possible that some relations between the entities are lost. There should be provided tests for each of them to ensure all data is persisted with proper relationships. Additionally, some data might not make sense without any relations - e. g. Phone. Such entities should not be extracted, so if there are such entries, it might indicate that the mapping process gone wrong. Test data for each provider should reflect the real data as much as possible but should cover cases where some data is missing.

**Comment by johnhbenetech** [comment]
QA, this task seems to indicate the need for additional testing and possibly more coverage in unit tests.

Please check that all fields are being mapped and displayed as expected (i.e. opening hours, holiday schedules, contacts, phones, etc).

Make a wiki/note to list which fields may still need to be mapped for each adapter.

**Comment by pmuchowski** [comment]
LGTM
