### ISSUE TITLE
Investigate taxonomy terms shown with no results

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1362]
* On dev server, create a user on existing silo 'Eden Silo'.
* Log in to SP view and explore taxonomy filter dropdown - see one listed as 'Free Meals'
* Selecting this filter yields no results

Expectation:
* No taxonomy term should be listed if no attached services/orgs exist in that silo

More details for dev server:

taxonomy id:
b001adc7-07a5-4100-87c2-b017c56dfb08

attached services:
f7b9c660-20f2-4be3-be6f-e334a80ae39f
e174845c-60c8-4f2e-9675-3f9c27cdd30f

attached orgs
e5501e5b-5c9c-4683-9f10-5c3d3efeb9f9
97ecf341-6b49-4bb8-93c2-2c329fd91a9e

attached users
johntest2
bognaprov

Both of these users are in Silo1 and not 'Eden Silo'

**Comment by abaranowska1** [comment]
**Tested with success**
Only taxonomies from one silo are displayed on filters dropdowns. I checked that for example in EdenSilo there are no taxonomies from another silo with no results. 
**Verified on:**
- Ubuntu 20.04
- Google Chrome Version 85.0.4183.83
