### ISSUE TITLE
Allow unauthenticated access to API documentation

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1364]
Is their any risk to making the /#/admin/docs endpoint available to unauthenticated users?

I still don't want them to be able to do anything (no REST verbs), but it would be useful to show prospective integration partners an idea of our architecture without giving them admin access.

I'm fine moving it to a different endpoint /api/docs or whatever.

Or let me know if there already exists an unauthenticated version of this somewhere

**Comment by awalkowiak** [comment]
@johnhbenetech I dug this a bit and I realized, that we have already the entire API documentation open. I went through what I added in #786 and seems that everything is accessible via https://benetechservicenet.org/#/api-documentation. There is an option to check docs by definition (service: default = Gateway, servicenet = Core, servicenetauth = Auth) and you can filter by externally available end-points. On the bottom of each page, you can find DTO models.

**Comment by awalkowiak** [comment]
@johnhbenetech let me know what do you think about it.

**Comment by johnhbenetech** [comment]
Lgtm. closing
