### ISSUE TITLE
Do not display records/contacts marked as confidential for iCarol partners (currently UWBA and Eden)

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#137]
Certain Resource objects may have isConfidential key set to true.

Additionally, certain field level objects may define an isConfidential key.

For example:
contactDetails[isCofidential]

We will digest these objects from the API, but they should not be displayed in the frontend (even to the owner partner user). It's probably safest to prevent them from traversing over the document->database divide.

**Comment by oskarhinc** [comment]
I believe the best way to achieve this is to finish https://github.com/benetech/ServiceNet/issues/84 for exclusions, and then adjust the logic to include this case

**Comment by johnhbenetech** [comment]
That sounds fine. If possible I'd like this to be the first case we handle and then circle back to field level exclusions (even if it's managed by the same logic/same admin page).

People were very clear on the confidential think (makes sense) people were less clear on specific examples for field exclusion (just that they may want it in the future)

**Comment by oskarhinc** [comment]
Sure, in this case, we'll cover this case first.

**Comment by oskarhinc** [comment]
@johnhbenetech should the admin user be allowed to see those confidential fields, e. g. through Entities page?

**Comment by oskarhinc** [comment]
As discussed on the meeting, the confidential data won't be persisted in the database, so even admin can't see this.

**Comment by wojtekbu** [comment]
Checked on Organization.url for Eden. There is no data persisted in the database. Works fine
