### ISSUE TITLE
Public View Header "Home" and "Feedback" change

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1370]
Current view of public view header 

<img width="944" alt="Screenshot 2020-11-06 111838" src="https://user-images.githubusercontent.com/65787629/98405857-d5541880-2021-11eb-9816-ff9f25ec96d9.png">

Please match the header, font, color, and remove underline on public view to the one of the CBO

<img width="936" alt="Screenshot 2020-11-06 111903" src="https://user-images.githubusercontent.com/65787629/98405913-e3a23480-2021-11eb-9900-4dab9b55ea76.png">

**Comment by awalkowiak** [comment]
@EnriqueCorado We are gonna unify everything related to header components in #1227. This ticket will be also handled there.
