### ISSUE TITLE
CSV Download Names 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1371]
Fo referral history CSV download change the download name to"Beneficiary_Referral_History _dateOfDownload" 
Ex "Beneficiary_Referral_History _11-6-20"

 For "All Referral Made To History" change the download name to "#_Referrals_Made_From_(add the specific organization name)"
Ex (#_Referrals_Made_From_EPA_Food_Pantry)

For "All Referral Statuses" change the download name to "Referrals_Made_To_Us__dateOfDownload"
"Referrals_Made_To_Us_2020-11-06"

**Comment by jkondrat** [comment]
@EnriqueCorado The user can have multiple organizations and the "All Referral Made To History" contains all of them - which one should we pick for the report name? Perhaps we should display current user's name instead?

**Comment by EnriqueCorado** [comment]
@jkondrat great point. let's go with the username

**Comment by abaranowska1** [comment]
**Tested with success**
The CSV download names were changed.
![image](https://user-images.githubusercontent.com/61964176/99681078-0d297a00-2a7e-11eb-9bcd-249face401c9.png)

**Comment by EnriqueCorado** [comment]
good. release
