### ISSUE TITLE
Map View card - UI issue on mobile

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#1377]
As you can see on the screenshot there is an issue with the card on the mobile map view. 
- The direction button is too close to the hour and 
- Search this area button shouldn't be displayed on the card.

![image](https://user-images.githubusercontent.com/61964176/98674048-888d7c00-2358-11eb-9c40-8eec809b45c4.png)

**Comment by johnhbenetech** [comment]
@sidmundhra @MeenakshiP As a result of the design change in #1331 the 'search this area' button is now colliding with  the organization card on map view.

Should we just obscure the button behind the card? Is there another design you would like to explore?

**Comment by johnhbenetech** [comment]
@sidmundhra @EnriqueCorado can someone chime in on this?

**Comment by EnriqueCorado** [comment]
Let's move the "Search this area"

<img width="356" alt="Screenshot 2020-11-13 074817" src="https://user-images.githubusercontent.com/65787629/99091365-a0e1de80-2584-11eb-940b-e90b3bf52dbc.png">

**Comment by abaranowska1** [comment]
The "Search this area" button is smaller and was moved to the top right corner. UI issues on the card also were fixed, but @jkondrat plz take a look at the iPhone issue with the bottom browser bar, because in this case filter,sort,search... section didn't stay static. 
![image](https://user-images.githubusercontent.com/61964176/99385159-db26e500-28d0-11eb-8079-5b13c9d21d51.png)
![image](https://user-images.githubusercontent.com/61964176/99385168-de21d580-28d0-11eb-9420-a76921e052f0.png)

**Comment by abaranowska1** [comment]
It works for me. I check the traditional and public view
![image](https://user-images.githubusercontent.com/61964176/99415579-3f10d400-28f8-11eb-92fc-78afda002053.png)
![image](https://user-images.githubusercontent.com/61964176/99415596-420bc480-28f8-11eb-82be-fb3e519fb330.png)
