### ISSUE TITLE
Do not display/map records with status Inactive

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#138]
various sources seem to have some concept of a 'status' field.

My understanding (at least from the iCarol participants) is that this field can change from time to time when they want to remove/temporarily retire a record.

We should evaluate the Status filed and for those Inactive records either not map them at all or remove a previous mapping if the record has recently become Inactive.

**Comment by awalkowiak** [comment]
@johnhbenetech I think it would be better to keep the data in our db with active = false, but just without displaying it (and probably without checking for conflicts). Additionally I could add some kind of filtering in /entity/organizations to check for active/inactive (showing only active by default, but users could look for inactive too or maybe having separate page for inactive orgs).

**Comment by johnhbenetech** [comment]
Yes let's keep the data but not display it (either on the owners account or as a match on a different partners account)


No need to do anything with the entity admin page for now

**Comment by awalkowiak** [comment]
@johnhbenetech Organizationas are persisted, but matches and conflicts are removed (when some one upload updated org data matches and conflicts will be recreated)

**Comment by kkrawczyk123** [comment]
@awalkowiak Unfortunately, I might not be able to test it right now according to an issue connected with uploading of iCarol records. Could you please investigate?

**Comment by bognasoldev89** [comment]
@awalkowiak during upload of iCarol records I hit a few obstacles:
ShelterTech data shows that files weren't uploaded, but in fact, they were
Eden data shows that files were uploaded, but in fact, they weren't
UWBA shows that files weren't uploaded and that is true.

Could You investigate those issues?

**Comment by awalkowiak** [comment]
@bognasoldev89 this is not related to this issue, please create new issue for mentioned stuff (and link it here). Someone will take a look.

**Comment by bognasoldev89** [comment]
#510

**Comment by bognasoldev89** [comment]
@awalkowiak I made #510 issue in Backlog

**Comment by bognasoldev89** [comment]
Confirmed that iCarol records with status Inactive are not displayed
