### ISSUE TITLE
Referrals fail to send

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1385]
Steps to reproduce (edensilo on dev):

* Add an org to referrals by clicking 'refer' button
* Go to referral tab, and choose location from dropdown
* Enter phone number
* Hit send

Result: nothing happens
Expect: SMS to send and referral to be submitted

JS Console output:
![image](https://user-images.githubusercontent.com/12927553/98995263-b4466880-24f6-11eb-90cb-7be507a08250.png)

**Comment by johnhbenetech** [comment]
I think both #1208 and #1385 are caused by the case where a user only owns 1 record

The dropdown for organization selection doesnt render (which makes sense since there would only be one option) but that also seems to prevent the send button from being enabled

**Comment by abaranowska1** [comment]
@johnhbenetech 
I check the situation when the user has only 1 own record and in this case, I cannot send a referral
![Peek 2020-11-13 09-37](https://user-images.githubusercontent.com/61964176/99047531-a0514400-2594-11eb-9d76-e07e9c505d17.gif)

**Comment by abaranowska1** [comment]
**Tested with success**
When the user is an owner only one Organization now "Send" buttons are active. I can do a check-in and referral. Records are displayed in the Beneficiary History table. 
![Peek 2020-11-16 13-07](https://user-images.githubusercontent.com/61964176/99255475-452d8480-2814-11eb-9542-506628ae752e.gif)
Tested together with #1208
