### ISSUE TITLE
Investigate repeated consul? failures on dev

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1386]
I believe there to be an issue where possibly the consul container is nonfunctioning but fails to restart itself

On dev i currently cant register with the following error:

Exception in org.benetech.servicenet.service.UserService.registerUser() with exception = '{}'

com.netflix.hystrix.exception.HystrixRuntimeException: ServiceNetAuthClient#registerUser(UserRegisterDTO) timed-out and no fallback available.

**Comment by jkondrat** [comment]
@johnhbenetech It turns out that the exception wasn't caused by consul failure - the registration request going from core to auth took more than a second, so it timed out. I will increase the timeout to 10s (seems like this was a recommended value)

**Comment by johnhbenetech** [comment]
@jkondrat do you think this was also the cause of why the dev server couldn't be logged into last week? Or is that still a consul health check issue?

**Comment by jkondrat** [comment]
@johnhbenetech The downtime last week was caused by consul, none of the services could connect to it. When that happens again, I'll try to find out why it crashes in the first place. For now, we can add some health checks

**Comment by johnhbenetech** [comment]
@jkondrat would you like to do that as part of this task? If not please break out a new task in tech debt
