### ISSUE TITLE
UUID Static per phone number 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1387]
**check-in UUID adds a +1 
on referrals, it adds a 1 
creating two distinct UUIDs for one number**

- UUID should be static per phone number 

<img width="371" alt="Screenshot 2020-11-12 154247" src="https://user-images.githubusercontent.com/65787629/99009996-f626dd00-24fd-11eb-8910-d25e8eba9b5f.png">

![Image from iOS](https://user-images.githubusercontent.com/65787629/99010011-fc1cbe00-24fd-11eb-9f9c-9032e86c2d88.png)

**Comment by abaranowska1** [comment]
**Tested with success**
Now the "+" is added when we do a check-in and referral. ID's are the same in these two cases.
![image](https://user-images.githubusercontent.com/61964176/99395182-58a62180-28e0-11eb-885d-704934d7162a.png)
