### ISSUE TITLE
Beneficiary check in and referral notification of missing info to fill 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1392]
**Instead of having the send button be grey until all necessary information is filled out**
- make the button clickable like the registration (screenshot 2)  to inform the user of what is missing, instead of having the user wonder why the 'Send' button isn't "working"
- Simply add the same style of the red border around the cells missing information 
- Add the same border and idea to the referral section so users know if there's data missing once the user clicks on 'Send' and are unable to send a referral 

<img width="959" alt="Screenshot 2020-11-13 092711" src="https://user-images.githubusercontent.com/65787629/99102307-bfe76d00-2592-11eb-8a80-c81851ea3f10.png">

<img width="701" alt="Screenshot 2020-11-13 092840" src="https://user-images.githubusercontent.com/65787629/99102369-d7265a80-2592-11eb-9c52-aaacebdc6b43.png">

<img width="785" alt="Screenshot 2020-11-13 093738" src="https://user-images.githubusercontent.com/65787629/99103096-e4901480-2593-11eb-89af-5b7a7457d92f.png">

**Comment by awalkowiak** [comment]
@EnriqueCorado what in case if the user won't enter the phone number or beneficiary ID? Should we highlight both fields separately or together? If we highlight both fields separately we will give fault info to the user that both are required.
In my opinion, we could set the red frame around both fields and give a note to enter one of these two fields. What do you think about it?

**Comment by EnriqueCorado** [comment]
@awalkowiak Great point. Set a frame around both fields and give a note

**Comment by abaranowska1** [comment]
**Tested**
@awalkowiak @EnriqueCorado  We should add a note below the fields in the red frame and I'm not sure if we want it, but on mockup we have also "x" icon near the required fields.
![image](https://user-images.githubusercontent.com/61964176/99962476-8aabfd80-2d90-11eb-80b2-8cc257a80af8.png)

![Selection_445](https://user-images.githubusercontent.com/61964176/99962203-0b1e2e80-2d90-11eb-9b51-a310d2098e89.png)
![Selection_446](https://user-images.githubusercontent.com/61964176/99962199-0a859800-2d90-11eb-86cc-4bc52171c9b3.png)

**Comment by awalkowiak** [comment]
@EnriqueCorado Do we need the notes and x-marks? Let me know what do you think about it.

**Comment by EnriqueCorado** [comment]
@awalkowiak on #1394 there are display changes to sign and referral. 
- Highlight the section header along with the boxes as you have above. So mark Red Beneficiary Information / Organization 
- No x icon 

![image](https://user-images.githubusercontent.com/65787629/99982053-fb3a2680-2d5e-11eb-9b2c-7842aaeed0a8.png)

**Comment by awalkowiak** [comment]
@EnriqueCorado sounds good. I'll do it that way.

**Comment by abaranowska1** [comment]
**Tested with success**
Tested together with #1394. As it was said, no "x" icon near the required fields and no note. Only marked labels.
![image](https://user-images.githubusercontent.com/61964176/100109866-92d96b00-2e6c-11eb-964d-a122a6bbd098.png)
![image](https://user-images.githubusercontent.com/61964176/100109882-979e1f00-2e6c-11eb-9327-c5d615c5267b.png)

**Comment by EnriqueCorado** [comment]
@abaranowska1 For all mobile devices can we change the text inside the Beneficiary Information in the Referral section from "Enter Phone Number" and "Enter Service Net ID" to "Phone Number" and "Service Net ID" in order to avoid the following 
- same change as above on the Beneficiary Check-In page 

<img width="190" alt="Screenshot 2020-11-24 084913" src="https://user-images.githubusercontent.com/65787629/100125796-08741580-2e32-11eb-86a7-6b7fe831f612.png">

<img width="194" alt="Screenshot 2020-11-24 085045" src="https://user-images.githubusercontent.com/65787629/100125890-28a3d480-2e32-11eb-82d5-0ec279d31a3f.png">

**Comment by abaranowska1** [comment]
Sure, @awalkowiak could you take a look at it and change the placeholders from "Enter Phone Number" and "Enter Service Net ID" to "Phone Number" and "Service Net ID" for all mobile devices on Referral and Beneficiary Check-In pages

**Comment by awalkowiak** [comment]
@abaranowska1 @EnriqueCorado sure, I'll do it.

**Comment by abaranowska1** [comment]
**Tested with success**
- the placeholders were changed on mobile
![image](https://user-images.githubusercontent.com/61964176/100331041-f92ace80-2fcf-11eb-8894-e2fd34c022a1.png)
![image](https://user-images.githubusercontent.com/61964176/100331054-fb8d2880-2fcf-11eb-9e30-f6eb134bebf2.png)
-  the "Send" buttons were clickable 
- red borders were added to the required fields

**Comment by EnriqueCorado** [comment]
good release
