### ISSUE TITLE
UUID name change systemwide

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1393]
Change "Unique Identifier" to "Service Net ID" system-wide
- On check-in/referral CBO interface 
- On the SMS that is sent to users

**Comment by abaranowska1** [comment]
**Tested with success**
- "Unique Identifier" was changed to "Service Net ID"
![Selection_485](https://user-images.githubusercontent.com/61964176/100213198-a3422200-2f0e-11eb-9c29-16e3c127cf56.png)
![Selection_484](https://user-images.githubusercontent.com/61964176/100213203-a3dab880-2f0e-11eb-95cc-f76830c29597.png)
![Selection_483](https://user-images.githubusercontent.com/61964176/100213204-a4734f00-2f0e-11eb-95ca-34cf77ad53b7.png)

**Comment by EnriqueCorado** [comment]
good. release
