### ISSUE TITLE
Check in and referral display changes 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1394]
**tasks build on from 1392**
**for check-in**
- add label "Beneficiary Information" 
- have "Enter Phone Number" and "Enter Service Net ID" in one line as below so it is clearer for the user to know that they can enter either phone or ServiceNetID
- add a label for "Organization" 
- Keep current "Select Organization to Check-In" as changes to that will follow in an upcoming task 
- please make labels bold for both check-in and referral 

**desktop**
<img width="955" alt="Screenshot 2020-11-13 132744" src="https://user-images.githubusercontent.com/65787629/99122908-08635280-25b4-11eb-9e1f-5187f7e8f8a4.png">

**mobile**
<img width="194" alt="Screenshot 2020-11-13 132701" src="https://user-images.githubusercontent.com/65787629/99122847-f1bcfb80-25b3-11eb-8d75-f2ff7a5284cd.png">

**for referral**
- same concept as above 

**desktop**
<img width="953" alt="Screenshot 2020-11-13 133209" src="https://user-images.githubusercontent.com/65787629/99123235-a5be8680-25b4-11eb-992d-5eedcc5fecb5.png">

**mobile**
<img width="201" alt="Screenshot 2020-11-13 133312" src="https://user-images.githubusercontent.com/65787629/99123322-cc7cbd00-25b4-11eb-9de2-5d91fb630578.png">

**Comment by abaranowska1** [comment]
**Tested**
![Selection_466](https://user-images.githubusercontent.com/61964176/100106203-8d7a2180-2e68-11eb-8b44-063267d9fbca.png)
![Selection_465](https://user-images.githubusercontent.com/61964176/100106206-8eab4e80-2e68-11eb-9b01-1e7c2fef8246.png)
![Selection_464](https://user-images.githubusercontent.com/61964176/100106208-8eab4e80-2e68-11eb-8d70-8606915bb716.png)
![Selection_463](https://user-images.githubusercontent.com/61964176/100106210-8f43e500-2e68-11eb-8112-a58b3262147b.png)
All fields look fine, but in the description, it was told that the labels should be bold, so @awalkowiak plz take a look for this ticket once again

**Comment by abaranowska1** [comment]
**Tested with success** 

- Labels "Beneficiary Information" and "Organization" are created and bolded. 
- "Enter Phone Number" and "Enter Service Net ID" are in one line 
![Selection_476](https://user-images.githubusercontent.com/61964176/100206204-54908a00-2f06-11eb-88cd-40d3cd2458a1.png)
![Selection_477](https://user-images.githubusercontent.com/61964176/100206209-55c1b700-2f06-11eb-82bb-2c51a8dc29bb.png)

**Comment by EnriqueCorado** [comment]
good. release

**Comment by johnhbenetech** [comment]
@meenupant this task implemented the either phone or servicenetid for referral. Please create a new task if you'd like to change this implementation

**Comment by meenupant** [comment]
@johnhbenetech KP says we want either phone or SNID to be a mandatory field. The referral system would not work if we don't have either of those. If they enter a phone number for the first time, it should generate the SNID automatically and assign it to that phone number. When they enter a phone number whose SNID already exists in our system then it should match with that SNID in our system and update the beneficiary history accordingly. So, let's go ahead with this task. Thanks

**Comment by johnhbenetech** [comment]
@meenupant but should the SNID be user input if phone number not given? or should we just generate for them?

**Comment by meenupant** [comment]
@johnhbenetech  We will generate the SNID when they provide phone number for the first time. And if that phone number is already in our records then they can either provide the phone number or SNID and we will match in our database and add that transaction in the beneficiary history.

**Comment by johnhbenetech** [comment]
@meenupant I'm asking in the case where it's the first time we have seen someone, and that person doesnt want to provide a phone number.

So in this case there isnt a SNID nor a phone number

**Comment by meenupant** [comment]
@johnhbenetech Ok, got it! In that case KP says we do not want to have that option since the referral system will not work and we will end up creating too many zombie IDs. So, either SNID or a phone number is required otherwise they will not be able to refer.

**Comment by johnhbenetech** [comment]
@meenupant so to clarify, first time beneficiaries must provide a phone number? i thought we already decided that wasnt ok?

**Comment by meenupant** [comment]
@johnhbenetech Yes, that is what we decided earlier but now KP has confirmed that first time beneficiaries will have to provide a phone number.
