### ISSUE TITLE
Referral Page auto load location if only one exists 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1396]
On the referral page, if the organization the user is referring to only has *one location, automatically load it on the location dropdown 
- 

<img width="958" alt="Screenshot 2020-11-16 105200" src="https://user-images.githubusercontent.com/65787629/99295076-ce838d80-27f9-11eb-80ef-d0527d951a5f.png">

**Comment by abaranowska1** [comment]
**Tested with success**
On the referrals page, if the organization referenced by the user has only one location, the location is automatically loaded from the location dropdown
![Peek 2020-11-23 13-19](https://user-images.githubusercontent.com/61964176/99967121-aebf0d00-2d97-11eb-966e-1809582e442c.gif)

**Comment by EnriqueCorado** [comment]
good. release
