### ISSUE TITLE
Referral Send Button not allow referral send SMS if not all locations are filled out

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1397]
- Tested only filling in two locations, added phone number, clicked send, and referral sent **Without ** filling in the third location 

<img width="960" alt="Screenshot 2020-11-16 105343" src="https://user-images.githubusercontent.com/65787629/99295298-1b676400-27fa-11eb-8f39-18e5f19d0431.png">

- Keep the send button clickable, but if a location is not selected, add a red box around it so users can see visually clearly what is missing 

<img width="884" alt="Screenshot 2020-11-16 105911" src="https://user-images.githubusercontent.com/65787629/99295873-caa43b00-27fa-11eb-8216-38b430b31156.png">

**Comment by awalkowiak** [comment]
Dev note: Add validation on the front end and in the resource on the backend

**Comment by abaranowska1** [comment]
**Tested**
@awalkowiak 
One issue, I can send a referral even I didn't choose the location from "Select location to Refer from" field, I think it also should be required, am I right @EnriqueCorado ?

![Uploading Peek 2020-11-23 13-41.gif…]()

**Comment by awalkowiak** [comment]
@EnriqueCorado let us know if the location pf the referring CBO is required (field mentioned by @abaranowska1)

**Comment by EnriqueCorado** [comment]
@awalkowiak @abaranowska1 
"Select location to Refer from" field should also be required. I believe in #1392 the red box requirement has been taken care of

**Comment by awalkowiak** [comment]
@EnriqueCorado sounds good. I'll do it that way.

**Comment by abaranowska1** [comment]
@awalkowiak Please change one thing. The red frame around the "Select location to Refer from" field should be visible only in the situation when we click "Send" button and this field is empty.
![Peek 2020-11-24 14-40](https://user-images.githubusercontent.com/61964176/100108078-b00d3a00-2e6a-11eb-9500-8fcb9c1495de.gif)

**Comment by abaranowska1** [comment]
Thanks @awalkowiak it works for me. The red frame around the "Select location to Refer from" field is visible in the situation when we click the "Send" button and this field is empty.

![Peek 2020-11-25 09-41](https://user-images.githubusercontent.com/61964176/100203506-fada9080-2f02-11eb-9385-aa53b7de77d6.gif)
![Peek 2020-11-25 09-43](https://user-images.githubusercontent.com/61964176/100203503-f910cd00-2f02-11eb-824a-0d598db249dc.gif)

**Comment by EnriqueCorado** [comment]
good. release
