### ISSUE TITLE
Sign in/Register Page Changes

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1398]
**Desktop Sign in View**
- Center Sign in on the top header 
- Remove the "Did you forget your password?" box and simply add "Forgot Password" aligned right to "Remember me"
- Turn the color of "register a new account" to black 
- Remove the "Cancel" button
- Center "Sign-in" button: keep color, font, size 
- add the Captcha icon aligned right of the sign-in button
- remove excess white space leftover 

<img width="880" alt="Screenshot 2020-11-16 140918" src="https://user-images.githubusercontent.com/65787629/99314094-6c388600-2815-11eb-9694-3ec16175f314.png">

**Mobile View Sign In View**
- Center Sign in on the top header 
- Remove the "Did you forget your password?" box and simply add "Forgot Password" aligned right to "Remember me"
- Turn the color of "register a new account" to black 
- Remove the "Cancel" button
- Center "Sign-in" button: keep color, font, size 
- add the Captcha icon aligned right of the sign-in button 
- remove excess white space leftover 

<img width="416" alt="Screenshot 2020-11-16 141247" src="https://user-images.githubusercontent.com/65787629/99314348-d51ffe00-2815-11eb-80ed-a35ab1534cc3.png">

**Comment by abaranowska1** [comment]
Dev note: plz check why sometimes the captcha icon is not displayed. For example, when we log in, sign out, and log in again - the captcha icon is not shown in this second login

**Comment by jkondrat** [comment]
@EnriqueCorado @johnhbenetech unfortunately, Google [only allows their style of ReCaptcha badge](https://developers.google.com/recaptcha/docs/faq), so we're limited to the existing one at the bottom left/right or this large inline badge:
![image](https://user-images.githubusercontent.com/5969801/99982950-87723b00-2dab-11eb-9efb-ac8062fcda48.png)
Alternatively, we can hide the badge and display the following text:
![image](https://user-images.githubusercontent.com/5969801/99982998-9bb63800-2dab-11eb-9da2-082d2cf542a2.png)

**Comment by EnriqueCorado** [comment]
@jkondrat can we use the one below? 

![image](https://user-images.githubusercontent.com/65787629/99986314-e57b3000-2d63-11eb-8f9c-957d16c24f61.png)

**Comment by EnriqueCorado** [comment]
if we can, mock-ups below. Otherwise, keep it in the lower right corner 

<img width="222" alt="Screenshot 2020-11-23 081904" src="https://user-images.githubusercontent.com/65787629/99986901-a13c5f80-2d64-11eb-9d22-373ba532d141.png">


<img width="943" alt="Screenshot 2020-11-23 081854" src="https://user-images.githubusercontent.com/65787629/99986910-a39eb980-2d64-11eb-947a-f4139c506de2.png">

**Comment by johnhbenetech** [comment]
@EnriqueCorado lets just leave the captcha badge as it is now. The 'im not a robot' is an entirely different style of verification than what we use noe

**Comment by abaranowska1** [comment]
**Tested**
@jkondrat 
- The Sign In button should be centered, please change it on the browser view
![image](https://user-images.githubusercontent.com/61964176/100226872-9f1f0000-2f20-11eb-896d-672c3fbc7cdb.png)
- The captcha icon is displayed for a second on the login modal
![Peek 2020-11-25 13-19](https://user-images.githubusercontent.com/61964176/100227186-0c329580-2f21-11eb-9fee-289b5611dea3.gif)

The rest of the things look fine, 
- "Forgot Password" is added aligned right to "Remember me"
- "Register a new account" is turned to black
- "Cancel" button is removed
- Sign in on the top header is centered
![Selection_482](https://user-images.githubusercontent.com/61964176/100227918-346ec400-2f22-11eb-963e-552b993dbb9b.png)
![Selection_487](https://user-images.githubusercontent.com/61964176/100227962-45b7d080-2f22-11eb-90f4-c4a6b55d81ac.png)
![Selection_486](https://user-images.githubusercontent.com/61964176/100227966-46e8fd80-2f22-11eb-8f46-0577874e6160.png)

**Verified on:**
- Ubuntu 20.04, Google Chrome Version Version 85.0.4183.83
- Ubuntu 20.04, Firefox Version 80.0
- Mac OS , Mojave, Safari 12.01
- Windows 10, Edge Version 86

**Comment by abaranowska1** [comment]
**Tested with success**
- Issues from the previous comment were fixed, the button is centered and the captcha icon is not displaying on modal
- "Forgot Password" is added aligned right to "Remember me"
- "Register a new account" is turned to black
- "Cancel" button is removed
- Sign in on the top header is centered
![image](https://user-images.githubusercontent.com/61964176/100354415-749c7800-2ff0-11eb-96bf-2290045c2321.png)
![image](https://user-images.githubusercontent.com/61964176/100354422-77976880-2ff0-11eb-90ef-4e5165930230.png)

**Verified on:**
- Ubuntu 20.04, Google Chrome Version Version 85.0.4183.83
- Ubuntu 20.04, Firefox Version 80.0
- Mac OS , Mojave, Safari 12.01
- Windows 10, Edge Version 86

**Comment by EnriqueCorado** [comment]
good. release
