### ISSUE TITLE
Public and CBO map change

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1399]
**Public View and CBO view**
- Make the tree icons individually clickable instead of clicking three times to go back to the grid view 

<img width="61" alt="Screenshot 2020-11-16 150050" src="https://user-images.githubusercontent.com/65787629/99318429-87f35a80-281c-11eb-88c4-0435a7916c52.png">

- Map should not take over the whole page, have the map popup on the right side and let it take up the size of the right two records
- if the map icon clicked on the CBO view, the page should automatically scroll down to show what screenshot 2 is showing. the map taking over the two right-sided records 

<img width="959" alt="Screenshot 2020-11-16 145723" src="https://user-images.githubusercontent.com/65787629/99318335-5c707000-281c-11eb-804c-4f2f82ff7aca.png">

<img width="884" alt="Screenshot 2020-11-16 150001" src="https://user-images.githubusercontent.com/65787629/99318370-6c884f80-281c-11eb-9f56-4aa7acd47bbc.png">

**Comment by johnhbenetech** [comment]
@EnriqueCorado how does this change the mobile view (if at all)?

**Comment by EnriqueCorado** [comment]
@johnhbenetech 

The mobile view doesn't change

**Comment by meenupant** [comment]
Each tree icon should be individually clickable. 
Provide description to the tree icons so that whenever someone hovers over that particular icon they know what it means. 
Do we have the functionality to select a CBO card, so that map displays only that selected CBO or multiple CBOs?

**Comment by EnriqueCorado** [comment]
@meenupant if we want to add that, we will need to add something along the lines of "See on the map" in the record. That would clutter the record more. The map should be kept as is, dynamic with the filters 

- If a  record is clicked on the map it can populate on the bottom of map just like the mobile interface does  
<img width="191" alt="Screenshot 2020-11-30 081217" src="https://user-images.githubusercontent.com/65787629/100634151-c80a1100-32e3-11eb-9925-60bd6bf2a7e2.png">


- add a bottom "pop-up/description" of the grid view icon, list view, and map
- Hover on grid view should have the pop up saying "Grid View" like below 
- For list view "List View" 
- On map "Map"

![image](https://user-images.githubusercontent.com/65787629/100633508-0521d380-32e3-11eb-8ab2-8aaa45db9616.png)

**Comment by abaranowska1** [comment]
**Tested**
@jkondrat 
- I think you forgot about the hover feature which was mentioned in the comment above 
1. Now we have only two views so it shouldn't be individually clickable  ![image](https://user-images.githubusercontent.com/61964176/104006771-4097a380-51a7-11eb-8e43-0e4636daefd3.png)
2. Map is replaced by the old filter window 
3. Whole functionality works as before
4. Map view was changed also on public and CBO views.
![Selection_762](https://user-images.githubusercontent.com/61964176/104006952-80f72180-51a7-11eb-81c2-7c4adec1051a.png)
![Selection_760](https://user-images.githubusercontent.com/61964176/104006959-82284e80-51a7-11eb-884f-83484883473d.png)
![Selection_759](https://user-images.githubusercontent.com/61964176/104006961-82c0e500-51a7-11eb-928f-dde0decae92e.png)

**Comment by abaranowska1** [comment]
**Tested**
- The hover feature was added to the Grid View and Map icon 
![Peek 2021-01-11 09-27](https://user-images.githubusercontent.com/61964176/104159260-57303b80-53ef-11eb-97a0-8766db244bb1.gif)

**Comment by abaranowska1** [comment]
Thanks @jkondrat, now all record cards have the same width.
![Peek 2021-01-12 11-11](https://user-images.githubusercontent.com/61964176/104300758-2cb1b180-54c7-11eb-964a-a84656ff2ece.gif)

**Comment by meenupant** [comment]
@jkondrat @abaranowska1 I searched for "American" and on clicked "Apply", it displayed the "American Civil..." record, and when I clicked this record I can see the details of this Organization. And when I click "Back to All Records" button on top left, I see only this "American Civil..." card/record and not the other records. The search field where I had put "American" is also blank. The only way I can see all the records again is when I click "Clear" button. Can you please let the search field be filled with the term "American" again, so the user can cross that field to see the display of all records whenever they wish to. Thanks
