### ISSUE TITLE
Check in/Referral SMS Content 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1401]
**updated task description matching desired end state**
- For the organizations with long names, apply John's suggestion to cut the long names to fixed-length

So for example on check-in example if the org name is over 24 characters it will break into two messages (should we think about a fixed length, like first 21 characters followed by ellipsis, "John's Food Pantry an...")

**Check-In**
-----------------------------------------------
Thank you for coming to _**John's test**_. 
Here is your Service Net ID: **000h**
Please provide this ID or your phone number to any service provider you go to..

-----------------------------------------------

On referral
------------------------------------------
- send the first section on 1st SMS, to make sure we have enough space for long addresses 
"Here are the recommended referrals:
17/11 test provider **address**,
regergrgr **address**, 
NYC Health Plan - Medicaid **address**."
- 2nd SMS 
"Here is your Service Net ID: 000h
Please provide this ID or your phone number to any service provider you go to."

**Comment by johnhbenetech** [comment]
@EnriqueCorado we need to take a hard look at the SMS/MMS length limits and how messages might split

Links cant be "embedded" in texts - other that just sending the full URL letter by letter. I'd like us to give some thought to this how sending all this info as well as a long URL works with the length limitations of SMS

**Comment by EnriqueCorado** [comment]
**Check-In**
-----------------------------------------------
- Keep the same line spaces 
-------------------------------------
Thank you for coming to _**John's test**_. 

Here is your Service Net ID: **000h**
you can provide instead of your phone number at any service provider you go to.

Visit: https://servicenet.benetech.org/#/public/BayArea

-----------------------------------------------
Referral
-----------------------------------------------
- Keep the same line spaces 
- Add corresponding addresses
-----------------------------------------------

Here are the recommended referrals:

17/11 test provider **address**,
regergrgr **address**, 
NYC Health Plan - Medicaid **address**.

Here is your Service Net ID: 000h
you can provide instead of your phone number at any service provider you go to. 

Visit: https://servicenet.benetech.org/#/public/BayArea

**Comment by EnriqueCorado** [comment]
Need to consider SMS in Spanish, Mandarin at least
- need to add language click on to Check-In so phone number gets saved with a default language 

211 FY 2017/2018 report
-------------------------
<img width="199" alt="Screenshot 2020-11-20 082857" src="https://user-images.githubusercontent.com/65787629/99824353-78b92900-2b0a-11eb-981b-ecadef201179.png">

**Comment by johnhbenetech** [comment]
@EnriqueCorado The organizations and addresses can be any length.

So for example on check in example if the org name is over 24 characters it will break into two messages (should we think about a fixed length, like first 21 characters followed by ellipsis, "John's Food Pantry an...")

This may just be overthinking *most* phones will reassemble texts before displaying them - I think the big question is how common is this on feature phone. We can test and get feedback

**Comment by johnhbenetech** [comment]
@EnriqueCorado also please break out language into separate task with the translations and UI for language selection

**Comment by kkaczmarczyk** [comment]
@EnriqueCorado FWIW: for the long-term we may consider using some URL shorteners like bit.ly to generate the shorter URL.

**Comment by EnriqueCorado** [comment]
@kkaczmarczyk 
- Apply John's suggestion, please cut long names to fixed-length 
- please use a URL shortener to generate shorter URL

**Comment by jkondrat** [comment]
I don't think that using a URL shortener is a good idea unless we create one on our own. We would be dependent on an external service for creating the URLs and redirecting. If we want that, I would use Google's one, but I'm not sure if it has a public API or if it has any limits. 
What do you think @johnhbenetech @kkaczmarczyk @EnriqueCorado ?

**Comment by johnhbenetech** [comment]
@EnriqueCorado do we still want a link? Why would we link to the bay area silo?

**Comment by EnriqueCorado** [comment]
@jkondrat @johnhbenetech let's not include a link to Service Net

**Comment by johnhbenetech** [comment]
@EnriqueCorado please update the task description to match the desired end state

**Comment by jkondrat** [comment]
@EnriqueCorado should we also shorten addresses with an ellipsis?

**Comment by abaranowska1** [comment]
Check-in message
![image](https://user-images.githubusercontent.com/61964176/106137855-9b4f6a00-616b-11eb-9e34-0d047e82a4aa.png)
Referral message
![image](https://user-images.githubusercontent.com/61964176/106138106-fed99780-616b-11eb-884c-adaba3953f99.png)
![image](https://user-images.githubusercontent.com/61964176/106138134-0a2cc300-616c-11eb-860c-b1c6b842a1f6.png)
![image](https://user-images.githubusercontent.com/61964176/106138580-9c34cb80-616c-11eb-8d76-5a3d92499e7b.png)
![image](https://user-images.githubusercontent.com/61964176/106138960-19f8d700-616d-11eb-942b-311d91e6c9cd.png)

**Comment by meenupant** [comment]
@abaranowska1 I have made a minor change in the SMS content and changed this line **"Please provide this ID or your phone number to any service provider you go to."** I hope its okay to change now. I will change the top description too. 

**Check-In**
-----------------------------------------------
Thank you for coming to _**John's test**_. 
Here is your Service Net ID: **000h**
Please provide this ID or your phone number to any service provider you go to.

-----------------------------------------------


On referral
------------------------------------------
- send the first section on 1st SMS, to make sure we have enough space for long addresses 
"Here are the recommended referrals:
17/11 test provider **address**,
regergrgr **address**, 
NYC Health Plan - Medicaid **address**."
- 2nd SMS 
"Here is your Service Net ID: 000h
Please provide this ID or your phone number to any service provider you go to."

**Comment by abaranowska1** [comment]
**Tested with success**
The SMS text message was changed to "Please provide this ID or your phone number to any service provider you go to." 
![Selection_992](https://user-images.githubusercontent.com/61964176/106459711-8ee04f80-6492-11eb-8e6b-97992905e7eb.png)
![Selection_991](https://user-images.githubusercontent.com/61964176/106459713-8f78e600-6492-11eb-8a38-43ddf67b8eab.png)
![Selection_990](https://user-images.githubusercontent.com/61964176/106459715-90117c80-6492-11eb-8ad9-2216c6d2beb8.png)
