### ISSUE TITLE
SP Refer Button Change

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1403]
- Please make the 'Refer' button is an actual button as shown below 
- For 'Refer' please use the #FAB28D 
- On 'Referred' please use #50AB0E
- Using these colors in order to meet the AA and AAA requirements 

<img width="637" alt="Screenshot 2020-11-17 114322" src="https://user-images.githubusercontent.com/65787629/99439631-45885700-28ca-11eb-90ea-7683dfc50be6.png">

<img width="621" alt="Screenshot 2020-11-17 114447" src="https://user-images.githubusercontent.com/65787629/99439647-4de09200-28ca-11eb-9031-f59f1585592e.png">
 

<img width="536" alt="Screenshot 2020-11-17 114736" src="https://user-images.githubusercontent.com/65787629/99439938-b62f7380-28ca-11eb-90bd-25e2e7afe60f.png">

**Comment by awalkowiak** [comment]
@EnriqueCorado here is the requested result:
![Selection_436](https://user-images.githubusercontent.com/12113312/101666330-5e5dd580-3a4e-11eb-99b1-9fafb6fa20d8.png)

However, I have two suggestions:

1. For colored button pills we are using a border in the same color as the buttons (the black border we only apply if there is a transparent background). So I'd suggest removing the black border (additionally I think having a black border around a color will visually make it a bit darker, which is undesirable if we are looking at the contrast ratio). Here is how it looks like without a black border:
![Selection_437](https://user-images.githubusercontent.com/12113312/101666545-a54bcb00-3a4e-11eb-8a42-0d1f95ef7d8d.png)

2. I checked the contrast ratio for our success button pill (#4bc64e) and it's better than the one you suggested (it is 9.48 with black font color). Here is how it looks like:
![Selection_438](https://user-images.githubusercontent.com/12113312/101666745-e348ef00-3a4e-11eb-95be-af6f5598f90c.png)

Let me know which version of the buttons you like the most and I'll push it.

**Comment by meenupant** [comment]
Please go ahead with your suggested second option. Thanks

**Comment by abaranowska1** [comment]
@awalkowiak two suggestions: 
- please change the size of the button on mobile, it should be a little bigger,
- center the text button on Safari, Edge, and Chrome browsers

**Comment by abaranowska1** [comment]
**Tested with success**
- Refer button changes the color,
- The size is optimal on mobile and browser view,
- The text button is centered on Safari, Edge, Chrome and Firefox browsers
![Selection_570](https://user-images.githubusercontent.com/61964176/101896048-aa249200-3ba8-11eb-981c-b3d3fad5d392.png)
![Selection_569](https://user-images.githubusercontent.com/61964176/101896051-ab55bf00-3ba8-11eb-80a9-da8fdbc2d385.png)
![Selection_568](https://user-images.githubusercontent.com/61964176/101896052-ab55bf00-3ba8-11eb-9f62-be72a78427d9.png)
![Selection_567](https://user-images.githubusercontent.com/61964176/101896055-abee5580-3ba8-11eb-8737-7feb30f7247e.png)
![Selection_566](https://user-images.githubusercontent.com/61964176/101896057-abee5580-3ba8-11eb-87ff-713c3cb228f0.png)
