### ISSUE TITLE
Public View: Hide record info not on record 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1407]
- If nothing is inputted, or currently displayed on any section on record in public view hide it so the public won't see it, as it is empty space 
- The service provider will have all the current cells pop up while they edit a record 

For example: below daily updates, the cell has nothing inputted, so no need to show it
- in Organization Details, both the organization details and main email address are missing, so hide those cells as they take up space 

<img width="949" alt="Screenshot 2020-11-19 074622" src="https://user-images.githubusercontent.com/65787629/99689079-602e0d80-2a3b-11eb-8ad5-22dd72aa6c48.png">

**Comment by johnhbenetech** [comment]
@EnriqueCorado is this just for public view, what about for a logged in CBO looking at a different CBO's records?

What happens if there is no information whatsoever for a section:
* If there isnt a daily update do we remove the daily update section card in its entirety?
* If there are no locations/services whatsoever do we remove those sections in their entirety?

**Comment by EnriqueCorado** [comment]
@johnhbenetech 

- add the functionality of hiding records for logged in CBO looking at different CBO's records 

If no information whatsoever for a section: hide it as it serves no purpose for the users looking at it if it is empty. This way we are able to "highlight" what is currently there and not what is missing 

- If there isn't a daily update do we remove the daily update section card in its entirety? Not remove, but hide to anyone who doesn't own the record. The CBO managing that record will be able to see all the fields empty or filled while they edit their record

- If there are no locations/services whatsoever do we remove those sections in their entirety? Not remove, but hide to anyone who doesn't own the record. The CBO managing that record will be able to see all the fields empty or filled while they edit their record

**Comment by EnriqueCorado** [comment]
On service details, also hide the sections that are empty

<img width="190" alt="Screenshot 2020-11-19 100643" src="https://user-images.githubusercontent.com/65787629/99705719-f881bd80-2a4e-11eb-95e3-88cd6e7f2b40.png">


<img width="194" alt="Screenshot 2020-11-19 100654" src="https://user-images.githubusercontent.com/65787629/99705724-fb7cae00-2a4e-11eb-9b9d-9040e9e1a6d0.png">

**Comment by meenupant** [comment]
@johnhbenetech - I believe we must display the most updated information after it is validated, else display the last available information with a warning sign that says this information may be inaccurate and has not been validated. For the missing information, it must be hidden from the public view but displayed to the CBOs for updates.

**Comment by EnriqueCorado** [comment]
@meenupant is this ready to be moved to ready for development?

**Comment by meenupant** [comment]
@EnriqueCorado Yes, unless @johnhbenetech has a different take on this.

**Comment by abaranowska1** [comment]
@jkondrat @EnriqueCorado 
If the Organization Information Panel is empty should it be displayed here? ( this Organization has only Organization Name filled ) 
![image](https://user-images.githubusercontent.com/61964176/103876455-f5609080-50d3-11eb-8b26-a5279c10ef42.png)

- The rest of the fields/sections look good. If there is no filled information the sections are not displayed in the single record / public view. 
- All fields, empty as well are enabled in the edit view. 
![image](https://user-images.githubusercontent.com/61964176/103876923-96e7e200-50d4-11eb-9795-a4ecc19022b2.png)

**Comment by EnriqueCorado** [comment]
@abaranowska1 
If the Organization Information Panel is empty should it be displayed? 
- No

**Comment by abaranowska1** [comment]
**Tested with success**
Confirmed that all empty information was hidden.
![Selection_755](https://user-images.githubusercontent.com/61964176/103987959-92cbcb00-518d-11eb-9a5f-c326d18c25c5.png)
![Selection_754](https://user-images.githubusercontent.com/61964176/103987966-96f7e880-518d-11eb-9919-a324624044e4.png)
