### ISSUE TITLE
Records Changes

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1408]
- Remove the "Organization  Name" section from under the Organization Details Panel as it is repetitive 
- Change the heading of the panel "Organization Details" to "Organization Information" as it is repetitive with a sub-section under it
- Building off #1407 

<img width="1919" alt="Screenshot 2020-11-19 081851" src="https://user-images.githubusercontent.com/65787629/99693998-cc5f4000-2a40-11eb-80b3-90cd83f61f2f.png">

<img width="961" alt="Screenshot 2020-11-19 083057" src="https://user-images.githubusercontent.com/65787629/99694728-93739b00-2a41-11eb-830e-8f0af896bc36.png">

**Comment by abaranowska1** [comment]
**Tested with success**
- "Organization Name" section was removed from the "Organization Details" Panel 
- The section title was changed from "Organization Details" to "Organization Information"
![image](https://user-images.githubusercontent.com/61964176/103873943-d6143400-50d0-11eb-80d2-96d0a738f946.png)
