### ISSUE TITLE
Service Details Remove the +# 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1409]
**No need to have the + in each service under service detail for Public and CBO looking at another CBO's record **

- if there is enough space both on mobile and desktop to show all service types instead of any +1, +2,+3, show the names
-  Essentially optimize the space to show as many service types without overcrowding. If there are more than the service types shown then we can add the + # at the end instead of having the +# everywhere 

<img width="959" alt="Screenshot 2020-11-19 100334" src="https://user-images.githubusercontent.com/65787629/99705426-8e691880-2a4e-11eb-881b-053c942086e7.png">

<img width="197" alt="Screenshot 2020-11-19 100355" src="https://user-images.githubusercontent.com/65787629/99705437-91fc9f80-2a4e-11eb-9fb9-ff1cb644dba4.png">

**Comment by jkondrat** [comment]
Dev note: sort the service names by length so we can show more of them

**Comment by jkondrat** [comment]
@EnriqueCorado should we display service names in multiple rows if there's enough space available?

**Comment by EnriqueCorado** [comment]
@jkondrat yes, display names in multiple rows if space allows

**Comment by abaranowska1** [comment]
**Tested with success**
We show as many service types as we can, the +# is displayed only if the service type is too long and the space is too small. 
![Selection_756](https://user-images.githubusercontent.com/61964176/103993224-91060580-5195-11eb-95d9-577b9c67b7c3.png)
![Peek 2021-01-08 09-32](https://user-images.githubusercontent.com/61964176/103993228-93685f80-5195-11eb-9e42-85b785ed4734.gif)
