### ISSUE TITLE
Website Links in Record active click ons

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1411]
On all records, public, and CBO looking at another CBO's Record 
- have the website link clickable and not as text as it is currently 

<img width="960" alt="Screenshot 2020-11-19 110729" src="https://user-images.githubusercontent.com/65787629/99712089-6f22b900-2a57-11eb-83d2-a91472cbb0e2.png">

**Comment by abaranowska1** [comment]
**Tested with success**
- The website links are clickable and the website is opened in a new tab 
![Selection_765](https://user-images.githubusercontent.com/61964176/104007730-ae909a80-51a8-11eb-9a05-aa0bacf607be.png)
![Peek 2021-01-08 11-56](https://user-images.githubusercontent.com/61964176/104007738-b18b8b00-51a8-11eb-9881-e9770df48b67.gif)

**Comment by meenupant** [comment]
@abaranowska1 it is not working for all the websites. Please check again. For example, when I click the the record for "**AMERICAN CIVIL LIBERTIES UNION OF NORTHERN CALIFORNIA (ACLU-NC)**" and I click on their website link "**www.aclunc.org**", it takes me to "**https://benetechservicenet.org/www.aclunc.org**" with an error message "**Your request cannot be processed**"

**Comment by jkondrat** [comment]
@meenupant there's no way to control how the browser opens new links - we can either open it in the current tab or open a new tab and switch to it

**Comment by meenupant** [comment]
@jkondrat Ok. Please keep the current behavior, open a link in a new tab and switch to it. Thanks

**Comment by abaranowska1** [comment]
I checked the Organization which threw the error message and now I cannot reproduce this issue anymore, I tried also with another links and it all work for me. 
![Peek 2021-01-11 19-47](https://user-images.githubusercontent.com/61964176/104224923-ed8f4c00-5445-11eb-8fe9-27cf5b191a11.gif)
