### ISSUE TITLE
Beneficiary Check-In and Refer Elsewhere Pop Up on SP View

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1413]
**dev note**
- please add hover over change color to the two new buttons and selected state
- add color to make the button clicked on visually apparent 
- take a creative approach  

Beneficiary Check-In and Refer Elsewhere
---------------------------
- add buttons for "Beneficiary Check-In" and "Refer Elsewhere"
- on hover over and clicked on change button color to #343f51 and white font 

<img width="799" alt="Screenshot 2020-11-19 150116" src="https://user-images.githubusercontent.com/65787629/99734697-1adc0100-2a78-11eb-9605-78a3b41f5c1c.png">

Beneficiary Check-In Button
---------------------
- When clicked on change color to #343f51 and white font 
- Have it populate "on top" of the two right records 

<img width="668" alt="Screenshot 2020-11-19 150228" src="https://user-images.githubusercontent.com/65787629/99734827-55de3480-2a78-11eb-9d8a-b7546bf3a1e2.png">

Beneficiary "Refer Elsewhere" Button
---------------------
- When clicked on change color to #343f51 and white font 
- Have it populate "on top" of the two right records 

<img width="667" alt="Screenshot 2020-11-19 150240" src="https://user-images.githubusercontent.com/65787629/99734825-55459e00-2a78-11eb-8b48-ddf60bb24faf.png">

Mobile Button Layout
----------------------
- Transitioning from referral in the header and having an icon
- Refer Elsewhere will have the counter on the top right with the color of #50AB0E and white color 

<img width="152" alt="Screenshot 2020-11-19 154034" src="https://user-images.githubusercontent.com/65787629/99737671-9d1af400-2a7d-11eb-9c7a-82873aecb1f7.png">

Mobile Beneficiary Check In
------------------------------
<img width="152" alt="Screenshot 2020-11-19 151348" src="https://user-images.githubusercontent.com/65787629/99735652-d6516500-2a79-11eb-91ea-858c96ad4b21.png">

Mobile Referral
------------------------------
<img width="155" alt="Screenshot 2020-11-19 151415" src="https://user-images.githubusercontent.com/65787629/99735691-e6694480-2a79-11eb-8d00-533dd734c360.png">

**Comment by EnriqueCorado** [comment]
@meenupant I would like your input to know if changes need to be done before development. This part is important as we will be eliminating a click to another page in the process

**Comment by meenupant** [comment]
@EnriqueCorado Does this allow multiple check-ins and referrals?

**Comment by EnriqueCorado** [comment]
@meenupant this is what we currently have on the separate tab on service net. As it stands, it allows for one beneficiary check-in and referral at a time. 

Allowing multiple check-ins and especially referrals at a time would make the interface confusing and not streamlined.
In the pilot, we will be able to see and get feedback if adding the option to add multiple check-ins at a time is necessary

**Comment by meenupant** [comment]
@EnriqueCorado I think eventually we will need that functionality, but we can proceed with the usability testing of the current version and gather feedback.

**Comment by jkondrat** [comment]
@EnriqueCorado @meenupant @johnhbenetech it might be hard to squeeze the referral tab on top of two records - what would happen if we referred to multiple organizations? The location names would also be hard to fit in, especially on smaller (or mobile) screens. Perhaps we could use a modal instead?

**Comment by EnriqueCorado** [comment]
@jkondrat let's go with a modal approach

**Comment by kkaczmarczyk** [comment]
@EnriqueCorado @meenupant Thanks for the answer. 2 more questions:
1. How the user should fire up the modal? Should it appear after clicking on the header button as it is now?
2. Should the modal contain the 3 tabs same as it is currently on the Referral page?

**Comment by EnriqueCorado** [comment]
@kkaczmarczyk 
1. fire up modal after the user clicks on any of the two buttons on top of the filters in mockup 
2. - we want check-in and referral to be on the main page as a pop-up in order to eliminate clicks in order to get to those features. On mobile, in order to get to check-in/referral, the user must click on the hamburger menu and it is not intuitive 
- on the mockup, we have two buttons clearly labeled above the filters. Each of the buttons, Check-in and Refer Elsewhere will pop-up their respective pop-up 
- the Bulk upload can be kept in the hamburger menu and also on the right top menu dropdown of the desktop view 
- we need to separate bulk upload from referral/check-in
3. appear in modal, but keep the same layout and pop up after the beneficiary has been checked in and referred

**Comment by abaranowska1** [comment]
**Tested**

@jkondrat  Suggestions: 
1. On the Beneficiary Check In modal after we click Send button we can see such screen which inform us about success.
![image](https://user-images.githubusercontent.com/61964176/102330832-550ec480-3f8a-11eb-8e60-cf6fe27bb418.png)
When we click the Send button on the ReferElsewhere modal page, the modal window is closed and a green popup is displayed. Maybe it needs to be standardized and two pages should display popups after Send? 
2. Plz remove this unnecessary line: 
![image](https://user-images.githubusercontent.com/61964176/102334484-0152aa00-3f8f-11eb-95c6-efaed9d50207.png)

**Verified cases:**
- The buttons were added and look the same as other buttons on page
- After hover and click the color was changed
- All UI issues which exist on mobile and web were fixed
- Modals look good also on Safari and macOS

![Selection_606](https://user-images.githubusercontent.com/61964176/102336355-5b546f00-3f91-11eb-81b3-33d1b81e55f2.png)
![Selection_605](https://user-images.githubusercontent.com/61964176/102336360-5c859c00-3f91-11eb-8501-d515cd688726.png)
![Selection_604](https://user-images.githubusercontent.com/61964176/102336363-5c859c00-3f91-11eb-8d8d-3f99783eee56.png)
![Selection_603](https://user-images.githubusercontent.com/61964176/102336366-5d1e3280-3f91-11eb-9004-ce5e3dc23150.png)
![Selection_602](https://user-images.githubusercontent.com/61964176/102336368-5db6c900-3f91-11eb-8c8a-9ccdef21f7e5.png)
![Selection_601](https://user-images.githubusercontent.com/61964176/102336369-5db6c900-3f91-11eb-8bb5-917e3611ec72.png)

**Comment by abaranowska1** [comment]
**Tested with success**
- The line was removed 
![image](https://user-images.githubusercontent.com/61964176/102353346-33710580-3fa9-11eb-8200-f17c5d71265e.png)
- The Beneficiary Check In and Referrals now are closed after click the Send button and the green pop-ups are displayed in both situations.
