### ISSUE TITLE
Investigate captcha issue with incorrect password

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1420]
Steps to reproduce:

* Attempt to login, but use an incorrect password
* You get the expected errors indicating wrong password
* only change password field to the correct one
* attempt to login (click, enter, tab to submit, etc)

Result:
* Second Log in event doesnt activate

I'm assuming this may be something with the captcha flow needing to be reset

**Comment by EnriqueCorado** [comment]
Captcha icon on top of about us and scroll bar 
Steps to reproduce 
- go to page https://servicenet.benetech.org/#/public/BayArea/
- click login, click x on the sign-in pop-up
- captcha icon stays there, bottom right corner, and overlaps about us and scroll bar click down arrow to scroll down 


<img width="958" alt="Screenshot 2020-11-23 145553" src="https://user-images.githubusercontent.com/65787629/100024616-ff386980-2d9b-11eb-8a32-e5f0c2bcfd79.png">

**Comment by abaranowska1** [comment]
**Tested with success**
The first and second issue is fixed. I can log in to the app after I changed the password from incorrect to correct. Also, there is no issue with login modal and captcha on public view. 
![Peek 2020-11-27 09-17](https://user-images.githubusercontent.com/61964176/100440353-0a91da80-30a5-11eb-9abf-91c4ee0dffb7.gif)
![Peek 2020-11-27 09-15](https://user-images.githubusercontent.com/61964176/100440360-0e256180-30a5-11eb-9dc2-e494baea6bd1.gif)
