### ISSUE TITLE
Interface Issues on Safari 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1422]

**Comment by johnhbenetech** [comment]
@EnriqueCorado is there more details here?

**Comment by EnriqueCorado** [comment]
@johnhbenetech yes, waiting on Meenakshi to upload her screenshots

**Comment by meenupant** [comment]
There is an overlap of images on the safari browser in Mac. The cards display and search bar are overlapping. Please see the images below. Thanks

<img width="952" alt="Screen Shot 2020-11-20 at 3 12 42 PM" src="https://user-images.githubusercontent.com/74263963/100115413-56375080-2e27-11eb-957e-e25f49d31774.png">
<img width="1467" alt="Screen Shot 2020-11-20 at 3 58 21 PM" src="https://user-images.githubusercontent.com/74263963/100115475-6818f380-2e27-11eb-9d29-214b77362fb4.png">

**Comment by abaranowska1** [comment]
**Tested with success**
Interface issues on Safari and Mac were fixed. 
![image](https://user-images.githubusercontent.com/61964176/100342684-a1e02a80-2fde-11eb-8b1c-96e36713e545.png)
![image](https://user-images.githubusercontent.com/61964176/100342694-a4428480-2fde-11eb-9cf2-6792bf71be34.png)
