### ISSUE TITLE
Registration Page remove snapshot in header

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1429]
Recreate Scenario
- go to https://servicenet.benetech.org/#/public/BayArea
- then go to register
- need to remove the 0.0.1-Snapshot in the heading 

<img width="1918" alt="Screenshot 2020-11-24 095848" src="https://user-images.githubusercontent.com/65787629/100133471-a8826c80-2e3b-11eb-8264-410c22c9c101.png">

**Comment by jkondrat** [comment]
this was done in #1373
