### ISSUE TITLE
Registration page new fields

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1430]
**Desktop and Mobile View **
---------------------------------

- Change the Organization Name section header to "Organization Name(s)" and inside the field to "Your Organization(s) Name(s)" in order to allow a user to be associated with potentially multiple records 
- use the same dropdown as in the admin portal, where users start typing an organization name, and automatically updates
- allow for multiple orgs being searched and selected, if no name matches allow for a "text" entry

<img width="615" alt="Screenshot 2020-12-07 134703" src="https://user-images.githubusercontent.com/65787629/101409515-dbdce680-3892-11eb-8f31-0ec77aee94a6.png">

what it can look like:
-----
<img width="572" alt="Screenshot 2020-12-04 140442" src="https://user-images.githubusercontent.com/65787629/101219985-b5703e80-3639-11eb-8b84-0c2c25a13b85.png">

for example how the record names can show
-----
<img width="263" alt="Screenshot 2020-12-07 135029" src="https://user-images.githubusercontent.com/65787629/101409777-35ddac00-3893-11eb-857a-f280c336ea56.png">

if the user registering finds not records in the dropdown matching their organization name
-----
- add a field under "Organization Name(s)" with a field name of "If the record(s) not found on the above dropdown, enter below"
- in order to allow them to input the organization name the user is associated with if the organization is not in our database

**Add the new field under Phone Number, "Provide a contact email who can verify your position in the organization"** 
---------------------
- add fields, for first name, last name, and email

**Comment by meenupant** [comment]
What if the person registering is the same person who verifies accounts in that organization? 
I think this is what we are trying to achieve:
1. If the email is a "work email" by matching it with the orgnanization name, then we email them a link to verify that email and register them automatically.
2. If the email is any other email like "gmail, yahoo, etc." (this could be a case with volunteer registration), then we ask them to provide a contact from the organization to verify and approve their account, and send an email to the "official work email" to verify and create that volunteer account. In this case these additional fields should only be displayed if they provide a "non work email".
3. We will have to think about the edge cases here where no one in that organization have a "work email". How do we verify these accounts?

**Comment by kkaczmarczyk** [comment]
@meenupant @EnriqueCorado Hi, 

1. Have you come up with the answer to this question: "We will have to think about the edge cases here where no one in that organization have a "work email". How do we verify these accounts"?
2. There could be quite a few edge cases. For example, besides the Gmail, Yahoo email domains someone could use a less known domain or a custom one - what should happen in that case? It's not possible to easily deduce the non-work vs work email in such cases. Would you be able to provide a list of domains that we should treat as "non-work email domains"?
3. In case of assignment of multiple organizations and user using "non-work email" should the "Provide a contact email who can verify your position in the organization" section contain multiple entries and assignments to an organization? 
4. As a general practice - could you try to summarize the findings of the discussion in the main description in the ticket? That would help to keep the ticket scope clear and concise.

**Comment by EnriqueCorado** [comment]
@kkaczmarczyk that logic will be broken down in a separate task. please just proceed with the dropdown filter on registration

**Comment by kkaczmarczyk** [comment]
@EnriqueCorado @meenupant is the sending of the email and the user verification action in the scope of this task or will be in a separate one?

**Comment by EnriqueCorado** [comment]
@kkaczmarczyk that ticket is currently in product board #1451

**Comment by abaranowska1** [comment]
**Tested**
1. @jkondrat Please change the field "If the record(s) not found on the above dropdown, enter below" for non required. 
![image](https://user-images.githubusercontent.com/61964176/104016179-0eda0900-51b6-11eb-9db4-3c640649a220.png)

@EnriqueCorado 
1. All new fields were added only to the Register Page, do you need to edit these fields in the future? Maybe it should be also added to the admin user management edit page or user settings page? If yes, please create new tasks. 
For example here, we can see only Organization Name fields which is a free text from : "If the record(s) not found on the above dropdown, enter below" field.
![image](https://user-images.githubusercontent.com/61964176/104017025-a724bd80-51b7-11eb-983d-273b8df7998d.png)
Same here : 
![image](https://user-images.githubusercontent.com/61964176/104017067-bc99e780-51b7-11eb-9be4-b76bf3f3249c.png)

**Comment by EnriqueCorado** [comment]
@abaranowska1 can we add a red box on the first name and last name as well please. that is required information and users should always fill it in

- I will also breakout new tasks for the fields to be added to user management edit page #1557

**Comment by abaranowska1** [comment]
@jkondrat In reference to the comment above please make the "First name" and the "Last name" required as well. Also "Organization name(s)" should stay required, but "If the record(s) not found on the above dropdown, enter below" was changed to non required which is good. 
![Selection_784](https://user-images.githubusercontent.com/61964176/104158663-12f06b80-53ee-11eb-9a78-78af27b0125c.png)
