### ISSUE TITLE
Service Provider: Add Phone Number Field 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1442]
- add phone number field to Organization tab when creating a new record
- add phone number field in "Tell us more about the services you offer" under adding a new record Services tab
- add phone number field while editing a record 
- store in the database the phone number for the organization and for each individual service they provide if they provide a phone number 

**Desktop View (in Tell us a bit more about your organization)**
-------------
<img width="902" alt="Screenshot 2020-12-01 152751" src="https://user-images.githubusercontent.com/65787629/100808863-cb87c000-33e9-11eb-84c7-b72fc0daf088.png">

**Mobile View (in Tell us a bit more about your organization)**
--------------------
<img width="171" alt="Screenshot 2020-12-01 153047" src="https://user-images.githubusercontent.com/65787629/100809090-3fc26380-33ea-11eb-880d-6318f965463e.png">

**Desktop View (in Tell us more about the services you offer**)
<img width="900" alt="Screenshot 2020-12-01 153644" src="https://user-images.githubusercontent.com/65787629/100809496-1bb35200-33eb-11eb-97ff-71c1ae16cc66.png">

**Mobile View (in Tell us more about the services you offer**)
<img width="173" alt="Screenshot 2020-12-01 154314" src="https://user-images.githubusercontent.com/65787629/100809851-f8d56d80-33eb-11eb-89f9-73594f342c8e.png">

**Comment by johnhbenetech** [comment]
@meenupant @EnriqueCorado i'd encourage you to look at some real world records to make sure this design makes sense.

We are in an environment where phone numbers could exist at the location service and organization level. There are considerations for phone vs fax vs mobile vs hotline. Often times these records will have the concept of a 'contact' so that there may be dozens of phone numbers attached to a single record indicating different departments or points of contact?

What data led us to these design decisions?

**Comment by EnriqueCorado** [comment]
@meenupant I added the phone number field to both organizations and at a per-service level. I'm not too sure about the other questions John has brought up, but I do think we need this field up by the pilot

**Comment by meenupant** [comment]
@johnhbenetech @EnriqueCorado Yes, we need to include phone number in our pilot. We can later figure out different ways to capture various other phone numbers as per the users requirements.

**Comment by awalkowiak** [comment]
Dev note: Ensure that phone numbers are copied during claiming records.

**Comment by kdondziak** [comment]
@EnriqueCorado @meenupant Should phone number be required?

**Comment by EnriqueCorado** [comment]
@kdondziak for now don't make it required  
heads up #1487 goes into detail as to which fields will be critical to have

**Comment by abaranowska1** [comment]
**Tested**
@kdondziak 
1. I think we should use the same phone number format/validation as in beneficiary/referral/registration pages. 
![Selection_816](https://user-images.githubusercontent.com/61964176/104189153-93c55c80-541a-11eb-9653-69abacaffade.png)
![image](https://user-images.githubusercontent.com/61964176/104189274-be171a00-541a-11eb-81c1-930ab5e92afd.png)
![image](https://user-images.githubusercontent.com/61964176/104189448-f4ed3000-541a-11eb-9b3b-8872fff130a7.png)
![Selection_815](https://user-images.githubusercontent.com/61964176/104189154-94f68980-541a-11eb-9994-017304bbbe2b.png)
![Selection_814](https://user-images.githubusercontent.com/61964176/104189156-94f68980-541a-11eb-8435-2515784d5790.png)
2. It is possible to create an Organization with the improper number 
![image](https://user-images.githubusercontent.com/61964176/104189679-4a294180-541b-11eb-9d3d-5725dd1b1afc.png)
![image](https://user-images.githubusercontent.com/61964176/104189738-5f9e6b80-541b-11eb-916e-4bf43c7cbb4e.png)

**Comment by abaranowska1** [comment]
**Tested with success**
Confirmed that the phone number format is consistent to +1 NXX-NXX-XXXX N=digits 2–9, X=digits 0–9
![Peek 2021-01-13 15-48](https://user-images.githubusercontent.com/61964176/104468824-32d38b00-55b8-11eb-9812-ed9283f61e0c.gif)
