### ISSUE TITLE
ROLLBACK: SP Beneficiary History

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1443]
- Hide the "Beneficiary History" button from Service Provider view: 
- this feature will be shown in the analytics portal only

<img width="140" alt="Screenshot 2020-12-02 133747" src="https://user-images.githubusercontent.com/65787629/100934458-9b9cf300-34a3-11eb-927f-931701bba5c7.png">

**Comment by abaranowska1** [comment]
**Tested with success**
- "Beneficiary History" button was hidden from Service Provider view
![image](https://user-images.githubusercontent.com/61964176/101633927-470bf180-3a28-11eb-9eef-8c8fce1e10b9.png)

**Comment by johnhbenetech** [comment]
@meenupant Beneficiary history was hidden in this task. Let us know if we need to reopen this task to surface it somewhere else?

**Comment by meenupant** [comment]
@johnhbenetech for the CA Marin pilot please don't hide the beneficiary history. Thanks

**Comment by johnhbenetech** [comment]
@jkondrat sorry for the reversal on this, can we back out this change?

**Comment by jkondrat** [comment]
@johnhbenetech sure, I'm revering the commit

**Comment by abaranowska1** [comment]
Beneficiary History came back 
![image](https://user-images.githubusercontent.com/61964176/101763900-b2fd6100-3adf-11eb-908a-e5ea1144a9ab.png)
