### ISSUE TITLE
SP Services: Fee field

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1449]
- please add a "Fees" field under "Required Documents" under service details 
- add the field to both, updating a record, and adding a new record
- Free text input field **not a required field** 

<img width="848" alt="Screenshot 2020-12-03 151716" src="https://user-images.githubusercontent.com/65787629/101100083-bc844780-357a-11eb-92ae-4b116c045e8b.png">

**Comment by abaranowska1** [comment]
**Tested with success**
- "Fees" field was added under "Required Documents" under service details
- It is free text, non required
- This field is not displayed to non-record owners if its blank ( Single Record View)
- Added to web and mobile
![image](https://user-images.githubusercontent.com/61964176/104311585-b0729a80-54d5-11eb-8a81-5102fe25d309.png)
![image](https://user-images.githubusercontent.com/61964176/104311805-08a99c80-54d6-11eb-9d88-ab9c2210c6f5.png)
![image](https://user-images.githubusercontent.com/61964176/104311987-40184900-54d6-11eb-98bc-3bc87fe4cbe1.png)

**Comment by meenupant** [comment]
@abaranowska1 Is the Fee field added in the database as well? Or shall we create a separate task for this?

**Comment by abaranowska1** [comment]
@meenupant Yes, the Fee field is in the database as well.
