### ISSUE TITLE
Email Verification + Benetech admin approval  

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1451]
User Story (encompasses persona, purpose, value) - e.g. As a [persona] i want to be able to [purpose] so that I can [value]:

As a brand new user registering to Service Net I want to know which step/stage I am in during the registration process, instead of having to ask "is my account approved." Having emails sent to the user specifying which stage they are in will make the process more friendly and personal. 

Description:

**Goal: Provide a registration process that** 

- after registration, the user must verify the email 
- after email verification, let the user know that the account must still get manually approved by Benetech staff in order to ensure accounts are real and the user can sign in after that approval
- two approval/verifications needed for users to log in
- First email verified, then account verified by benetech staff, after both those steps the user gets to sign in 
- 3 stages of account approval: 
1. registered
2. email verified
3. email + account verified (enable login)
**Only after step 3 can users log in**

**Process:** 
1. Enable email verification feature 
- email to use be used to send email verification feedback@benetech.org
- in the email verification email, the user will click the link sent in the email in order to verify their email 
Format:
Subject: "Verify Your Email Address for the Service Net account"
Content: 
"Hello **First name last name,** 

Thanks for creating your account on Service Net. Please click on the below link to verify your email address
**insert link**"

Thank you,
Service Net Team
**Insert Logo**

2. Once the user clicks on the link, the user goes to service net and gets the following content on the page. 

"Thanks for verifying your email. You can login after you receive an email notification from Service Net staff after approval of your account"

The user also gets the following email: 
Format:
Subject: Service Net Account Waiting Approval
Content:
"Hello **First name last name,** 

Your email has been successfully verified. Please wait for "Account Approval" email notification from Service Net. You can sign in once your account is approved by our staff."

Thank you,
Service Net Team
**Insert Logo**

3. Benetech staff will approve and activate this account (admin login: user management)
- once the account gets activated/verified by benetech staff, send an email saying 
Format:
Subject: Service Net Account Approved
Content:
"Hello **First name last name,** 

Thank you for your patience. We have verified and approved your account.

You can log in here: [ServiceNet](https://servicenet.benetech.org/#/)"

Thank you,
Service Net Team
**Insert Logo**

Accounts previously made
-------------------------
**Question: what happens with all the historical accounts previously made after this feature has been implemented?**
- All accounts previously made can be grandfathered in and not have to go through the process above 
- all users from the day the feature gets implemented will go through the process above
- all users before the feature gets implemented are given a "free pass"
- make all historical accounts automatically the third stage (email + account verified)

Dependencies (links to other related tasks):
*building for #1473

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [ ] Regression test cases cycle updated if needed

Product Signoff
- [x] Approved for release

**Comment by johnhbenetech** [comment]
@EnriqueCorado @meenupant to be clear, once this is on users will be able to register and instantly approve themselves and log into servicenet, Is this what we want? Should there still be a manual approval step on the benetech side?

**Comment by jkondrat** [comment]
@kkaczmarczyk @awalkowiak @kdondziak it seems that this issue has changed since we estimated it - there's admin approval and more emails to send out, perhaps we should re-estimate it/

**Comment by jkondrat** [comment]
@EnriqueCorado @johnhbenetech 
* the approval should be done on the 'User management' admin screen, right?
* could you please provide us with the logo used in these emails?

**Comment by EnriqueCorado** [comment]
@jkondrat 
- correct: approval in user management admin screen
- ![benetech-logo (2)](https://user-images.githubusercontent.com/65787629/106159034-3d099380-6139-11eb-8678-d5ace42d34d0.png)

**Comment by abaranowska1** [comment]
@jkondrat 
Please fix the verification link in the first email
![Selection_996](https://user-images.githubusercontent.com/61964176/106473323-f3f07100-64a3-11eb-9be1-3a3c063078c0.png)

**Comment by abaranowska1** [comment]
**Tested with success**
Now registration process looks like this:
- after registration, the user should verify the email
![Selection_999(004)](https://user-images.githubusercontent.com/61964176/106607466-9f142f80-6563-11eb-919f-176aac36e717.png)
- after clicking the link the email is verified
![Selection_999(005)](https://user-images.githubusercontent.com/61964176/106607508-adfae200-6563-11eb-97ea-4b884277c446.png)
- after email verification, the user knows that the account should still be manually approved by Benetech staff 
![Selection_999(006)](https://user-images.githubusercontent.com/61964176/106607556-be12c180-6563-11eb-844f-01a9dbffde05.png)
- after manual verification as admin on the user management page, the 
![Selection_999(007)](https://user-images.githubusercontent.com/61964176/106607800-ffa36c80-6563-11eb-99cf-a71b3933ac9f.png)
user gets third mail
- User can log in
