### ISSUE TITLE
Refer off "state" by default for linked records to UWBA, Eden, etc

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1458]
For a silo that has referral functionality enabled:

* By default, users cannot send a referral to 'linked' records from partners like UWBA/Eden/etc (basically orgs linked by silo_organizations)

* The 'refer' link should not appear on these cards

For records created by other ServiceProviders, the referral functionality and link visibility should respect the silo setting (the current functionality)

**Comment by EnriqueCorado** [comment]
@johnhbenetech

**Comment by abaranowska1** [comment]
**Tested with success**

- Users cannot send a referral to 'linked' records from partners like UWBA/Eden/etc
- The 'refer' button does not appear on these cards
![image](https://user-images.githubusercontent.com/61964176/101641637-48421c00-3a32-11eb-9277-bacb8f5be549.png)

**Verified on:**
- Ubuntu 20.04
- Google Chrome Version 85.0.4183.83
