### ISSUE TITLE
Can't send referral when user owns 1 or 0 records

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1463]
situation: 
* SP user is logged into a silo with referrals enabled
* SP user owns 1 or 0 records
* SP adds a referral to their cart
* SP user visits referral page, selects receiving location, enters phone or SNID

Result:
* User cannot send referral, send button does nothing

My gut says the form is checking for the existence of the 'sending from' box which isn't applicable for a user with 0 or 1 orgs

Let me know if there are considerations needed for a user that owns 0 records. Can that just be null or will that cause issues elsewhere.

**Comment by johnhbenetech** [comment]
@abaranowska1 this should be added to regression tests

**Comment by abaranowska1** [comment]
**Tested with success**
- As a Service Provider user with only 1 or 0 Organization, I can send a referral.
- SMS is sent and the referral is submitted

![Peek 2020-12-10 14-49](https://user-images.githubusercontent.com/61964176/101780520-f0b9b400-3af6-11eb-8a9b-d6128209879f.gif)
![image](https://user-images.githubusercontent.com/61964176/101780827-527a1e00-3af7-11eb-8bc5-793b1b6cbe08.png)
