### ISSUE TITLE
Beneficiary check in/referral pop up changes

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1465]
Purpose/Goal: Provide a "summary" of what transaction was done

Items of actions for check-in:
------
- After the beneficiary checks-in, and the user clicks send, the following pop up with content will popup:
- if the user checked in with a phone number, then show that phone number
- if the user checked in with a service net ID, then display that service net id
- "org name" should be the name of the organization the beneficiary checked in to

"Beneficiary _**(650)533-0950**_
checked in successfully
to _**org name**_!"

Items of actions for referral:
-----
- After the beneficiary gets a referral, and the user clicks send, the following pop up with content will popup:
- if the user provided a phone number, then show that phone number
- if the user provided a service net ID, then display that service net id
- "org name" should be the name of the organization the beneficiary got referred to

"
Beneficiary **_(650)533-0950_**
was successfully referred to the
following organizations:
_**org name
org name
org name**_"

mockups
-------
<img width="374" alt="Screenshot 2020-12-09 134402" src="https://user-images.githubusercontent.com/65787629/101692879-af0d0880-3a25-11eb-8ca2-1edb3576a860.png">

**Comment by awalkowiak** [comment]
@EnriqueCorado should this be done as it is on mockups (on this old version of UI) or the text should be displayed in the green popup that was unified in https://github.com/benetech/ServiceNet/issues/1413

**Comment by EnriqueCorado** [comment]
@awalkowiak in the UI. change text in this new popup that we have now

![image](https://user-images.githubusercontent.com/61964176/102330832-550ec480-3f8a-11eb-8e60-cf6fe27bb418.png)

**Comment by abaranowska1** [comment]
**Tested**
All looks fine, following by acc:

- After the beneficiary gets a referral, and the user clicks send, the following pop up is displayed
- If the user provided a phone number, then show that phone number
- If the user provided a service net ID, then display that service net id

@awalkowiak One small issue: On mobile 360x640 in Referral Pop up the text shouldn't be broken.

![image](https://user-images.githubusercontent.com/61964176/104906616-3aae7900-5984-11eb-9ce0-4068cea26e6b.png)

![Selection_916](https://user-images.githubusercontent.com/61964176/104906249-beb43100-5983-11eb-992c-2d41381662f7.png)
![Selection_915](https://user-images.githubusercontent.com/61964176/104906251-beb43100-5983-11eb-83f6-67ac4955fdec.png)
![Selection_914](https://user-images.githubusercontent.com/61964176/104906252-bf4cc780-5983-11eb-99ac-9d0dc7776687.png)

**Comment by abaranowska1** [comment]
**Tested with success**
Thanks for the changes, now it looks fine. 
![image](https://user-images.githubusercontent.com/61964176/105011353-25e1ec00-5a3d-11eb-9a7e-944b0292c677.png)

- After the beneficiary gets a referral, and the user clicks send, the following pop up is displayed
- If the user provided a phone number, then show that phone number
- If the user provided a service net ID, then display that service net id

**Verified on:**
- Ubuntu 20.04
- Google Chrome Version 85.0.4183.83
- Mobile 360x640
