### ISSUE TITLE
Extend DataImportReport in order to log failed parsing attempts

### ISSUE THREAD

**Issue by wojtekbu** [benetech/ServiceNet#147]
As soon as https://github.com/benetech/ServiceNet/issues/75 will be done we can log all failed attempts to the upload reports. Those logs should point out which object/field/part of the date caused the failure and what was the value. 

To do:
* extend the DataImportReport,
* handle parsing workflow, so errors will be persisted in those reports

**Comment by bognasoldev89** [comment]
Confirmed that extension exists and works
