### ISSUE TITLE
Reset Password Pop-up changes

### ISSUE THREAD

**Issue by meenupant** [benetech/ServiceNet#1476]
As a user when I forget my password and enter my email to reset my password, I should see the following pop-up message on the page itself, and NOT as a disappearing pop-up message on the top left corner. 

Replace this:
![image](https://user-images.githubusercontent.com/74263963/102267436-bffac580-3ece-11eb-905f-973b14fa89b5.png)

With this message:

![image](https://user-images.githubusercontent.com/74263963/102267498-d6088600-3ece-11eb-82c8-4db91f19cada.png)

**Comment by abaranowska1** [comment]
**Tested with success**
The popup message was replaced by the communicate "Enter the email address you used to register" on the blue rectangle 
![Peek 2021-01-12 11-36](https://user-images.githubusercontent.com/61964176/104303495-70f28100-54ca-11eb-82b6-dea5cc7d6995.gif)
