### ISSUE TITLE
Error in updating record 

### ISSUE THREAD

**Issue by meenupant** [benetech/ServiceNet#1477]
I encountered an error in my account meenakship on dev, I created my record with incomplete random information and when I click on this record / card (top right), a pop-up disappearing message says "null is not an object (evaluating 'e.children')". Then, the page gets frozen and nothing works, except Sign out.

![image](https://user-images.githubusercontent.com/74263963/102269083-018c7000-3ed1-11eb-8745-95efdf3376b9.png)

![image](https://user-images.githubusercontent.com/74263963/102269040-ef123680-3ed0-11eb-992d-e9a59edb2343.png)

**Comment by meenupant** [comment]
When I click "I'm Finished" on the page below, I get a pop-up message "Internal Server Error". Is this due to the new feature 'Hours of Operation'?

![image](https://user-images.githubusercontent.com/74263963/102270777-431e1a80-3ed3-11eb-914f-77756c807024.png)

**Comment by johnhbenetech** [comment]
this is on EdenSilo in dev

**Comment by abaranowska1** [comment]
@jkondrat 
Plz check it. I see that for example organization (Org Name) which I used fot tests doesn't generate an error:  https://benetechservicenet.org/#/record/a5deecef-3af9-4f22-b012-ea742a077ecf/edit ( provider user account ), but I confirmed that for example this Organization (Chihuly Garden and Glass New test 31/08) https://benetechservicenet.org/#/record/55a115e3-dd96-4218-a9f4-bc8c72d162f3/edit displays an error from the description.

**Comment by abaranowska1** [comment]
**Tested with success **
- Unexpected error doesn't occur anymore during updating and displaying edit view. I cannot replicate the Internal Server Error during the creation, but I will also take a look at it during regression tests. 
![Peek 2020-12-16 13-36](https://user-images.githubusercontent.com/61964176/102351860-6adeb280-3fa7-11eb-84e7-636fd37753f8.gif)

**Comment by johnhbenetech** [comment]
@jkondrat was there a corresponding commit that fixed this?

**Comment by jkondrat** [comment]
@johnhbenetech This was fixed as a part of #1413 (6e04527a75aba5e3f48c6a9c9c1f0b2710ac0e5d), sorry for not tagging it properly

**Comment by kkaczmarczyk** [comment]
Doing a clean-up of the project board. I am closing the issues which were released
