### ISSUE TITLE
Same phone number different Service Net ID

### ISSUE THREAD

**Issue by meenupant** [benetech/ServiceNet#1479]
I used my phone number for referrals in two different accounts "meenakship" and "women". Each time I referred this phone number, I received messages with a service net id. However, I received two different service net ids "000t", and "0005" from these different accounts on the same phone number. I believe we want to have one SN ID associated with one phone number irrespective of which organization the person is referred from.

@johnhbenetech Is there a way to check if this is set up correctly or is it a bug that needs to be corrected?

**Comment by johnhbenetech** [comment]
it's most likely a requirement bug. @meenupant can you turn this into a task that fully defines the intended design? Then we can make sure to get this fixed for all cases.
