### ISSUE TITLE
Investigate performance issue during claiming more than 5/6 records

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#1491]
During claiming more than 5/6 records which also have some services and locations I can meet a performance issue during loading this Organization to the carousel. 
![Peek 2020-12-17 11-20](https://user-images.githubusercontent.com/61964176/102475313-ffa1e880-4059-11eb-83fd-157b33036489.gif)

**Comment by awalkowiak** [comment]
@johnhbenetech, @EnriqueCorado, @meenupant 
Here is the complete version of it (not yet pushed). Let me know if you'd like to change something.
Version when claiming 3 records:
![claiming_progress_3_records](https://user-images.githubusercontent.com/12113312/102810885-cb655980-43c4-11eb-89ac-f9dc8c85d12f.gif)

Varsion when claiming 12 records:
![claiming_progress_12_records](https://user-images.githubusercontent.com/12113312/102810856-bf799780-43c4-11eb-85c3-a287043941f6.gif)

Note: I modified a bit label above progress bar. At this point it is "The cloning process might take a while depending on the amount of records to claim"

Let me know if you have any feedback.

**Comment by abaranowska1** [comment]
@awalkowiak Plz investigate Internal Server Error during claiming records 
![Selection_683](https://user-images.githubusercontent.com/61964176/102887520-66a70f00-4457-11eb-9009-ceb1f0c28d3c.png)
![Selection_682](https://user-images.githubusercontent.com/61964176/102887530-6a3a9600-4457-11eb-9acc-2bb2c8429358.png)
![Selection_681](https://user-images.githubusercontent.com/61964176/102887533-6c045980-4457-11eb-8906-2936515b19cf.png)

**Comment by abaranowska1** [comment]
**Tested**
- The Internal Server Error is not displayed during claiming records 
- New modal which shows us loading progress was added to the claiming functionality
![Selection_712](https://user-images.githubusercontent.com/61964176/102912733-08415700-447e-11eb-952d-36d0b614bdf4.png)
