### ISSUE TITLE
Feedback page to Help Center (in wordpress missing official content)

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1499]
User Story (encompasses persona, purpose, value) - e.g. As a [persona] i want to be able to [purpose] so that I can [value]:
As a service provider, I want to be able to have and see a help center in order to see any tutorial videos as well as send a feedback email if I have a concern.

Description:
Turning the Feedback button on the Service Provider View to "Help Center"
- in addition to the current Feedback option we have, add a new tab for "Tutorials" where benetech admin can update tutorial videos through the admin portal as new features get rolled out, we want to have the ability to easily add another "row" to embed a video and also add a title to it 
- Keep the same font, style, size on the top menu bar on desktop 
- Keep the same font, style, size as the hamburger menu on mobile 
- Keep the same button color/layout like the ones in the new "Claim records", "Beneficiary Check In" on the SP view 

Scope (includes UI mockups, user flow, and out of scope):
Desktop

<img width="881" alt="Screenshot 2020-12-17 093346" src="https://user-images.githubusercontent.com/65787629/102522369-ff4e2100-404a-11eb-8e8b-cdb6e7051a5b.png">

<img width="884" alt="Screenshot 2020-12-17 093551" src="https://user-images.githubusercontent.com/65787629/102522594-4d632480-404b-11eb-81cb-ceb9901e8936.png">

<img width="887" alt="Screenshot 2020-12-17 093623" src="https://user-images.githubusercontent.com/65787629/102522637-5b18aa00-404b-11eb-8f86-45a7cebd6acd.png">

Mobile

<img width="208" alt="Screenshot 2020-12-17 093708" src="https://user-images.githubusercontent.com/65787629/102522699-71bf0100-404b-11eb-84ae-a494cd0b55d5.png">

<img width="205" alt="Screenshot 2020-12-17 093732" src="https://user-images.githubusercontent.com/65787629/102522751-7f748680-404b-11eb-9b8e-586c55b9d49a.png">

<img width="206" alt="Screenshot 2020-12-17 093814" src="https://user-images.githubusercontent.com/65787629/102522833-9adf9180-404b-11eb-8016-6c628aba731f.png">

Acceptance criteria (includes edge cases):
*

Dependencies (links to other related tasks):
*

Any required analytics for task:
*

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [ ] Passes Acceptance Criteria
- [ ] All bug reports fixed/merged/tested
- [ ] Regression test cases cycle updated if needed

Product Signoff
- [ ] Approved for release

**Comment by EnriqueCorado** [comment]
@meenupant

**Comment by awalkowiak** [comment]
@meenupant will the videos be hosted on youtube and the admin will provide only a link to it?

**Comment by EnriqueCorado** [comment]
@awalkowiak will be hosted on youtube and an admin will provide a link
- ideally, if we could have the functionality to keep adding videos in admin would be good (not anticipating having more than 10-15 max explainer videos)

**Comment by meenupant** [comment]
@awalkowiak Yes, that's correct. Make these videos on YouTube as "unlisted". Thanks
