### ISSUE TITLE
UI issue with displaying locations and services

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#1506]
**Bug description**
UI issue with displaying locations and services occur on the edit view page

**To Reproduce**
1. Go to the edit view page and click the location/service card.

**Actual result**

![Peek 2020-12-18 14-43](https://user-images.githubusercontent.com/61964176/102621350-b5933280-413f-11eb-9d12-226987634833.gif)

**Expected behavior**

![image](https://user-images.githubusercontent.com/61964176/102621558-09058080-4140-11eb-9666-610f1eff8ad7.png)

**Verified on:**
 OS: Ubuntu 20.04
 Browser: Chrome
 Version: Version 85.0.4183.83

**Additional context**
DEV note: It could be related to #1490 

Dev Signoffs
- [x] Unit test added for the core business features at the minimum
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [ ] Approved for release

**Comment by abaranowska1** [comment]
@jkondrat 
Plz, look at this issue once again, because after changes all modals don't look good. Also, there is a lot of free space above the first rows on the locations and services edit page. 
![Selection_673](https://user-images.githubusercontent.com/61964176/102865375-f340d580-4435-11eb-8501-39eb61b864cc.png)
![Selection_671](https://user-images.githubusercontent.com/61964176/102865377-f3d96c00-4435-11eb-98d5-3a49607ef865.png)
![Selection_670](https://user-images.githubusercontent.com/61964176/102865379-f4720280-4435-11eb-9184-df4649cadb3f.png)
![Selection_669](https://user-images.githubusercontent.com/61964176/102865385-f50a9900-4435-11eb-814a-a43b0bef669a.png)
![Selection_668](https://user-images.githubusercontent.com/61964176/102865389-f63bc600-4435-11eb-94f4-5e15c35a88ba.png)
![Selection_667](https://user-images.githubusercontent.com/61964176/102865396-f8058980-4435-11eb-94ec-7a629a947913.png)
![Selection_674](https://user-images.githubusercontent.com/61964176/102865372-f1771200-4435-11eb-8ec1-3da2e4b3ba17.png)

**Comment by abaranowska1** [comment]
**Tested with success**
- Modals are in the right size 
- There is no internal server error during editing records
- There is no UI issue with displaying locations and services
![Peek 2020-12-22 16-17](https://user-images.githubusercontent.com/61964176/102905024-d8d91d00-4472-11eb-9190-7d270364ac62.gif)
![Selection_709](https://user-images.githubusercontent.com/61964176/102905036-e0002b00-4472-11eb-9a92-27dc15a4a86e.png)
![Selection_708](https://user-images.githubusercontent.com/61964176/102905047-e393b200-4472-11eb-84ed-37218de9ea2c.png)
![Selection_707](https://user-images.githubusercontent.com/61964176/102905051-e42c4880-4472-11eb-968f-41c47445cb49.png)
![Selection_706](https://user-images.githubusercontent.com/61964176/102905053-e4c4df00-4472-11eb-9c2d-d8079c1cf8f4.png)
![Selection_705](https://user-images.githubusercontent.com/61964176/102905059-e55d7580-4472-11eb-90dc-df63381f5498.png)
![Selection_704](https://user-images.githubusercontent.com/61964176/102905061-e68ea280-4472-11eb-9800-2480f60405e1.png)
![Selection_703](https://user-images.githubusercontent.com/61964176/102905068-e7bfcf80-4472-11eb-9c1f-7cfc3f86957f.png)
![Selection_702](https://user-images.githubusercontent.com/61964176/102905072-e8f0fc80-4472-11eb-9b8b-248472d6f99c.png)

**Comment by meenupant** [comment]
@abaranowska1 @jkondrat 

![Screen Shot 2020-12-22 at 8 08 50 AM](https://user-images.githubusercontent.com/74263963/102910695-ce496400-442f-11eb-9dc0-27fdc89a6627.png)

Done button not displayed in full (Safari browser on Mac). Also, "I'm Finished" not clickable in the development environment

**Comment by abaranowska1** [comment]
@meenupant  Screenshots from Mojave , macOS, Safari 12.1 Browser 
![Selection_713](https://user-images.githubusercontent.com/61964176/102911933-0d51d680-447d-11eb-8b7d-55d47ac61fde.png)

![Selection_714](https://user-images.githubusercontent.com/61964176/102911930-0aef7c80-447d-11eb-9357-1da4ef768bac.png)
