### ISSUE TITLE
Issue with Refer and Referred button when resizing page on chrome

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1520]
**Bug description**
Issue with Refer and Referred button when resizing page on chrome

**To Reproduce**

1. Resize chrome window to less than half screen
2. When I click on Refer and the text changes to Referred, the text is hiding since the size of the button bubble is too small 

**Actual result**

![Screenshot 2020-12-22 090125](https://user-images.githubusercontent.com/65787629/102913922-56ca0380-4434-11eb-8843-75adf601719b.png)

**Expected behavior**
button text should not be hidden. Make the size of the button more responsive to not allow the text to be hidden 

**Screenshots/gifs**

**Verified on:**
 OS: 
 Browser: Chrome 
 Version: 87.0.4280.88

**Mobile:**
 Device: 
 OS: 
 Browser: 
 Version:

**Additional context**
DEV note:

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [x] Code review passed
- [x] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [ ] Regression test cases cycle updated if needed

Product Signoff
- [ ] Approved for release

**Comment by awalkowiak** [comment]
Dev note: the refer button has now 25% of card width, lets use a fixed value, and for locations instead of 75% the flex-grow or sth.

**Comment by abaranowska1** [comment]
**Tested with success**
Refer/Referred buttons are more responsive and the text to is not hidden during resizing
![Peek 2021-01-07 15-48](https://user-images.githubusercontent.com/61964176/103906468-44241f80-5100-11eb-931e-79e0ae0ccf5e.gif)
