### ISSUE TITLE
Can't unclaim all records 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1523]
**Bug description**
Can't unclaim all of the records I claimed 
- solution to this bug on #1544 

**To Reproduce**
1. Claim any number of records
2. Unclaim all
3. When you get to the last record and try to unclaim it, an "Internal server error" pops up 

**Actual result**
user stuck with one record that can't be unclaimed 

**Expected behavior**
be able to unclaim all records on my account 

**Screenshots/gifs**
<img width="958" alt="Screenshot 2020-12-22 114712" src="https://user-images.githubusercontent.com/65787629/102927746-60f7fc00-444c-11eb-83da-b68262727e25.png">

**Verified on:**
 OS: 
 Browser: Chrome
 Version: 87.0.4280.88 (Official Build) (64-bit)

**Mobile:**
 Device: 
 OS: 
 Browser: 
 Version:

**Additional context**
DEV note:
May be an issue with record "Mayor's Office of Housing & Community Development (MOHCD)" because I claimed another record and tried to unclaim "Mayor's Office of Housing & Community Development (MOHCD)" and it gave me an internal error again 
The same is happening with "Lawyers' Comittee for Civil Rights (LCCR)"

login credentials to my account 
user: enriquecorado
pw: ********

<img width="960" alt="Screenshot 2020-12-22 115531" src="https://user-images.githubusercontent.com/65787629/102927883-a9171e80-444c-11eb-92c7-9694d11ca4a1.png">

Dev Signoffs
- [x] Unit test added for the core business features at the minimum
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [x] Approved for release

**Comment by awalkowiak** [comment]
@EnriqueCorado I looked into sentry why this one is failing. Turns out, that this record was referred. The unclaim action deletes the record. In order to delete this one, we'd need to delete the refer objects that are related to this record. Is it a proper action? Or perhaps records should be 'Unclaimable' if it was already referred?
cc @johnhbenetech, @meenupant

**Comment by awalkowiak** [comment]
@EnriqueCorado how about if the user tries to unclaim a record that is already referred or checked in we throw info, that "this record is referred you can only deactivate it now"?

**Comment by meenupant** [comment]
@awalkowiak Good question. This question has opened up many other similar situations. I am preparing a list and discuss with the team for the best solutions.

**Comment by awalkowiak** [comment]
@meenupant thanks

**Comment by awalkowiak** [comment]
@EnriqueCorado the same is happening for "Lawyers' Comittee for Civil Rights (LCCR)" from #1567.
Let's keep it consistent and if you will have any other issues with uncaliming, please mention the organization name in this issue.

@meenupant any news about the list of similar situations and how we'd like to handle it?

**Comment by meenupant** [comment]
@awalkowiak how to handle the edge case situations have been explained in the SN Glossary spreadsheet

**Comment by EnriqueCorado** [comment]
related task #1544 to edge case

**Comment by abaranowska1** [comment]
**Tested**
@EnriqueCorado I can unclaim 
"Lawyers' Comittee for Civil Rights (LCCR)" ,
"Mayor's Office of Housing & Community Development (MOHCD)" and other previously referred organizations.
