### ISSUE TITLE
Move Beneficiary History to Header

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1524]
User Story (encompasses persona, purpose, value) - e.g. As a [persona] i want to be able to [purpose] so that I can [value]:

As a SP I want to find the Beneficiary History page fast and not have to click on the dropdown at the top right in order to get there 

Description:

- Move the Beneficiary History menu option to the header in between "Home" & "Feedback"
- Keep the same font, size, color 
- desktop **only**

Scope (includes UI mockups, user flow, and out of scope):

currently the "Beneficiary History" sits in the top right menu option of the below screenshot
<img width="959" alt="Screenshot 2020-12-22 121718" src="https://user-images.githubusercontent.com/65787629/102929571-b5e94180-444f-11eb-8331-f28ddfa8b25f.png">

please move "Beneficiary History" to the header as displayed below between home and feedback

<img width="890" alt="Screenshot 2020-12-22 121626" src="https://user-images.githubusercontent.com/65787629/102929473-86d2d000-444f-11eb-87b3-54f388859a84.png">

Dev Signoffs
- [x] Unit test added for the core business features at the minimum
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [x] Approved for release

**Comment by abaranowska1** [comment]
**Tested with success**
The Beneficiary History page was moved to the header
![image](https://user-images.githubusercontent.com/61964176/105866283-1f7ee180-5ff4-11eb-9b83-347ae882592c.png)
**Verified on:**
- Ubuntu 20.04
- Google Chrome Browser Version 85.0.4183.83
