### ISSUE TITLE
Unclaimed record doesn't disappear without a reload 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1525]
**Bug description**

When unclaiming a record, the record should automatically disappear 

However, every time I unclaim a record the record stays on my view unless i reload my browser

same issue on mobile view

**To Reproduce**
1. Claim any record
2. Unclaim it 
3. Record will show as an owned record
4. Disappears only until the user reloads browser 

**Actual result**

**Expected behavior**
every time the user tries to unclaim a record, it should automatically disappear 

**Screenshots/gifs**
I have unclaimed the first record 

<img width="959" alt="Screenshot 2020-12-22 134032" src="https://user-images.githubusercontent.com/65787629/102935616-58f38880-445b-11eb-968d-a4316f12c4fe.png">

record still there

<img width="959" alt="Screenshot 2020-12-22 134047" src="https://user-images.githubusercontent.com/65787629/102935623-5b55e280-445b-11eb-9b6f-4cd177fc261f.png">

when I reload it disappears 

<img width="959" alt="Screenshot 2020-12-22 134057" src="https://user-images.githubusercontent.com/65787629/102935625-5d1fa600-445b-11eb-9452-62a9f5127727.png">

**Verified on:**
 OS: 
 Browser: Chrome
 Version: 87.0.4280.88 (Official Build) (64-bit)

**Mobile:**
 Device: 
 OS: 
 Browser: 
 Version:

**Additional context**
DEV note:

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [x] Approved for release

**Comment by abaranowska1** [comment]
**Tested with success**
I cannot reproduce this bug anymore, everytime when I unclaim the record, the organization disappeared. 
![Peek 2021-01-11 13-13](https://user-images.githubusercontent.com/61964176/104181538-4263a000-540f-11eb-91f8-69459ca82501.gif)

**Comment by EnriqueCorado** [comment]
@abaranowska1 can you check my account for this issue. My account still isn't able to unclaim records 
username - enriquecorado
ps: Benetech!

**Comment by abaranowska1** [comment]
@EnriqueCorado Actually there is a problem with Organization Lawyers' Committee for Civil Rights (LCCR), @kdondziak could you please check this edge case? 
Organization: Lawyers' Committee for Civil Rights (LCCR)
![Selection_827](https://user-images.githubusercontent.com/61964176/104223626-2af2da00-5444-11eb-8b4d-95e5f176baee.png)
![Selection_826](https://user-images.githubusercontent.com/61964176/104223628-2c240700-5444-11eb-8680-2414d55286a8.png)

**Comment by EnriqueCorado** [comment]
@abaranowska1 @kdondziak there is also an issue with the second record I owned 
Mayor's Office of Housing & Community Development (MOHCD)

**Comment by awalkowiak** [comment]
@abaranowska1, @EnriqueCorado Issue the last two organizations you both mentioned are related to this: https://github.com/benetech/ServiceNet/issues/1523#issuecomment-750018305

cc @kdondziak

**Comment by kdondziak** [comment]
closing this since mentioned bugs will be solved in #1523
