### ISSUE TITLE
Forgot Password Should be clickable 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1526]
**Bug description**

On the public view, when I open the sign in modal and click "Forgot Password" the username field gets highlighted for me to input the username as it cannot be empty

however, the user should be able to not fill anything in and go straight to the forgot password page

only until the second time of clicking forgot password is when I'm able to see the reset your password page

**To Reproduce**
1. go to https://servicenet.benetech.org/#/public/BayArea
2. Click on account then sign in 
3. click on fogot password
4. username field gets highlighted 
5. click forgot password and then the user is taken to that page 

**Actual result**

**Expected behavior**
the user should be able to click account, sign in, and click forgot password NOT highlight the username field and then take the user to the forgot password page 

**Screenshots/gifs**
<img width="960" alt="Screenshot 2020-12-22 134722" src="https://user-images.githubusercontent.com/65787629/102936047-3a41c180-445c-11eb-9b80-6edbac2d355c.png">

**Verified on:**
 OS: 
 Browser: Chrome 
 Version: 87.0.4280.88 (Official Build) (64-bit)

**Mobile:**
 Device: 
 OS: 
 Browser: 
 Version:

**Additional context**
DEV note:

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [ ] Approved for release

**Comment by abaranowska1** [comment]
**Tested with success**
The "Forgot Password" link is clickable.

![Peek 2021-01-07 15-25](https://user-images.githubusercontent.com/61964176/103904143-2acda400-50fd-11eb-8a73-f07dabe6237c.gif)

![Peek 2021-01-07 15-28](https://user-images.githubusercontent.com/61964176/103904136-2903e080-50fd-11eb-810c-7ae91ba1c469.gif)
