### ISSUE TITLE
text Update to :Claim records" button

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1527]
Description:

Update the text of the "Claim records" button to "Claim Record(s)"

<img width="88" alt="Screenshot 2020-12-22 140046" src="https://user-images.githubusercontent.com/65787629/102937022-18e1d500-445e-11eb-8fc8-697843e82820.png">

Dev Signoffs (remove items if not applicable to this issue)
- [ ] Unit test added for the core business features at the minimum
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs (remove items if not applicable to this issue)
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff (remove items if not applicable to this issue)
- [ ] Approved for release

**Comment by abaranowska1** [comment]
**Tested with success**
The button text was updated from "Claim Records" to Claim Record(s)"
![image](https://user-images.githubusercontent.com/61964176/103868261-f3450480-50c8-11eb-8e27-4716311264fb.png)
