### ISSUE TITLE
Claim a record flow: record information within modal

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1528]
**Bug description**

When a user is claiming a record and the user clicks on the name of the record, instead of taking them to a different page, have the details of the record show up on the modal itself 

**To Reproduce**
1. Click on Claim record(s)
2. Click on a record name
3. User gets taken to a complete page of viewing a record

**instead show the record information within the modal**
- add a back button and an arrow just like in the registration page

**Actual result**

**Expected behavior desktop**
<img width="958" alt="Screenshot 2020-12-22 135320" src="https://user-images.githubusercontent.com/65787629/102936561-39f5f600-445d-11eb-9dbd-315b2060477a.png">

<img width="889" alt="Screenshot 2020-12-22 135836" src="https://user-images.githubusercontent.com/65787629/102936871-d6b89380-445d-11eb-96fd-0d9cd8a1539b.png">

**Expected behavior mobile**

<img width="190" alt="Screenshot 2020-12-22 140456" src="https://user-images.githubusercontent.com/65787629/102937375-dbca1280-445e-11eb-90b7-3d27429a336a.png">

<img width="176" alt="Screenshot 2020-12-22 141211" src="https://user-images.githubusercontent.com/65787629/102937753-b4c01080-445f-11eb-9e2e-a2f1e85cf027.png">

**Screenshots/gifs**
**what is currently looks like desktop **

<img width="958" alt="Screenshot 2020-12-22 135320" src="https://user-images.githubusercontent.com/65787629/102936561-39f5f600-445d-11eb-9dbd-315b2060477a.png">

<img width="959" alt="Screenshot 2020-12-22 135334" src="https://user-images.githubusercontent.com/65787629/102936566-3bbfb980-445d-11eb-8808-6e9dda1c169e.png">

**what it looks like mobile**

<img width="190" alt="Screenshot 2020-12-22 140456" src="https://user-images.githubusercontent.com/65787629/102937345-cc4ac980-445e-11eb-8092-4140f93b9e85.png">

<img width="175" alt="Screenshot 2020-12-22 140507" src="https://user-images.githubusercontent.com/65787629/102937348-cead2380-445e-11eb-9258-51e6275b4989.png">

**Verified on:**
 OS: 
 Browser:
 Version: 

**Mobile:**
 Device: 
 OS: 
 Browser: 
 Version:

**Additional context**
DEV note:

Dev Signoffs
- [x] Unit test added for the core business features at the minimum
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [x] Approved for release

**Comment by awalkowiak** [comment]
Dev note: be sure to check the mobile version on the 360 width and on IOS (use browserstack).

**Comment by abaranowska1** [comment]
**Tested**
@kdondziak 
1. Please make sure that the back button is in the one line with the title and in my opinion it should be moved a little bit to the right 
![image](https://user-images.githubusercontent.com/61964176/104185910-ec462b00-5415-11eb-9e4f-df9f1e030ff8.png)
2. UI issue with displaying a progress bar on the services page
![image](https://user-images.githubusercontent.com/61964176/104186067-257e9b00-5416-11eb-96ab-65dbd091c164.png)
![image](https://user-images.githubusercontent.com/61964176/104186081-2a434f00-5416-11eb-8d97-ff77437cbf65.png)
3. Well know iOS device issue, probably it is related to the bottom device nav bar
![image](https://user-images.githubusercontent.com/61964176/104186219-68407300-5416-11eb-8bf2-6706ed8abd44.png)
4. I'm not sure if it is related to this ticket, but the new "opening 24/7" checkbox is not displaying here in the claiming modal #1536 @jkondrat @kdondziak 
![image](https://user-images.githubusercontent.com/61964176/104186510-cd946400-5416-11eb-88c7-a0a7c8a179e8.png)

**Verified on:**
- Google Chrome Version 85.0.4183.83 
- iOS 14.1, iPhone X
- mobile 360x640
- Ubuntu 20.04

**Comment by abaranowska1** [comment]
**Tested with success**
Confirmed that all four points are fixed. 
- UI issues are not displayed,
- 24/7 checkbox is available if checked,
- iOS UI claim modal issues are resolved.
![Selection_919](https://user-images.githubusercontent.com/61964176/104915482-0097a400-5991-11eb-88df-843629dd4619.png)
![Selection_920](https://user-images.githubusercontent.com/61964176/104915489-02616780-5991-11eb-8b3e-b6db65c02fa7.png)
![Selection_921](https://user-images.githubusercontent.com/61964176/104915495-03929480-5991-11eb-8c4c-06b50d6ad82d.png)
