### ISSUE TITLE
Claiming a record search bar to modal

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1529]
User Story (encompasses persona, purpose, value) - e.g. As a [persona] i want to be able to [purpose] so that I can [value]:

As a user claiming a record I want to be able to search for my records and not have to scroll to find them

Description:

Add the same search bar as in the screenshot below in order to find record(s) by name 
<img width="946" alt="Screenshot 2020-12-22 142512" src="https://user-images.githubusercontent.com/65787629/102938624-84797180-4461-11eb-8d8e-a0af5beffe98.png">

Scope (includes UI mockups, user flow, and out of scope):
<img width="175" alt="Screenshot 2020-12-22 142555" src="https://user-images.githubusercontent.com/65787629/102938686-a541c700-4461-11eb-8706-64f30f8f3614.png">

<img width="886" alt="Screenshot 2020-12-22 142606" src="https://user-images.githubusercontent.com/65787629/102938688-a541c700-4461-11eb-97c1-3ce4fb8257c4.png">

Acceptance criteria (includes edge cases):
*

Dependencies (links to other related tasks):
*

Any required analytics for task:
*

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [x] Approved for release

**Comment by abaranowska1** [comment]
@kdondziak please fix the search bar position when there is no/ one record searched. 
![Selection_805](https://user-images.githubusercontent.com/61964176/104182979-8fe10c80-5411-11eb-82bb-d2744117d2b9.png)
![Selection_804](https://user-images.githubusercontent.com/61964176/104182982-91123980-5411-11eb-8816-0045e7b8d83b.png)
![Selection_803](https://user-images.githubusercontent.com/61964176/104182984-91123980-5411-11eb-92f8-e0e54ed740c1.png)
- the search bar was added to the claiming modal, and there is possible to search by organization name, organization description, service name, service description, eligibility

**Comment by abaranowska1** [comment]
**Tested with success**
The search bar position was fixed. 
![Selection_872](https://user-images.githubusercontent.com/61964176/104458893-40831380-55ac-11eb-871a-d5df4f4599c4.png)
![Selection_871](https://user-images.githubusercontent.com/61964176/104458897-42e56d80-55ac-11eb-87b0-1fc3322354d2.png)
![Selection_868](https://user-images.githubusercontent.com/61964176/104458903-44af3100-55ac-11eb-869f-06d81f5c29bd.png)
![Selection_867](https://user-images.githubusercontent.com/61964176/104458906-44af3100-55ac-11eb-8dd4-74aa5303f9cc.png)
![Selection_866](https://user-images.githubusercontent.com/61964176/104458908-4547c780-55ac-11eb-9a12-c85defe78ca8.png)
![Selection_865](https://user-images.githubusercontent.com/61964176/104458910-4547c780-55ac-11eb-804b-8d03f174f092.png)
![Selection_864](https://user-images.githubusercontent.com/61964176/104458913-45e05e00-55ac-11eb-825b-407be1d5a5a4.png)
