### ISSUE TITLE
Deactivating Record Pop Up Text Update

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1530]
Description:

Update the current pop up after a user clicks on Deactivate Record from what is it below 

<img width="959" alt="Screenshot 2020-12-22 144910" src="https://user-images.githubusercontent.com/65787629/102940304-dc65a780-4464-11eb-895a-b6c1fb6f97f2.png">

**To**
"Are you sure you want to deactivate this record? If you deactivate this record, no other organization will be able to find this record, and no one else will be able to claim it. If you owned this record in error and want to make it available for others to claim, please use the 'Unclaim' button instead of the 'Deactivate' button."

Acceptance Criteria:
*

Dev Signoffs (remove items if not applicable to this issue)
- [x] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs (remove items if not applicable to this issue)
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff (remove items if not applicable to this issue)
- [x] Approved for release

**Comment by EnriqueCorado** [comment]
@meenupant is the text update/change ok?

**Comment by meenupant** [comment]
@EnriqueCorado I have updated the description above. Please move it to Up Next and mark it mid-sprint. Thanks

**Comment by awalkowiak** [comment]
@EnriqueCorado We assume that this new question will be shown only to the claimed records. Is it correct?

**Comment by EnriqueCorado** [comment]
@awalkowiak correct

**Comment by abaranowska1** [comment]
**Tested with success**
- When we clicked Deactivate Record button on the claimed organization we can see the updated pop-up message.
![Selection_873](https://user-images.githubusercontent.com/61964176/104570396-256adf00-5652-11eb-80ea-e8d6be1755dd.png)
- It is still possible to deactivate record and activate ( claimed and nonclaimed ) 
- For nonclaimed records, the pop-up message looks the same as before 
![Selection_874](https://user-images.githubusercontent.com/61964176/104571312-39631080-5653-11eb-8fc7-239563a345bb.png)
