### ISSUE TITLE
SP: COVID 19 Protocols Field

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1535]
User Story (encompasses persona, purpose, value) - e.g. As a [persona] i want to be able to [purpose] so that I can [value]:

As a beneficiary, I want to know if there are any protocols regarding COVID 19 when going to a CBO

Description:

Add a field both in editing a record and new record flow for "COVID 19 Protocols" 
- continue using the same look and field as the other fields in their pages 
- add to both mobile and desktop
- the new field will keep the same look and field as the entry fields in the page 
- add "COVID 19 Protocols" after Organization Description 

Scope (includes UI mockups, user flow, and out of scope):

<img width="887" alt="Screenshot 2021-01-04 132959" src="https://user-images.githubusercontent.com/65787629/103581530-0c637080-4e91-11eb-98ea-75e7bb294c31.png">
<img width="884" alt="Screenshot 2021-01-04 133011" src="https://user-images.githubusercontent.com/65787629/103581531-0cfc0700-4e91-11eb-9269-c27d9b8c88ea.png">

Acceptance criteria (includes edge cases):
* add functionality to not show field to non-record owners if its blank #1407 

Dev Signoffs
- [X] Unit test added for the core business features at the minimum
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [x] Approved for release

**Comment by abaranowska1** [comment]
**Tested with success**
All look fine. The new field "COVID 19 Protocols" was added to the Create, Single, Edit View Page. New field is not displayed to non-record owners if it's blank.
![Selection_832](https://user-images.githubusercontent.com/61964176/104291109-6e3c5f80-54bb-11eb-8a4b-3388ae03eec8.png)
![Selection_830](https://user-images.githubusercontent.com/61964176/104291127-709eb980-54bb-11eb-8e49-8a83efcf4581.png)
![Selection_829](https://user-images.githubusercontent.com/61964176/104291133-72687d00-54bb-11eb-8244-49ac708bb423.png)
![Selection_834](https://user-images.githubusercontent.com/61964176/104291278-a04dc180-54bb-11eb-8ee9-0ea23d2fe5bb.png)
![Selection_833](https://user-images.githubusercontent.com/61964176/104291280-a0e65800-54bb-11eb-9cfa-bb31b090c365.png)

**Comment by EnriqueCorado** [comment]
@abaranowska1 "COVID-19 Protocols"

**Comment by abaranowska1** [comment]
**Tested with success**
![image](https://user-images.githubusercontent.com/61964176/104454323-f72fc580-55a5-11eb-969c-5bb5cd95446f.png)
