### ISSUE TITLE
24 / 7 Opening checkbox in Opening Hours

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1536]
Description:

Add a check box with the text "Open 24/7" to the current hours in services 

<img width="886" alt="Screenshot 2021-01-04 145652" src="https://user-images.githubusercontent.com/65787629/103587942-1b502000-4e9d-11eb-9b09-ea1560b8b926.png">

- if the user clicks this, there is no need to need to show the time and day hour fill in

Acceptance Criteria:
*

Dev Signoffs (remove items if not applicable to this issue)
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs (remove items if not applicable to this issue)
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff (remove items if not applicable to this issue)
- [x] Approved for release

**Comment by awalkowiak** [comment]
@EnriqueCorado how this should be formatted for others to see?

**Comment by EnriqueCorado** [comment]
@awalkowiak 

<img width="1502" alt="Screenshot 2021-01-07 072206" src="https://user-images.githubusercontent.com/65787629/103909891-149df480-50b9-11eb-8976-54f060be8b41.png">

**Comment by abaranowska1** [comment]
**Tested**
- check box with the text "Open 24/7" was added to the current hours in locations
- if the user clicks this, there is no need to need to show the time and day hour fill in
![image](https://user-images.githubusercontent.com/61964176/104172686-eeec5
![image](https://user-images.githubusercontent.com/61964176/104172939-54404580-5405-11eb-9f90-e7406c22b411.png)
480-5404-11eb-8d0d-48ca8ae0fac0.png)
![image](https://user-images.githubusercontent.com/61964176/104172707-f7dd2600-5404-11eb-8292-9ea066fff2c3.png)
![image](https://user-images.githubusercontent.com/61964176/104172722-fe6b9d80-5404-11eb-8955-fb95be1d94c2.png)

@EnriqueCorado @meenupant 
This feature was added only to the CBO and public view if we want to have some changes to the old view pls create a new task. 
If the checkbox 24/7 is checked ( no other days were added before ): 
![Selection_800](https://user-images.githubusercontent.com/61964176/104179285-dfbcd500-540b-11eb-95c2-156956e21f38.png)
If the chcecbox 24/7 is chcecked ( for example one day with opening hours was added before) 
![Peek 2021-01-11 11-51](https://user-images.githubusercontent.com/61964176/104179850-c8321c00-540c-11eb-8ca5-5cae9ba18340.gif)

**Comment by abaranowska1** [comment]
**Tested with success**
- The last issue with the remaining state was fixed. Now during creating a new Organization we always see the default view with opening hours. 
![Peek 2021-01-12 11-27](https://user-images.githubusercontent.com/61964176/104302724-6f748900-54c9-11eb-8b92-c92e7fc48373.gif)
- check box with the text "Open 24/7" was added to the current hours in locations
- if the user clicks this, there is no need to need to show the time and day hour fill in
