### ISSUE TITLE
Unclaiming record(s) Logic to Referrals

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1544]
User Story (encompasses persona, purpose, value) - e.g. As a [persona] i want to be able to [purpose] so that I can [value]:

As an SP that has claimed a record, received referrals/sent referrals I would like to still be able to unclaim a record in order to ensure someone else can claim the record and receive those referrals.

As a SP that has claimed a record and checked in a beneficiary, I also want to be able to unclaim a record even if i have checked in a beneficiary

Description:

If a record has been claimed, user refers beneficiary elsewhere then the user cant unclaim the record 
- we have the issue #1523

If a record has been claimed, user checks in beneficiary, then the user can't unclaim the record 

Solution: 
Update descriptions of pop ups depending on which action they took as the screenshots below 
- allow the user to uncalim the record, and whatever referrals or check ins they did add them to a new table with this information to keep track of 

for pop ups keep the size, color, and font the same 

text: 
Referred:  
- "You have sent referrals from **CBO Name**  to these following places:
**- placed referred one
- placed referred two
-place referred three**
Are you sure you want to unclaim this record?"

Checked In
- "You have checked in **number of people checked in to org** 
Are you sure you want to unclaim this record?"

Both
- "You have checked in **number of people checked in to org** and referred 
**number of people referred** from **org name**
Are you sure you want to unclaim this record?"

Scope (includes UI mockups, user flow, and out of scope):
Current
<img width="959" alt="Screenshot 2021-01-12 082834" src="https://user-images.githubusercontent.com/65787629/104342911-311ea000-54b0-11eb-90aa-58fdef641cbe.png">

Update pop ups to depending on the what action CBO has taken with the record
<img width="1156" alt="Screenshot 2021-01-12 084528" src="https://user-images.githubusercontent.com/65787629/104344884-8bb8fb80-54b2-11eb-997d-160bfd620669.png">

Dev Signoffs (remove items if not applicable to this issue)
- [x] Unit test added for the core business features at the minimum
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs (remove items if not applicable to this issue)
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff (remove items if not applicable to this issue)
- [x] Approved for release

**Comment by awalkowiak** [comment]
@EnriqueCorado What do you understand by "new table with this information to keep track of"? Does it mimic the current Referral model? What should I keep as referred to the organization in that case? I can't set there the claimed record id that is being unclaimed (I could use the name of the organization).

Perhaps the easiest solution here would be to temporary replace the refer to organization in the existing referral table with the original organization (the one that was claimed) and possibly in the future if someone will claim again the organization that had referrals/check-ins, the refer to the organization would be replaced back with the claimed (cloned) record?

**Comment by EnriqueCorado** [comment]
@awalkowiak let's go with your approach thank you for giving this some thought

**Comment by awalkowiak** [comment]
@abaranowska1 I slightly modified the popup labels accordingly to what we agreed at the meeting.
If only check-ins:
`You have checked in {{ checkInsCount }} time(s). Are you sure you want to unclaim this record?`
If only referrals:
`You have {{ referralsCount }} referral(s) connected to this organization. Are you sure you want to unclaim this record?`
If check-ins and referrals:
`You have checked in {{ checkInsCount }} time(s) and have {{ referralsCount }} connected referrals. Are you sure you want to unclaim this record?`
If no check-ins or referrals the old question will be shown: `Are you sure you want to unclaim this record?`

**Comment by abaranowska1** [comment]
**Tested with success**
**Verified cases:**
- Pop up changes : 
1.  If only check-ins:
`You have checked in {{ checkInsCount }} time(s). Are you sure you want to unclaim this record?`
2. If only referrals:
`You have {{ referralsCount }} referral(s) connected to this organization. Are you sure you want to unclaim this record?`
3. If check-ins and referrals:
`You have checked in {{ checkInsCount }} time(s) and have {{ referralsCount }} connected referrals. Are you sure you want to unclaim this record?`
![Selection_955](https://user-images.githubusercontent.com/61964176/105369244-a736ab80-5c02-11eb-8708-f2888f826556.png)
![Selection_954](https://user-images.githubusercontent.com/61964176/105369249-a867d880-5c02-11eb-8f4e-81d7b2061df7.png)
![Selection_953](https://user-images.githubusercontent.com/61964176/105369253-a867d880-5c02-11eb-8594-43e936c91781.png)
![Selection_952](https://user-images.githubusercontent.com/61964176/105369256-a9006f00-5c02-11eb-8b8c-ea2ddf4db5e3.png)
- There is a chance to unclaim every record,
-
