### ISSUE TITLE
Add integration end-to-end tests for providers using iCarol

### ISSUE THREAD

**Issue by wojtekbu** [benetech/ServiceNet#155]
This is a child issue of https://github.com/benetech/ServiceNet/issues/135

Acceptance criteria:
* prepare json file with test data for int tests,
* add tests for a case when no significant data is missing,
* add tests for a case when some part of data is missing.
* add information about required data to the wiki

**Comment by wojtekbu** [comment]
@oskarhinc could you test it? The wiki is here: https://github.com/benetech/ServiceNet/wiki/iCarol-Data-Mapping-(Eden-and-UWBA)#restrictions

**Comment by oskarhinc** [comment]
I've verified this issue and it seems like the scope and implementation of this issue is more related to testing the whole adapters process end to end. However we indeed need those end-to-end tests as well, so I'll rename this one, and create a separate one for iCarol Unit tests
