### ISSUE TITLE
Icons to Refer and Send Referral

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1551]
Description:

- Change the color of the circle to red #D9001B on the Send Referral(s) button
- match color of "Send Referral(s)" with Refer button color 
- add icons to the buttons 
- below are examples of what the icons can look like (HEX #FAB28D)

<img width="367" alt="Screenshot 2021-01-06 130727" src="https://user-images.githubusercontent.com/65787629/103820132-a148a400-5020-11eb-8e76-fae046174a18.png">

![103799341-d09ae900-4fff-11eb-8531-9809acd44d74](https://user-images.githubusercontent.com/65787629/103806961-971bab00-500a-11eb-8130-11f7320ad54d.png)

![103799329-cd076200-4fff-11eb-8d87-b911204fa743 (1)](https://user-images.githubusercontent.com/65787629/103820106-92fa8800-5020-11eb-8346-dcd736d7cc9f.png)

Acceptance Criteria:
*

Dev Signoffs (remove items if not applicable to this issue)
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs (remove items if not applicable to this issue)
- [ ] Passes Acceptance Criteria
- [ ] All bug reports fixed/merged/tested
- [ ] Regression test cases cycle updated if needed

Product Signoff (remove items if not applicable to this issue)
- [ ] Approved for release

**Comment by meenupant** [comment]
And we can add a tracker to this icon for "Send Referral" in the menu bar, just like the cart button below. This will be a visual indicator to the user that there is some action waiting to be completed. 
![Screen Shot 2021-01-06 at 10 05 18 AM](https://user-images.githubusercontent.com/74263963/103804398-e8c23680-5006-11eb-852e-a2d7f7ba8cf8.png)

**Comment by meenupant** [comment]
@EnriqueCorado I think the background color of "Refer" and "Send Referral" should be the same so that users can make a connection visually. Please change the color of "Send Referral' and match it to the "Refer" button. Thanks

**Comment by EnriqueCorado** [comment]
@meenupant updated
