### ISSUE TITLE
Send Referral button

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1552]
Description:

On the Send Referral button 
- if only one referral is in the cart, the button should say "Send Referral"
- if more than one referral is in the cart, change the text on the button to "Send Referrals"

Acceptance Criteria:
*

Dev Signoffs (remove items if not applicable to this issue)
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs (remove items if not applicable to this issue)
- [ ] Passes Acceptance Criteria
- [ ] All bug reports fixed/merged/tested
- [ ] Regression test cases cycle updated if needed

Product Signoff (remove items if not applicable to this issue)
- [ ] Approved for release

**Comment by meenupant** [comment]
Related tasks #1548 #1549 #1550 #1551
