### ISSUE TITLE
Claim a record page split second pop up after claim flow

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1564]
**Bug description**

after claiming a recoird, clicking done, and saying no to the pop up the modal to claim a record pops up for a split second

**To Reproduce**
1. Click on Claim Record(s)
2. Claim any record
3. Click done
4. CLick no on pop up
5.  For a split second the modal for claim a record pops up wich should happen 

**Actual result**

after going through all the steps in claiming a record i shouldn't see another window (the claim a record modal) pop up for a split second 

**Expected behavior**

smooth transition into the home page

**Screenshots/gifs**

**Verified on:**
 OS: 
 Browser: Google Chrome
 Version: Version 87.0.4280.141 (Official Build) (64-bit)

**Mobile:**
 Device: 
 OS: 
 Browser: 
 Version:

**Additional context**
DEV note:

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [x] Approved for release

**Comment by abaranowska1** [comment]
**Tested with success**
- After going through all the steps in claiming a record i didn't see another window (the claim a record modal) pop up for a split second, I have a smooth transition into the home page.
