### ISSUE TITLE
Cant Unclaim "Lawyers' Comittee for Civil Rights (LCCR)

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1567]
**Bug description**

cant unclaim "Lawyers' Comittee for Civil Rights (LCCR)" and also got a "timeout error of 600000ms exceeded"

Login to my account:
username: Enriquecorado
ps: Benetech!

may be related to #1523 

**To Reproduce**
1. 
2.
3.

**Actual result**
<img width="1920" alt="Screenshot 2021-01-08 112945" src="https://user-images.githubusercontent.com/65787629/104056154-dda50d00-51a4-11eb-8c13-685da604455d.png">
<img width="1920" alt="Screenshot 2021-01-08 112956" src="https://user-images.githubusercontent.com/65787629/104056152-dd0c7680-51a4-11eb-8353-d3d92840d60d.png">

**Expected behavior**

**Screenshots/gifs**

**Verified on:**
 OS: 
 Browser:
 Version: 

**Mobile:**
 Device: 
 OS: 
 Browser: 
 Version:

**Additional context**
DEV note:

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [ ] Passes Acceptance Criteria
- [ ] All bug reports fixed/merged/tested
- [ ] Regression test cases cycle updated if needed

Product Signoff
- [ ] Approved for release

**Comment by awalkowiak** [comment]
@EnriqueCorado this is the same issue as mentioned here https://github.com/benetech/ServiceNet/issues/1523#issuecomment-750018305. Let's keep it consistent and the board clean. If you will have other issues with unclaiming please report the organization name in #1523.
