### ISSUE TITLE
Linking Site Search on Google Analytics

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1580]
User Story (encompasses persona, purpose, value):

As a benetech employee, I want to know to what extent do the users take advantage of the search functionality, which search terms they entered, and how effectively the search results created deeper engagement with your site.

Description:
Site search google documentation: https://support.google.com/analytics/answer/1012264?hl=en
- goal: track all search terms 
- Due to SPA, should likely use virtual page path approach

Dependencies (links to other related tasks):
* #1578 

Dev Signoffs
- [x] Unit test added for the core business features at the minimum
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs
- [ ] Passes Acceptance Criteria
- [ ] All bug reports fixed/merged/tested
- [ ] Regression test cases cycle updated if needed

Product Signoff
- [ ] Approved for release

**Comment by jkondrat** [comment]
In order to turn on reporting on GA, turn on Site search Tracking under Site Search Settings and add the 'query' Query parameter 
![Screenshot from 2021-01-26 15-03-39](https://user-images.githubusercontent.com/5969801/105855351-47684800-5fe8-11eb-8c6d-93453188dedc.png)

**Comment by johnhbenetech** [comment]
@jkondrat tracking is now enabled

**Comment by jkondrat** [comment]
@johnhbenetech please let us know once you see data in the behavior -> site search tab (it can take some time)

**Comment by johnhbenetech** [comment]
@jkondrat yeah it's not showing up yet, but i was waiting a little. the site search settings are as follows:
![image](https://user-images.githubusercontent.com/12927553/105861590-8086c500-5fb4-11eb-97f2-04ef90543695.png)


I can see the page views being received:
![image](https://user-images.githubusercontent.com/12927553/105861815-bc218f00-5fb4-11eb-9616-27d37ae3e4a4.png)

But the Site Search page says 'no data for this view' and no search terms
