### ISSUE TITLE
Add copy to excluded fields

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#160]
As part of #84 we need to add placeholder text when a partner views their own record with excluded fields.

"This field has been excluded from ServiceNet per your data sharing agreement"

When a different partner view this record (in the side-by-side for example) the field should just appear blank for now. I may revisit in the future.

**Comment by oskarhinc** [comment]
@johnhbenetech I assume fields of a different type (date/boolean) can be excluded as well. Should we create a special label next to them for those or just blank them? It could also be an icon (maybe with a tooltip).

**Comment by johnhbenetech** [comment]
@oskarhinc Oooo.. I like the tooltip idea. Maybe we can just do that for every excluded field (regardless of type). Something like a grey x:
![image](https://user-images.githubusercontent.com/12927553/52064962-3c829600-253b-11e9-8491-b7865ac809d5.png)

What do you think?

**Comment by wojtekbu** [comment]
Works fine
excluding partner:
![excluding_partner](https://user-images.githubusercontent.com/7571152/52562745-c82fd880-2dff-11e9-8e63-9635d6b2f1b1.png)
another partner:
![another_partner](https://user-images.githubusercontent.com/7571152/52562777-e0075c80-2dff-11e9-94bd-27e540f4b8ab.png)
