### ISSUE TITLE
LinkForCare Column Name Mapping to Service Description

### ISSUE THREAD

**Issue by meenupant** [benetech/ServiceNet#1606]
**Bug description**

The rule mapping the following column names to Service Description on Service Net (If TRUE, write column name after removing _ and C at the end, AND add "available") does not work

IN_CENTER_HEMODIALYSIS__C, 
IN_CENTER_NOCTURNAL_DIALYSIS__C, 
IN_HOME_NON_MEDICAL_SERVICES__C, 
IN_UNIT_WASHER_AND_DRYER__C, 

MUST_SCHEDULE_24_HRS_OR_MORE_IN_ADVANCE__C
MUST_SCHEDULE_48_HRS_OR_MORE_IN_ADVANCE__C

PET_CARE__C
PET_THERAPY__C
PHARMACY_SERVICES__C
PHYSICAL_THERAPISTS__C
PHYSICIANS__C
PSYCHIATRIC_NURSE__C
PSYCHIATRIST__C
PSYCHOANALYST__C
PSYCHOLOGIST__C
PSYCHOTHERAPIST__C
REGISTERED_DIETICIANS__C
REGISTERED_NURSE_ON_CALL__C

SINGLE_FAMILY_HOMES_VILLAS_1_BEDROOM__C
SINGLE_FAMILY_HOMES_VILLAS_2_BEDROOMS__C
SINGLE_FAMILY_HOMES_VILLAS_3_BEDROOMS__C
SKILLED_NURSING_FACILITY__C
SNACK_S__C
SOCIAL_WORKERS__C
SPANISH__C
SPECIALTY_CARE_FORMULA__C
SPEECH_LANGUAGE_THERAPISTS__C
STATE_LICENSED__C
STRESS_AND_TRAUMA__C
STROKE_NEUROLOGICAL_REHABILITATION__C

In “Assisted Transportation” Organization name (PROVIDER_C), the first four column contents say FALSE, but these column names are  showing up in Service Description for this record.

Please change the current rule to "**If TRUE, write column name after removing _ and C at the end, if FALSE do not write anything**"

**To Reproduce**
1. Go to Assisted Transportation Record details and check Service Details - Service Description
2. The column names are appearing in this description

**Actual result**

The column names appear although their values are "FALSE" in the original data sheet

**Expected behavior**

These column names should not appear in the service description if the values are FALSE

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [ ] Approved for release

**Comment by abaranowska1** [comment]
It seems that now after fix the column names appear in the service description and add "available" if the values are TRUE.
![Selection_893](https://user-images.githubusercontent.com/61964176/104739198-bc18c800-5746-11eb-965f-8779538c3c75.png)

**Comment by meenupant** [comment]
@abaranowska1 @jkondrat Could you please remove the word "available". It is getting repeated too often. Thanks

**Comment by abaranowska1** [comment]
@jkondrat Please removed the word "available" at the end. "If TRUE, write column name after removing _ and C at the end, if FALSE do not write anything"

**Comment by abaranowska1** [comment]
Now the rule is changed to "If TRUE, write column name after removing _ and C at the end, if FALSE do not write anything"
![image](https://user-images.githubusercontent.com/61964176/104901509-c2dd5000-597d-11eb-8cba-0ee43b89fbdb.png)

**Comment by meenupant** [comment]
@jkondrat @abaranowska1 The Assisted Transportation record still shows Laundry Services, Licensed Practical Nurses, Licensed Professional Counselor, Licensed Staff on Duty 24/7 although its FALSE.

**Comment by abaranowska1** [comment]
@meenupant The rule mapping for the following column names to Service Description on Service Net was (When NOT Blank, Add Column name remove _ and C at the end + "available") I guess that you want to change it for "When NOT Blank, Add Column name remove _ and C at the end, if FALSE do not write anything"

LAUNDRY_SERVICES__C
LICENSED_PRACTICAL_NURSES__C
LICENSED_PROFESSIONAL_COUNSELOR__C
LICENSED_STAFF_ON_DUTY_24_7__C
LIGHT_HOUSEKEEPING__C
LIVE_IN_CARE__C

I checked that when I leave the columns blank all works fine and the column name for example here (LAUNDRY_SERVICES__C) disappeared : 
![image](https://user-images.githubusercontent.com/61964176/105022164-b6bec480-5a49-11eb-9742-9a5caff97300.png)

**Comment by meenupant** [comment]
@abaranowska1 can you please check why Services Provided: 0 in "Assisted Transportation" record. This should not be written. Where is the 0 coming from?Just FYI, Services Provided is mapped to only two columns 
SATOP_CLASSES__C
SERVICES_PROVIDED_INHOME_NONMED_FORMULA__C
and both are blank in this record. Thanks

**Comment by abaranowska1** [comment]
@meenupant It should work now.

**Comment by meenupant** [comment]
Thanks @abaranowska1
