### ISSUE TITLE
LinkForCare Column Name mapping with Service Description (when not blank)

### ISSUE THREAD

**Issue by meenupant** [benetech/ServiceNet#1607]
**Bug description**

The following column names 
SATOP_CLASSES__C
SERVICES_PROVIDED_INHOME_NONMED_FORMULA__C

are mapped to Service Description on Service Net with the rule (When NOT blank, Add "Services Provided" in front of the column contents), however some records for these columns not blank and have FALSE, we do not want to write "Services Provided: FALSE". Please change the rule to 

"**When NOT blank and when the column content does NOT say "FALSE", Add "Services Provided" in front of the column contents**"

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [x] Approved for release

**Comment by abaranowska1** [comment]
**Tested with success**

The following column names:

- SATOP_CLASSES__C
- SERVICES_PROVIDED_INHOME_NONMED_FORMULA__C

are mapped with the following rule: "When NOT blank and when the column content does NOT say "FALSE", Add "Services Provided" in front of the column contents"
![image](https://user-images.githubusercontent.com/61964176/104902973-b2c67000-597f-11eb-8c61-f504b77e6077.png)
