### ISSUE TITLE
LinkForCare Service Available 24/7

### ISSUE THREAD

**Issue by meenupant** [benetech/ServiceNet#1608]
**Bug description**

For the column
SERVICE_AVAILABLE_24_7__C 
The rule is: Check 24/7 if "YES"

**To Reproduce**
1. Go to the record "Metropolitan Organization to Counter Sexual Assault (MOCSA)" 
2. Their SERVICE_AVAILABLE_24_7__C says "YES"
3. However, it is not mapped to Service Net and 24 / 7 Opening checkbox is not checked in Opening Hours (task #1536)

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [x] Approved for release

**Comment by abaranowska1** [comment]
@jkondrat If we change only SERVICE_AVAILABLE_24_7__C for YES the checkbox is not updated. 
`2021-01-15 16:13:11.157  INFO 1 --- [ XNIO-1 task-15] o.b.s.s.i.OrganizationImportServiceImpl  : Organization Northland Adult Day Center TEST1 didn't change, skipping`

**Comment by abaranowska1** [comment]
@jkondrat Thanks for a quick fix. Now after change SERVICE_AVAILABLE_24_7__C for YES the checkbox is displayed. 
![Selection_898](https://user-images.githubusercontent.com/61964176/104753262-0787a200-5758-11eb-8911-d8845228084a.png)
