### ISSUE TITLE
When claiming a record, include the new fields used by LinkForCare import

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#1610]
Make sure that all the fields are copied when claiming a record

**Comment by jkondrat** [comment]
@abaranowska1 It seems that all the (existing) fields are already included, could you please confirm?

@kdondziak when adding remote service checkbox (#1321) please remember to verify that it works with claiming

**Comment by abaranowska1** [comment]
@jkondrat it seems that not every fields are included after claim. 
PRIMARY_CONTACT_PHONE__C, "Which Locations Offer This Service?" (location in the service is not selected) 
![image](https://user-images.githubusercontent.com/61964176/104898575-19e12600-597a-11eb-8752-4cf86cc5bb59.png)
![image](https://user-images.githubusercontent.com/61964176/104898609-25345180-597a-11eb-86fb-f5f72b9c8132.png)

**Comment by abaranowska1** [comment]
**Tested with success**
"Which Locations Offer This Service?"  and "Phone number" fields are copied after claim. 
![image](https://user-images.githubusercontent.com/61964176/105186362-ecd77380-5b31-11eb-8550-d38bed377637.png)
Note: I should update the record via import firstly.
