### ISSUE TITLE
Include the last update field in LinkForCare import

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#1611]
The last update shows the date of the import on SP view. It should show the value from the imported spreadsheet

**Comment by abaranowska1** [comment]
The LASTMODIFIEDDATE is included during import data from the spreadsheet. On SP view we show the LASTMODIFIEDDATE
![image](https://user-images.githubusercontent.com/61964176/104898956-8a884280-597a-11eb-9828-4bc566ec14a2.png)
![image](https://user-images.githubusercontent.com/61964176/104898972-8fe58d00-597a-11eb-956f-f5014f6b3e2a.png)
