### ISSUE TITLE
Locations are not present in Organization entity during similarity check

### ISSUE THREAD

**Issue by kcissewski** [benetech/ServiceNet#162]
Should be fixed by #176 

After saving data of second provider we are looking for conflicts. During location similarity check newly added organization doesn't contain Set of Locations (it is marked as null) which causes NPE and whole conflict check failure.

**Repro Steps**
1. Add Provider1 conflicting data
2. Add Provider2 conflicting data

**Actual Behavior:**
No conflicts and matches are created

**Expected Behavior:**
Conflicts and matches should be created

**Comment by awalkowiak** [comment]
@abaranowska1, @bognasoldev89 this should be fixed, could you take a look and confirm that it is resolved?

**Comment by bognasoldev89** [comment]
@awalkowiak as far as I am concerned Locations and, in fact, all of the entities are saved and conflicts and matches are created.
