### ISSUE TITLE
LinkForCare Service Description Mapping (adding FALSE to the rule)

### ISSUE THREAD

**Issue by meenupant** [benetech/ServiceNet#1624]
**Bug description**

The current rule mapping the following column names to Service Description on Service Net (When NOT Blank, include the column description and Add "available" at the end). Please change the rule for these columns to 
**When NOT Blank, include the column description, and if FALSE do not write anything**. Please note that I have removed the requirement to add "available" and when it says FALSE or BLANK, do not write anything in Service Description field of Service Net. 

LAUNDRY_SERVICES__C
LENGTH_OF_CARE_SERVICE_FORMULA__C
LICENSED_PRACTICAL_NURSES__C
LICENSED_PROFESSIONAL_COUNSELOR__C
LICENSED_STAFF_ON_DUTY_24_7__C
LIGHT_HOUSEKEEPING__C
LIVE_IN_CARE__C
MEALS_SERVED_FORMULA__C

**To Reproduce**
1. In “Assisted Transportation” Organization name (PROVIDER_C), the Laundry_Services_C column contents say FALSE, but this column name shows up in Service Description for this record.

**Actual result**
The column names appear although their values are "FALSE" in the original data sheet

**Expected behavior**
These column names should not appear in the service description if the values are FALSE

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [x] Approved for release

**Comment by abaranowska1** [comment]
The rule for these columns is  **"When NOT Blank, include the column description, and if FALSE do not write anything."**
LAUNDRY_SERVICES__C
LENGTH_OF_CARE_SERVICE_FORMULA__C
LICENSED_PRACTICAL_NURSES__C
LICENSED_PROFESSIONAL_COUNSELOR__C
LICENSED_STAFF_ON_DUTY_24_7__C
LIGHT_HOUSEKEEPING__C
LIVE_IN_CARE__C
MEALS_SERVED_FORMULA__C
![image](https://user-images.githubusercontent.com/61964176/105032830-9990f280-5a57-11eb-841c-a95048ca98ea.png)
