### ISSUE TITLE
LinkForCare Service Type Mapping (adding FALSE to the previous rule)

### ISSUE THREAD

**Issue by meenupant** [benetech/ServiceNet#1625]
**Bug description**

**NEW RULE: Map the following Link For Care columns to Service Net Service Type field (If TRUE use column name as Service Type after removing_ and C at the end, AND if FALSE do not write anything)**

OTHER_TYPES_OF_CARE_PROVIDED__C
RENAL_DIALYSIS__C
RESIDENTIAL_HEALTH_CARE__C
RESPIRATORY_THERAPISTS__C
RESPITE_CARE__C
SKILLED_NURSING_AND_THERAPY_SERVICES__C
TRANSPORTATION__C
VETERANS__C
VOCATIONAL_WORK_PROGRAM__C
WELLNESS_FACILITY__C

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [ ] Passes Acceptance Criteria
- [ ] All bug reports fixed/merged/tested
- [ ] Regression test cases cycle updated if needed

Product Signoff
- [ ] Approved for release

**Comment by jkondrat** [comment]
Closing as we're already doing nothing for FALSE (and any value other than TRUE)
