### ISSUE TITLE
LinkForCare NEW RULE for Service Description (Adding FALSE)

### ISSUE THREAD

**Issue by meenupant** [benetech/ServiceNet#1626]
**Bug description**

NEW RULE to Map the following Link For Care Columns to the Service Net Service Description Field
**"If TRUE use column name and remove _ and C at the end, AND if FALSE do not write anything"**

MUST_SCHEDULE_24_HRS_OR_MORE_IN_ADVANCE__C
MUST_SCHEDULE_48_HRS_OR_MORE_IN_ADVANCE__C

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [ ] Passes Acceptance Criteria
- [ ] All bug reports fixed/merged/tested
- [ ] Regression test cases cycle updated if needed

Product Signoff
- [ ] Approved for release

**Comment by jkondrat** [comment]
Closing as we're already doing nothing for FALSE (and any value other than TRUE)
