### ISSUE TITLE
LinkForCare Eligibility Criteria Mapping new rule (Adding FALSE)

### ISSUE THREAD

**Issue by meenupant** [benetech/ServiceNet#1627]
**Bug description**

New Rule to MAP the following Link For Care Columns to the Service Net **Eligibility Criteria** field: 
**"If TRUE use column name and remove _ and C at the end, AND if FALSE do not write anything"**

MUST_BE_AMBULATORY__C
MUST_MEET_AGE_GUIDELINES__C
MUST_MEET_DISABILITY_GUIDELINES__C
MUST_MEET_INCOME_GUIDELINES__C
MUST_BE_A_VETERAN__C

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [ ] Passes Acceptance Criteria
- [ ] All bug reports fixed/merged/tested
- [ ] Regression test cases cycle updated if needed

Product Signoff
- [ ] Approved for release

**Comment by jkondrat** [comment]
Closing as we're already doing nothing for FALSE (and any value other than TRUE)
