### ISSUE TITLE
LinkforCare: Comma showing instead of address 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1638]
**Bug description**

In public dev env the below screenshot shows some records with no address but a comma 

records which show this 
- DCF Fraud Hotline Kansas
- DCF Fraud Hotline Missouri

**To Reproduce**
1. 
2.
3.

**Actual result**

**Expected behavior**

**Screenshots/gifs**
<img width="960" alt="Screenshot 2021-01-19 081002" src="https://user-images.githubusercontent.com/65787629/105060937-ca5c3200-5a2d-11eb-816d-4c7cd104b1b6.png">

**Verified on:**
 OS: 
 Browser:
 Version: 

**Mobile:**
 Device: 
 OS: 
 Browser: 
 Version:

**Additional context**
DEV note:

Dev Signoffs
- [x] Unit test added for the core business features at the minimum
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [x] Approved for release

**Comment by EnriqueCorado** [comment]
I noticed a good amount of those records with no address are hotlines. Instead of showing locations for those "hotlines" with a comma as an address could we hide the location address fields?

**Comment by abaranowska1** [comment]
@EnriqueCorado Now when the Organization has no address we are hiding the location address fields.
![Selection_943](https://user-images.githubusercontent.com/61964176/105326699-51e0a700-5bce-11eb-942e-8eb74ab003e4.png)
![image](https://user-images.githubusercontent.com/61964176/105327075-c61b4a80-5bce-11eb-9de6-fc0f11326d05.png)
