### ISSUE TITLE
North Carolina: Social Media Links + Icons

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1661]
User Story (encompasses persona, purpose, value) - e.g. As a [persona] i want to be able to [purpose] so that I can [value]:

As a service provider, I want to be able to have a place where I can add links to my social media and display them on my record with their icons accordingly

Description:

- add three new fields to edit record view and creating new record view under organization details 
- those fields are "Facebook URL", "Twitter URL", "Instagram URL"
- only show the icon based on which social media URL
- if user only inputs a facebook URL, only show that icon
- if user inputs all three URLs show all three icons
- each icon should be clickable and take the user to the corresponding social media platform link

Icons:
![icons8-facebook-48](https://user-images.githubusercontent.com/65787629/106159428-a12c5780-6139-11eb-9ad6-062b71da0c55.png)
![icons8-instagram-48](https://user-images.githubusercontent.com/65787629/106159525-bc976280-6139-11eb-8c39-ee90537f5c3d.png)
![icons8-twitter-48](https://user-images.githubusercontent.com/65787629/106159532-be612600-6139-11eb-9265-9ed26ffa056a.png)

Scope (includes UI mockups, user flow, and out of scope):
**Record Detail View
desktop** 

<img width="1202" alt="Screenshot 2021-01-25 095009" src="https://user-images.githubusercontent.com/65787629/105745077-bbc0bf80-5ef2-11eb-93d4-2427d5edf470.png">

**mobile**

<img width="298" alt="Screenshot 2021-01-25 095045" src="https://user-images.githubusercontent.com/65787629/105745134-cf6c2600-5ef2-11eb-870c-bd0798d1fddf.png">

**Home page view**
**Desktop** 
<img width="1205" alt="Screenshot 2021-01-25 095132" src="https://user-images.githubusercontent.com/65787629/105745244-ed398b00-5ef2-11eb-8523-3710b196283b.png">

**Mobile**
<img width="269" alt="Screenshot 2021-01-25 095149" src="https://user-images.githubusercontent.com/65787629/105745287-f7f42000-5ef2-11eb-83da-f8910917a5c8.png">

**Record edit view** 
<img width="1202" alt="Screenshot 2021-01-25 095354" src="https://user-images.githubusercontent.com/65787629/105745566-45708d00-5ef3-11eb-88cd-db39c2eb2346.png">

Acceptance criteria (includes edge cases):
When any Service Provider wants to add links to social media 
Then during creation or updating of their record under the Org Website field they should see the social media fields

When users checks any organizational details on the card display
Then users should be able to view the social media icons on the record only when the information is provided otherwise these icons are not displayed. 

When any social media icon is clicked
Then this link would open in a new tab

Dependencies (links to other related tasks):
*

Any required analytics for task:
*

Dev Signoffs
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [ ] Approved for release

**Comment by jkondrat** [comment]
@EnriqueCorado  could you provide us with these icons?

**Comment by EnriqueCorado** [comment]
@jkondrat updated ticket description with logos

**Comment by abaranowska1** [comment]
**Tested with success**

- three new fields( "Facebook URL", "Twitter URL", "Instagram URL" ) were added to edit record view and creating new record view under organization details
![image](https://user-images.githubusercontent.com/61964176/107050218-434bdf80-67cb-11eb-9cde-75e46330b8f3.png)
- if user only inputs a facebook URL, it shows that icon
- if user inputs all three URLs, it shows all three icons
![image](https://user-images.githubusercontent.com/61964176/107051065-485d5e80-67cc-11eb-823b-0c902f9c3b8d.png)
- each icon are clickable and takes the user to the corresponding social media platform link
- all works fine also on mobile and ios view
![image](https://user-images.githubusercontent.com/61964176/107051014-38457f00-67cc-11eb-938e-2ddf3ba2bb30.png)
![image](https://user-images.githubusercontent.com/61964176/107051021-3aa7d900-67cc-11eb-8e98-c4f51f1f07fa.png)
