### ISSUE TITLE
Claim a record search issue

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1665]
**Bug description**
I'm noticing inconsistencies with the search functionality in the claim a record dialogue.  Subsequent searches (after the first) don't seem to work unless you close out and reopen the dialogue. Search terms also do not persist if you search, click into a record, then go back to the search (it starts you from the beginning).

**To Reproduce**
1. Log into a silo where you can claim records
2. Search, then try to search again
3. Search, click into a record, go back

**Actual result**
* second search doesnt seem to work
* search term is cleared out after returning with back button

**Expected behavior**
* multiple searches should be allowed
* search term should be retained after navigating back

Dev Signoffs
- [x] Unit test added for the core business features at the minimum
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [ ] Approved for release

**Comment by johnhbenetech** [comment]
@abaranowska1 can you confirm this?

**Comment by abaranowska1** [comment]
@johnhbenetech I cannot reproduce the subsequent search issue, but I confirm that the search terms don't stay after going back from the detail view. 
![Peek 2021-01-26 12-05](https://user-images.githubusercontent.com/61964176/105837426-f861e900-5fce-11eb-8cc9-f9ba49044819.gif)
![Peek 2021-01-26 12-03](https://user-images.githubusercontent.com/61964176/105837436-fc8e0680-5fce-11eb-83a3-34c0902d1544.gif)

**Comment by abaranowska1** [comment]
**Tested with success**
- The search term is retained after navigating back
![Peek 2021-01-27 13-07](https://user-images.githubusercontent.com/61964176/105991209-ce2e2b00-60a3-11eb-8c9b-05cbe379db49.gif)

- I checked also the search functionality on our homepage and public view and I think it should work the same as in the claim modal @johnhbenetech @EnriqueCorado what do you think
![Peek 2021-01-27 13-08](https://user-images.githubusercontent.com/61964176/105991978-c753e800-60a4-11eb-94d8-1eb055a9bf83.gif)
? 
![Peek 2021-01-27 13-09](https://user-images.githubusercontent.com/61964176/105991972-c58a2480-60a4-11eb-8308-b3d5d6691777.gif)

**Comment by johnhbenetech** [comment]
@abaranowska1 #1596 will handle that

**Comment by meenupant** [comment]
@abaranowska1 I checked on safari Version 13.1.3 (15609.4.1) on Mac the search term is cleared out after returning with back button.

https://user-images.githubusercontent.com/74263963/106020254-6adad380-6078-11eb-828e-04f048d5c8e2.mov

**Comment by abaranowska1** [comment]
@meenupant 
I checked on Mac OS Mojave, Safari 12.1 
![Peek 2021-01-28 09-01](https://user-images.githubusercontent.com/61964176/106107940-df307800-6147-11eb-9374-7934992a9fd2.gif)
and also on Mac OS Catalina, Safari 13.1 
![Peek 2021-01-28 09-03](https://user-images.githubusercontent.com/61964176/106108003-f53e3880-6147-11eb-8fca-542d4ce7a204.gif)
and I cannot reproduce it, but I used a BrowserStack, @jkondrat do you have any idea why it doesn't work on Safari Version 13.1.3 (15609.4.1) on Mac

**Comment by abaranowska1** [comment]
@meenupant It works fine on my Safari simulator, please check if it works on your Mac OS
