### ISSUE TITLE
Opening claim records modal takes long time when there were a couple of pages loaded

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#1673]
Description:
After loading a couple of pages of records and closing the modal, opening it again takes a long time. This also happens when opening the detail view and clicking on the back button.

Acceptance Criteria:
* The modal is responsive and renders quickly even after loading a couple of pages of records

Dev Signoffs (remove items if not applicable to this issue)
- [x] Code review passed
- [x] CI passed successfully
- [x] CodeQL scan for vulnerabilities in code has passed 
- [x] Docker images have been built and deployed to the dev server

QA Signoffs (remove items if not applicable to this issue)
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff (remove items if not applicable to this issue)
- [x] Approved for release

**Comment by abaranowska1** [comment]
**Tested with success**
The modal is responsive and renders quickly even after loading a couple of pages of records. The performance is better. 
![Peek 2021-02-02 10-35](https://user-images.githubusercontent.com/61964176/106580900-8f382380-6542-11eb-848d-43d9aea76d43.gif)
