### ISSUE TITLE
Duplicated records in the Claim modal

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#1674]
**Bug description**
I found a duplicated record example: "National Suicide Prevention Lifeline". What is more, when I click the Claim button it Claimed two records

**Screenshots/gifs**
![Peek 2021-01-28 12-35](https://user-images.githubusercontent.com/61964176/106134029-4c530600-6166-11eb-8ede-fdea545e6218.gif)
![image](https://user-images.githubusercontent.com/61964176/106134465-db601e00-6166-11eb-8ba3-ec3739cf8663.png)

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [ ] Regression test cases cycle updated if needed

Product Signoff
- [x] Approved for release

**Comment by jkondrat** [comment]
@abaranowska1 I'm no longer able to reproduce this issue, are there any additional steps I should take to see the duplicate?

**Comment by jkondrat** [comment]
@abaranowska1 I discovered that this is probably an issue with pagination - when I scrolled down to see more records and searched for something, records were appended to the existing list

**Comment by abaranowska1** [comment]
@jakeab 
Still, we can see duplicated records.
![Selection_994](https://user-images.githubusercontent.com/61964176/106456713-3313c780-648e-11eb-8db6-1bd86f576076.png)
![Selection_993](https://user-images.githubusercontent.com/61964176/106456718-33ac5e00-648e-11eb-9133-eca01fdf9ef3.png)

**Comment by jkondrat** [comment]
@abaranowska1 it turns out that there's another issue with the backend endpoint, it returns the same records on different pages; I'm on it

**Comment by abaranowska1** [comment]
**Tested with success**
I cannot reproduce it anymore. It seems that all duplicated records were fixed.
