### ISSUE TITLE
Deleting locations doesn't delete referals to that location

### ISSUE THREAD

**Issue by kdondziak** [benetech/ServiceNet#1675]
**Bug description**
https://benetechservicenet.org/#/record/5fe152b5-9a59-4b9b-817a-b621cabedf13/edit throws Internal server error

**To Reproduce**
1. Create organization A with 1 or more location
2. Refer to this location
3. Open this Organization and delete that location
4. On edit error is thrown

**Actual result**
500 Error is thrown 

**Expected behavior**
Error is not thrown, referral with deleted location is removed

**Screenshots/gifs**
![image](https://user-images.githubusercontent.com/52406204/106161555-723cd280-6187-11eb-9e63-20e5c98e710b.png)

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested
- [x] Regression test cases cycle updated if needed

Product Signoff
- [x] Approved for release

**Comment by abaranowska1** [comment]
**Tested with success**
- The 500 ISE is not thrown after we remove all locations from the referred organization 
![Peek 2021-02-02 10-15](https://user-images.githubusercontent.com/61964176/106586121-5d29c000-6548-11eb-9519-d05d251ffc27.gif)
