### ISSUE TITLE
The internal Server error is thrown after login to the app and scroll the homepage

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#1687]
**Bug description**

The internal Server error is thrown after login to the app and scroll the homepage

![Selection_999(013)](https://user-images.githubusercontent.com/61964176/106726020-3cc23a00-660a-11eb-8a89-b77c56eb5465.png)
![Selection_999(012)](https://user-images.githubusercontent.com/61964176/106726026-3e8bfd80-660a-11eb-9ba4-970669968433.png)

{type: "https://www.jhipster.tech/problem/problemwithmessage", title: "Internal Server Error",…}
detail: "ServiceNetAuthClient#getUser(String) failed and no fallback available."
message: "error.http.500"
path: "/api/all-provider-records"
status: 500
title: "Internal Server Error"
type: "https://www.jhipster.tech/problem/problemwithmessage"

**To Reproduce**
1. Log in to the app as provider 
2. Quickly scroll down the page 

**Actual result**

I noticed that after logging in and quickly scrolling the page down, the page freezes for a moment, we can see an issue with loading and after a while, it throws Internal Server Error

**Expected behavior**
Scrolling the page without error 

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [x] Passes Acceptance Criteria
- [x] All bug reports fixed/merged/tested

Product Signoff
- [x] Approved for release

**Comment by jkondrat** [comment]
@johnhbenetech Is it okay to disable the task that removes auth users afters 3 days without activation? 
It seems that one of the users got deactivated and the task picked him up for removal. The issue is that it only removes users from auth service and the user profile is still there causing ISE. 
If we still want it, we can move it to the core service

**Comment by johnhbenetech** [comment]
@jkondrat I'm not sure which task you are talking about? Is it basically just the session timeout?

**Comment by jkondrat** [comment]
@johnhbenetech there was no task for it, but the users that haven't verified their email are removed after 3 days by default (in JHIpster's generated UserService)

**Comment by johnhbenetech** [comment]
@jkondrat ok. Yes it's fine to keep users

**Comment by abaranowska1** [comment]
**Tested with success**
After login and quickly scrolling the page down the internal server error is not thrown.
