### ISSUE TITLE
Rewrite ImportService

### ISSUE THREAD

**Issue by kcissewski** [benetech/ServiceNet#170]
ImportService needs to share methods for:
1. saving an organization
2. saving service
3. saving location
4. saving taxonomy

Each of the above methods should take parent entity that contains all data that need to be persisted. On this basis, ImportService will persist all entities. 

Test for ImportService must be changed.

**Comment by oskarhinc** [comment]
In code, it seems like it should work, but we need to do the referenced issues to verify each of the providers:

- [ Adjust logic of LAACDataAdapter to new ImportService implementation #171 ](/benetech/ServiceNet/issues/171)
- [ Adjust logic of HealthleadsDataAdapter to new ImportService implementation #172 ](/benetech/ServiceNet/issues/172)
- [ Adjust logic of ShelterTechDataAdapter to new ImportService implementation #173 ](/benetech/ServiceNet/issues/173)
- [ Adjust logic of SMCConnectDataAdapter to new ImportService implementation #174 ](/benetech/ServiceNet/issues/174)
- [ Adjust logic of iCarolDataAdapter to new ImportService implementation #175 ](/benetech/ServiceNet/issues/175)

**Comment by wojtekbu** [comment]
https://github.com/benetech/ServiceNet/issues/176 main issue
