### ISSUE TITLE
Adjust logic of LAACDataAdapter to new ImportService implementation

### ISSUE THREAD

**Issue by kcissewski** [benetech/ServiceNet#171]
This ticket has to be done after #170 

Since ImportService will change we need to adjust logic to the new implementation.

**Comment by wojtekbu** [comment]
I have tested uploading data using LAAC real data orgs.csv from the repository and it works fine

**Comment by wojtekbu** [comment]
https://github.com/benetech/ServiceNet/issues/176 main issue
