### ISSUE TITLE
Adjust logic of HealthleadsDataAdapter to new ImportService implementation

### ISSUE THREAD

**Issue by kcissewski** [benetech/ServiceNet#172]
This ticket has to be done after #170 

Since ImportService will change we need to adjust logic to the new implementation.

**Comment by wojtekbu** [comment]
I have tested it on the Healthleads real data from 2019-01-02 and it works fine

**Comment by wojtekbu** [comment]
https://github.com/benetech/ServiceNet/issues/176 main issue
