### ISSUE TITLE
Adjust logic of iCarolDataAdapter to new ImportService implementation

### ISSUE THREAD

**Issue by kcissewski** [benetech/ServiceNet#175]
This ticket has to be done after #170 

Since ImportService will change we need to adjust logic to the new implementation.

**Comment by wojtekbu** [comment]
I have tested it on iCarol API data for Eden for period 2019/02/10-2019/02/18 and it works fine

**Comment by wojtekbu** [comment]
https://github.com/benetech/ServiceNet/issues/176 main issue
