### ISSUE TITLE
Save all related entities along with Organization

### ISSUE THREAD

**Issue by kcissewski** [benetech/ServiceNet#176]
Right now all entities are saved in a separate transaction. We need to change implementation and save all entities related in one transaction.
This story is the implication of #162 work.

We have to rewrite ImportService to meet above specification. After this, we will have to make changes in each provider's DataAdapters.

Tickets in this story:
#170
#171
#172
#173
#174
#175

**Comment by oskarhinc** [comment]
@wojtekbu I've verified if everything was done properly in the scope of this story, and made some final fixes. I think all should work properly now, but please take a look as well after https://github.com/benetech/ServiceNet/pull/250 will be merged, and before closing this story.
