### ISSUE TITLE
Make the home page pageable

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#187]
If there are many conflicts found for the provider, the home page loads too slow. There should be pagination for the activities to display.

UPDATE 02/15/19:
* a user should always see how many activities are displayed and what is the total number of them,
* pagination should be implemented as a button 'see xyz more' at the bottom https://user-images.githubusercontent.com/12927553/48443971-55f41d00-e758-11e8-96ad-6596c7a6092c.png
* add infinite scroll instead of button if possible

**Comment by wojtekbu** [comment]
@oskarhinc Here is a PR for that feature https://github.com/benetech/ServiceNet/pull/245
Could you test it after review?

**Comment by oskarhinc** [comment]
@wojtekbu the pagination can't be done on the front-end side as it doesn't speed loading the records at all. All records are loaded anyway and it took too long. The infinite scroll would look really cool but we should indicate the user that more records are loading, or it could be omitted if it would load really fast, but for now, I think it's confusing for the user that not all records were loaded, and he has no possibility to load more. The best performance we could achieve with using pagination on the DB but as we have to create the records on the fly I think it's fine to just do it within the algorithm manually.

**Comment by oskarhinc** [comment]
I confirm it's working well, but I think it would be nice to indicate that the records are loading, as at the beginning for a few seconds the user only sees 0/0. Also maybe we could decrease the number of fetched records to 5 or so? However, I don't know if that's a priority now. 

@johnhbenetech could you verify if that satisfies you, or you would like us to change something?
