### ISSUE TITLE
Add pagination to all entity pages that require it

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#199]
For the admin entity pages that we expect to have 100s+ results we should add pagination to prevent performance issues

I imagine this would include almost all entities

This doesnt need to be prioritized as for the pilot I can use SQL to search/find info i may need.

**Comment by mariaogryczak** [comment]
@johnhbenetech 
How many results should be on one page?
Do you have any requirements to displaying page numbers? Here are some suggestions:
http://vayser.github.io/react-js-pagination/

**Comment by johnhbenetech** [comment]
@mariaogryczak I *think* jhipster actually has this built in in some way - it may just need to be enabled:

https://www.jhipster.tech/creating-an-entity/#pagination


If not, the default styling is fine and we can do 100 items per page

**Comment by mariaogryczak** [comment]
@johnhbenetech 
Taking into consideration, how many records are now displayed in each entity, I suggest to divide it like this:
Pagination:
Shelter
Beds
Option
Organization
Service
Document Upload
Contact
Service at Location
Location
Physical Address
Postal Address
Phones
Regular Schedule
Holiday Schedule
Funding
Eligibility
Required Documents
Language
Accessibility for Disabilities
Service Taxonomy
Taxonomy
Organization Matches
Opening Hours
Conflict
Organization Error
Data Import Reports
Geocoding Results
Match Similarity

No pagination:
System Account
Program
Service Area
Payment Accepted
Metadata
Field Exclusion
Location Exclusion
Exclusions Config

Although we think that all of the entities visible for users should have pagination (just in case, for the future).
Should I add it to all of them or just this from the group 'pagination'?

**Comment by johnhbenetech** [comment]
The pagination group you outlined seems to be the right list, lets start with those

**Comment by bognasoldev89** [comment]
Back buttons (browser's and application's) don't work after changing number of items per page.
Examples:

![pagination back button doesn't work](https://user-images.githubusercontent.com/51324797/62767201-74dbd180-ba94-11e9-938e-4cb9412ce7d4.gif)

![pagination back button from details](https://user-images.githubusercontent.com/51324797/62767399-ddc34980-ba94-11e9-8fe6-fdd846645a32.gif)

**Comment by bognasoldev89** [comment]
I checked pagination feature again and it works fine now. Example of back/forward action:

![pagination back-forward works good](https://user-images.githubusercontent.com/51324797/63779826-84a64300-c8e7-11e9-8d43-2e05fe8c8839.gif)
