### ISSUE TITLE
Add all available information to side-by-side comparison view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#200]
We need to allow the side by side view to display all available information for each partner's record (even if that entity isnt available for both partners). Right now it seems to be only a select few fields based on our ability to detect conflicts.

**Comment by johnhbenetech** [comment]
I'm moving this priority up based on some early user testing. I like how the single record view looks (how it includes all the entities) we should have this same type of view for all side by side records.

**Comment by oskarhinc** [comment]
@wojtekbu Could you review https://github.com/benetech/ServiceNet/pull/285 and then test this task, please?

**Comment by johnhbenetech** [comment]
@oskarhinc @wojtekbu Please review #286

**Comment by wojtekbu** [comment]
Works fine
