### ISSUE TITLE
Add additional info to single record view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#201]
I believe we should also display all available information for a single record view of a partner (even if we don't have the capability to detect conflicts for that field).

I believe this will help users to understand the system better and see that we have their full records in our system. All related entities should appear under headers

for example:

Organization
-org fields

Locations
-Location 1
-- location 1 fields
-Location 2
--location 2 details

Contacts
-Contact 1
-- contact 1 details
--Phones
---Phone 1
-Contact 2
--contact 2 details

Services
-Service 1
--Service 1 details
--Schedules
---Schedule 1
---Schedule 2

etc. etc.

**Comment by wojtekbu** [comment]
'See another recor'd for location does not update the view

**Comment by wojtekbu** [comment]
@oskarhinc  There are errors in translation for singleRecordView.details.noRecords (Funding) and  singleRecordView.details.title (side-by-side-view)
![screenshot from 2019-02-23 17-01-13](https://user-images.githubusercontent.com/7571152/53288868-6d4a9980-378e-11e9-8801-daa1966ca966.png)
![screenshot from 2019-02-23 17-10-18](https://user-images.githubusercontent.com/7571152/53288869-6facf380-378e-11e9-9a26-93201a3a65dc.png)

**Comment by oskarhinc** [comment]
@wojtekbu I've fixed the translations in PR https://github.com/benetech/ServiceNet/pull/276

**Comment by wojtekbu** [comment]
@oskarhinc works fine
