### ISSUE TITLE
Ensure all partner records are displayed in multirecord view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#204]
This may be the case already, but i need to check.

The multirecord screen should display all records for the logged in partner (regardless if matches/conflicts exist for that record). This will help with clarity of the platform, and we may add features to these records in the future. Sorting on all views/filters should sort these record last (behind those records with recent activity/matches/conflicts/etc)

**Comment by wojtekbu** [comment]
Works with H2, we need to adjust it to psql.

**Comment by oskarhinc** [comment]
Confirm that it also works for psql after @wojtekbu's fix
