### ISSUE TITLE
Allow the data upload to work across all popular systems and browsers

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#213]
File upload page detects files as a wrong type for some browsers/operating systems.

**Comment by oskarhinc** [comment]
I confirm it's working well now. 
@johnhbenetech can you confirm as well before we close it?

**Comment by johnhbenetech** [comment]
@oskarhinc @kcissewski Still no luck from my side. I'm using master branch latest commit 2413075.

I tried on my local machine as well as on a version deployed to production web. Using windows, neither chrome nor firefox recognized CSV as a valid format (same error as before).

How are you testing this on your side? Do you have a windows machine? Are you running the Docker containers? Do I need to sync to a different commit?

**Comment by oskarhinc** [comment]
We were running it on our Linux machines and connecting with them remotely from Windows. For us, the problems were resolved after @kcissewski but if it's not working for you I'm afraid we would have to do much more cross-platform testing to ensure it will work for all users, so we can't rely on the MIME type here. We thought it's a better approach as for Linux you don't have to specify the file type with an extension. 
As the file names are rather going to be constant, can we assume for now that the extensions will be always provided? We're going to do it for now, so it won't block you, but if you think we should rather use the MIME type, I think we can revisit it after the top priority issue will be done.

**Comment by oskarhinc** [comment]
And according to the question "Do I need to sync to a different commit?" - the master branch contains all fixes now, and the newest commit is `1bb07bebea6b18f2e476a98ba83e3e7d8de028e6`

**Comment by johnhbenetech** [comment]
@oskarhinc thats fine to skip MIME right now. I haven't pulled the latest changes yet, but when i use my Linux VM to attempt to upload the LAAC data from the data repo - it passes the filetype check, but fails during upload:
![image](https://user-images.githubusercontent.com/12927553/52729921-c725b500-2f7f-11e9-8164-6df04a78628d.png)

Can you confirm this works from your side on Linux? I'll pull the latest changes and try again on both OS, but I worry this may big a bigger, nastier issue (encoding, line endings, something AWS is doing when passing requests, etc)

**Comment by oskarhinc** [comment]
@johnhbenetech sure, I'll verify it tomorrow morning. Have you selected the delimiter for the uploaded file?

**Comment by johnhbenetech** [comment]
@oskarhinc OMG! I thought it wasn't required haha. My bad. Confirmed working on Linux now.

I'll sync to latest version, confirm on windows (making sure to select delimiter!) and then close this task. Ill open the MIME type revisiting and put it in the backlog to address later.

Thanks!

**Comment by oskarhinc** [comment]
@johnhbenetech happy to help! I'm glad to hear it's working!
