### ISSUE TITLE
Fix fetching data with API Jobs

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#215]
Investigate the issue with fetching API Jobs. The errors which occurred:
`2019-02-08 23:53:29.598 ERROR 8 --- [ryBean_Worker-5] org.quartz.core.JobRunShell              : Job DEFAULT.Eden Data Update Job threw an unhandled Exception: 
2019-02-08T23:53:29.598997700Z 
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.benetech.servicenet.domain.Location.accessibilities, could not initialize proxy - no Session`
 and 
`2019-02-08 23:53:29.606 ERROR 8 --- [ryBean_Worker-5] org.quartz.core.ErrorLogger              : Job (DEFAULT.Eden Data Update Job threw an exception.
2019-02-08T23:53:29.608153500Z 
org.quartz.SchedulerException: Job threw an unhandled exception.
at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.benetech.servicenet.domain.Location.accessibilities, could not initialize proxy - no Session`

The problem might be related to updating the data, and occured using production docker.

**Comment by wojtekbu** [comment]
Works fine
@johnhbenetech can you confirm it on the production as well before we close it?

**Comment by johnhbenetech** [comment]
@wojtekbu @oskarhinc ShelterTech isn's working in local or my prod web. Synced to latest master commit, running via Docker.

For Sheltertech i get the following:
![image](https://user-images.githubusercontent.com/12927553/52680010-9b152000-2efc-11e9-983d-6c215036c1e7.png)

The iCarol jobs seem to be running ok. I completed the eden job in it's entirety, I'm waiting for results on uwba now, will update if experience any issues

**Comment by johnhbenetech** [comment]
Ok UWBA failed as well, it got through all 4 steps of the collection, then failed 13% through the saving of the data.

![image](https://user-images.githubusercontent.com/12927553/52686768-cf94d600-2f14-11e9-8824-31c9a52864e6.png)

Theres also some references later to type issues:
![image](https://user-images.githubusercontent.com/12927553/52686803-f3581c00-2f14-11e9-903c-fab4c670560a.png)

**Comment by oskarhinc** [comment]
@johnhbenetech thanks for stack traces. I'm working on UWBA fix, but ShelterTech server seems to be broken for now - we're getting Internal Server Error as a response for our requests. I'll add a check of the response status so it will be clear when we won't be able to connect with any external API.

**Comment by oskarhinc** [comment]
@johnhbenetech I've encountered the same problem while importing the UWBA data today, and already fixed it. It occurs that we expected shorter strings for two columns. I hope that we'll cover all cases until the error handling is finished. I have run both Eden and UWBA jobs today on the docker environment once again to make sure it will work for you, so I hope it will be finished successfully.
