### ISSUE TITLE
Adjust ICarol Data Adapter and Mapper

### ISSUE THREAD

**Issue by wojtekbu** [benetech/ServiceNet#216]
All issues with the complete and missing data adapter/mapper should be found in classes: ICarolDataAdapterCompleteTest and ICarolDataAdapterMissingTest. There are some tests marked 'Ignore' to point out what should be corrected. After this issue is done, none of those should be ignored anymore.

**Comment by awalkowiak** [comment]
LGTM

**Comment by johnhbenetech** [comment]
This change caused a checkstyle failure for me:
\src\main\java\org\benetech\servicenet\adapter\icarol\ICarolDataMapper.java:77: Line is longer than 125 characters (found 127). [LineLength]

**Comment by johnhbenetech** [comment]
@pmuchowski can you review this?

**Comment by pmuchowski** [comment]
the checkstyle issue was fixed
