### ISSUE TITLE
Ensure that entities like Opening Hours are not detached

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#220]
It seems like in some cases entities like OpeningHours has relation no with Regular Schedule or HolidaySchedule either. We need to verify this and add a proper logic to the ImportService. We also need tests verifying if it works properly for the future and other entities ( like Phones, Languages, and other list based)

**Comment by oskarhinc** [comment]
Additionally, we need to determine if we want to store historical data for some purposes, or we can get rid of them, as we have metadata anyway. Based on the decision, we need to add the same cascade removal for detached entities and test it well.

**Comment by johnhbenetech** [comment]
Closing this as obsolete
