### ISSUE TITLE
Adjust healthleads Data Adapter and Mapper

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#223]
All issues with the complete and missing data adapter/mapper should be found in classes: HealthleadsCompleteDataAdapterTest and HealthleadsMissingDataMapperTest. There are some tests marked 'Ignore' to point out what should be corrected. After this issue is done, none of those should be ignored anymore.

**Comment by awalkowiak** [comment]
LGTM

**Comment by johnhbenetech** [comment]
This change caused a checkstyle failure for me:
\src\main\java\org\benetech\servicenet\service\impl\ServiceImportServiceImpl.java:57:64: ',' is not followed by whitespace. [WhitespaceAfter]

Line 57 has the comma with no space

@pmuchowski please review

**Comment by pmuchowski** [comment]
@johnhbenetech I pushed a PR, I thought the checkstyle runs with the tests when I use `./mvnw test`.

**Comment by pmuchowski** [comment]
the checkstyle issue was fixed
