### ISSUE TITLE
Add activity log to single record view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#24]
This should include a list of historical updates by partner systems

![image](https://user-images.githubusercontent.com/12927553/48446782-d10d0180-e75f-11e8-92c7-8d6f6a419334.png)

Clicking the 'See Full' or Activity tab at top:
![image](https://user-images.githubusercontent.com/12927553/48446805-e71ac200-e75f-11e8-87bb-69befcaf4947.png)

**Comment by NeilMBenetech** [comment]
@johnhbenetech similarly, you moved this back to the Product Board in January. Does it need some refinement? I think it's a good idea and we should categorize it and move to Ready For Dev.

**Comment by johnhbenetech** [comment]
@NeilMBenetech related to #325 

You can prioritize and combine as you see fit
