### ISSUE TITLE
Add side-by-side compare to single record view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#25]
In side panel add an overview of matches in partner systems:

![image](https://user-images.githubusercontent.com/12927553/48446869-1e896e80-e760-11e8-8ae5-2b976718ada2.png)

Clicking, always shows logged in user's record on left - matching record (complete original record, with normalized fields where possible) on right. When there are multiple matches, the user should be able to flip between records on the right side. We should have a feedback mechanism for each match allowing a user to manually remove a match when they think it's wrong - this should remove the match relationship in our DB (and maybe negate weights if we ever get to ML)

![image](https://user-images.githubusercontent.com/12927553/48446921-36f98900-e760-11e8-94a2-3132ad87e61c.png)

**Comment by oskarhinc** [comment]
@johnhbenetech how about approving the matches? Should it trigger any action?

**Comment by johnhbenetech** [comment]
@oskarhinc not sure. I don't think anything directly at this time. What do you think about adding a column to the matches table just to track this? If we ever revisit the matching algorithm using ML this would be useful

**Comment by oskarhinc** [comment]
It seems like a good idea. We can also leave the relationships if uses choose "No", but just switch the "status" of the match, so if we'll ever switch to ML, the records won't be lost.

**Comment by johnhbenetech** [comment]
completed under #113 

other issues logged separately #203
