### ISSUE TITLE
Optimze location matching algorithm

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#261]
Request to the Google API are done too often, so the location matching is taking too long. Additionally,  the location matching might be the cause of problems with the heap size. The algorithm should be optimized.

**Comment by oskarhinc** [comment]
@wojtekbu after the latest improvements, the algorithm should work much faster. Please review: https://github.com/benetech/ServiceNet/pull/278

**Comment by wojtekbu** [comment]
@oskarhinc works fine
