### ISSUE TITLE
Fix user removal

### ISSUE THREAD

**Issue by wojtekbu** [benetech/ServiceNet#266]
Remove metadata DB constraint for a user. The user is related to all the documents which he/she uploaded.

org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [fk_metadata_user_id]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by wojtekbu** [comment]
@oskarhinc here is a PR https://github.com/benetech/ServiceNet/pull/282
Could you test it afterward?

**Comment by oskarhinc** [comment]
I confirm it's working properly now (on dev branch)
