### ISSUE TITLE
Fix upload data for providers

### ISSUE THREAD

**Issue by wojtekbu** [benetech/ServiceNet#269]
An ordinary user with assigned provider account should be able to upload data. At this point, data is uploaded but the backend cannot determine which provider adapter it should use.

**Comment by wojtekbu** [comment]
@oskarhinc could you test it? please remember to check both the admin and user perspective. For admin try to upload data with provider name assigned to admin's account and without

**Comment by oskarhinc** [comment]
I confirm all scenarios are working now (on the dev branch)
