### ISSUE TITLE
Remove or improve cache when entering to the sinlge record view

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#275]
1. Have multiple activities on the home page
2. Enter one of them
3. Go back to the home page
4. Enter another one of them
5. Proper data should be loaded. Instead, the previous record is visible, and the page needs to be refreshed to show proper data.

**Comment by oskarhinc** [comment]
This might be problematic for basic user workflow, so I've put it on the top of 'Up next'

**Comment by johnhbenetech** [comment]
Thanks! I agree with the priority. I noticed it yesterday during testing (it also seems to persist across logout/logins)

**Comment by oskarhinc** [comment]
@wojtekbu I've fixed it in PR https://github.com/benetech/ServiceNet/pull/281 , could you review and test it?

**Comment by wojtekbu** [comment]
@oskarhinc  works fine
