### ISSUE TITLE
Single page search results clear when scrolled to bottom

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#289]
I've noticed if I enter a search term that only results in one page of results (13/13 for instance) if I scroll to the bottom of the page, the results disappear. Sorting brings them back - after a sort it doesnt repeat until you clear the term and search again. No log output. Video:

https://drive.google.com/file/d/1Z1uJSqL7WF6lswsrTttCFhod-2MKhtHC/view

**Comment by kkrawczyk123** [comment]
I wasn't able to reproduce the issue. Confirmed that fixed.
