### ISSUE TITLE
Updating data causes several issues that cause fatal errors

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#291]
Steps to reproduce:
* Start from an empty database
* Take a recent copy of SMC data and import, wait for import process to finish
* Take a recent copy of LAAC data and import, wait for import process to finish, wait for conflict detection to finish

* Make smc user, Log into smc user, note a single matching organization with conflicts, note the name of the matching record for LAAC. Note a specific conflict (such as URL) and note the last updated timestamp

* make LAAC user and log in. See that records display and platform roughly works

* Go back to the LAAC spreadsheet. Find that record that matched above. Update the field involved in the conflict that you noted above (such as URL) to something else.

* Reupload the LAAC data to the platform, wait for processing to complete, wait for conflicts to finish

ISSUE 1: log in to smcuser. find the record from above. Note: date update field has not changed to reflect last update time (from the second upload).

ISSUE 2: From issue 1, conflicts have not updated to reflect new data. Existing conflicts still represent old data value (old URL value, old date updated value). Even looking at direct query of conflict db reveals no new conflicts being created for this record. Looking at side-by-side view, however, the data has been updated for the matching record to reflect the new value (even though a conflict hasnt)

ISSUE 3: logout, and log back in as laacuser. A fatal ISE occurs rendering the platform useless for this user. The error seems to reference being unable to find a reference (even though everything worked after the first upload). I have to assume then that the platform is expecting something from the first version of the record that no longer exists. I haven't gone as deep as to ensure each entity's ID remains consistent across updates (and maybe it shouldn't if the approach is just to make a new entity). But the log below seems to indicate that maybe a Contact entity couldnt be found. There was no more log activity following that so I think it killed any subsequent attempt to display records.

javax.persistence.EntityNotFoundException: Unable to find org.benetech.servicenet.domain.Contact with id ce59cfb3-eed7-4610-afc2-dafdd874cc8e

**Comment by wojtekbu** [comment]
Hi, @johnhbenetech I figured it out how to handle ISSUE 3. I'm working on two others, but I want to make sure that we both have the same organization-match-threshold value, which is 1.0 in my env.

**Comment by johnhbenetech** [comment]
@wojtekbu yes I'm using 1.0. I did set the always location option to false, because I was having performance issues when it was on

**Comment by johnhbenetech** [comment]
@wojtekbu @oskarhinc This still isn't working as intended.

Same test as above. Import two partners' data. Wait for conflicts to complete, note the record involved in a specific conflict. Go back to source data, change a value involved in the previously noted conflict. Reupload the data, wait for conflict detection to finish.

For this test I used LAAC and HealthLeads. A conflict in URL on 'Record A' was found. I then changed the URL in the healthleads record to something entirely different (and reimported). 

### Only new data should change updated date
ISSUE 1 & 2: Several things still aren't working here.

Expected behavior:
* After the very **first** time uploading data, all records would be marked as updated at the time the record was created (let's call it 'Time1')
* Any conflicts that were found would be marked as having occured at the time the conflict was created  
* After changing a single field in a single record and reuploading, **only that single record** should have any change in updated date and conflict date.

All **other** records that had no values changed, should remain with an unchanged updated/conflict time (Time1).

We need this to work so that if a user sorts by recently updated, they see the records that have been changed in a partner system since the last upload closer to the top. If the data from the import/API exactly matches the data already in the database, the date updated shouldn't change.

Current Behavior:
* Existing conflicts are entirely rejected and replaced with entirely new set of conflicts. This makes it look like every record is being updated every time despite no data actually changing.

### Old Conflicts still persist

In the above example, I changed URL1 -> URL2.

While a new conflict is created (for URL2), I still see an old conflict for URL1 (only one of the old conflicts was rejected laac->healthleads, whereas the healthleads-> laac version of the old conflict still exists)



### ISE still occurs
ISSUE 3 still persists. For example i changed a single value in a healthleads CSV, and reuploaded the entire set. After processing this second change, if i try to log in as a helathleads user i get a fatal ISE:
 Internal Server Error javax.persistence.EntityNotFoundException: Unable to find org.benetech.servicenet.domain.Language with id 9e0aa277-3767-49b8-9147-d6ad930cfa20 at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:159)

**Comment by wojtekbu** [comment]
@johnhbenetech the fixes for old conflicts which still persist and ISE for a non-existing entity are available on dev branch. The ISE is a little bit tricky to reproduce, but I believe I have resolved it.

**Comment by johnhbenetech** [comment]
@wojtekbu ok I tested it. Yeah the ISE is a bit weird. Here's what I'm noticing:

* Upload LAAC and Healthleads recent dump, wait for matching and conflicts
* Find an existing match and conflict
* Go to LAAC spreadsheet and make change to that field from conflict
* Reupload LAAC data

Ok so now I wait until I think conflict detection is completed (it's been a few minutes since last log entry). When I try to log in as a LAAC user I get the fatal ISE (log returns that it can't find a specific entity, usually it's some nested entity like a contact or a phone)

Then I just left it alone for like 30-60minutes. When I tried to log in as LAAC user, it works fine now?

Any thoughts what might be happening? Is there some sort of two step process with old entity clean up or old conflict cleanup? If I'm not waiting long enough for conflict detection to complete is this expected behavior? Is I look at a record after organization match but before conflict detection does it make sense that I would be getting ISE? Is it some weird cache issue that might get resolved once a cache clears in time?

If its not cache related, I guess one thing to explore might be on the method that pulls the records for the main page. Putting some sort of try/catch and skipping the display of a record with missing entities (instead of killing the whole process). 

Any thoughts?

**Comment by wojtekbu** [comment]
@johnhbenetech it could be cache on  SQL view activity_view. I'll check that

**Comment by wojtekbu** [comment]
@johnhbenetech I have tried to reproduce this bug for both:
- LAAC & SMCConnect data and LAAC & HelthLeads data,
- commit 14084e9340c78eec6b416de1d7b3a2761e07a81f and 1ac71d2f07e4b622a18d3a9cae017719e7202902 (last two commits).
Unfortunately, I cannot reproduce this bug since 14084e9340c78eec6b416de1d7b3a2761e07a81f. I will need: 
- database dumps of PostgreSQL and MongoDB before re-upload,
- LAAC's modified CSV file,
- commit id on which the error appeared.

I can add volumes to the docker-compose config for both PostgreSQL and MongoDB containers, to make it easier to make those database dumps. Would it be helpful?

**Comment by johnhbenetech** [comment]
Closing this for now with separate task #396
