### ISSUE TITLE
Display last update date on side-by-side view

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#296]
Make it clearer when record was last updated in side by side view

**Comment by laurabenetech** [comment]
@CloVasco 
Here are a two designs for the “last updated” Side by Side view.
The extra text makes the “See another match” option less noticeable, so I did an alternate design with a colored button. LMK what you think. 

<img width="545" alt="Last updated SbSide w button" src="https://user-images.githubusercontent.com/48697326/54788668-17321000-4bed-11e9-8db8-4aa267b2c6e7.png">
<img width="541" alt="Last updated SbSide" src="https://user-images.githubusercontent.com/48697326/54788675-1e591e00-4bed-11e9-90fb-b0bce2096a8a.png">

**Comment by CloVasco** [comment]
Thanks @laurabenetech . I like your new design as the current "see another match" is not very noticeable. 
over to you @johnhbenetech

**Comment by johnhbenetech** [comment]
After #359 this task should list the latest audit record date for the currently displayed partner record

**Comment by kkrawczyk123** [comment]
Confirmed that Last updated date is visible on the ui of all matches on side by side pages. However, I was not able to verify if the Last updated date is updating correctly according to the issue with the upload reported in https://github.com/benetech/ServiceNet/issues/412. I will be back to verify that.
