### ISSUE TITLE
Enhance search feature - category

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#297]
enable users to search by:
-category - food, homelessness

Question - should be through search or filter??
-How to use taxonomy?
-Which list should we use - they can use an unlimited list or we give them a specific list?

**Comment by NeilMBenetech** [comment]
Hi @CloVasco , can this one be closed/discarded because it is a duplicate of this one https://github.com/benetech/ServiceNet/issues/531 , which has more detail in it?

**Comment by CloVasco** [comment]
@NeilMBenetech yes. you are right

**Comment by NeilMBenetech** [comment]
Closed as a duplicate.
