### ISSUE TITLE
Advanced search features - misspellings, exact phrase, etc

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#299]
-common mispellings
-wildcard search 
-Ability to be very targeted by including words in quotes. For example: “health” in quotes wouldn’t include heal, but health without quotes would.
-on other info such as phone numbers, etc

**Comment by NeilMBenetech** [comment]
Renamed this item to be more specifically focused on misspellings and exact phrases. "Wildcard search" I'll split into its own task. "Other info such as phone numbers" already incorporated into another task.
