### ISSUE TITLE
Create data file upload screen

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#3]
There should be available data file upload page. For authorized users, link to this page should be visible in a navbar. The user should be allowed to select a file using file dialog or drag it into the page. After the file is loaded, there should be a button to confirm its upload available, but no action has to be attached to the button at the moment.

**Comment by pgesek** [comment]
@oskarhinc lets hold this of for a day or two

**Comment by pgesek** [comment]
@oskarhinc there are tslitn errors in the upload screen

**Comment by oskarhinc** [comment]
@pgesek Those errors should be fixed with the last PR. I believe it's working now

**Comment by wojtekbu** [comment]
- data file upload page - OK,
- for authorized users, link to this page should be visible in a navbar - OK,
- the user should be allowed to select a file using file dialog or drag it into the page - OK,
- after the file is loaded, there should be a button to confirm its upload available - OK,
- an admin should see a dropdown which allows him/her to choose a provider - OK.

**Comment by wojtekbu** [comment]
Works fine
