### ISSUE TITLE
Add text to explain the search button

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#300]
Include friendly text on search page indicating what users can search on.
by org name or acronym +  altername name will be added

**Comment by laurabenetech** [comment]
@CloVasco Let me know if this covers the new search capabilities or if I missed anything.
<img width="413" alt="Search New Prompts" src="https://user-images.githubusercontent.com/48697326/54947582-e48f5c80-4ef7-11e9-92d7-a2eeb8b7d41d.png">

**Comment by CloVasco** [comment]
Thanks @laurabenetech 
I talked with both you and John about it. Decision - keep alternate name but not acronym. I updated the other search task as well. 
Then your text becomes "Search by Organization Name or Alternate Name". 
Over to you @johnhbenetech

**Comment by awalkowiak** [comment]
LGTM
