### ISSUE TITLE
Hover on fields (homepage)

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#303]
Give users ability to hover on the fields such as "X has a conflicting address" or "X+5 partners have a conflicting name"

(for instance Julie wanted to be able to see the different names of the record from the homepage and not to have to click on the record if names are obviously from another org - not a good match)

**Comment by NeilMBenetech** [comment]
I think this is now obsolete as we are displaying other metadata in the search results and comparison screens to help users more quickly go to relevant records.
