### ISSUE TITLE
Hover feature: readability and ? icon

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#305]
-Consider changing the question mark icon to something more actionable. 
-Improve readability in hover feature by making the hover background less transparent.
_In hover, enable users to click on a specific record to navigate to that record?

**Comment by CloVasco** [comment]
Alex's comment when he first saw the platform: "The question marks are a bit confusing and overwhelming"

**Comment by NeilMBenetech** [comment]
The question mark icon is a little odd, I agree, but I don't have a replacement suggestion at this stage.

Here's an example showing how the background of the hover needs to be "less transparent". In fact it should be fully opaque. https://servicenet.benetech.org/#/all-records-view/e594d599-8347-4e83-b5ea-a680d80093fa

![Capture](https://user-images.githubusercontent.com/52297301/75903122-f5c63600-5df5-11ea-8a1b-5d6bf8132b36.PNG)

**Comment by kdondziak** [comment]
@johnhbenetech  @NeilMBenetech My suggestions about changing icon:
https://fontawesome.com/icons/hand-point-left?style=regular
https://fontawesome.com/icons/medapps?style=brands
https://fontawesome.com/icons/exclamation?style=solid
https://fontawesome.com/icons/comment-dots?style=regular
Feel free to add suggestion. Find icons here:
https://fontawesome.com/icons?d=gallery&m=free

**Comment by johnhbenetech** [comment]
I like the medapps one

**Comment by kdondziak** [comment]
@johnhbenetech See if it looks good for you:
![image](https://user-images.githubusercontent.com/52406204/79312989-fd522200-7eff-11ea-8213-350764b249dc.png)

**Comment by kdondziak** [comment]
@johnhbenetech I've found solid lightbulb. Please see if it fits better:
![image](https://user-images.githubusercontent.com/52406204/79313497-b9135180-7f00-11ea-856e-2b3a11859a96.png)

**Comment by johnhbenetech** [comment]
@kdondziak I like the outline version. Is it possible to reduce the padding in the Description box so the icon aligns?

**Comment by abaranowska1** [comment]
**Tested with success**
**Verified on:**  

- Firefox Version 75.0
- Google Chrome Version 81.0.4044.92
**Verified cases:**

- Question mark icon is changed to medapps icon 
![image](https://user-images.githubusercontent.com/61964176/79441724-e0891d80-7fd7-11ea-9ec1-78cba2c995af.png)
- The background of the hover is fully opaque]
![image](https://user-images.githubusercontent.com/61964176/79442048-4f667680-7fd8-11ea-88ad-6327329825ae.png)
- In hover, the user can click on a specific record and navigate to that specific record
![Peek 2020-04-16 11-52](https://user-images.githubusercontent.com/61964176/79442501-ea5f5080-7fd8-11ea-8de3-9295356889de.gif)
- Padding in the Description box is reduced - icons are aligned
