### ISSUE TITLE
side by side comparison page to monitor

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#307]
We need to monitor this possible risk: if users spend most of their time on the side-by-side comparison page, will they be less likely to remember to view records using filtering, sorting, and searching?

Recommendation: Determine how often users are staying on this page vs. the main page that includes searching and filtering.
Action item: Monitor in observations, interviews, and quantitatively (page statistics).

Recommendation: If users are spending the majority of time on this side-by-side page, does it make sense to include navigation buttons to Search from the side by side page?
Priority: Not yet determined
Action item: Team to discuss

**Comment by NeilMBenetech** [comment]
I think this has become obsolete due to a number of other related Workflow tasks that were subsequently implemented. We could revisit if partner feedback indicated we need some further refinement.
