### ISSUE TITLE
Matching: Make matching probability more visible

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#309]
Consider other ways that we can make matching more understandable to users so they can choose where to focus. For example, could we show percentage of match (90%, 20%, etc.) and allow users to focus on certain things.

Technical questions for John: 
	Can we show percent of likelihood of match?
	On main page, are we showing highest likelihood first (at top of list)? If not, is this technically possible?

**Comment by NeilMBenetech** [comment]
@johnhbenetech does our matching algorithm result in a numeric score or probability, or is it just "match or no match" ?

**Comment by johnhbenetech** [comment]
@NeilMBenetech It has several sub scores (%) that are weighted and added up. So we have % similarity name, % similarity locations, etc.

So yes eventually it rolls up into a single number.

**Comment by bognasoldev89** [comment]
@jkondrat Match similarity is displayed and it looks good, but can you investigate logic in it? Sometimes it shows 0% (why?) and it's not ordered in any way:
2 exemplary gifs:

![399 no logic in matching](https://user-images.githubusercontent.com/51324797/69148187-ff8c8d80-0ad3-11ea-9267-c38f4d72c66b.gif)

![399 no logic in matching 2](https://user-images.githubusercontent.com/51324797/69148189-ff8c8d80-0ad3-11ea-8b4c-b35383699331.gif)

**Comment by bognasoldev89** [comment]
During regression testing, I spotted this unexpected error and I believe it could be caused by this feature.
@jkondrat can you please investigate?

CALL Primrose organization as hluser on staging server caused this

![unexpected error](https://user-images.githubusercontent.com/51324797/69613969-b8058480-1032-11ea-8d39-a9cd3bd14a3a.gif)

**Comment by jkondrat** [comment]
@bognasoldev89 The records on the homepage are ordered (there's a new 'sort' option) by the highest match similarity. The matches on multi-record view are ordered by "lastVerifiedOn". I have opened a pull request to address the other issue

**Comment by bognasoldev89** [comment]
@jkondrat it seems more clear now. I haven't found any match with 0%, but I found this one:

![Screenshot from 2019-12-03 11-07-49](https://user-images.githubusercontent.com/51324797/70041280-28754e00-15bd-11ea-8a18-2fd8e803c349.png)

Is there a chance to round those numbers?

**Comment by bognasoldev89** [comment]
I confirm that numbers are rounded now. I haven't found any odd numbers.

Example:
![309 working](https://user-images.githubusercontent.com/51324797/71174684-11de2080-2266-11ea-9624-2fb82eceffaa.gif)
