### ISSUE TITLE
Add their source of info (web/call/etc)

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#310]
Recommendation: include a way for partners to indicate how they got the data to update a record. (From Clotilde’s bug list: indicate call, website, site visit, etc.).
Action item: Team to discuss design ideas and technical feasibility. Consider using the Exygy mockup designs as a starting point.
Clotilde question - we know how our partners verify data (mostly through website/call/in-person contact/service providers update their record directly). The real question is how do we make it feasible and can be creative considering that no one tracks how they go the info in their own system?

**Comment by NeilMBenetech** [comment]
This was incorporated in some of the other Data Trust tasks. Most partners don't actually track the source of information (surprisingly) but we introduced the notion of a "complete review".

https://github.com/benetech/ServiceNet/issues/681

https://github.com/benetech/ServiceNet/issues/680
