### ISSUE TITLE
Allow user to add their own notes to partner records that persist across imports

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#313]
Several partners said that they would like the ability to add information that doesn’t fit into existing fields, etc. and suggested notes fields. 

Recommendation and Action item: Follow up with partners through observations/ interviews to find out what kinds of notes they would find most useful, which fields or sections might be most helped by notes, etc. Have partners prioritize and then create list for version release: where would partners like to add notes? Under what kinds of circumstances? Which fields/topics are the most important?

**Comment by NeilMBenetech** [comment]
Good idea. Let's clarify a bit,.

Add a multi-line free-text box at the bottom of each partner record you're viewing in Comparison view with the following text just above it: "Your private notes about this record (won't show to other users)"

As suggested, whatever a user saves into this free text box should be retained across database imports and should also not show to any other users. It's just a place for them to keep their own private notes.

If we see usage, we might refine this idea further, such as allowing other users to see and respond to the notes; etc.

**Comment by johnhbenetech** [comment]
@NeilMBenetech yeah this is related to #104 but private/public difference
