### ISSUE TITLE
Timestamp of latest export?

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#314]
Idea from Rick (Eden) - add to the homepage when we last imported data from pilot partners onto the SN platform.
Clotilde - not sure many beyond Rick care about that

**Comment by NeilMBenetech** [comment]
It's a good idea and would improve Data Trust.

**Comment by kdondziak** [comment]
@NeilMBenetech @johnhbenetech My suggestion is to add column on the left of the filter section with table | Partner Name | Last update Date |. How would you like that? See mockup below. Next question is about source of 'last update date'. Since we have 2 methods of updating records (upload files, scheduled jobs), what should be source of 'last update date'? Note that healthleads doesn't have job.
![image](https://user-images.githubusercontent.com/52406204/77903164-b8cd5200-7282-11ea-9a8e-3a5b284af2a4.png)

**Comment by NeilMBenetech** [comment]
@kdondziak That's a bit too prominent for me. What about another button next to "Saved Filters" called "Imported dates" and then the same table in your screen shot appears? @johnhbenetech any thoughts?

**Comment by johnhbenetech** [comment]
@NeilMBenetech I dont want to overload the main page more than it already is. Could we add a page to the header like 'Data Status' that just leads to a page with the table?

As far as date - yeah we need something that works for the iCarol APIs, ShelterTech API as well as HealthLeads, SMC, and LAAC.

I'm open to suggestions, it might be as simple as MAX(Last updated date), but that's not 100% accurate but may be ok for relative accuracy.

**Comment by NeilMBenetech** [comment]
Sure @johnhbenetech that sounds like a good approach.

**Comment by kdondziak** [comment]
@johnhbenetech @NeilMBenetech Should It be visible to non admin users?

**Comment by johnhbenetech** [comment]
Yes

**Comment by johnhbenetech** [comment]
@kdondziak Can we non show this for non logged-in users on the homepage?

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified on:**

- Google Chrome Version 81.0.4044.92 

**Verified cases:**

- Data Status table displays after click Data Status in the upper panel menu 
- Provider Name || Date of last update, updates after upload data
- Data Status is displayed for admin and regular user 
- Data status is not displayed on the homepage

![image](https://user-images.githubusercontent.com/61964176/79575494-2e7a5000-80c2-11ea-9f0d-4c796ce98a8a.png)
![image](https://user-images.githubusercontent.com/61964176/79575516-333f0400-80c2-11ea-995f-2d6dbc7e2c34.png)
![image](https://user-images.githubusercontent.com/61964176/79575553-44881080-80c2-11ea-965a-634ad5233b85.png)
