### ISSUE TITLE
User can dismiss records they've considered and dispositioned for now

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#315]
Several partners wanted ways to keep track of what they had updated, and some emphasized the importance of this feature. ”That would be extremely helpful to do this while in the [Service Net] system.” (Laurie: Eden)

Recommendation: Include a way for users to check off when they’ve updated something and also an indicator of what has been updated, and when
Priority: Not yet determined 
Action item: Team to discuss. If we decide to include this, Laura will create mockups for this feature.

**Comment by NeilMBenetech** [comment]
I can very much see the utility of this. Once in place we'd also want to refine how to find Organizations so that you could choose to exclude (by default) Organizations you've marked that you've already reviewed it, until perhaps a new change gets imported into SN.
