### ISSUE TITLE
Hiding empty fields

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#316]
Some commented on how there are a lot of empty fields displayed. They wanted the option to show/hide blank fields. Another option: have the UI hide blank fields?
Recommendation: if this is an easy UI fix, prioritize this to be high.
Priority: Not yet determined
Action item: Team to discuss with John how long this would take to implement either user initiated show/hide or system show/hide
When: Not yet determined

Important to give them the power to open of hide if they want. not hide it automatically.

**Comment by NeilMBenetech** [comment]
I think this is now less relevant than the requests for consistent spacing https://github.com/benetech/ServiceNet/issues/388 and for the user to be able to select sets of fields to show/hide. https://github.com/benetech/ServiceNet/issues/735
