### ISSUE TITLE
Expanding/contracting views

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#317]
give users a quick way to open/close views (e.g. sections such as location, services, etc.). This would enable users to quickly scan a record without having to expand each section individually
Alex's idea - create several tabs

**Comment by CloVasco** [comment]
@laurabenetech Could you please provide a visual?

**Comment by laurabenetech** [comment]
@CloVasco 
The top section “Organization details” always stays expanded.

For all other sections, the user can quickly expand/collapse all sections by clicking on the button, which toggles between Expand All and Collapse All. This button affects both sets of records (the user’s own database and the matching partner record).

Visual of Expand/Collapse sections toggle button:
Expand:
<img width="170" alt="Expand toggle" src="https://user-images.githubusercontent.com/48697326/57554372-23516880-7326-11e9-9ea3-aa5d00917355.png">

Collapse:
<img width="172" alt="Collapse toggle" src="https://user-images.githubusercontent.com/48697326/57554392-2e0bfd80-7326-11e9-8d98-6dc679c67e53.png">


Button placement is the same for single and side-by-side pages—on the LH side right under the end of the Org details section. Here’s a visual of the button placement on the side-by-side page.

<img width="673" alt="Expand Contract LH side" src="https://user-images.githubusercontent.com/48697326/57554493-73c8c600-7326-11e9-9925-9da58acc6106.png">

**Comment by CloVasco** [comment]
@laurabenetech 
@johnhbenetech over to you

**Comment by johnhbenetech** [comment]
on call we decided to show both buttons all the time for each record

**Comment by bognasoldev89** [comment]
Confirmed that button works on both single record view and multi-record view. User is able to browse matches with an expanded view.
