### ISSUE TITLE
if search, show record even if there's no conflict

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#322]
to reassure users and show them that we have their record in the SN platform but there are no other users who have a matching record

**Comment by laurabenetech** [comment]
Need quick clarification: When the user searches, we'll show an unmatched record with messaging such as: "No current partner conflicts to this record." Question: are we giving users the choice to see all their records or just the conflict matches during a search? If there's no choice, this could get unwieldy/overwhelming for those with larger databases when they search for common words. Do we want to design it without the choice (for this version) and get feedback from users? Let me know what you think.

**Comment by laurabenetech** [comment]
@johnhbenetech @CloVasco Forgot to add your names on last comment. Here is is again: Need quick clarification: When the user searches, we'll show an unmatched record with messaging such as: "No current partner conflicts to this record." Question: are we giving users the choice to see all their records or just the conflict matches during a search? If there's no choice, this could get unwieldy/overwhelming for those with larger databases when they search for common words. Do we want to design it without the choice (for this version) and get feedback from users? Let me know what you think.

**Comment by laurabenetech** [comment]
<img width="484" alt="0 partner conflicts" src="https://user-images.githubusercontent.com/48697326/54780922-3ffbda80-4bd8-11e9-9cde-64d3c104137c.png">
@johnhbenetech @CloVasco I've pasted the screenshot with the new message here. How do I indicate that this is ready for review? Do I choose "close and comment"? For now I'll just add this as a comment. Thanks, Laura

**Comment by johnhbenetech** [comment]
@laurabenetech I think we show em all at first (with the understanding that those without conflicts are sorted to the bottom).

We can then get feedback and add something to the filtering when we make those features.


Another option would be for you to give suggestions on a visual indicator (like greying out those without matches)

**Comment by laurabenetech** [comment]
@johnhbenetech @CloVasco I think the design with the text telling them there aren't any conflicts is a sufficient  indicator that there aren't conflicting records. I'm concerned that greying out could end up being tricky to read/view, so I would say to go with the text indicator for now, but LMK if either of you think differently.

**Comment by CloVasco** [comment]
@laurabenetech  @johnhbenetech I have no opinion on this. Will you send us a visual recommendation for both scenarios (1-when there's no partners' conflict and 2-when there are search results that are both matches and non-matches at the bottom)? Thanks!

**Comment by laurabenetech** [comment]
@CloVasco I added the visual (see above) for no conflict about an hour ago and notified you, but let me know if you can't see it. The search results with matches and non-matches is up and running already on Service Net and looks fine--check it out by doing a search--I don't see anything we need to change but let me know if you think differently!

**Comment by CloVasco** [comment]
@laurabenetech hadn't seen it. Sorry!

**Comment by CloVasco** [comment]
Thanks @laurabenetech . I agree - when they search, we show all the results with matches first and at the bottom the ones without matches. Over the you @johnhbenetech

**Comment by johnhbenetech** [comment]
Dev team - The records are already being displayed in the system - this task is for two things:

1) Update the visual for those records without matches to include the following:
![image](https://user-images.githubusercontent.com/12927553/55414813-81be4680-5531-11e9-8988-3574a322e5bd.png)


2) Make sure those records without matches are sorted to the bottom in all sorts

**Comment by CloVasco** [comment]
**Update of the visual**
The right side should display "0 Partner conflicts with this record" 
instead of "Last updated 03/21/19 12:32 // 0 Partner conflicts with this record"

**Comment by kkrawczyk123** [comment]
Confirmed that records without conflicts are displayed at the bottom of the page when using the search feature.
