### ISSUE TITLE
Show that record has been inactivated in the activity log

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#325]
-When a user is inactivating a record (because the service provider is not answering or it is a seasonal service), the SN platform is not going to show this record to other partners any more -- loss of information
-Add some text in the activity log so that other partners see that a previous  match has become inactivated like "UWBA inactivated the record "xx" on "date".

**Comment by NeilMBenetech** [comment]
I feel like instead we should just be showing the "status" field of records and it's just another thing users can compare. @johnhbenetech would it be a simple matter to display when SN detected a record changed its status?

**Comment by johnhbenetech** [comment]
@NeilMBenetech This was something from the early days where we thought we would have a permanent audit log displayed with each record. Obviously we can choose a subset of fields that we wish to display

It's basically a way more detailed version of last updated so you could see recent changes that might point you to which fields to focus on when you are looking at a record.

If we wanted to go forward we would need a UI recommendation

**Comment by NeilMBenetech** [comment]
@johnhbenetech let's back-burner it. This kind of auditing is super helpful in your own database system but I can't see it being heavily referred to in SN. If this emerged as a new/revived idea I think you would say we could retroactively construct these logs since we have all the source data.

**Comment by johnhbenetech** [comment]
@NeilMBenetech Seems to be the same as #24 to me. Let me know what you see as the difference that makes one a better idea than the other
