### ISSUE TITLE
“About Us” page

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#327]
add the about us page with this text
https://benetech.app.box.com/file/411257100653

**Comment by CloVasco** [comment]
@laurabenetech - Attached the text for the About Us Page (it's also there-https://benetech.app.box.com/file/411257100653 ). 
I think it should be accessible to all on the servicenet.benetech website so we would need to decide where it would be displayed.. 

Could you please have a look at the text, give us feedback, and give us your opinion in terms of where the "about us" button should appear on the landing page? thanks!

[About us Page.docx](https://github.com/benetech/ServiceNet/files/3010658/About.us.Page.docx)

**Comment by laurabenetech** [comment]
@CloVasco Hi Clotilde, can you grant my Benetech login with permissions to view in Box? Right now I can't access this. Thanks!

**Comment by CloVasco** [comment]
@laurabenetech done. I also attached the document in my GitHub comment

**Comment by laurabenetech** [comment]
@CloVasco Before I mock this up a couple of quick questions:
Location: We can definitely put it at the top of the home page, and we can also include it on the footer of all pages. I think we should include this in the footer for all pages since the home page is currently a continuous scrolling page, so it's often hard to see the footer on that particular page. Let me know what you think.  
Sign in page too?: Do you also want this on the sign in page before they sign in or is this just for users after they sign in?

**Comment by CloVasco** [comment]
@laurabenetech Whatever is the easiest and the usual way of doing it on websites. 
What's the "generic"/best practice - put it in the footer?
I don't think we should worry too much about our current users - if they have access to the home page with a long list of records, then they know what Benetech/Service Net is about!

**Comment by laurabenetech** [comment]
@CloVasco 
We can definitely put it in the footer.
Re:  the only pages I have links to are the home page *after* the user logs in, and the sign-in page. If you want "About us" on an external-facing home page for Service Net can you send me the link so I can see what it looks like? I haven't seen that page yet!. :-)

**Comment by CloVasco** [comment]
@laurabenetech I am not sure I understand your question. The About us page should appear on every page of the https://servicenet.benetech.org/ website, and be seen by all whether you are a pilot partner or not (so whether you have a log in or not). This website is not easily findable but everybody can go to it if they have the address so we should give them access to at least the about us page (which is in the welcome message). There' no need to put the about us page on any other website. 
Am I answering your question?

**Comment by laurabenetech** [comment]
Understood now. Confusion was with terminology of "home page" which I understood to mean the first page the user lands on AFTER they sign in. 
You want this on the Signin page, so I will add it there, along with the website footer after they log in.

**Comment by laurabenetech** [comment]
@CloVasco Following style of Benetech.org website for About placement, and this also makes the most sense. 
Links are in header and footer 
<img width="525" alt="About Header" src="https://user-images.githubusercontent.com/48697326/55196876-f7ab6200-516d-11e9-8b90-b5937d983a38.png">
<img width="412" alt="Footer About" src="https://user-images.githubusercontent.com/48697326/55196878-fa0dbc00-516d-11e9-851e-cc555dba6208.png">

**Comment by CloVasco** [comment]
Thanks @laurabenetech 
Over to you @johnhbenetech

**Comment by awalkowiak** [comment]
@johnhbenetech since I am making placeholder for About-us page while working on home page, I could add the content to it. But i cant access the box folder with text (I am using this email to log in 
awalkowiak@soldevelo.com), can I be included in this folder or could you share what is there via email/slack?

**Comment by johnhbenetech** [comment]
Sent via slack

**Comment by awalkowiak** [comment]
https://github.com/benetech/ServiceNet/pull/460

**Comment by bognasoldev89** [comment]
Confirmed that "About us" page is accessible from every page on the app for every user
