### ISSUE TITLE
Nicer welcome page

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#328]
Have a nicer SN homepage – welcome to the SN platform, etc! 
-Clotilde to ask Marketing so that they help us on that? or Laura to start something and have Marketing react on it? to be discussed

**Comment by CloVasco** [comment]
@laurabenetech here is the text for a nicer welcome page. 
Do you agree with the content? 
Could you please provide recommendations regarding the look and feel? thanks!

[Welcome text.docx](https://github.com/benetech/ServiceNet/files/3010670/Welcome.text.docx)

**Comment by laurabenetech** [comment]
@CloVasco Text looks fine. I designed the page so it's not so text heavy. 
![Welcome Page 1 button](https://user-images.githubusercontent.com/48697326/55102239-36182280-5083-11e9-8bd5-e29cf5c975e9.jpg)

**Comment by CloVasco** [comment]
Thanks @laurabenetech 
Discussion 3/27/2019 -- John/Clotilde/Laura agree with Laura's suggestion. 
One edit to Laura's visual - replace the email with "servicenet[at]benetech.org" (last line)
Over to you @johnhbenetech
