### ISSUE TITLE
Sorting of "recommended" updates on main search page

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#329]
Recommendation sorting to refine based on users' feedback ? monitor if they use it or not

**Comment by NeilMBenetech** [comment]
Hi @CloVasco would you kindly clarify what "recommendation sorting" is?

**Comment by CloVasco** [comment]
@NeilMBenetech when you are on the landing page, you can sort by either "recently updated" (default) or recommended. that's what I meant by recommendation sorting. I think the way it works for the moment is: the more partners and conflicting info there are, the higher it will be when you sort that way.

**Comment by johnhbenetech** [comment]
@NeilMBenetech ill add to @CloVasco 

"Recent" - purely based on last update date for any matching partner records. Intending to prioritize any recently updated record

"Recommended" - this is our 'smart' sort that we had hoped to improved over time. some of the thinking:

- Some fields are more important than others. An update to something like 'legal status' or 'funding' or something is probably less important than an update to a service or a description which are less important than an update to a phone/email/address.

- Some records are more important than other records. If multiple partners have a record in the system - it might be a proxy for record importance. We may also add the concept of a 'favorite' record at some point - so updates to those records would be higher priority.

So the idea is 'Recommended' sort would be a way to play around with different weighting of components  to escalate the most important records for an individual.

**Comment by johnhbenetech** [comment]
Sounds right. Let us know if you have recommendations on fields and weightings

________________________________
