### ISSUE TITLE
Deduplicate partners' records?

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#332]
When partners have duplicate records (or duplicate programs and services), should we de-duplicate them? in order not to confuse other partners who look at records and may think it's a bug from the SN platform!

-3/19 - shouldn't be our priority as this is a partner problem. adjouned and to be discussed later

**Comment by NeilMBenetech** [comment]
@john could you comment please on where we stand now? Are we doing any de-duplication and/or does it arise as an issue from partners occasionally? I know we've had a few cases but I'm not sure we need some systemic tweak for this, in which case we could close this item and remove from the Product Board.

**Comment by johnhbenetech** [comment]
@NeilMBenetech we don't run the matching script to compare your own record's against each other. So definitely possible. I don't have any idea of how common this is.

**Comment by NeilMBenetech** [comment]
OK, I'll close it because neither of us are hearing it is an issue.
