### ISSUE TITLE
Font (from Alex)

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#333]
Problem: As an end-user, the font is very difficult to read, particularly while scrolling through a database scanning for particular info. This could also create issues for individuals with dyslexia or low vision due to the poor contrast and spacing. 

<img width="1119" alt="Screenshot showing the squished, bold light blue font over light gray background" src="https://user-images.githubusercontent.com/47576069/55094283-5c35c680-5073-11e9-8ea2-2876e71e769d.png">

Solution: Change the font face to Helvetica (generally easy to read, sans-serif, good kerning/spacing for readability). The record title text should be larger -- about 2x the size compared to the information about conflicts on the right. Only the title portion on the left hand side and any "and 4 more" text on the right hand side should highlight as a link. Color for the linked title should be standard (~#170d9d), and color for the conflicts text should be standard black text. 

<img width="1127" alt="Mockup showing the proposed changes" src="https://user-images.githubusercontent.com/47576069/55094941-8e93f380-5074-11e9-83ae-3e1d060daf2d.png">

**Comment by CloVasco** [comment]
Thanks @alexrcabral !
@laurabenetech and @johnhbenetech - here is Alex's recommendation regarding font, size and color. To be discussed this morning during our meeting

**Comment by CloVasco** [comment]
@alexrcabral 
@johnhbenetech told us that technically speaking, we'd need to pay to use Helvetica. 
is there another equivalent in Open Source google fonts that we can use? for instance, John mentioned this https://fonts.google.com/specimen/Open+Sans. Would this be a good alternative we could use? thanks!

**Comment by alexrcabral** [comment]
@CloVasco Absolutely! The main requirements are that it is a sans-serif font with clear spacing (kerning) between letters and words. Helvetica and Arial are good examples, but Open Source google fonts include Open Sans, Lato, and Roboto.

**Comment by CloVasco** [comment]
Thanks @alexrcabral !
@johnhbenetech - let us know if you need anything else on that topic.

**Comment by johnhbenetech** [comment]
Let's go with Open Sans

"The record title text should be larger -- about 2x the size compared to the information about conflicts on the right. Only the title portion on the left hand side and any "and 4 more" text on the right hand side should highlight as a link. Color for the linked title should be standard (~#170d9d), and color for the conflicts text should be standard black text."

![image](https://user-images.githubusercontent.com/12927553/55512890-ebba1700-5629-11e9-9f85-d2d67e1dc182.png)

**Comment by awalkowiak** [comment]
@johnhbenetech i have question regarding this part: 

> Only the title portion on the left hand side and any "and 4 more" text on the right hand side should highlight as a link

Does this mean that only those two mentioned texts should be clickable or does it mean that whole card should be clickable as it is now, but only mentioned parts should be highlighted in different color?

Here it is how it looks now (I removed the map pin if there is no location to display):
![card](https://user-images.githubusercontent.com/12113312/57945169-68067200-78d9-11e9-9221-ceaa0ddc1225.png)
 Should I move Last updated date to the right and make it black as it is on your mockup?

**Comment by johnhbenetech** [comment]
@awalkowiak i think the whole ca d should still be clickable, and other those two texts should be styled differently. 

Yes, please right align the date but you can keep it as grey

Also can you vertically center the organization name

**Comment by awalkowiak** [comment]
@johnhbenetech those changes are on dev instance, let me know if there is anything that I'd need to change more.

**Comment by johnhbenetech** [comment]
I made some small tweaks after review, but this can be closed now
