### ISSUE TITLE
ability to dismiss record when not good match

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#339]
Once red button removed - Include a way for record to disappear after users take action on it if not good match
- what happens when click on the red button? disappear automatically - yes. new window to confirm - yes.
- for that user only? or for the team?  - Clotilde to ask partners
-at what level - the record or service/address? after discussion on 3/27 - decision to do by whole record. 
- what do we do when dismissed?  can the user see it again or never ever - no. John will review after

**Comment by CloVasco** [comment]
@laurabenetech and @johnhbenetech 
Our partners voted on this item ;)! See detailed notes in the attached doc. In a nutshell:
-5/6 said it should be for the whole organization
-2 raised the idea that they want to still have access to it if needed - a queue where can go back, look at it and reintegrate it if we want (UWBA) // a note on top of the side by side page where the bad matches are mentioned (Eden)
-2 raised the idea that it's not a black and white decision - could give more details on why it's not a match (LAAC)/Benetech should clarify and define what is a match or not - otherwise won't be consistent between users and orgs (HL)

[dismissal when not a good match - for whom.docx](https://github.com/benetech/ServiceNet/files/3036390/dismissal.when.not.a.good.match.-.for.whom.docx)

**Comment by CloVasco** [comment]
@laurabenetech and @johnhbenetech 
So my proposition:
-	The decision is for everybody in the organization
-	We still give them the ability to go back to the wrong match and reintegrate it 
o	I like Rick’s idea of adding a note somewhere in the side by side view to show that some other records have been dismissed and when you click on it, it shows dismissed records (+who and when dismissed them) and you can reinstate them
-	Open questions
o	Do we want to give them ability to give explanation? I could argue both ways
o	Should we clarify what a good/bad match is? Yes probably but it’s a complex discussion

**Comment by CloVasco** [comment]
Do you want to do a back and forth through github or have a quick phone call to decide before Laura works on visuals? If you think it will be faster to reach a decision, I can talk on:
-	Wednesday – at 10am or after 3.320
-	Thursday – between 11-1pm and 3pm

**Comment by johnhbenetech** [comment]
Proposition seems fine. I'll just need a visual for how to display the "dismissed records" and bringing them back.

On your open questions, technically there isn't a big difference. I think the question is would anyone actually fill it out and how would we use that info. We can always make it optional.

Re: good/bad match... It's tricky. I think it's better handled through training documents than on the platform. I still worry that people will say a HQ record shouldn't match to a site record, or that if a partner record has 2 locations and theirs only has 1 location then it isn't a match - even though I think they should be considered matches.

**Comment by CloVasco** [comment]
Thanks @johnhbenetech .
@laurabenetech - let me know if you want to hop on a quick call tomorrow to talk this through!

**Comment by CloVasco** [comment]
@laurabenetech to add 3 visuals:
Nber 1- visual of link to see non-matching records that have been dismissed
Nber 2-visual of page when click on Nber 1 to see records that have been dismissed with info (record has been dismissed by person on date. reason for it
Nber 3- feedback window - thanks for your feedback. confirm that you want to dismiss with link to provide reason (non mandatory!!)

**Comment by laurabenetech** [comment]
@CloVasco here is a mockup of the page for the nonmatching records that have been dismissed for individual records. Let me know if you have any changes to or questions about this--I'll keep working on the other visuals in the meantime.
![mismatch_list_individual_record_dropdown](https://user-images.githubusercontent.com/48697326/55648483-4f148800-5795-11e9-9e8e-4bd54984ece1.png)

**Comment by laurabenetech** [comment]
@CloVasco Here is the markup for the complete mismatch confirmation with note. I was able to leverage a design from Exygy.

![Mismatch confirm_with_note](https://user-images.githubusercontent.com/48697326/55648579-8edb6f80-5795-11e9-818c-5151ee8c134d.png)

**Comment by laurabenetech** [comment]
@CloVasco Here is the menu for Dismissed records. Eventually this menu can also include menu items for viewing the "I'm done" dismissed records as well.
![menu_for_viewing_dismissed](https://user-images.githubusercontent.com/48697326/55651654-30ff5580-579e-11e9-91f8-e996fc4c9af0.png)

**Comment by laurabenetech** [comment]
@CloVasco Here is the updated page.
![mismatch_list_individual_record](https://user-images.githubusercontent.com/48697326/55740809-bf631980-59e0-11e9-8e34-11a56b3d8869.png)

**Comment by laurabenetech** [comment]
@CloVasco Here is the updated visual for confirmation with original text. The word "Thanks!" appears in the final message they get ("Thanks! Your feedback has been saved.")
![confirm_with_note 4 8 19](https://user-images.githubusercontent.com/48697326/55741006-1cf76600-59e1-11e9-8095-e73315a17e99.png)

**Comment by laurabenetech** [comment]
@CloVasco can you point me to the visual we decided to implement that has the red button, so that I can include the visual of the link for viewing previously dismissed records? 
I don't see the visual here, and I have 2 different versions in my files (I need to know which one we finalized on previously). Is it in this bug somewhere (I can't find it). Thanks!

**Comment by CloVasco** [comment]
@laurabenetech - you can find it here -https://github.com/benetech/ServiceNet/issues/294

**Comment by CloVasco** [comment]
Here is a visual from @laurabenetech . 
![image](https://user-images.githubusercontent.com/21065773/55755792-e03d6600-5a04-11e9-947c-af5a48748912.png)

**Comment by CloVasco** [comment]
thanks @laurabenetech 
@johnhbenetech  -- here are the visuals for this item, which is the last one we owed you for this sprint. Do you have everything that you need? Do you want to talk about it? Let us know!

**Comment by johnhbenetech** [comment]
@clovasco So the only way to reinstate a match is from the 'view previously removed records' next to the not a match button?

What about the case where there is only one match to begin with, then a user dismissed that match. Now the record will display a 'no matching records' visual. How should they be able to reinstate a match in this case.

Second question. Lets say a user dismisses a match. At a later point that partner record receives an update (phone number, address, org name, etc) - should we keep ignoring the match no matter what? Should we reevaluate the match in light of the new info?

**Comment by CloVasco** [comment]
@laurabenetech please send us the visual on John's issue #1 
@johnhbenetech let's talk about your second item tomorrow. you raise a good point!

**Comment by laurabenetech** [comment]
@CloVasco Here is the visual of the page with the link, to address John's issue #1 re: how to view previously removed records:

![single_record_page_view_dismissed_records_link 4 10 19](https://user-images.githubusercontent.com/48697326/55908109-6e445880-5b8d-11e9-8f90-6119479eb712.png)

**Comment by CloVasco** [comment]
@johnhbenetech over to you
Let us know if you have remaining questions!

**Comment by johnhbenetech** [comment]
Per discussion on call, if a user removes a match for a record with only one match - they should be returned back to the single record view.

**Comment by bognasoldev89** [comment]
Confirmed that everything looks ok, users can remove and reinstate records.
