### ISSUE TITLE
Search for Services and Locations, not just Organizations

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#340]
enable to search by 
-programs and services

**Comment by NeilMBenetech** [comment]
Also by taxonomy / category names - possibly more useful as they are trying to discover new services they don't currently have.

**Comment by NeilMBenetech** [comment]
@johnhbenetech For improved clarity on this item, the user should be able to filter by any of the three major record types : Organization, Service and Location. I propose that every search should target exactly one of these, hence the UI element should be either a set of 3 radio buttons or a drop-down list. The default should be Organization and then any selection made by the user should be persisted and used for all subsequent searches (until the user changes it to something else).

**Comment by johnhbenetech** [comment]
@NeilMBenetech 

Which fields are you talking about specifically for services? There are a lot of fields, so let me know which you feel should be covered in the search scope. 

The geography filtering already allows you to segment by city, zip, county. Are you talking about allowing them to search by street address as well?

**Comment by NeilMBenetech** [comment]
@johnhbenetech For now we should be consistent with the existing search, which is on Name and Alternate Name (correct?) of the targeted record type. 

When we implement https://github.com/benetech/ServiceNet/issues/437 though, the intention there is that any text field in that record type is searchable. We could start though with a subset of fields that we agree are most interesting. But users will surprise us - one random example is wanting to search the Service's Eligibility field for "veteran" as a way to find stuff specific to that type of person.

**Comment by NeilMBenetech** [comment]
@johnhbenetech And yes, street address can also be a great field to search on. "I'm looking for a homeless shelter in San Francisco on Market Street. I don't remember the name." This would use four different filters in combination : taxonomy, geography, record type and targeted search field (last one is this workitem).

**Comment by johnhbenetech** [comment]
@NeilMBenetech 
Ok. Location Name is poorly populated. In many cases we artificially populate it using street address. So lets proceed with name, alt name, and street address for locations.

With regards to UI. Four options (or others if you have a suggestion). A. top level radio (only can search one type), B. top level checkbox (to search multiple types), move either A or B below into filter.

A:
![image](https://user-images.githubusercontent.com/12927553/61809582-380cab00-ae03-11e9-84fa-ddecb075bcc2.png)

B:
![image](https://user-images.githubusercontent.com/12927553/61809880-c6812c80-ae03-11e9-8960-c0d0c2576eba.png)

C:
![image](https://user-images.githubusercontent.com/12927553/61810178-5030fa00-ae04-11e9-8bdb-63503e6c04d0.png)

**Comment by NeilMBenetech** [comment]
@johnhbenetech I think option A (radio) and yes move into Filter accordion.

**Comment by johnhbenetech** [comment]
so we'll go with this

![image](https://user-images.githubusercontent.com/12927553/61817409-18ca4980-ae14-11e9-8e94-96299e603c70.png)

**Comment by bognasoldev89** [comment]
Confirmed that search for Services and Locations is now possible .

**Comment by NeilMBenetech** [comment]
@johnhbenetech The basic search is working properly but we will likely need further refinements to improve the user experience. Please let me know if this should be made into a new workitem.

When searching on a Location or Service, it is correctly finding those records BUT the search results are listing the parent Organization. Then you have to go into the Organization and manually cycle through all the Services (or Locations) via Next/Previous to find the one you searched for. This is laborious.

Instead we should consider returning the Services (or Locations) that matched the search, directly in the search results list, and when you click for details it automatically has pre-selected the matching Service (or Location) and also in some way highlighted other Services (or Locations) at that Organization that matched the originating search.

**Comment by johnhbenetech** [comment]
@neilmbenetech please break each discrete feature into a new ticket. Include any user stories or wireframes you may have for specific user flows.

**Comment by NeilMBenetech** [comment]
@johnhbenetech Done, created new task : https://github.com/benetech/ServiceNet/issues/634

This one can indeed be considered "closed".
