### ISSUE TITLE
enhance search feature - geography

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#341]
enable to search by 
-location - address/city/county

**Comment by NeilMBenetech** [comment]
Hi @CloVasco , if you agree with my modifications to https://github.com/benetech/ServiceNet/issues/357 can this one be closed and discarded?

**Comment by CloVasco** [comment]
@NeilMBenetech both are covering the same purpose and #357 is more detailed. so feel free to close this one

**Comment by NeilMBenetech** [comment]
Closed as a duplicate.
