### ISSUE TITLE
"heal" vs "health" search

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#343]

**Comment by NeilMBenetech** [comment]
Hey @CloVasco can you clarify this one please? Are you saying searches should not operate on partial words, so if you search for "heal" it will not match on "health" but just the full word "heal", for example ?

**Comment by CloVasco** [comment]
@NeilMBenetech I was copying an idea from our UI/UX contractor, Laura. Here is the full explanation she gave me at the time: "Ability to be very targeted by including words in quotes. For example: “health” in quotes wouldn’t include heal, but health without quotes would"

**Comment by NeilMBenetech** [comment]
Thanks Clotilde. I'm going to close this one for now but  I've captured the concept in my overall "big picture" document. I'll reintroduce this idea when the time comes.
