### ISSUE TITLE
add filtering feature - geog and partners

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#344]
Enable users to filter by:
-partner (easy)
-geography (city/county/zipcode)
   - autocomplete

**Comment by laurabenetech** [comment]
@CloVasco Need technical (John) and overall design strategy (team) decision on Location field behavior. 
See attached PDF for 2 options for this field: Option 1: Location in 1 field or Option 2: Location in 3 different fields.
[Filtering options Location 2 options.pdf](https://github.com/benetech/ServiceNet/files/3020408/Filtering.options.Location.2.options.pdf)

**Comment by johnhbenetech** [comment]
Technically both are possible. Option 1 would probably need to have "San Mateo County" and "San Mateo" as options to deal with the city/county issue.

one thing to consider is whether search options would function as EITHERs or BOTHs. 

So if they select both a zip code and a city:

1. Only show records that have locations that are BOTH in that zipcode AND in that city
2. Show any records with locations EITHER in that zipcode OR in that city

Seeing that #1 may return no results if that zip is far from that city

**Comment by CloVasco** [comment]
Thanks @laurabenetech. 
Because we're going to have a fixed list of cities, counties and zipcodes, I guess this would be doable for the machine to give you options - for instance when you type "San Mateo" - the machine could offer you 2 lines - San Mateo (city) and San Mateo (county). and then you select the one you want. 

If too complex to do at this stage and option 2 is easier (let us know @johnhbenetech ), I am fine with three boxes. My brain and logic would tell me that it is zipcode AND city. would it be complex to add a message like - "there is no result because your zipcode is not in this city"? we can also do either if it's easier.

**Comment by laurabenetech** [comment]
@CloVasco @johnhbenetech I have a preference for Option 2 with the 3 fields because I think it's clearer and easier for users to use quickly.  I can also add the address field on that line, so we'd have one line for location-related filtering. 
In terms of searches, I was also thinking that AND made sense. So we could start with that and see what the database admins think.

**Comment by CloVasco** [comment]
@laurabenetech sounds good to me!

**Comment by johnhbenetech** [comment]
If we want AND, option #2 is easier.

I think we should break address out into it's own task because i dont really understand it.

@laurabenetech I still need to see a mockup for what actually happens when you type into the fields, how should it autocomplete, what does it look like when you have things selected, how do you remove a filter once it's chosen?

**Comment by laurabenetech** [comment]
@CloVasco I'm going to go ahead with Option 2 (3 fields for location) unless I hear otherwise. Can you make a separate issue for "address" since it's no longer going to be part of this task? @johnhbenetech I'm going to do my best to finish covering all of these different choices today, but I might need a bit more time to add that level of functionality into this for all the different behaviors/choices. If so, I'll have it done by Monday at the latest.

**Comment by CloVasco** [comment]
@laurabenetech Option 2 works for me. I updated the filtering tasks in the Product Scoping column

**Comment by laurabenetech** [comment]
@CloVasco See attached document for Filtering for location and partners. This covers all the instances we agreed on in our 4.2.19 white boarding meeting.
[Filtering behavior 4.3.19.pdf](https://github.com/benetech/ServiceNet/files/3040938/Filtering.behavior.4.3.19.pdf)

**Comment by CloVasco** [comment]
thanks @laurabenetech !
Over to you @johnhbenetech 

One question to you John regarding the lists we'll use - I suppose we’re going to use the list of cities/zipcodes/counties that we can find in each partner’s database. For instance if Sheltetech only has SF records – they will only see SF related lists in their filtering options for city/county/zipcode. 

Do you agree or did you have another approach in mind? like the aggregated list from all partners and if a user selects a city where they have no record, they have no result? I don't know what the tech implications are on this choice

**Comment by johnhbenetech** [comment]
@clovasco they are both about the same from a tech point of view. My gut says start with your first approach where we only show those relevant to the logged in partner.

Two questions:

@laurabenetech @clovasco for zip, do we really want auto complete? Considering zips are not semantically different from each other and in fact all zip near to each other will only be 1-2 digit different?

@clovasco how does partner filter work? Let's say we have three records.

Rec 1 has matches from partnerA and partnerB
Rec 2 has a single match from partnerA
Rec 3 has a single match from partnerB

The user selects filter on partnerA
I think:
Rec2 shows
Rec3 doesn't show

But for Rec 1 does it show both A and B matches, or does it hide the B match? The first option is much easier technically.

**Comment by laurabenetech** [comment]
@johnhbenetech @CloVasco John, For ZIP, autocomplete can be helpful if someone wants to see all the zips nearby. See Google search autocomplete as an example:
<img width="280" alt="ZIP autocomplete" src="https://user-images.githubusercontent.com/48697326/55519154-8a934300-562b-11e9-96a7-bb6ed2174617.png">
Re: Filtering with partners I agree with Clotilde re: going with the first option.

**Comment by CloVasco** [comment]
@johnhbenetech On your second question, yes about rec 2 and 3

For rec 1 - If you interpret the filter choice very stricly, you would only show partner A.
at the same time, I would imagine that if they see the record A and notice something interesting, they may still want to look at other partners' info first to evaluate partner A's data before taking a decision....

So I'd tend to say that we filter strictly in the list of record displayed in the landing page - only records that partner A has are shown. 
And then we keep A and B in the side by side view. 
Advantage - it's always possible to get stricter during or after pilot if we want and hear partners complain + it's easier technically

...My 2 cents after a long day. Let me know if that doesn't make sense or if you disagree!!

**Comment by kkaczmarczyk** [comment]
@johnhbenetech finally got this covered - there was a lot of refactoring involved. I am deploying it at the moment and will let you know once done. Please feel free to try it out on demo.

**Comment by bognasoldev89** [comment]
Confirmed that filtering engine is up and running
