### ISSUE TITLE
fix "imported on" language on single record view

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#345]
Alex noticed that on the single record view, when you hover on ?, it's written "imported on" and not updated - confusing language. 
->to be consistent - change it to "updated on"

**Comment by mariaogryczak** [comment]
I additionally corrected the form of sentences:
partners has conflicting data -> partners have conflicting data (in the same field as 'updated on')
partner have similar records -> partner has similar record (on the right, under 'Compare')

**Comment by bognasoldev89** [comment]
Confirmed that changes are visible
