### ISSUE TITLE
why do we enable them to upload data at that stage? (Clotilde's question)

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#346]
-Clotilde's idea - keep that idea for post piloting stage and hide this tab during the pilot

**Comment by awalkowiak** [comment]
@johnhbenetech / @CloVasco 

> why do we enable them to upload data at that stage? 

Who are "them"? What "stage"?

> -Clotilde's idea - keep that idea for post piloting stage and hide this tab during the pilot

What "idea"? Which "tab"?

**Comment by johnhbenetech** [comment]
this task is to hide the upload data header option for non-admin users

________________________________

**Comment by awalkowiak** [comment]
Yeah, that's what i thought. Does this pilot stage has any mean here? Or can I just hide it for non admins and not care about any other circumstances?

**Comment by johnhbenetech** [comment]
Yeah you can just hide it for non admins.


If I ever need it put back, I will make another task

________________________________

**Comment by bognasoldev89** [comment]
Confirmed that "Upload data" menu item is hidden from non-admin users
