### ISSUE TITLE
add a "back" button (from Alex)

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#347]
Currently, users have to use the browser back button

**Comment by laurabenetech** [comment]
@CloVasco Include a Back button so users can navigate back to the previous page they were viewing. Here are examples of placement on the Side by Side and Single Record page: Upper LH corner, under the Benetech logo.
![back_button_side_by_side 4 8 19](https://user-images.githubusercontent.com/48697326/55741242-aad35100-59e1-11e9-835f-b1d92e361de1.png)
![back_button_single_record 4 8 19](https://user-images.githubusercontent.com/48697326/55741257-b0c93200-59e1-11e9-8c70-16d4b8d503db.png)

**Comment by CloVasco** [comment]
@laurabenetech thanks.
Over to you, @johnhbenetech

**Comment by awalkowiak** [comment]
@CloVasco should this work in the same way as a browser's back button?

**Comment by CloVasco** [comment]
Yes, that is the idea. 
I'll let you follow up with @johnhbenetech going forward as my position recently changed within Benetech and I'm not working on the Service Net roadmap anymore. Thanks!

**Comment by bognasoldev89** [comment]
Confirmed that "back" button is on every page available and is working
