### ISSUE TITLE
Make it clearer that the left record is theirs

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#348]
Alex's suggestion - On the single view and side by side view, under the name of the record on the left, add
"From ShelterTech" (If I am a ShelterTech person!)
Use the same style and police that we use for the other partners' records on the right - in the side by side view

**Comment by NeilMBenetech** [comment]
This has been addressed. We default to "Your data" where appropriate. If it is a "discovered" record that doesnt yet have a match to one of your own, it will say the name of the partner whose record it is.
