### ISSUE TITLE
Add backend for uploading files

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#35]
All uploaded files should be sent to the server and be persisted in the non-relational database. Use the provided upload page for this. Only authorized users should be able to upload a file. If the file is in a different format than JSON, it should be converted before saving.

**Comment by wojtekbu** [comment]
I've tested most of it here https://github.com/benetech/ServiceNet/issues/3
and also I have checked:
* persistence in MongoDB,
* content can be inspected on webapp.
