### ISSUE TITLE
Keep search/sorting/filtering options during session

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#350]
Problem today - When I sort, go to a record and then come back to the home page, the platform has erased my sorting options (and I guess we will have the same problem with filtering)
Solution - Have the platform keep my sorting/filtering until I erase them

@laurabenetech - could you please put together a visual of what it would look like ? we need at least a button to enable users to delete Sorting/filtering preferences (and I may be forgetting other things!).

**Comment by laurabenetech** [comment]
@CloVasco Here are the decisions we made about Sorting behavior during our 4.2.19 whiteboarding session:

- When users logs in, the default sort is by Recently Updated.
- Users sort by choosing the dropdown from the Sort button.
- The user choice for sorting persists when users go to view other records and return to the page again.
- Sort reverts to the default setting when the user logs out.

For a visual of Sort button placement, see #344

**Comment by CloVasco** [comment]
thanks @laurabenetech 
Over to you @johnhbenetech

**Comment by CloVasco** [comment]
@johnhbenetech  Please keep search as well
-- When I search, go to a record, and come back to the landing page, the platform has forgotten my search. It should keep it.
thanks!

**Comment by kkrawczyk123** [comment]
Confirmed that search and sort results are kept until user won't change/delete them, default values are restored when log out and log in again.
