### ISSUE TITLE
For record with multiple locations/services - the accordion should be expanded by either clicking the arrow OR clicking the next button

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#351]
currently, need to click on arrow first and then on button "see other locations/services"

**Comment by johnhbenetech** [comment]
If the accordion is collapsed, hitting the next button should expand it. 

Hitting the arrow should toggle expanded/collapsed

accordion should only be collapsed via the arrow.

**Comment by kkrawczyk123** [comment]
Confirmed that works like described above.
