### ISSUE TITLE
User dropdown list to clean - "session"

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#352]
-	Hide "Session" page

**Comment by awalkowiak** [comment]
@CloVasco I will remove this for non admin users. Are you ok with that?

**Comment by johnhbenetech** [comment]
Yeah that's fine!

________________________________

**Comment by johnhbenetech** [comment]
@awalkowiak I think #492 is related to this

**Comment by awalkowiak** [comment]
@johnhbenetech fixed

**Comment by bognasoldev89** [comment]
Confirmed that users don't see Sessions in dropdown list.
