### ISSUE TITLE
Tracking tool (Amazon QuickSight AWS)

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#355]
John to put together a dashboard page with metrics that Clotilde need (Laura to add another GitHub task with additional ones for her specific needs):
-% overlap between databases/# records shared through SN
-# updates imported and by whom
-Frequency of people using the platform (# time and duration per user per week)
-Evolution of databases size over time (- # records)
-Evolution of freshness over time (% records updated)

**Comment by CloVasco** [comment]
@laurabenetech John is putting together an Amazon page where we’ll be able to see some stats and metrics. He'll send us a link when it is ready for us to look at it. I added this github task for @johnhbenetech. I know you need more detailed tracking info on the use of the buttons, etc. So feel free to add a github task for John with your specific needs!

**Comment by laurabenetech** [comment]
@CloVasco  I took a look at Amazon QuickSight. It isn’t clear from their webpage whether they can track highly specific UX/UI user behavior and actions, such as button clicks, time spent on particular pages, what was typed in search bar, etc.

If it doesn’t track this kind of UI/UX behavior, then I don’t have any additional requests to the ones that you listed. If it can track these particular types of actions on pages and elements, let me know.

**Comment by CloVasco** [comment]
@laurabenetech could you please add a list of the specific things you will need to track for your user research (I have no idea what they are - I imagine - buttons they clicked on, time spent per page, and things like that?) on this Github page. 
And then @johnhbenetech will figure out what the best tool will be for your purposes, whether is is A QuickSight and/or something else.

**Comment by laurabenetech** [comment]
Per @Clotilde's request I'm adding a list of user-specific UI/UX behaviors to track. 
These might not be tracked with Amazon QuickSight if it can't track these type of user actions. John will determine what tool to use based on this list.
[Service Net user analytics 3.28.19.docx](https://github.com/benetech/ServiceNet/files/3020297/Service.Net.user.analytics.3.28.19.docx)

**Comment by CloVasco** [comment]
Thanks @laurabenetech 
@johnhbenetech over to you. Let us know if you have any questions!
