### ISSUE TITLE
Filter search results by location or service area, and sort by proximity

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#357]
Add advanced filtering features
- instead/on top of(?) of miles distance- could be time - 30 mins transit..) 
-service area (filter by .. food, homelessness, etc) 
-type of updates (to be discussed - recommendation from Exygy - by conflicts, updates, recommendations)

**Comment by NeilMBenetech** [comment]
I'm going to modify this task somewhat for clarity.. I propose it should be:

Be able to filter results for those either located within, or serving, a designated location. Also be able to sort results by proximity to that designated location.

That location ideally could be either a Lat/Long coordinate (selected on a map?) or just a specified county, city/town or zip code. If the latter (which is probably easier to code?), code should retrieve that place's approximate lat/long from Google Geo API.

If a "located within" search, user should be able to specify a county. An Organization should be included if it has at least one Location matching the criteria.

@johnhbenetech , a "serving the location" search requires that we have well-structured "service area" data coming from the partners. That should be the case for iCarol data. Is it the case from other partners  ?

**Comment by johnhbenetech** [comment]
Unsurprisingly service area isn't readily available in other sets.

Re: geography

We already have filtering based on the physical location of the org (by city, county, zip) but obv that doesnt get at 'distance from a specific place' or could be confusing if the agency doesnt offer services in the area they are located.

Re: distance

Yeah i have no problem with a map based approach, or address entry - just would need any suggestions re: UI and how it might manifest to the user.

The only concern i have is we will need to do some technical work to make sure we can do on the fly distance calculations against 100s of records - it's def possible we just might need to optimize a few things.

**Comment by NeilMBenetech** [comment]
I think a linear calculation of distance will suffice for a long time to come. Travel distance and time based on routing, transit etc is much more relevant when one is making referrals to a help seeker. But when you're just doing data updates, linear distance is good enough and hence calculatable in code without hammering the Google API hundreds of time per search.

**Comment by awalkowiak** [comment]
This is related to #572

**Comment by awalkowiak** [comment]
@NeilMBenetech I am currently polishing this feature. I added a map to the filters component and i have select for choosing records search radius. I have question to you what values should be in it? Currently I have: 1, 10, 20, 30, 100 miles. I think it is not required to have more than 20 miles search. Do you have any particular requests regarding radius selector?

![Selection_003](https://user-images.githubusercontent.com/12113312/69354752-ebd25a00-0c80-11ea-9f4d-881153974920.png)

**Comment by NeilMBenetech** [comment]
@awalkowiak  good question. In urban areas you need much smaller distance increments but beyond 20 probably gets less useful even in rural environments. So I suggest: 

1, 2, 3, 4, 5, 10 and 20

**Comment by awalkowiak** [comment]
@bognasoldev89  this was added on home page filters. Sacramento filter will be done once everything is ok with the first part.

**Comment by bognasoldev89** [comment]
I confirm that, in my opinion, this feature works as expected.
I tried filtering organizations only through this feature, and with other filters and search applied and I haven't noticed any record that wouldn't fit.

Here exemplary gif of basic usage:

![357 working](https://user-images.githubusercontent.com/51324797/69871490-3e2ffe00-12b3-11ea-8256-d4a0bce39dad.gif)

I will create similar task for the Shelter project.
