### ISSUE TITLE
BUG - SMC address

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#358]
John, Edwin told me about a strange bug during my call with him on Thursday. 

Record - Law Foundation of Silicon Valley
On his website, he has the right physical address 4N 2nd street in san Jose. And a mailing address at 111 West St. John, SJ
But on Service Net, both physical and postal addresses are on 111 West St. John.
 
Could you look at that bug and see whether the problem comes from the SMC API or our platform please (and keep me posted so that I can tell him if the pb comes from his system)? Thanks!

**Comment by johnhbenetech** [comment]
QA, please check this as part of #136

**Comment by CloVasco** [comment]
@johnhbenetech - Edwin found another example with the same type of problem
Record - Christian Counseling Centers, Inc. 
The SMC Connect database has a website address in its record, which doesn't appear in the Service Net platform - https://www.smc-connect.org/locations/christian-counseling-centers-inc?keyword=christian+counseling&location=&utf8=%E2%9C%93

**Comment by awalkowiak** [comment]
This will be checked together with #244

**Comment by awalkowiak** [comment]
@johnhbenetech I added test for SMCConnect here https://github.com/benetech/ServiceNet/pull/397. I have not seen any issue with data being mismatched.

**Comment by pmuchowski** [comment]
LGTM

**Comment by johnhbenetech** [comment]
@awalkowiak @pmuchowski 

So I confirmed there is an issue in our system. I agree the testing of the mapping seems to be accurate. I believe the issue actually lies in the 'update' data section of the code

For that first example given, the addresses were at one point in time the same.  on Mar 31 they updated the physical address to the new value. So there's been three weeks of updates without the change getting picked up. Can we look into this?

**Comment by johnhbenetech** [comment]
@CloVasco I can't see what's wrong in your second example

I only see one address on that SMC record (same for physical + postal). This is the same address in ServiceNet. Let me know if I'm missing something. We are working on a fix for the first example, so hopefully that will fix all remaining issues

**Comment by kkaczmarczyk** [comment]
@pmuchowski Could you have a look at it, since @awalkowiak is ooo for time being?

**Comment by CloVasco** [comment]
@johnhbenetech I double checked the second example (Christian counseling Centers). I can't find the problem any more.

**Comment by johnhbenetech** [comment]
Just commenting to capture what was discussed on a call.

Currently it seems if no organization fields are updated, no related entity field updates will be taken in. We need to change this so that if **any** field in **any** entity has changed from the previous week, we log and enact that change in ServiceNet.

Before this is released, devs need to evaluate any potential issues with processing this many changes compared to our previous process. It's fine if the import/update jobs take a long time, they just need to not cause major issues with memory, processing, or blocking of the main functions of the platform.

**Comment by kkrawczyk123** [comment]
I am able to edit physical and postal addresses separately when uploading data. Confirmed that the issue has fixed.
