### ISSUE TITLE
Clarify how updated dates are captured and displayed

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#359]
Currently it's unclear exactly where in the DB creation/change dates are captured and for which actions. Feel free to break this out into multiple tasks, but I believe we would like dates logged for:

* The first datetime a new organization parent record is created (the first time we were able to see it in an upload or API call)

* A field to capture any 'created datetime' field for the organization from the partner data systems (several APIs have this). maybe 'partner_created_date'

* For each organization record and all sub-entities - we need to create a complete audit table for all field changes. I'm imagining 2 possible approaches:

-- A table for each entity i.e. organization_audit, location_audit, etc etc

-- A single field_audit table with a column for entity

    For either approach we will need columns for: fieldname, old_value, new_value, datetime

* Currently on the main page, there is an 'Last Updated' date displayed. I believe this is currently populated from the latest conflict created (not the actual latest updated field). Once we get the audit table(s) in place we can change this to the latest audit record from all matched entities. For efficiency we may want to create a 'last_updated' at the organization level that is overwritten whenever an audit record is created. If we go with the single audit table approach - this probably isn't needed since the query would be straightforward.

**Comment by johnhbenetech** [comment]
To be clear, the audit table(s) should record the ENTIRE history of a record's fields, not just the last change for a field. The datetime column will be used to find latest

**Comment by pmuchowski** [comment]
@johnhbenetech you're right about the 'Last Updated' date it's the last conflict created date, but in the sorting the correct last update date is used (at leas I think it's the correct one, it's described below).

We are recording the history of the changes using the entity called Metadata, it's have following fields:
- resource_id - id of the entity the change was recorded for
- last_action_date - date of the change
- last_action_type - type of the change: create, update or delete
- field_name - name of the field that was changed (has value only for the update)
- previous_value - previous value of the field (has value only for the update)
- replacement_value - new value of the field (has value only for the update)
- resource_class - name of the class this record was created for
- user - user which make the change

When some entity is removed or created, the record in the metadata is created for entire entity, but when it's updated, records are created for specific fields (only the fields that was changed).

Conflict has 2 date fields: current_value_date and offered_value_date. When conflict it's created it's getting the latest last_action_date for the specific field (or for entire entity if there is no update type) from the metadata. The current_value_date is the latest last_action_date for the current organization and offered_value_date is the latest last_action_date for the partner organization.

In the sorting it's used the latest update date from all conflicting organizations (matched organizations with some conflicts with current organization). It's getting all conflicts for the current organization and choosing the max offered_value_date.

**Comment by johnhbenetech** [comment]
@pmuchowski So to sum it up:

Last update date = Most recent conflict created for user's record
Most Recent Sort = Most recent conflict created in any matching partner record?

And then second question:
From your description - if a matching partner record adds/removes/edits a location or service (but did NOT change any of the organization fields) the last update date will not be affected because conflicts only look at org fields.

Do you think it would be possible to start pulling update dates from the metadata so that it covers all related entities? I imagine this would be a multi-table query and we should probably explore it as part of 
#426. What do you think?

**Comment by pmuchowski** [comment]
@johnhbenetech the Most Recent Sort is no the conflict creation date, but the update date of the partner organization (which is stored in conflict).
When we start detecting conflicts for location and services it will include those entities in the 'last update' date.
I'm not sure if I understand correctly the ''last update date" should be the update date from the partner organization event if this organization don't have any conflicting fields with the current one?

**Comment by johnhbenetech** [comment]
@pmuchowski Yeah I guess we could prioritize the work to add conflict detection to all entities higher. I just worry it's a lot of work for little gain.

There are so many records in a user's database (1000s) that we have two goals:

1. Allow a user to find specific records they know they want to look at. This is where searching and filtering come in to help them isolate specific orgs or specific geographies. 

2. Highlight records a user should review because they were recently changed (as opposed to one of the 1000s of records that haven't been touched in 3 years and where the info is outdated). As you can imagine if a partner changes something like a phone number or an address - that is really important to know because it could indicate that your record is out of date and you might send someone in need to a dead end.

So my hope would be that we can make sure to highlight those records with recent/important updates (by sorting them to the top for instance). 

I understand if we do that purely off of metadata, we run the risk of sorting a change to the top that was actually a partner changing an old piece of information TO your information. When i think of how often that will happen (almost never) vs. how much time it would take to add conflict detection everywhere (~1+ weeks) - I wonder if we should just display the lost recent change from metadata table.

What are your thoughts? I know metadata stuff can be a big performance hit if we dont optimize the database

**Comment by pmuchowski** [comment]
@johnhbenetech I created and issue #469 to change the Last Updated date.

**Comment by johnhbenetech** [comment]
@pmuchowski i updated #469 with what we discussed today
