### ISSUE TITLE
when many services/locations/matches, add "left arrow"

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#361]
From Arantxa. "when there are 15 services, I want to be able to go back and forth. Otherwise I have to go through the whole list to see the previous location/address again".

-  Add left arrow to three places:
1. See another match
2. See another location
3. See another service

**Comment by CloVasco** [comment]
Discussion with John, Laura and clotilde - april 10. we're choosing this solution in the short term as the drop down menu (for different services/locations/matching records) is part of the big overhaul of SN. 
@johnhbenetech you need visuals for this one, right?

**Comment by laurabenetech** [comment]
@CloVasco Here are the visuals for See Another Match and Locations/Services. Adding color so they are more noticeable and visually appealing.

<img width="212" alt="See Another Match" src="https://user-images.githubusercontent.com/48697326/57249940-1e757780-6ffb-11e9-8d5f-5bd4d800c1c3.png">

<img width="222" alt="Locations next prev" src="https://user-images.githubusercontent.com/48697326/57249776-adce5b00-6ffa-11e9-8ec5-e45f43405fb2.png">

**Comment by CloVasco** [comment]
thanks @laurabenetech 
@johnhbenetech - moving it to "Ready for Development". Let us know if you have any questions

**Comment by bognasoldev89** [comment]
Confirmed that there are "left arrows" moving to previous pages in places mentioned in the issue
