### ISSUE TITLE
Expand right and left sections at the same time

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#365]
From Jay (4/4/2019)
So I was thinking that it would be super convenient that if you click on an arrow to expand a section that the section adjacent to it expands along with it. For example if you expand Locations in your record then locations for the matching record expands along with it.

**Comment by CloVasco** [comment]
See Jay's visual attached
![Expansion of section_Service Net](https://user-images.githubusercontent.com/21065773/55594770-bf6bcc80-56f5-11e9-9705-29f8f57c8164.png)

**Comment by laurabenetech** [comment]
Oops--my apologies. I didn't mean to close this--I clicked the wrong button after viewing it.

**Comment by awalkowiak** [comment]
@johnhbenetech I think this is the same feature as this one: https://github.com/benetech/ServiceNet/issues/317

**Comment by johnhbenetech** [comment]
@awalkowiak #317 is for adding expand all and contract all buttons.

This task (if we choose to do it) is to expand the location on the right side record when the location on the left side record is expanded.

**Comment by johnhbenetech** [comment]
Closing this as obsolete
