### ISSUE TITLE
Side by side view - fields should be at the same level

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#366]
Feedback from Jay (call end of March)
On the side by side view, the fields on the left and right are not matching up. It is super hard to read and to use. Should be consistent.
see visual below

**Comment by CloVasco** [comment]
![Data side by side - fields not matching](https://user-images.githubusercontent.com/21065773/55644325-73b73280-578a-11e9-9251-48d794eb5680.png)

**Comment by CloVasco** [comment]
another example that I noticed yesterday (Laac's account)

![image](https://user-images.githubusercontent.com/21065773/55644435-c7298080-578a-11e9-99e3-1ce8da259eb4.png)

**Comment by CloVasco** [comment]
Discussion - @johnhbenetech, @laurabenetech and Clotilde on April 10 - conclusion:
when the org doesn't have a section (for instance "funding", "opening hours", "languages") - which could happen on the left or on the right, display the header and have a sentence below like this partner doesn't have this information. And then blank space until the beginning of the next section
@laurabenetech could you please provide a visual? 

@johnhbenetech What would happen then if I expand a field on the left for instance? Would it recreate the problem? or would the platform always keep both sides at the same level in a real time way? (not a big deal if it doesn't. I was just wondering)

**Comment by laurabenetech** [comment]
@CloVasco 
Fields need to line up for readability and section titles need to match on right and left side.

When a section doesn’t have info, display the section title and a blank space that matches the size of the section area with info. 

Result: the fields always line up on both sides. Blank space should include the message: “This partner does not have this information.”

<img width="752" alt="Blank section" src="https://user-images.githubusercontent.com/48697326/57393906-00ce1c80-7179-11e9-85a4-813559dfab34.png">

**Comment by CloVasco** [comment]
@laurabenetech . thanks for the visual. Looks good to me. I assume we'll change the sentence when it's the user (left side) who doesn't have the data so that it says something like: "No information in my database"?
Over to you @johnhbenetech . Let us know if you need anything else
and a question for you John - What would happen then if a user expands a field on the left? Would it recreate the problem? or would the platform always keep both sides at the same level in a real time way?

**Comment by laurabenetech** [comment]
@CloVasco Yes, when it's on the partner side, it can say "Your database does not have this information."
