### ISSUE TITLE
Add button to open all sections at once

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#368]
Julie's idea
- when on the side by side view (and could do it on single view as well? - not priority?), have a button to open all the sections (locations, services, etc) at once instead of having to scroll down and open them manually one by one

**Comment by NeilMBenetech** [comment]
Having them all open by default might be even better. I would think when you first go into a record you are scanning for differences in all fields.

**Comment by johnhbenetech** [comment]
Closing this as obsolete
