### ISSUE TITLE
rounder corners

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#371]
see mock ups in In-Vision

**Comment by CloVasco** [comment]
@johnhbenetech I assume you need visuals or specific recommendations from Laura on that one, am I right?

**Comment by johnhbenetech** [comment]
Not every place obviously, but like if she has suggestions for what a button could look like or a text box, etc etc

**Comment by CloVasco** [comment]
Thanks @johnhbenetech !
@laurabenetech could you please send us recommendations for every type of button and text box that needs to be improved?
