### ISSUE TITLE
Be able to click on website address

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#376]
-From call with Edwin
To give users the ability to click on the website URL form the SN platform
(instead of having to copy the website address and go to a browser to paste it)

**Comment by NeilMBenetech** [comment]
This seems to be working, however it needs a target="_blank" added so it opens in a new tab/window. Here's an example.

https://servicenet.benetech.org/#/all-records-view/e594d599-8347-4e83-b5ea-a680d80093fa

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified on:** 
- Google Chrome Version 80.0.3987.149,
- Firefox Version 74.0
**Verified cases:** 
- possibility to click on the website address and open page in a new tab
