### ISSUE TITLE
Add google analytics

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#383]
We need to add google analytics to ServiceNet.

An account has been set up and is currently pointing to our dev server. We will transition it to the production server when the work is complete.

The tracking ID is: UA-2390830-31

I have also created a custom dimension that should be used to pass the username of the currently logged in user to Google Analytics. the dimension is 'dimension1' in GA and should be set as follows

var dimensionValue = 'SOME_DIMENSION_VALUE';
ga('set', 'dimension1', dimensionValue);

The following events should be sent to GA (all with the username dimension)
* Log In
* Log Out
* Clicking On A Record
* Clicking On Side By Side View
* Clicking 'See Another Match' on side by side view
* Searching Records
* Sorting Records
* Confirm Match Button
* Deny Match Button

**Comment by johnhbenetech** [comment]
Unfortunately we can't give you all access to the underlying account at this time. Feel free to either set up your own temporary GA account and change the tracking ID - or once the work is completed I can push changes and confirm working as expected

**Comment by pmuchowski** [comment]
@johnhbenetech what should be the categories for those actions?

**Comment by johnhbenetech** [comment]
@pmuchowski you can just make it a single category for now - "UserActions"

**Comment by pmuchowski** [comment]
@johnhbenetech can you confirm if the google analytics is working?

**Comment by johnhbenetech** [comment]
Confirmed. We can close this out and move to done
