### ISSUE TITLE
Matching: More than one service or location, add drop down menu with name

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#384]
In the long term, instead of having <> arrows for "see another service/location" (and potentially for partner record as well?) - add a dropdown menu so that they can see the full list and select which one the user wants to see. 

-Potential problem - when there is no name for a location - which Name to display? name of the address and/or city?

**Comment by NeilMBenetech** [comment]
I like this. And yes, Address Line 1 plus City Name would be perfect to use in case Location has no name. If it has these neither, have a default value like "Unnamed Location 1" and increment for multiple unnamed.

**Comment by NeilMBenetech** [comment]
To clarify, this should apply to Services and Locations in both the left column ("my" records) and the right column (comparison record).

**Comment by NeilMBenetech** [comment]
For Services, use the Service Name for the dropdown box. 

For Locations, Please use my suggestion above from June 28 on how to name the Location records. I think we should try always using this method (rather than whatever might be populated from the database) so that the data is consistent from partner-to-partner.

**Comment by bognasoldev89** [comment]
I confirm that the functionality works as described. The user is able to select Services and Locations from the dropdown lists in both single and multi record views.

Here how this looks before selecting:
![384 1](https://user-images.githubusercontent.com/51324797/67478520-862c8700-f65c-11e9-9c6e-69aef89d513a.png)

Behavior in single record view:
![384 2](https://user-images.githubusercontent.com/51324797/67478573-9cd2de00-f65c-11e9-846f-7d9508a280c6.gif)

![384 3](https://user-images.githubusercontent.com/51324797/67478574-9d6b7480-f65c-11e9-8040-aa8762593023.gif)

And multi record view:
![384 4](https://user-images.githubusercontent.com/51324797/67478602-a8260980-f65c-11e9-9a4f-0217ae000bff.gif)

![384 5](https://user-images.githubusercontent.com/51324797/67478603-a8260980-f65c-11e9-9810-3c5fa491a770.gif)

**Comment by johnhbenetech** [comment]
@NeilMBenetech can you take a look at this implementation and make any recommendations

**Comment by NeilMBenetech** [comment]
@johnhbenetech this is looking really nice. Couple of comments:
1. In the last two screen captures, the Locations are giving the name of the location rather than the Address 1 + City. I think we should always use Address 1 + City for Locations, never the name, as that could be less meaningful/accurate, especially when comparing across partners.
2. What is the sorting algo for Locations and Services in the drop-down box? Looks like there is no sorting. I think we should sort alphabetically for Services, at least, by name. For Locations, what do you think about sorting first by City name and then by Address 1 ?

**Comment by bognasoldev89** [comment]
@NeilMBenetech it seems like your comments are fulfilled now.

1. I found Location with Location name and now on the dropdown list Address 1 + City is visible, as presented on the screenshot:
![384 loc address line](https://user-images.githubusercontent.com/51324797/68209183-1a8ad800-ffd3-11e9-9ab3-09ca954ede3f.png)

2. Locations and Services are sorted alphabetically:
![384 loc alphabet](https://user-images.githubusercontent.com/51324797/68209219-2d9da800-ffd3-11e9-8a56-fcdd681a2597.gif)

![384 serv alphabet](https://user-images.githubusercontent.com/51324797/68209221-2d9da800-ffd3-11e9-8e80-d1e8e410f30c.gif)

@NeilMBenetech I think it's OK now, but maybe you want to take another look?

**Comment by bognasoldev89** [comment]
@NeilMBenetech I see you added a new label but didn't confirm that you want to check it additionally. Is it good to go? In my opinion, all of the issues are resolved.
cc @johnhbenetech

**Comment by NeilMBenetech** [comment]
@bognasoldev89 @johnhbenetech looks good to me I think this one is done.

**Comment by NeilMBenetech** [comment]
@bognasoldev89 @johnhbenetech Oops, I spoke too soon. The dropdown is overlapping the "Next/Prev" selector. See screen shot. Using Google Chrome on Windows. I think the <select> element is too wide or needs to wrap text in each of the <option> elements so it doesnt expand to be too wide.
<img width="801" alt="Capture" src="https://user-images.githubusercontent.com/52297301/68900189-2750af80-06e8-11ea-91fc-4e14f7696180.PNG">

**Comment by NeilMBenetech** [comment]
<img width="801" alt="Capture" src="https://user-images.githubusercontent.com/52297301/68900229-3df70680-06e8-11ea-9d90-5d76736f6bc3.PNG">

**Comment by awalkowiak** [comment]
@NeilMBenetech I think it is because of the checkbox and icon on right hand side of the select which were added after the select feature. I think this should be a quick styling fix.

**Comment by bognasoldev89** [comment]
@NeilMBenetech can you tell us what screen resolution do you use?

**Comment by NeilMBenetech** [comment]
@bognasoldev89 I was on my laptop at 1920 x 1080.

**Comment by awalkowiak** [comment]
@NeilMBenetech were you resizing browser window or zooming in/out? Or do you have this selector constantly overlapping?

**Comment by NeilMBenetech** [comment]
@awalkowiak negative, I was full-screen with Google Chrome on my Windows 10 desktop machine.

**Comment by bognasoldev89** [comment]
Seems good now!

![384 working](https://user-images.githubusercontent.com/51324797/70036870-d7159080-15b5-11ea-8c65-190979b38e98.gif)
