### ISSUE TITLE
Marketing - super nice well designed home page

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#387]
Clotilde to ask marketing to help us on this task

**Comment by CloVasco** [comment]
@johnhbenetech here is the visual provided by the Marketing team. 
For the “Play Video” button, Michael was thinking of linking it to a pop up of the Service Net video on YouTube.
![Service_Net Webpage Mock Up ](https://user-images.githubusercontent.com/21065773/57740455-dabee580-766c-11e9-957b-e55ae0970905.png)

**Comment by CloVasco** [comment]
@johnhbenetech - this replaces #328 that you have in your Soldevolo project board

**Comment by johnhbenetech** [comment]
@clovasco looks good. I'll need the hi-res image files for the logo/service net text and the hero image

**Comment by CloVasco** [comment]
@johnhbenetech Here you go. 
![Benetech_Service_Net_Temp_Logo](https://user-images.githubusercontent.com/21065773/57799609-4dc76b00-7704-11e9-8de3-e8219904fb62.png)
![ServiceNet-PageBg](https://user-images.githubusercontent.com/21065773/57799610-4dc76b00-7704-11e9-96d0-91745232300c.jpg)
![Header_Mom and daughter at clinic](https://user-images.githubusercontent.com/21065773/57799611-4dc76b00-7704-11e9-921a-e3c84f8ef939.png)

And Michael also told me that the baby blue background color is #ddecf3. The button color is #b74900.

**Comment by awalkowiak** [comment]
@johnhbenetech @CloVasco Do you have this picture of "3 people connected" (the one that is on top of the blueish picture). I could use temporary something from fontawesome, but i can't find something that will look close to the one that you used (eg. https://fontawesome.com/icons/users?style=solid)

**Comment by johnhbenetech** [comment]
I'll look into it.

Also the play video link should go to: https://www.youtube.com/watch?v=bfoh5CXzWNk

**Comment by awalkowiak** [comment]
@johnhbenetech thanks this was the other thing that i wanted to ask. Thanks. 

btw. here is a sneak peek of current state of this page:
![Selection_283](https://user-images.githubusercontent.com/12113312/58573249-9ff8a800-823d-11e9-9a93-3f1a84b0b572.png)

**Comment by johnhbenetech** [comment]
let's go with the attached for now
[image2vector.zip](https://github.com/benetech/ServiceNet/files/3233465/image2vector.zip)

**Comment by johnhbenetech** [comment]
Can we also put a little JS to update the copyright in the footer automatically to the current year?

**Comment by johnhbenetech** [comment]
@awalkowiak can we fix some small issues with mobile responsiveness? I know the whole app isn't necessarily responsive, but i'd like the home page to be.

1. I think it should be pretty easy. The icon and "connecting..." text should move below the hero image on mobile.

2. The sign in button text overflows and doesnt display accurately

3. the body text overflows out side of div

![image](https://user-images.githubusercontent.com/12927553/58838530-8e8c1300-8624-11e9-995c-f27658e8827d.png)

**Comment by awalkowiak** [comment]
@johnhbenetech I was not thinking about the mobile responsiveness as at beginning of project there was said, that we don't need it. But ofc I'll fix this today :)

**Comment by awalkowiak** [comment]
@awalkowiak remember to fix issue related to links in header:
![Selection_299](https://user-images.githubusercontent.com/12113312/58892208-17bb4c80-86ee-11e9-89f4-ee8d48bc8b29.png)

**Comment by awalkowiak** [comment]
@johnhbenetech it is hard to use provided images for backgrounds on mobile (readability is very low). I can set the background color as blue and light grey (taken from provided images) are you ok with this solution? Here is how it looks like:
![Selection_308](https://user-images.githubusercontent.com/12113312/59029696-44db3c80-885f-11e9-98b2-99b77a9c667e.png)

**Comment by johnhbenetech** [comment]
Yes, looks fine!

________________________________

**Comment by bognasoldev89** [comment]
@johnhbenetech I was exploring the homepage on my mobile phone and I have a few issues about it. I think it would be better to adjust the upper panel that logo would be in the middle of it, making place for menu icon in the same line. For now it slightly overlaps the content of the app. It's ready to use, it just could look better. Just look:
![Screenshot_2019-06-07-14-04-03](https://user-images.githubusercontent.com/51324797/59103557-7faca580-892f-11e9-9515-dcf0e545295f.png)

One cosmetics issue, it would look better in "About" page if the text was justified. As it is now it looks ok on the computer, but not so good on the mobile browser.

**Comment by awalkowiak** [comment]
@johnhbenetech is it ok for hiding "version - SNAPSHOT" on mobile? This simple change would easily fix the issue with header.

**Comment by johnhbenetech** [comment]
@awalkowiak We can hide that throughout

**Comment by bognasoldev89** [comment]
Confirmed that issues from comment are resolved, homepage looks great
