### ISSUE TITLE
Run checkstyle when starting tests

### ISSUE THREAD

**Issue by pmuchowski** [benetech/ServiceNet#395]
The checkstyle should start when `./mvnw test` command is used.

**Comment by pmuchowski** [comment]
@johnhbenetech can we make this change? I think it should simplify the development process.

**Comment by johnhbenetech** [comment]
@pmuchowski yes go ahead

**Comment by pmuchowski** [comment]
To start it before the test I added it on compile. Also I created another ticket for the PMD check: #399

**Comment by kkaczmarczyk** [comment]
This should be fixed now.
