### ISSUE TITLE
Post Data Updates, certain user accounts ISE after login

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#396]
See #291 for more history

This is happening in production after doing weekly data updates. After some point in the data update process, all users attached to a system account can no longer see the main views of the app. They are allowed to log in, but attempting to load the main page data results in an ISE.

 A fatal ISE occurs rendering the platform useless for this user. The error seems to reference being unable to find an entity. I have to assume then that the platform is expecting something from the first version of the record that no longer exists. I haven't gone as deep as to ensure each entity's ID remains consistent across updates (and maybe it shouldn't if the approach is just to make a new entity). But the log below seems to indicate that maybe a Contact entity couldnt be found. There was no more log activity following that so I think it killed any subsequent attempt to display records.

javax.persistence.EntityNotFoundException: Unable to find org.benetech.servicenet.domain.Contact with id ce59cfb3-eed7-4610-afc2-dafdd874cc8e

another example:
Internal Server Error javax.persistence.EntityNotFoundException: Unable to find org.benetech.servicenet.domain.Language with id 9e0aa277-3767-49b8-9147-d6ad930cfa20 at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:159)

The only work around i have found is after the data update/matching completes for all partner data, I need to stop the app docker and restart the app docker. Once the container boots back up, the previously blocked users are functioning normally again.

Maybe this is a cache thing? If we cant track it down can we at least try/catch the initial data loading so the platform's main function works regardless.

**Comment by kkrawczyk123** [comment]
Testing currently blocked by https://github.com/benetech/ServiceNet/issues/412

**Comment by kkrawczyk123** [comment]
Confirmed that I am able to update data in each try. I haven't encountered any problems.
