### ISSUE TITLE
Enable PMD check and fix all PMD issues

### ISSUE THREAD

**Issue by pmuchowski** [benetech/ServiceNet#399]
The PMD check was disabled, when I enabled it there was over 500 issues. I left it disabled for now, but we should fix all of the PMD issues and reenable it.

**Comment by pmuchowski** [comment]
@johnhbenetech what do you think, is this something we should work on now or should this be done later?

**Comment by johnhbenetech** [comment]
We can put this off till later. Get a few more front end changes in first.

________________________________

**Comment by pmuchowski** [comment]
ok, can you move it down in the "Up Next" column then?
