### ISSUE TITLE
Don't create conflict if partner's field is empty

### ISSUE THREAD

**Issue by pmuchowski** [benetech/ServiceNet#403]
In case some field has different value in some organization and matched partner's organization, two conflicts are created (for each of those two organizations). If one of the organization's field has empty value conflict should not be created for its matched organization.

**Comment by kkrawczyk123** [comment]
@pmuchowski I have noticed the case where I have removed the content of conflicted fields (Description and website) of the partner, upload file and the content of both fields is removed but the conflicts are still visible for the organization. See the attached screenshot:
![Screenshot from 2019-05-16 18-09-55](https://user-images.githubusercontent.com/33342488/57869908-52744800-7806-11e9-84b5-d4f42641d4eb.png)
Please investigate the issue.

**Comment by kkrawczyk123** [comment]
Confirmed that issue has been fixed. However, the conflicts are not updated immediately but with a little delay.
