### ISSUE TITLE
Gracefully handle errors during data imports

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#405]
I'm worried there has been a misunderstanding with how the data adapters should work, and I want to make sure we are on the same page.

After the latest changes to the adapters checked into the dev branch, there are lots of new errors and failures of data processing - and I'm not sure exactly how things work anymore. 

The data we are collecting is ugly, human entered, non-normalized, unstructured, data. Our job is to:

* Take that raw information into our system through an API or a data upload

* Our first priority is to get absolutely as much data as possible into our system from that raw data - even if it is messy, even if it is not currently normalized, even if it doesn't adhere to a specific data type we think it should. 

* After we get that data into the system, after we take multiple updates week after week, after we understand the variability of data in that data - only then should we look at a field-by-field basis about how we might extract more structured, more normalize, and more specific data typed fields.

I worry we are taking a way too strict approach right now that isn't realistic for our use case and ultimately negatively affects the goals of our process. We need to:

* Ensure our postgres column types aren't too restrictive, largely aren't mandatory, are large enough, and are of a generic type so that they can take in the data we see regularly

* Ensure our processing scripts are very resilient - if a field is empty, if a field is too large, if a field is mistyped, etc etc - We need the processing scripts to catch those exceptions, skip that field if necessary, and continue to successfully import the rest of that record and DEFINITELY the rest of the records in that upload

**Comment by johnhbenetech** [comment]
The main goal here is to help me understand how it works today, and what we need to do to get it closer as descibed above (if it isn't already)

To talk about specific issues, in recent API job runs and/or data uploads I believe these jobs are running into errors (potentially even on the first records) and fatally failing and not processing the remaining records in the update. As stated above, these jobs should log errors, but should always recover and complete the rest of the job. Some examples of new errors which I don't believe should exist and should definitely not cause the job to fatally fail:

java.lang.NumberFormatException: For input string: "5pm"

Skipping organization with name: COUNTY OF SANTA CRUZ HUMAN SERVICES WORKFORCE

java.lang.NullPointerException: null at java.base/java.util.Arrays.stream(Arrays.java:5614) at org.benetech.servicenet.adapter.icarol.ICarolConfidentialFieldsMapper.extractNameIfNotConfidential(ICarolConfidentialFieldsMapper.java:47)

java.lang.IllegalArgumentException: Accessibility for disabilities cannot be empty

**Comment by johnhbenetech** [comment]
Another key point here is that unit tests aren't enough. Developers should be running the actual API jobs and doing actual CSV data uploads (using real data from the repo) after doing significant changes to major data scripts

**Comment by johnhbenetech** [comment]
@awalkowiak I don't know if others are seeing this, but for icarol upload i'm getting a lot of failures that result in no data being taken in.

There were 100+ errors like this:
2019-05-20 19:24:49.565  INFO 9 --- [ryBean_Worker-3] o.b.s.adapter.icarol.RelationManager     : Saving data for ICarol: 0% completed
2019-05-20 19:24:49.581 ERROR 9 --- [ryBean_Worker-3] o.b.s.manager.ImportManagerImpl          : null
2019-05-20 19:24:49.581  INFO 9 --- [ryBean_Worker-3] o.b.s.adapter.icarol.RelationManager     : Saving data for ICarol: 0% completed
2019-05-20 19:24:49.584 ERROR 9 --- [ryBean_Worker-3] o.b.s.manager.ImportManagerImpl          : null


Anyway to make that null more verbose?

**Comment by johnhbenetech** [comment]
Additionally, I've been having issues with healthleads job - lots of errors like the following:


2019-05-20 21:55:39.524  WARN 9 --- [  XNIO-2 task-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 23505
2019-05-20 21:55:39.524 ERROR 9 --- [  XNIO-2 task-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: duplicate key value violates unique constraint "ux_service_at_location_srvc_id"
  Detail: Key (srvc_id)=(7823f01f-a860-460c-9e07-e52537fb77f4) already exists.
2019-05-20 21:55:39.524  WARN 9 --- [  XNIO-2 task-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 23505
2019-05-20 21:55:39.524 ERROR 9 --- [  XNIO-2 task-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: duplicate key value violates unique constraint "ux_service_at_location_srvc_id"
  Detail: Key (srvc_id)=(7823f01f-a860-460c-9e07-e52537fb77f4) already exists.

**Comment by awalkowiak** [comment]
@johnhbenetech null is because we got no message here (https://github.com/benetech/ServiceNet/blob/dev/src/main/java/org/benetech/servicenet/manager/ImportManagerImpl.java#L67). I'll add stacktrace to error message and I try to debug this issue, to check what is going on there.

Regarding service_at_location exception, @pmuchowski do you have any idea why this might occur? I remember, that you were implementing that part.

**Comment by pmuchowski** [comment]
@awalkowiak @johnhbenetech there were some serviceAtLocation records with empty providerName, I think this was causing the issue. I removed those records, so it should work fine now.

**Comment by awalkowiak** [comment]
@johnhbenetech regarding the iCarol issues: I have not seen any problems during downloading data for UWBA (either update on existing db or downloading all into empty db), for Eden I only had issue with Google Api (probably I have old key), but no "null" issues. I can push improved logger (with stacktrace logging), then we could see what the exception is.

**Comment by kkrawczyk123** [comment]
@awalkowiak I have noticed that uploading an organization name longer than 255 letters is not working. I was checking on LAAC data.

**Comment by awalkowiak** [comment]
@kkrawczyk123 I managed to reproduce this bug. However the issue here is not related to Organization name, but to Location name. For LAAC we take the org name and add " - Location" to it and then we save this in db. Unfortunately, location name can not be longer than 255, hence the issue. All other providers should work fine (I'll fix the LAAC, but you should be able to check other providers).
@johnhbenetech fyi: I am removing the length limit on this field (Location.name).

**Comment by kkrawczyk123** [comment]
@awalkowiak small update: I have also checked other providers. Uploading an organization name longer than 255 letters worked for healthleads and SMC. It doesn't work for LAAC, Eden and UWBA. ShelterTech file upload failed for me. Do you have any ideas why?

**Comment by awalkowiak** [comment]
@kkrawczyk123 I have no idea why ShelterTech failed, will investigate that. 
Locally I also checked iCarol name longer that 255 and no update was made and there was no exception/error. I need to investigate this further.

**Comment by awalkowiak** [comment]
@kkrawczyk123 I fixed LAAC (iCarol and sheltertech still needs more investigation, see: https://github.com/benetech/ServiceNet/issues/472). I'll let you know once LAAC fix is deployed.

**Comment by bognasoldev89** [comment]
@johnhbenetech I was trying to upload a small number of records with services e-mail longer than required (as an admin, healthleads data). In this upload I also wanted to change organization name. The app ignored the whole upload because of that e-mail. Shouldn't it skip this error and upload the rest of the data? Or inform user of this error at least?

**Comment by johnhbenetech** [comment]
@bognasoldev89 yes, that's the whole point of this task. Any data provider should be able to upload data even if a few records/sub entities run into errors. There errors should be logged (to standard out as well as data import report) but the rest of the data should be uploaded

**Comment by bognasoldev89** [comment]
@johnhbenetech well it's not working for Healthleads and ShelterTech for sure. I'm still tesitng the other organizations.
There is another problem with ShelterTech upload data. After uploading the app shows information that data couldn't be uploaded, while, in fact, it is.

**Comment by johnhbenetech** [comment]
@bognasoldev89 yeah it sounds like this needs to go back to development :)

I've seen the error before, I think the frontend process just has a timeout - so if it's a long running upload you see those red error boxes. I'm fine dealing with that as long as the data actually gets into the app!

**Comment by awalkowiak** [comment]
@johnhbenetech @bognasoldev89 I'll investigate issues described here

**Comment by bognasoldev89** [comment]
As far as I am concerned, issues brought up above are resolved.
