### ISSUE TITLE
Document steps required for migration in order to release to production

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#427]
For the required changes to the database layer, help john reproduce necessary steps for releasing to production

**Comment by johnhbenetech** [comment]
@pmuchowski 

As I understand it I may need to delete any locations and services where provider_name is null (along with any related entities to those locations/services)

Does anything else need to happen?

**Comment by pmuchowski** [comment]
@johnhbenetech the services and locations with empty provider name should be easy to remove. There was new field added to the conflict - partnerResourceId. It's used in conflict detection to reject outdated conflicts. I needed to run several sql scripts and even update some of the conflicts manually to fill this new field in all of the pending conflicts.
At any time you can use this sql to check if there are any conflicts with no partnerResourceId left:
`select count(c.id) from "conflict" c where c.state = 'PENDING' and partner_resource_id is null;`

First you can try to use metadata and the update date to find partner organization for conflict
`select c.id, count(c.id) from "conflict" c, organization_match m,organization o, metadata
where c.resource_id = m.organization_record_id and m.partner_version_id = o.id and o.account_id = c.partner_id and o.id::text = metadata.resource_id
and c.state = 'PENDING' and partner_resource_id is null and c.offered_value = metadata.replacement_value and c.offered_value_date = metadata.last_action_date and metadata.last_action_type = 'UPDATE'
group by c.id
having count(c.id) > 1;`

if there are some results it means it was not possible to determine partner organization this way, but if there are no results you can safely run the update
`update "conflict" c set partner_resource_id = o.id from organization_match m, organization o, metadata
where c.resource_id = m.organization_record_id and m.partner_version_id = o.id and o.account_id = c.partner_id and o.id::text = metadata.resource_id
and c.state = 'PENDING' and partner_resource_id is null and c.offered_value = metadata.replacement_value and c.offered_value_date = metadata.last_action_date and metadata.last_action_type = 'UPDATE';`

here is the second sql using metadata (you will need to run both of them)
`select c.id, count(c.id) from "conflict" c, organization_match m, organization o, metadata 
where c.resource_id = m.organization_record_id and m.partner_version_id = o.id and o.account_id = c.partner_id and o.id::text = metadata.resource_id
and c.state = 'PENDING' and partner_resource_id is null and c.offered_value_date = metadata.last_action_date and metadata.last_action_type = 'CREATE'
group by c.id
having count(c.id) > 1;`

and if there are not results the update:
`update "conflict" c set partner_resource_id = o.id from organization_match m, organization o, metadata 
where c.resource_id = m.organization_record_id and m.partner_version_id = o.id and o.account_id = c.partner_id and o.id::text = metadata.resource_id
and c.state = 'PENDING' and partner_resource_id is null and c.offered_value_date = metadata.last_action_date and metadata.last_action_type = 'CREATE';`

if there was some results in any of the selects or there are still some conflicts without partnerResourceId you can try to use field names to join the tables, first to find out which fields have multiple results:
`select c.id, c.field_name, count(c.id) from "conflict" c, organization_match m, organization o 
where c.resource_id = m.organization_record_id and m.partner_version_id = o.id and o.account_id = c.partner_id
and c.state = 'PENDING' and partner_resource_id is null
group by c.id, c.field_name
having count(c.id) > 1;`

and then for every field (exapmle for url):
`select c.id, c.field_name, count(c.id) from "conflict" c, organization_match m, organization o 
where c.resource_id = m.organization_record_id and m.partner_version_id = o.id and o.account_id = c.partner_id
and c.state = 'PENDING' and partner_resource_id is null
and c.field_name = 'url' and c.offered_value = o.url
group by c.id, c.field_name
having count(c.id) > 1;`

and if there are no results you can run the update:
`update "conflict" c set partner_resource_id = o.id from organization_match m, organization o 
where c.resource_id = m.organization_record_id and m.partner_version_id = o.id and o.account_id = c.partner_id
and c.state = 'PENDING' and partner_resource_id is null
and c.field_name = 'url' and c.offered_value = o."url";`

for other fields you will need to change this part (for select and update):
`and c.field_name = 'url' and c.offered_value = o."url"`

I'm not sure if there is any other way to find the partner organization for the conflict, so if there will be some results in all of the selects, I think you will need to choose one of the conflicts, add its id to the conditions, remove the group by and add organization id to the select and just pick one of the ids and manually set it in the conflict partner_resource_id field. After this you can rerun the scripts and if there are still some results do the same for another conflict.
