### ISSUE TITLE
Create Shelter Entity

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#428]
Create a new entity called Shelter containing the following fields:

Any fields designated as text should not have length limits. Ignore the "D"/"M" for now, I'm using that as a notation that will become relevant in a later task.

General Info
* Agency Name (text) M
* Program Name (text) M
* Alternate Name (text) D

More Info
* Website (text) D

Eligibility
* Eligibility Details (text) M
* Documents Required (text) M
* Language (multi select) D
- English, Spanish, Russian, Hmong, Vietnamese, Tagalog, Chinese

Process
* Application Process (text) M
* Fees (text) D
* Defined Coverage Area (multi select - counties) D
-  Sacramento, Yolo, Solano, Contra Costa, Sutter, Placer, El Dorado, San Joaquin, Amador

Hours
* Program Hours (text) D
* Holiday Schedule (text) D

Contact
* Email (text)(many to one) M

* Phone Entity (many to one) M
** Phone Number (text) (for each phone) M
** Phone Type (text)(for each phone) M

Location (single) 
* Address 1 (text) M
* Address 2 (text) M
* City (text) M
* Zipcode (text) M
* Location Description (text) D
* Bus service (text) D
* Transportation (text) D
* Disability Access (text) D

Beds
* Number of available beds (number) M
* Waitlist (number) M
* Last updated date (automatic)(for both beds and waitlist) M

Tags (multi select) D, Options as followed:
* Audience Men
* Audience Women
* Audience Families
* Accessible
* Accepts Pets
* Accept personal belongings
* Provide medical beds

**Comment by johnhbenetech** [comment]
@jkondrat Here's a good first task for beginning work on the new project. Please note there are a few intricacies that I'll need some suggestions from you on how to implement.

1. Multi-Select fields. I can imagine doing this by creating a separate entity for each of these fields (with a key back to the shelter entity), but that approach seems a little clunky. How do you think we should handle this? Maybe storing as a pipe-separated value and doing the rendering/validation in the frontend. That seems ugly too though, let me know what you think with the understanding that at some point we will want to display all of the above fields on a single page.

2. Phones. Many Phones can be associated with a Shelter. For each Phone, there are two related text fields - Phone Number, and Phone Type. Once again not sure how to handle this - we will need to display all of these fields on the same page.

3. Bed/Waitlist Audit. These fields are going to change rapidly (potentially multiple times a day). We actually need to record each time these fields are changed (kinda like an audit trail). On the front end we will display only the most recent value (along with the datetime it was last changed), but we need to keep the historic data in the database for reporting purposes.

**Comment by jkondrat** [comment]
Hi @johnhbenetech : 
1. We should be able to easily add and modify the options in these multi-select fields, right? Otherwise, we could simply use enums. I think that the approach with separate entities is also fine, it would allow us to store additional properties if needed. Another solution would be to have a generic table with list of options for each of these multi-select fields (each record having a value and a type).
2. How about separating Phone and PhoneType entities and displaying them as a list/table? 
3. We could insert number of beds, waitlist and the date to a separate table and reference the latest record in the Shelter entity.

**Comment by johnhbenetech** [comment]
@jkondrat

1. Generic table with value/type seems like a good plan for now.

2. Just to be clear, if we make two entities, type will need a join to number. I'm most worried about how we handle this on the admin page (where you add/edit shelters). I want the admins to be able to create a complete shelter record without having to jump between pages for multiple entities. If we feel we can somehow embed the ability to add number/type pairs within the shelter admin page - then I'm fine with this approach.

3. Seems good but with the same concern as 2. The admin needs the ability to update these fields in a single shelter admin screen (without jumping between multiple entity pages)

**Comment by bognasoldev89** [comment]
Creating a shelter entity works fine and looks good, as well as editing it. One thing I couldn't do was to delete a record. ServiceNet shows Internal Server Error.

I also have a small suggestion: that on the page with the list of shelters, from side to side slider was not on the bottom. Later, with a huge list of shelters, it will be inconvenient to scroll down to it every time the user wants to check some information or edit the record.
@johnhbenetech maybe there is a way to align it to the browser?

**Comment by bognasoldev89** [comment]
Confirmed that Shelter Entity is created
