### ISSUE TITLE
Create Shelter listing view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#429]
This is a continuation of #481 with updated mockups. Updated header:

![image](https://user-images.githubusercontent.com/12927553/59389195-5a56d780-8d33-11e9-8445-20e2239caad5.png)
 
chevron down, unexpanded (clickable by clicking anywhere on the accordion menu item, not just the arrow)

when expanded:
![image](https://user-images.githubusercontent.com/12927553/59389831-0a791000-8d35-11e9-9e95-493deb58a7f4.png)

Here's an example with some real data:
![image](https://user-images.githubusercontent.com/12927553/59389223-70fd2e80-8d33-11e9-8b06-6c7b356b2413.png)

**Comment by johnhbenetech** [comment]
@alexrcabral Please provide a mockup showing how fields should be displayed similar to -

![image](https://user-images.githubusercontent.com/12927553/58359741-98568f00-7e4a-11e9-94c1-15de81fe977f.png)

**Comment by bognasoldev89** [comment]
Confirmed that the menu can be expanded and all required info is displayed
