### ISSUE TITLE
Add a list of activities to the main page

### ISSUE THREAD

**Issue by wojtekbu** [benetech/ServiceNet#43]
The parent ticket can be found here: https://github.com/benetech/ServiceNet/issues/11
According to the mock https://user-images.githubusercontent.com/12927553/48443971-55f41d00-e758-11e8-96ad-6596c7a6092c.png add a list of all resources that have been uploaded/read from the logged-in Database Manager’s system.

Acceptance criteria:
- the list should show the same level of information as on the mock,
- the list does not have to look exactly the same as the mock,

**Comment by wojtekbu** [comment]
@johnhbenetech I have a question regarding the mock https://user-images.githubusercontent.com/12927553/48443971-55f41d00-e758-11e8-96ad-6596c7a6092c.png
Should an 'x' button reject the updates or just postpone it?
Should we display all resources on the activities' list or just the updated ones?

**Comment by johnhbenetech** [comment]
I think we should display all resources but always sort those with updates to the top of the list.

As for the 'x', I'm open to suggestions. I think the ideal interaction would be that clicking the 'x' hides/deprioritizes that record until a new conflict/update is found. this would probably require a new meta field like UserID/RecordID/NoUpdateBeforeDate or something. Seems like a lot of hassle for right now.

I think you can just break the 'x' into a different task and we can revisit it after the main features are built.

**Comment by wojtekbu** [comment]
@johnhbenetech  according to the update meeting 12/11/18:

- every notification element on the list will have a full list of activities. We will revisit this solution later adjust it for example by adding unfold button,
- the list should be available on one page with a possibility to load more notifications. An amount of notification per one fetch will be adjusted in next iterations,
- blue - there is a conflict for resources which we believe are a match (synchronization for the first time),
- yellow/orange - there is a conflict for resources which were synchronized at least once,
- red - the same situation as for 'yellow/orange' but more than one provider decided to approve this version.

**Comment by wojtekbu** [comment]
Services types are not available yet so tag like 'Housing' will be added later

**Comment by oskarhinc** [comment]
I can confirm it's showing required information for mocked data
