### ISSUE TITLE
Allow for shelter filtering

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#430]
The main view described in #429 needs to allow the user to filter the shelters they are being shown

The first set of filters (these combinations should be AND logic)

1. Allowing users to multiselect entries that associate with the Shelter.Tags data. This filter should work as an AND (not OR) filter - i.e. all of the selected tags must be present in the displayed shelters (there can be additional tags on the shelters however).

2. 'Only show beds currently available. This will filter out any shelters where the latest Shelter.BedCount is 0

3. Change County. This corresponds to Shelter.CoverageArea. This should return any Shelters in which the coverage area selections contained the county specifed in the filter dropdown.

Filters should be applied after hitting Update Search

We will break out search and sort into separate tasks. 
 

![image](https://user-images.githubusercontent.com/12927553/58362018-5f251b80-7e58-11e9-9946-4bb24049644d.png)

**Comment by bognasoldev89** [comment]
Confirmed that filtering feature works fine
