### ISSUE TITLE
Route 'Sacramento' users to Shelter homepage (instead of current organization homepage)

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#432]
For users with the 'Sacramento' User Profile, when they log in they shouldn't be brought to the current main view.

They should be brought to the main view that will be outlined in #429 

Please set up a placeholder page and adjust routing for those users.

**Comment by bognasoldev89** [comment]
Confirmed that placeholder page for the main view is displayed when logged in as "Sacramento" user.
