### ISSUE TITLE
Create user setting to allow 'Sacramento' users to be owner of one or more shelter entities

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#433]
As an admin on the user management page:

when a user has the role 'Sacramento' I need a field to be added which allows the admin to select one or more of the existing shelter entities to associate with this user.

The shelter search/selection can be based on shelter name. Shelters should be able to be associated or disassociated with a user at any time.

A user should be able to be associated with multiple shelters or no shelter.

A shelter can be associated with multiple users or no user.

I will refer to this concept as a user being an "owner" of a shelter.

**Comment by bognasoldev89** [comment]
I confirm that a new field in editing page for users with sacramento role is created (it's not there for regular users):

![433 1](https://user-images.githubusercontent.com/51324797/68874856-2d538a00-0702-11ea-9faa-9d6d08fc8c04.png)

"My Shelters" is created in users' accounts if they are owners of shelter and list of shelters is consistent with those chosen in user management

![433 2](https://user-images.githubusercontent.com/51324797/68875007-655acd00-0702-11ea-86d1-0fd6c828d4c6.png)

"Regular" sacramentouser doesn't see "My Shelters" in the upper panel:

![433 3](https://user-images.githubusercontent.com/51324797/68875128-9a671f80-0702-11ea-9a54-f76dc70adeea.png)

I also managed to associate one shelter for many owners.
In my opinion, this functionality works well.

**Comment by bognasoldev89** [comment]
@johnhbenetech @awalkowiak proposed to create responsive fields during creation of users with different roles. For example, when admin creates a new user and gives him role sacramento, field "Shelters" could appear (same for regular users and "System account" field). 
At this moment a new sacramento user has to be created and saved and shelter can be chosen during editing users. And "System account" field is always present even if it's not needed to sacramento users.
So, what do you think, @johnhbenetech ? It can be done in the scope of this ticket, but I can create a new issue for that. Or maybe it's redundant?

**Comment by johnhbenetech** [comment]
You can create a separate ticket and put in backlog. Thanks

________________________________
