### ISSUE TITLE
Discovery feature - records not in your own database

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#440]
-Landing Page
Enable all users to be able to see all records. We need to enable users to make a clear difference between records that they have and records they don’t have in their directory. Proposition – have 2 tabs on the landing page – one for records they have (what we have today) and one for other agencies they don’t have. Users need to be able to sort/filter/search on those 2 tabs
Laura –we need a visual for those 2 tabs

-Cards
In the discovery tab, what will the cards display on the left as the name of the card if 3 partners have this record with 3 different name..? the easiest solution seems to have 3 different cards for the 3 different partners’ records. 
We’ll need a visual for this as well – or at least a clear understand of what info we put in there. If we use this imperfect but easy solution, we’d have (name of the record on the left – name of the partner and last day of update on the right. That’s it. 
Laura – do you agree? Do you have a better solution?

-Single view 
But if we apply this solution, I think it would be better if users can view those 3 records and “compare them” – meaning if they click on one of those 3 cards, they’d have access to our single view page today and on this page, they would see that 3 partners have it and they’d be able to toggle between them (basically the right potion of our side by side view we have today)

-Side by side view
An idea that would be great if possible would be to provide them a side by side view through which they’d be able to compare those records from partners.. it’d be basically the right potion of our current side by side view both on the right and on the left. John – you didn’t seem to think that this was easy. If it’s not, let’s not do it but at least provide a single view on which they can toggle between records. 

@laurabenetech - please send me through email your comments/suggestions/questions and I’ll answer them through email. Then John will tell you if we actually do this or not. 
@johnhbenetech – Laura told me a while ago that she is not working between tomorrow afternoon and Wednesday. So she’d be able to help next Thursday and Friday.

**Comment by laurabenetech** [comment]
Thanks @CloVasco I'll answer these in separate comments so this doesn't get overwhelming.

**Comment by laurabenetech** [comment]
-Landing Page
Enable all users to be able to see all records. We need to enable users to make a clear difference between records that they have and records they don’t have in their directory. Proposition – have 2 tabs on the landing page – one for records they have (what we have today) and one for other agencies they don’t have. Users need to be able to sort/filter/search on those 2 tabs
Laura –we need a visual for those 2 tabs
@CloVasco The two tab design ok for now since this is a quick solution and you said it’s the simplest to implement. However, I recommend revisiting this for the major overhaul of the design, especially after we get feedback from users about this two-tab design. 
**Question:** I’m not quite clear about what you want to happen when they click on the Discovery tab. I recommend they are offered the same experience that they have with their matched records in terms of being able to search, sort, and filter on all records, just the way they do with their matched records—is that what you’re describing as well here?

**Comment by laurabenetech** [comment]
-Cards
In the discovery tab, what will the cards display on the left as the name of the card if 3 partners have this record with 3 different name..? the easiest solution seems to have 3 different cards for the 3 different partners’ records.
We’ll need a visual for this as well – or at least a clear understand of what info we put in there. If we use this imperfect but easy solution, we’d have (name of the record on the left – name of the partner and last day of update on the right. That’s it.
Laura – do you agree? Do you have a better solution?
@CloVasco This seems okay for the immediate short term solution, and we can get feedback from partners about what is important for them to see in this view.

**Comment by laurabenetech** [comment]
Clotilde's description: -Single view 
But if we apply this solution, I think it would be better if users can view those 3 records and “compare them” – meaning if they click on one of those 3 cards, they’d have access to our single view page today and on this page, they would see that 3 partners have it and they’d be able to toggle between them (basically the right potion of our side by side view we have today)
@CloVasco **Question:** I’m not quite sure what you mean by **toggling** through records. Would this be the same as how we’re currently doing the single view, with the only difference being that the user could click on any of the 3 partner links to go to a page that displays the particular partner record?
**Partner record on left side**	Compare Window would display links:, **Partner 1 link**, **Partner 2 link**, **Partner 3 link**
Clicking on a Partner link in that Compare window **goes to a page** showing that record? **Without** showing the partner record on left side? @johnhbenetech is this doable without being too technically difficult to implement?

**Comment by laurabenetech** [comment]
Clotilde's description: -Side by side view
An idea that would be great if possible would be to provide them a side by side view through which they’d be able to compare those records from partners.. it’d be basically the right potion of our current side by side view both on the right and on the left. John – you didn’t seem to think that this was easy. If it’s not, let’s not do it but at least provide a single view on which they can toggle between records.
@CloVasco @johnhbenetech This would be fine if it’s technically feasible. Just to make sure I understand: on **left** side is Partner 1 and the right side they could **cycle through Partner 2, 3, 4, etc. using See Next Match button**. 
The user would first need to choose which partner they want to see comparisons of, and have that **one partner remain stable on the left side**, while the other partner matches cycle through. If that's the case, I’d just need to include in the UI design a way that enables users to choose which partner record they want to see matches of.

**Comment by CloVasco** [comment]
-Landing Page
_**Question:** I’m not quite clear about what you want to happen when they click on the Discovery tab. I recommend they are offered the same experience that they have with their matched records in terms of being able to search, sort, and filter on all records, just the way they do with their matched records—is that what you’re describing as well here? 
Correct - this is what I am describing

**Comment by CloVasco** [comment]
-Single view
_@CloVasco **Question:** I’m not quite sure what you mean by **toggling** through records. Would this be the same as how we’re currently doing the single view, with the only difference being that the user could click on any of the 3 partner links to go to a page that displays the particular partner record?
> **Partner record on left side**	Compare Window would display links:, **Partner 1 link**, **Partner 2 link**, **Partner 3 link**
> Clicking on a Partner link in that Compare window **goes to a page** showing that record? **Without** showing the partner record on left side? @johnhbenetech is this doable without being too technically difficult to implement?_

Laura - not sure I understand your description. Example of what I have in  mind: I'm UWBA and don't have the EHRA record. On the discovery tab, I see that 2 other partners have it. So I see 2 cards: "Housing Economic Rights Advocates (HERA)" from LAAC and "HERA" from Eden. 
If I click on the LAAC record, I'd have access to the single page view with the LAAC's record. but if I want, I can click to see Eden's record.. (so even though there were 2 cards on the discovery tab, I can see both on the single view and can switch between one and the other. does that make sense? 

![Visual_single page with button to toggle btw similar records](https://user-images.githubusercontent.com/21065773/58368077-ac2ae100-7e9c-11e9-9763-f42ba0cdbf7d.png)

**Comment by CloVasco** [comment]
_-Side by side view
> The user would first need to choose which partner they want to see comparisons of, and have that **one partner remain stable on the left side**, while the other partner matches cycle through._ 
We could do it even more simply if we want and enable user to change both the right and left sides. that way we can leverage what we have on the current side by side view page (what we have on the right side).. 
@johnhbenetech what do you think?

**Comment by NeilMBenetech** [comment]
@johnhbenetech Might I suggest a simplification for this one that would be consistent with other filtering options we have in mind for the short- and medium-term. 

On the current main search page, let's allow a user to indicate which partner database(s) they are targeting for their search, with the default being their own database.  But they have the ability to target any other partners' database, and whatever selection they make will be retained for that user, for every subsequent search they make until they change it again.

It would probably be most simple to allow them to target exactly one partner database at a time, which would remove the need for thinking about how to display results from multiple partners' databases where the records are equivalent but not necessarily named the same thing. If we go this route then the UI element could just be a simple drop-down list with single-selection capability.

However it could be laborious for the user to have to conduct their search multiple times, one for each partner database they want to look in. So we may want to allow for multi-selection of target partner databases and OR the results together. If so, then I would support Laura and Clotilde's ideas earlier in this item to display all results from every partner database with some visual differentiation. For those results that don't match to the user's own database, the "side by side" view will collapse to only showing the parnters' records but for consistency I recommend that the left column be essentially blank but with a message at the top indicating "You do not have a matching record in your own database" and continue showing the partner records in the right column.

All other search filters would be incorporated (geography, category/taxonomy, etc) in this search along with this partner database selection.

**Comment by johnhbenetech** [comment]
@NeilMBenetech 
Any thoughts on UI for the partner selector? I assume you're thinking it wouldnt be under the filter accordion, but rather at the top level?

Any suggestions for how we might visually differentiate the 'not your' records in the list display?

If we decide to allow for looking at multiple partners simultaneously:
In the case where lets say 3 other partners have a record you dont have - are you suggesting we display a card for each of 3 records on the main list? If you only want one record how do we choose which of the three record's org titles to choose for the card?

**Comment by NeilMBenetech** [comment]
@johnhbenetech we should think through all the various filters we're considering to put in place. Given the currently implemented motif, it would probably make sense to put them in the Filter accordion. The filter for category/taxonomy will likely take up a bit of real estate if we allow a browse-able hierarchical tree. It might need its own accordion especially to render well on a mobile device.

Is Toptal recommending any visual changes that might affect filtering?

Good points in the scenario where we're allowing search on more than one partner database at a time. A good reason to punt this until later unless you have more solid ideas than I'm coming up with now. Perhaps we show your org's card if there is a match, if not we need some way to figure out which other org's card to primarily show, and then have some sort of visual stacking (I'm thinking a la Google Material Design) underneath to show and give access to the other ones upon clicking.

**Comment by johnhbenetech** [comment]
@NeilMBenetech The current rec is to move it into a sidebar

![image](https://user-images.githubusercontent.com/12927553/61810423-d51c1380-ae04-11e9-857f-902be4118c01.png)

**Comment by johnhbenetech** [comment]
@NeilMBenetech 

One thing to look at is the current 'Partner Sources' filter. What it does is allow a user to only show records that have a match to the partners you selected.

Does the discovery feature obviate/complicate this filter? Should we just change that filter into the discovery feature with a different title like "Include Partner Records"


Yeah lets start with single partner and go from there.

**Comment by NeilMBenetech** [comment]
Ooo I like the Partner Sources selector. But it's currently serving a slightly different function ("show me matching records from these particular partners") than this new Discovery ("show me records I don't have from this/these particular partner(s)").

If we retain this one and add a new one it may be confusing, right? So perhaps we should rename "Partner Sources" to "Show matching records from....". But then I'm not sure how to clearly name the Discovery function to make it clear that it is different. Maybe : "Show records I don't have from..." ? 

If that sounds too confusing (which it kind of does to me) we should probably just collapse this into one filter named "Search in partner databases", retain the ability to multi-select, and just perform the search on both "discovery" and "matching" records. Then a checkbox beneath it to optionally "Just show partner records that match ones I already have", default = selected. What do you think?

**Comment by johnhbenetech** [comment]
@NeilMBenetech I guess I don't necessarily buy the need for "show me matching records from these particular partners". It's not being used, and i think it's weirdly anti-trust.

If we retain both it breaks down quickly. Like you need to add a bunch of extra logic and it become very confusing.

For instance: Show me records from UWBA that only have matches to UWBA? So to prevent this we have to change the available options in one filter based on the other.

I like your suggestion. We'll probably go with the following and we can improve copy/UI after we get functionality working.

![image](https://user-images.githubusercontent.com/12927553/61817384-0819d380-ae14-11e9-935b-1be95d3c73c8.png)

**Comment by kkaczmarczyk** [comment]
Update per Slack discussion: 

- add the checkbox filter option "only show matching" somewhere near Partner selection. 
- It should be checked by default
- checked: would work as it is now - displaying Org with Org Matches within user's account
- by unchecking it and clicking 'Filter' button, user would trigger displaying Org with Org Matches unrelated with user's account (without a match to user's records)

**Comment by johnhbenetech** [comment]
@jkondrat Getting a lot of JS console errors:
![image](https://user-images.githubusercontent.com/12927553/63522977-ecf7bd80-c4be-11e9-9728-643b454b1716.png)

**Comment by pmuchowski** [comment]
@johnhbenetech I fixed this issue in my PR

**Comment by bognasoldev89** [comment]
Feature works as expected, I tested a few configurations.

Below some examples
- Another provider records searched by name:

![discovery feature by name](https://user-images.githubusercontent.com/51324797/63866845-2eeb9c80-c9b4-11e9-907e-fe8cf11b2276.png)

- Another provider record found by taxonomy:

![discovery feature by taxonomy](https://user-images.githubusercontent.com/51324797/63866907-4b87d480-c9b4-11e9-980c-c0c6a4d3483d.png)

- Records filtered by date with chosen another provider with "Only show matching" checkbox (without shows longer list of records, including records from other providers, suitable to filtering settings):

![discovery feature by date with checkbox](https://user-images.githubusercontent.com/51324797/63867070-87bb3500-c9b4-11e9-85ee-31d8e2b77d07.gif)
