### ISSUE TITLE
Create detail view for each shelter

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#441]
When a user clicks on 'more info' on the listing view they are are brought to this page for that record:

![image](https://user-images.githubusercontent.com/12927553/59389910-4b712480-8d35-11e9-9457-8cc931007a4f.png)

The top title is {Agency Name}{Program Name} ({alternate name})

Don't worry about the data in parenthesis to the right, nor the map. I will break them out into separate tasks

**Comment by bognasoldev89** [comment]
Confirmed that details page for shelters is created with all fields demanded in this issue.
