### ISSUE TITLE
Create Add and Edit Shelter views for admins

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#442]
For a logged in admin user, they should be able to add new shelter entities and edit existing shelter entities.

This admin page should list all the fields from #428 including:

* Ability to multiselect values for those fields that are multiselect
* Ability to add/edit/remove multiple phone elements (with a phone number and phone type filed for each)

Since this is an admin view it doesn't need to look fancy or anything.

**Comment by bognasoldev89** [comment]
Confirmed that admin can add and edit shelters
