### ISSUE TITLE
Set-up Travis CI for the project

### ISSUE THREAD

**Issue by kkaczmarczyk** [benetech/ServiceNet#448]
As discussed on recent calls we would like to achieve as good code quality as possible. The CI will help with that - it'll run builds, along with tests and static code analysis.

- Travis is a good fit as it provides relative ease of setup, free of charge plan for open source repositories and hosting in the cloud (no need to set-up anything in AWS)
- it will take about 3-8 hours to add 
- I'd need a few clicks of your mouse to authorize Travis Ci per instructions at https://travis-ci.org/getting_started (I don't have admin permissions)
- the rest will be defined in the configuration file '.travis.yml' in the root of the project

Steps to activate Travis CI:
1. Go to https://travis-ci.org/account/repositories
2. Authorize Travis CI to run on 'ServiceNet' repo

**Comment by johnhbenetech** [comment]
Closing this as obsolete
