### ISSUE TITLE
Clarify when conflict detection runs, last update date pulled from

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#450]
After recent changes, I no longer see any logging for conflict detection following the data import/API jobs. Additionally, I don't see records with last updated dates matching my data update jobs.

Is conflict detection still being triggered? Have we suppressed logging?

I think we talked about this, but is last update time pulled from metadata or conflict table.

In production I am also noticing issues with 'Most Recent' sorting no longer being accurate based on the displayed dates. See the screenshot below.

Additionally it seems odd to me that there are dozens and dozens of records with the exact same last update time (to the second) - but maybe that's to be expected if it's an atomic database action.

**Comment by johnhbenetech** [comment]
Example:
![image](https://user-images.githubusercontent.com/12927553/58522991-5306ca00-8188-11e9-946f-8af5aefef186.png)

**Comment by johnhbenetech** [comment]
![image](https://user-images.githubusercontent.com/12927553/58598351-a38e2e00-8241-11e9-8f37-215ecab83865.png)

**Comment by pmuchowski** [comment]
@johnhbenetech the logging in the conflict detection was not changed. The conflict detection was updated, so the conflicts are only recreated if the organization was changed, but it should start on every import, so you should have the "Searching for conflicts between ..." in the logs.

The issue with "last update" date is described in #359.

**Comment by johnhbenetech** [comment]
@pmuchowski  Well for example I just ran all three API jobs - all of which had created/updated organizations - none of which triggered any conflict logging.

so for example a ShleterTech Job - after finishing had no conflict logging even after waiting several minutes:

`2019-05-30 15:46:13.388  INFO 8 --- [ryBean_Worker-4] o.b.s.s.ShelterTechDataUpdateJob         : ShelterTech Data Update Job is being executed
2019-05-30 15:46:25.960  INFO 8 --- [ryBean_Worker-4] o.b.s.s.impl.DocumentUploadServiceImpl   : Data upload for ShelterTech has started
2019-05-30 15:46:30.155 ERROR 8 --- [ryBean_Worker-4] o.b.s.manager.ImportManagerImpl          : Cannot connect with Google Maps API

java.lang.IllegalStateException: Cannot connect with Google Maps API
        at org.benetech.servicenet.matching.counter.GeoApi.geocode(GeoApi.java:49)
...

2019-05-30 15:47:29.877  INFO 8 --- [ryBean_Worker-4] o.b.s.s.impl.DocumentUploadServiceImpl   : Data upload for ShelterTech took: 63917ms`

But the job report indicates several orgs were updated and one was added:

![image](https://user-images.githubusercontent.com/12927553/58645669-6d948c80-82c9-11e9-8d0d-8e6870ea3582.png)

**Comment by pmuchowski** [comment]
@johnhbenetech the exception from Google Maps API is breaking the organization matching, so the match is not created and conflict detection is done for matches.

**Comment by johnhbenetech** [comment]
@pmuchowski But for UWBA and Eden jobs for example, I do not get the google maps error, orgs are created/updated, and there still isnt conflict logging

**Comment by pmuchowski** [comment]
@johnhbenetech are there any matches for those organizations?

**Comment by johnhbenetech** [comment]
@pmuchowski Yes, I see 3 new pairs in organization_match after the job completed.

Does the matching algorithm run anytime an org is updated? Or only when an org is added?

**Comment by pmuchowski** [comment]
@johnhbenetech yes, it's done for every update, but only for active organizations. If the organization is active, even if there are no matches you should have the "Searching for conflicts took ..." in the logs, unless there are some exceptions.

**Comment by johnhbenetech** [comment]
@pmuchowski 

Well I dont see them after trying several different jobs with new orgs and new matches.

I wonder if it just takes a really long time, is that possible? For instance, go onto dev and view the app logs.

A healthleads data import was kicked off at 2019-05-28 17:18:45
A SMC import was kicked off 2019-05-28 17:22:27

No other jobs were kicked off since then (i just did one now but it's irrelevant)

There are some conflict logging at:
2019-05-29 06:51:44 - 13.5 hours later
2019-05-29 17:21:16 - 24 hours later

Then a bunch of conflict logging starting:
2019-05-30 14:57:49 - almost 2 days later

**Comment by pmuchowski** [comment]
@johnhbenetech I don't think it should take that long. The match searching is logging the time, can you find the "Searching for conflicts took ..." in the logs before this conflict detection?

**Comment by johnhbenetech** [comment]
@pmuchowski Yes, sorry when i said 'conflict logging' i meant "searching for conflicts took..." messages

They all report times under a second, so nothing too weird there. But yeah there's like no data related logging/data uploads for days and then suddenly a bunch of 'searching for conflicts' appear.
