### ISSUE TITLE
Add filtering activities to the main page

### ISSUE THREAD

**Issue by wojtekbu** [benetech/ServiceNet#46]
Add a list of resources with related conflicts to the main page
The parent ticket can be found here: https://github.com/benetech/ServiceNet/issues/11
According to the mock https://user-images.githubusercontent.com/12927553/48443971-55f41d00-e758-11e8-96ad-6596c7a6092c.png add filtering activities to the main page.

**Comment by johnhbenetech** [comment]
Also see #19 for more details
