### ISSUE TITLE
Progress bar doesn't recognize the number of results on the page. 

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/ServiceNet#464]
A progress bar always displays the same number of results on the page. Screenshots of examples attached:
![Screenshot from 2019-06-03 11-47-02](https://user-images.githubusercontent.com/33342488/58794026-8ff31680-85f7-11e9-8eaf-2ea6c359629d.png)
![Screenshot from 2019-06-03 11-46-19](https://user-images.githubusercontent.com/33342488/58794027-8ff31680-85f7-11e9-829b-48f0aa1094f9.png)

It used to work properly and displayed:
![Screenshot from 2019-05-16 13-17-37](https://user-images.githubusercontent.com/33342488/58794115-bc0e9780-85f7-11e9-9a49-d5d60c1fd5eb.png)

**Comment by bognasoldev89** [comment]
Confirmed that issue is fixed
