### ISSUE TITLE
Weekdays are not sorted after uploading opening hours data. 

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/ServiceNet#465]
After uploading opening hours data by csv import. Weekdays are not sorted in the correct order in the week they are displayed like randomly, screenshot attached:
![Screenshot from 2019-06-03 13-19-18](https://user-images.githubusercontent.com/33342488/58798352-b23e6180-8602-11e9-9a5f-2e05546ec302.png)
It would be more user-friendly and readable when days will be sorted in the week order.

**Comment by bognasoldev89** [comment]
Confirmed that weekdays are sorted after uploading opening hours data
