### ISSUE TITLE
Get the Last Updated date from the Metadata instead of Conflict

### ISSUE THREAD

**Issue by pmuchowski** [benetech/ServiceNet#469]
On the home page the Last Updated date should be the most recent update date from Organization and all related entities. We can get this date from the Metadata entity. When conflict detection will be added to all entities related to the Organization this should be changed, so the Conflict offeredValueDate is used again.

**Comment by johnhbenetech** [comment]
As discussed on call:

Home page:
* Change 'Last Updated' to 'Last Partner Update'
* This date is the most recent metadata date from all matching partner records

Side by side:
* For 'your' record (the record on the left) it should be the most recent metadata date associated with that record
* For matching partner records (the record on the right) it should be the most recent metadata date associated with each matching record

**Comment by bognasoldev89** [comment]
The ticket is blocked until the pagination issue is resolved ( #199 ). Metadata entity stops browser.

**Comment by bognasoldev89** [comment]
@pmuchowski proposed a different approach to test this issue and it confirmes that issue is solved.
