### ISSUE TITLE
Add "reset" button

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#476]
I think filtering feature would use “reset” or "clear" button that would clear all filtering fields at once beside original way: “unclicking” every field and confirming it by “Apply”

@johnhbenetech  what do You think?

**Comment by mariaogryczak** [comment]
What the button label should be - "clear" or "reset" or different?

**Comment by mariaogryczak** [comment]
@johnhbenetech What the button label should be - "clear" or "reset" or different? Do you want to have message send to Google Analytics like it is while applying filters?

**Comment by johnhbenetech** [comment]
Reset is fine
________________________________

**Comment by johnhbenetech** [comment]
@mariaogryczak reset I fine for label. Yes send a Google analytics event called 'filter reset' (make sure to send username dimension as with other GA events)

**Comment by bognasoldev89** [comment]
Confirmed that "reset" button is working
