### ISSUE TITLE
Create basic structure for main shelter view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#481]
Please see mockup available at: https://h0pkya.axshare.com/page_1.html

note that the 'more info' link is an accordion. We do not yet have the design for which fields will be listed in the accordion - so that will be handled in a separate task.

Additionally, the search and filtering side bar content/functionality will be handled in other tasks. But we will need a visual placeholder in the structure.

Please note the mockups are not intended to be pixel-perfect. Please try to match existing fonts, card styles, etc from the other project views.

**Comment by bognasoldev89** [comment]
Confirmed that basic structure is created
