### ISSUE TITLE
Filters don't clear after logging out and logging in as a different user

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#486]
After applying filters on homepage, logging out and logging in as a different user, filter settings are still as they were in previous user account.

**Comment by kkaczmarczyk** [comment]
@johnhbenetech would you like filters to work similarly to searching and sorting in terms of caching?

**Comment by johnhbenetech** [comment]
They should persist within a session (until cleared) but should be cleared when logging out/session time out. They certainly shouldn't persist across users

**Comment by bognasoldev89** [comment]
Confirmed that filters are cleared after changing users.
