### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#492]
ERROR in /home/ec2-user/SN611/ServiceNet/src/main/webapp/app/modules/account/index.tsx(15,6):
[INFO] TS2322: Type '{ path: string; component: ComponentClass<Pick<ISessionsProps, never>, any> & { WrappedComponent: ComponentType<ISessionsProps>; }; hasAnyAuthorities: string[]; }' is not assignable to type 'Readonly<Pick<IPrivateRouteProps, "path" | "exact" | "strict" | "children" | "location" | "component" | "isAdmin" | "hasAnyAuthorities" | "render" | "sensitive"> & IOwnProps>'.
[INFO]   Property 'isAdmin' is missing in type '{ path: string; component: ComponentClass<Pick<ISessionsProps, never>, any> & { WrappedComponent: ComponentType<ISessionsProps>; }; hasAnyAuthorities: string[]; }'.

**Comment by awalkowiak** [comment]
@johnhbenetech fixed

**Comment by awalkowiak** [comment]
@johnhbenetech  i am closing this issue, since this error does not occur anymore
