### ISSUE TITLE
Add map view to Shelter detail page

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#495]
As seen in:
![image](https://user-images.githubusercontent.com/12927553/59390519-267db100-8d37-11e9-9457-f7f49de186ec.png)

add a map of the shelter address (if available)

I'll leave it up to you how best to implement. We can probably use the existing google api key - but let me know if you recommend a different approach

**Comment by bognasoldev89** [comment]
Confirmed that map view is added to shelter detail page (if the address is available)
