### ISSUE TITLE
Restrict locations shown for UWBA records (both in self and partner views)

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#496]
For UWBA records we do not want to show any Location entities where the county is in the following:

* San Benito
* Santa Cruz 

I'll leave it up to you how best to implement this. Some clarifications:

* The overall record should still show, just not that location records
* Other non San Benito/Santa Cruz locations should still show
* This is only for UWBA records and not for other partners
* These locations should not show for neither a UWBA user nor a partner user who may see a UWBA record in side by side view
* This is not a one-time job and should continue for all future data updates
* This can be entirely in the 'view' portion of the app. they can still be stored in database

look at the previous 'Field Exclusion' work. It's not a clear connection to this task - but could possibly be extended.

**Comment by bognasoldev89** [comment]
Confirmed that locations are restricted for UWBA records
