### ISSUE TITLE
Upper left back button doesn't work as expected on shelter detail view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#557]
https://drive.google.com/file/d/13eC4NG-Zy4cY_ih0z64BBygdSibMm180/view

**Comment by johnhbenetech** [comment]
if logged in as admin you get sent to the shelter admin screen

if logged in as user you get sent to the other main page with no results (since you are a sacramento user not a system account user).

In either case it should just send you back to the main shelter list view.

**Comment by bognasoldev89** [comment]
@johnhbenetech I spotted this too, back button, in this case, seems to skip main shelters view and sends a user to page displayed before it

**Comment by bognasoldev89** [comment]
Confirmed that "Back" button on shelter detail view is fixed and works as expected
