### ISSUE TITLE
Shelter map view doesn't recenter across different results

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#563]
To produce:

Click on shelter 1 with location 1. See map centered accurately

Go back, click shelter 2 with location 2. Map is still centered to location 1

Video: https://drive.google.com/file/d/1KPp8nu5_ucyY_Mw42Wds9XL-5dSWgQrD/view

**Comment by bognasoldev89** [comment]
Confirmed that bug is fixed
