### ISSUE TITLE
ServiceNet Logo should go to shelter view for sacramento users

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#568]
I realized this as part of #541, but any 'home' concept for sacramento users should go to shelter view - including the logo link.

So this gets back to if we have a user with both sacramento and system account set. My gut says just let Sacramento overrule anything else.

Then for internal testing we should just make a separate sacramento user for testing

**Comment by bognasoldev89** [comment]
Unfortunately ServiceNet Logo doesn't work for sacramento users as supposed

**Comment by bognasoldev89** [comment]
Confirmed that ServiceNet logo button work properly now.
