### ISSUE TITLE
The mapped data from the providers should not be duplicated 

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#57]
For each provider, all entities should be persisted only if they're unique. 

Acceptance Criteria: 
1. Same data, persisted twice results in no new entities
2. There are no unwanted duplicated entities within one data upload

**Comment by oskarhinc** [comment]
@wojtekbu mapping is not finished for all partners yet, so I was able to apply it only for Eden data. However, I've created a special service for data imports, that has to be used for data uploads instead of raw EntityManager, so it won't differ for other providers.

**Comment by wojtekbu** [comment]
Works fine
