### ISSUE TITLE
Add filters option for returning records that have locations 'within X miles' of a user-entered location

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#572]
We will need this logic for both the bay are and sacramento projects.

We would like for a user to be able to enter a location (wither by entering an address or potentially clicking a pin on a map).

After getting a GPS for the entered location - a user should be able to ask to return records that have locations within a set distance (5 mi, 10mi, 15 mi for example).

I'm not clear how quickly we will be able to run this filtering on the fly across 1000s of coordinates. I see some vague references to some postgres plugins for this task - let me know of a recommended approach.

**Comment by awalkowiak** [comment]
This will be resolved in https://github.com/benetech/ServiceNet/issues/357
