### ISSUE TITLE
Search - Autosuggest on search box

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#584]
As user types, search box auto-suggests search words and phrases. Clicking on an auto-suggested item performs the search immediately. All filters as currently selected are enforced in that search.

Initially the autosuggested items are the names of the selected record type for this search for the target partner database selected, as described in https://github.com/benetech/ServiceNet/issues/440 .

Ideally, autosuggested items would dynamically reflect ALL of the “Filtering” choices made by user. Example 1: If I am looking for “resources within Santa Clara County”, only autosuggest those that have at least one Location there. Example 2: If I am targeting Service records, don’t show me Organization names.

**Comment by jkondrat** [comment]
@johnhbenetech I just realized that currently the records are filtered and shown as user types which makes autosuggest pointless. Does it make sense to disable that auto-search and only show a couple of suggestions? We could then perform full search when user selects one of them or clicks enter/some button on the page. I imagine this would decrease the database load especially when there are lots of activities.

**Comment by awalkowiak** [comment]
@jkondrat @johnhbenetech personally I think, that having autosuggest together with automatic filtering seems a bad approach. The solution that Jakub suggested is a bit better version of that feature.

**Comment by NeilMBenetech** [comment]
@jkondrat @johnhbenetech If autosearch takes longer than autosuggest would, then I propose we should disable autosearch and that searches only happen when you hit Enter or the Search button. And that we do implement Autosuggest as proposed in this task. Also for some reason this task seemed not to be assigned to a project board so I've put it back into the Product board for revival.

**Comment by johnhbenetech** [comment]
@NeilMBenetech I guess im confused still. Can you give some specific examples of words you imagine would autosuggest?

**Comment by NeilMBenetech** [comment]
@johnhbenetech primarily I would expect the autosuggest of Organization and Service names to be the most useful items.

**Comment by bognasoldev89** [comment]
I confirm that autosuggest works good for Organizations and Services with and without filters applied, within one and more providers.
I also was able to search through other fields, like email or URL, after clicking Apply button.

I have some comments though:
- after a performed search, search field doesn't clear (but behaves like it's cleared)
- dropdown with suggestions is a little too wide comparing to search field.

![584](https://user-images.githubusercontent.com/51324797/69863537-644aa380-129d-11ea-9d0e-f490c59b8c08.gif)

**Comment by bognasoldev89** [comment]
@jkondrat search field still does not clear after deleting content after performed search. Can you please look into it?

**Comment by awalkowiak** [comment]
@jkondrat @bognasoldev89  the search field is clearing properly, but the results are remain filtered by the search value.

**Comment by bognasoldev89** [comment]
@jkondrat try this reproduction steps:
1. perform search
2. hit enter or click name of organization to be sure that search has been done
3. delete the whole organization name from search field using delete or backspace key on keyboard

In the search field placeholder should be visible, not name of deleted organization.

![584](https://user-images.githubusercontent.com/51324797/71181082-bb77de80-2273-11ea-9da0-674c1762448a.gif)

**Comment by bognasoldev89** [comment]
It looks great now!

![584 field working](https://user-images.githubusercontent.com/51324797/71965476-0c8a4b00-3200-11ea-8850-e0929f8d92f7.gif)
