### ISSUE TITLE
Exception when uploading LAAC data

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#614]
There are lots of exceptions when uploading LAAC data on staging. It looks that "findOneWithEagerAssociationsByExternalDbIdAndProviderName" method in ServiceRepository returns multiple results where it should only return one.

> 2019-08-06 09:56:40.126 ERROR 9 --- [  XNIO-2 task-9] o.b.s.manager.ImportManagerImpl          : query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2
> 
> org.springframework.dao.IncorrectResultSizeDataAccessException: query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2
> 	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:378)
> ...
> 	at org.benetech.servicenet.service.impl.ServiceServiceImpl.findWithEagerAssociations(ServiceServiceImpl.java:115)
> 	at org.benetech.servicenet.service.impl.ServiceServiceImpl$$FastClassBySpringCGLIB$$4f4503a3.invoke(<generated>)
> 	...

**Comment by jkondrat** [comment]
While investigating non unique result exceptions on data upload, I noticed that we have duplicate organizations, services and locations on staging (the same external_db_id and provider_name/account_id)
I'm about to create a constraint on the database which would prevent such cases, but we will need to confirm if there are any duplicates on production, if so we will have to review and remove them

**Comment by jkondrat** [comment]
> SELECT * FROM (
>   SELECT
>   (SELECT COUNT(*) FROM service s WHERE s.external_db_id = svc.external_db_id AND s.provider_name = svc.provider_name) AS count,
>   *
>   FROM service svc
> ) x
> WHERE count > 1;
> 
> SELECT * FROM (
>   SELECT
>   (SELECT COUNT(*) FROM location l WHERE l.external_db_id = loc.external_db_id AND l.provider_name = loc.provider_name) AS count,
>   *
>   FROM location loc
> ) x
> WHERE count > 1;
> 
> SELECT * FROM (
>   SELECT
>   (SELECT COUNT(*) FROM organization o WHERE o.external_db_id = org.external_db_id AND o.account_id = org.account_id) AS count,
>   *
>   FROM organization org
> ) x
> WHERE count > 1;

**Comment by kkaczmarczyk** [comment]
@jkondrat anything else concerning this task? Can QA test it?
