### ISSUE TITLE
Create QA approach for testing different user types document

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#616]
Document is important for using defined user roles/types/personas for future testing strategy.

Goal:

- Understand different roles (defined or not) in the system.
- Understand business goal of these users, their purpose.
- Use this knowledge to define future testing approaches.

**Comment by bognasoldev89** [comment]
Hi @NeilMBenetech @johnhbenetech mentioned that you are reviewing this document. What do you think about it? Does it need any improvement?

**Comment by johnhbenetech** [comment]
@bognasoldev89 @NeilMBenetech I ran through it and it looks good. The only thing is it will need to be updated to include the new shelter owner functionality

**Comment by NeilMBenetech** [comment]
@johnhbenetech @bognasoldev89 I don't recall discussing this but it sounds like a good idea.

**Comment by bognasoldev89** [comment]
@johnhbenetech @NeilMBenetech I added information about shelter owner functionality.
Please review this document if it's OK. And if yes, is it supposed to stay on Google Drive or maybe should be put somewhere else, for example, Wiki?

Link to the document: https://docs.google.com/spreadsheets/d/1rqiXVwQpsMJaNlF2o4lIlFhR1nu1lt9bXYiw4inJiWc/edit#gid=0

**Comment by NeilMBenetech** [comment]
@johnhbenetech do you have a place you store technical / QA documentation? If not I can make a home for this in Box somewhere.

**Comment by johnhbenetech** [comment]
@NeilMBenetech There is a wiki option on the github repo so i think thats the obvious place:
https://github.com/benetech/ServiceNet/wiki

**Comment by bognasoldev89** [comment]
@johnhbenetech GitHub doesn't support this form of a table (merged cells) :(. Would it be okay to put the link to GSuite in Wiki (anyone with the link can comment) or should I rework this document to Markdown table?

**Comment by bognasoldev89** [comment]
@johnhbenetech @NeilMBenetech I put the link to Google Spreadsheet on wiki, because I had difficulties to rework this document to Markdown table.
Please let me know if that's OK or should I approach it differently.

Link to Wiki: https://github.com/benetech/ServiceNet/wiki/QA-documentation-for-the-project
