### ISSUE TITLE
Create Testing Strategy document

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#617]
Team (especially testers) needs set of guidelines that explain test design and determines how testing needs to be done.
Testing Strategy document comments on general approach to the ServiceNet app testing.

**Comment by bognasoldev89** [comment]
At last, the document seems to be finished.
@johnhbenetech @NeilMBenetech can you please check Testing Strategy if it suits your needs and can be shared on the wiki? 
Since this is Google Doc, should it be stored like "QA approach for testing different user types" (on Google Drive, link available on wiki page) or should I try to convert this document?

Link to the Strategy: https://docs.google.com/document/d/1_rGUiEu3w4zXlxoB2EVhfWny70_dHSen7Awcs2js7HM/edit?usp=sharing

**Comment by johnhbenetech** [comment]
as discussed, doc URL can be added to wiki

**Comment by bognasoldev89** [comment]
@johnhbenetech so it's done: https://github.com/benetech/ServiceNet/wiki/QA-documentation-for-the-project
