### ISSUE TITLE
Adjust placeholder in search feature to search settings

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#625]
Placeholder text in search feature reacts to "Search On" radio buttons but not to Search fields.

![Screenshot from 2019-08-09 13-12-37](https://user-images.githubusercontent.com/51324797/62776200-2df8d680-baaa-11e9-9f85-f0ea35858cc7.png)
![Screenshot from 2019-08-09 13-13-24](https://user-images.githubusercontent.com/51324797/62776201-2e916d00-baaa-11e9-9716-a48eee30d956.png)
![Screenshot from 2019-08-09 13-13-46](https://user-images.githubusercontent.com/51324797/62776202-2e916d00-baaa-11e9-9a41-36d1237283b8.png)

**Comment by jkondrat** [comment]
@johnhbenetech @bognasoldev89 @kkaczmarczyk :
Maybe it would be enough to remove fields from that placeholder? It would get too long when someone selects lots of them.
I did this in the PR for #639 https://github.com/benetech/ServiceNet/blob/e54b699d390b2a83152d362c90d25e6d1069720d/src/main/webapp/i18n/en/activity.json#L66

**Comment by NeilMBenetech** [comment]
@johnhbenetech I'm not understanding the issue. Is it that the "Search Fields" text box has no placeholder text? If so, we could get away with some generic text such as : "Choose in which fields you want to search."

**Comment by johnhbenetech** [comment]
@neilmbenetech this is for the generic top level search bar. currently the placeholder text says search on name or alternate name, but with the changes we made to allow to search on additional fields that placeholder doesn't make sense anymore.

one suggestion was to dynamically switch out the placeholder text based on which fields youve selected. But if you select lots of fields that could get quite long.

Are you okay with just having the placeholder text staticly defined? For example, search by organization, search by service, search by location?

**Comment by NeilMBenetech** [comment]
@johnhbenetech Ah that makes sense. Yes I think it is a good idea to just use the more simple placeholders you propose above.

**Comment by bognasoldev89** [comment]
Placeholder looks neat right now. It is consistent and clear.
Some examples:

![placeholder1](https://user-images.githubusercontent.com/51324797/64019860-8747a900-cb30-11e9-8685-861697c0d463.png)
![placeholder2](https://user-images.githubusercontent.com/51324797/64019861-8747a900-cb30-11e9-8848-d617853fdfd1.png)
![placeholder3](https://user-images.githubusercontent.com/51324797/64019862-8747a900-cb30-11e9-993f-c871c860be95.png)
![placeholder4](https://user-images.githubusercontent.com/51324797/64019863-87e03f80-cb30-11e9-9b38-bf191df3a5a5.png)
