### ISSUE TITLE
when go back to main view, filter shade expanded even when default filter

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#626]

**Comment by bognasoldev89** [comment]
Filter feature seems to behave a little erratic - sometimes it is expanded and sometimes it is not. I was not able to reproduce or spot anything specific.

I recorded this gif, after clicking "Sign out" and before user is logged out filtering feature expands for a moment:
![filter visibility log out and in](https://user-images.githubusercontent.com/51324797/62779073-6bf9f880-bab2-11e9-9e33-0845deadda28.gif)


@johnhbenetech maybe decide if it should be hidden or displayed by default or maybe additional setting for users to decide what they want?

**Comment by bognasoldev89** [comment]
@johnhbenetech it seems like this problem doesn't occur anymore and the filter feature is displayed by default. In my opinion, it works fine now.
