### ISSUE TITLE
Add sorting to all of the entities

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#628]
I noticed that some of the entities detail pages can be sorted and some of them cannot. It would be consistent to add sorting to every entity detail page.

![Screenshot from 2019-08-14 11-21-06](https://user-images.githubusercontent.com/51324797/63012779-1dba7000-be8b-11e9-906d-8f94aeddc272.png)
![Screenshot from 2019-08-14 11-21-24](https://user-images.githubusercontent.com/51324797/63012780-1dba7000-be8b-11e9-89ac-a1e68206000b.png)

**Comment by kdondziak** [comment]
Dev note: Consider using regex search and replace instead of coping

**Comment by bognasoldev89** [comment]
@pmuchowski the sorting feature seems fine.
I found a few entities where it was not applied (minor things):
- programs
- service areas
- payments accepted
- metadata
- field exclusions
- location exclusions
- exclusions configs.

Is it possible to make this pagination and items per page feature on the data status page more consistent with the pagination on the other entities?
![Screenshot from 2020-08-13 11-26-51](https://user-images.githubusercontent.com/51324797/90124253-5de35580-dd60-11ea-94ef-cfc58b8d93e2.png)


![Screenshot from 2020-08-13 12-26-48](https://user-images.githubusercontent.com/51324797/90124218-53c15700-dd60-11ea-8c02-a0abee93c153.png)

**Comment by bognasoldev89** [comment]
**Tested with success**

**Environment**
- staging env
- browsers
-- Chrome 83.0.4103.116
-- Firefox 79.0

**Verified cases**
- Checking all of the entities
- Sorting entities by chosen columns
- Checking changing items per page feature
-- Back button

**Summary**
All of the entities can be sorted, not changing items per page nor backing page in any combination changes the applied order.

**Attachments**
![sn 628 2](https://user-images.githubusercontent.com/51324797/90482816-14b24d80-e134-11ea-8738-77d5392e7656.gif)

![sn 628](https://user-images.githubusercontent.com/51324797/90482963-504d1780-e134-11ea-9f46-7b2eee74c949.gif)
