### ISSUE TITLE
Leverage BigDecimal classes for decimals calculations

### ISSUE THREAD

**Issue by kkaczmarczyk** [benetech/ServiceNet#629]
Decimals calculation should use Big Decimals instead of plain floats, especially in case of multiplications. Precision is being lost as a result of using floats for such operations.

I've seen it is mostly being done in OrganizationSimiliarityCounter

**Comment by kkaczmarczyk** [comment]
@johnhbenetech I think this should be done asap

**Comment by bognasoldev89** [comment]
Similarity values are now displayed correctly in Match Similarities entity.
