### ISSUE TITLE
Load partner names dynamically on file upload dropdown

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#63]
The list of partners to select should be loaded dynamically from the backend (all system accounts). As a part of this ticket, all partners from stage 1 of the project should be loaded to the database automatically when the app starts.

**Comment by wojtekbu** [comment]
The functionality works but the list of all system accounts should be available only for admin. At this moment a default user can fetch, add, update and delete a system account. The 'USER' should be allowed only to get his/her system account.

**Comment by wojtekbu** [comment]
@oskarhinc please add _@PreAuthorize("hasRole(\"" + AuthoritiesConstants.ADMIN + "\")")_ to
https://github.com/benetech/ServiceNet/blob/master/src/main/java/org/benetech/servicenet/web/rest/SystemAccountResource.java

**Comment by wojtekbu** [comment]
@oskarhinc  Default user has no longer access to the list of accounts but he is still requesting it while entering the upload page.

**Comment by wojtekbu** [comment]
Works fine
