### ISSUE TITLE
Update OrganizationMatches when Org has changed (after upload)

### ISSUE THREAD

**Issue by kkaczmarczyk** [benetech/ServiceNet#632]
It would make sense to update existing Organization Matches in case if Org has changed, since the previous upload.

**Comment by bognasoldev89** [comment]
I managed to "unmatch" and "rematch" organizations and also change them - all of these actions had an impact on OrganizationMatches ("unmatching" took a while though).

Here some examples of Organization Match before "unmatching", rematched and changed (ID of matches is different and Timestamp is changed):

![632 changed org name](https://user-images.githubusercontent.com/51324797/65243349-7911fa80-dae8-11e9-99dc-5df5e1dcf5eb.png)

![632 changed org name 2](https://user-images.githubusercontent.com/51324797/65243351-79aa9100-dae8-11e9-8e1a-176962a9f241.png)

![632 changed org name 3](https://user-images.githubusercontent.com/51324797/65243352-79aa9100-dae8-11e9-8d50-75a1f053db62.png)

![632 changed org name 4](https://user-images.githubusercontent.com/51324797/65243353-79aa9100-dae8-11e9-9502-1094b8111024.png)

**Comment by kkaczmarczyk** [comment]
@johnhbenetech would like to have some more documentation regarding this issue and its cases in the Wiki or is that pretty clear?

**Comment by johnhbenetech** [comment]
@kkaczmarczyk I think it would be helpful
