### ISSUE TITLE
Search filter on "Updated date" - select range validation

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#637]
As a follow-up to this task : https://github.com/benetech/ServiceNet/issues/301 please enforce validation so that the "from" date must be before the "until" date.

**Comment by bognasoldev89** [comment]
I confirm that date range validation is enforced

![637 1 working](https://user-images.githubusercontent.com/51324797/64122890-3095d580-cda3-11e9-8800-c4e7961962aa.gif)
![637 2 working](https://user-images.githubusercontent.com/51324797/64122891-3095d580-cda3-11e9-97e3-84d1b9730fc3.gif)
