### ISSUE TITLE
Service Taxonomy is not showing in detailed view of records

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#638]
As a follow-on to this task : https://github.com/benetech/ServiceNet/issues/531

When I do a search in the Staging environment, logged in as hluser, specifying "The" (without quotes) as the search term, and "Clothing" as the Taxonomy filter, I get two results. Then viewing the details of one http://benetechservicenet.org/#/single-record-view/a2e6500b-f8a0-4d4e-84bd-c1f47f3cf39f , I scroll down to Services and expand. In both of the services for this Organization, the "Service Taxonomy" field is blank. I would expect it should show "Clothing" since that is what was matched in the search.

I repeated the search with uwbauser (since they use the official 211 taxonomy) and this Organization's single Service also does not show anything in the "Service Taxonomy" field - though notably there are three blank text boxes. So perhaps it "knows" there are three different taxonomy terms assigned, but just is not successfully resolving the names of each. http://benetechservicenet.org/#/single-record-view/000f756e-6991-4055-9ecd-d5575edb942a

**Comment by bognasoldev89** [comment]
I checked a few combinations for filtering with Taxonomy filter and I also checked if taxonomies are visible in side-by-side view.
Here some examples showing that Service taxonomy field is now filled:

![638 1 working](https://user-images.githubusercontent.com/51324797/64097926-c874ce80-cd65-11e9-97bd-79c1a1a5c4bd.gif)

![638 2 working](https://user-images.githubusercontent.com/51324797/64098155-6e283d80-cd66-11e9-86f9-f9c24345b1fc.gif)
