### ISSUE TITLE
Staging environment not secured with SSL/TLS

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#640]
Please configure http://benetechservicenet.org with a valid SSL/TLS certificate as sensitive information is being transmitted to/from that site....user passwords, records from our pilot partners, etc. Once configured please also "require secure connection" so that HTTPS is always in use and HTTP cannot be used.

**Comment by johnhbenetech** [comment]
@neilmbenetech should be good now. The certificate was in place for everything but manually hardcoded http/www requests. Those should now be enforced to Https. Let me know if you confirm from your side.

**Comment by NeilMBenetech** [comment]
@johnhbenetech Yep, works now, that was fast!
