### ISSUE TITLE
Match on domain name only of website not full URL

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#641]
When the matching algorithm considers the "website" field in comparing two records, only use the domain name to decide if it is a match or not. Don't use the full URL (which could point to different pages on the same website).

For example, these website addresses should be considered equivalent for purposes of determining if two organizational records match:

www.bobsfoodpantry.org/home/about
www.bobsfoodpantry.org/clinic

However to avoid false positives, you should not apply this logic to large/shared websites that could host pages for all sorts of entities, like : Wikipedia, Wix, Google, Yahoo, Guidestar and Yelp (feel free to add other major such aggregation sites you may come across).

**Comment by mariaogryczak** [comment]
@NeilMBenetech 
In the website field should be displayed the URL only with domain name or the original one with URL to different pages?

**Comment by bognasoldev89** [comment]
So I tested this issue and it looks good.
The ServiceNet app doen't show URL conflict based on domain anymore:

![641 example1](https://user-images.githubusercontent.com/51324797/64956057-0acffc80-d88a-11e9-8b3c-e14bef1d953e.png)

![641 example2](https://user-images.githubusercontent.com/51324797/64956058-0acffc80-d88a-11e9-9db2-b9ec7f983229.png)

All links are clickable and long ones are shown like that:
![641 long url](https://user-images.githubusercontent.com/51324797/64956152-394dd780-d88a-11e9-9915-c7507fe766e8.png)

Additionally I checked all of mentioned websites: Wikipedia, Wix, Google, Yahoo, Guidestar and Yelp and they're showing confilcts, as they're supposed to do. Some examples:

![641 wiki](https://user-images.githubusercontent.com/51324797/64956355-a95c5d80-d88a-11e9-9469-09b81b253ce8.png)

![641 yahoo](https://user-images.githubusercontent.com/51324797/64956356-a95c5d80-d88a-11e9-9b3e-d5fa27fb29a3.png)

It looks like issue is resolved.
