### ISSUE TITLE
Add additional fields to 'search by field' options

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#647]
See #437 for more details. This task is to add additional fields that are able to be searched on,

From Neil's note on #437

Organization : Name, AlternateName, Description, Email, Phone, Contact.Name, Contact.Phone
Service: Name, AlternateName, Description, Email, ApplicationProcess, Fees, Eligibility, RequiredDocument, Language, Phone, Contact.Name, Contact.Phone
Location : PhysicalAddress.Address1, PostalAddress.Address1 (Geo filters can handle the rest of the address fields), Accessibility, Phone, Contact.Name, Contact.Phone

**Comment by jkondrat** [comment]
@johnhbenetech : Should we also remove fields that are not listed, for example: URL, tax status, external db id?

**Comment by jkondrat** [comment]
@johnhbenetech : Location is not related with Contact, so it's not possible to add contact name and phone there

**Comment by bognasoldev89** [comment]
I checked fields in search engine and all fields discussed in this issue are added and working. I didn't stumble on any obstacles. I've checked addresses fields carefully and it looks like search engine doesn't make mistakes during searching them.

Here some examples:
![647 1](https://user-images.githubusercontent.com/51324797/64174566-d73cad80-ce59-11e9-9577-80a63bd4a0c1.png)
![647 2](https://user-images.githubusercontent.com/51324797/64174567-d7d54400-ce59-11e9-8629-86ea3524bea6.png)
![647 3](https://user-images.githubusercontent.com/51324797/64174568-d7d54400-ce59-11e9-9bd4-869486aebcf6.png)
![647 4](https://user-images.githubusercontent.com/51324797/64174569-d7d54400-ce59-11e9-9657-cae73eb51d03.png)
![647 5](https://user-images.githubusercontent.com/51324797/64174570-d7d54400-ce59-11e9-85fe-c236402ca6e8.png)
![647 6](https://user-images.githubusercontent.com/51324797/64174571-d86dda80-ce59-11e9-9156-37fe919aafd1.png)
