### ISSUE TITLE
Add a custom scheduler to the project and a page for its administration

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#65]
Some of the partners will provide their data as an API that can be queried. It'll have to be downloaded automatically after a specific period of the time, but there has to be an option to manually trigger it as well. Probably the best way to achieve it is to have a simple page for scheduler administration. There should be listed all schedulers with a button to automatically trigger them. If it can be easily done, there could also be information about previous and next trigger dates.

**Comment by wojtekbu** [comment]
Works as expected
