### ISSUE TITLE
Consistently apply plurals to record type search; rename slightly.

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#651]
Organization needs to be plural for consistency with Services and Locations. While we’re in there please change “Search On: “ to “Search For: “.

![Capture](https://user-images.githubusercontent.com/52297301/63730842-d2f10e80-c821-11e9-8456-deabe4d46560.PNG)

**Comment by bognasoldev89** [comment]
Confirmed that issue is resolved.

![651 fixed](https://user-images.githubusercontent.com/51324797/64014406-4fd20000-cb22-11e9-956c-5a31f46d90c8.png)
