### ISSUE TITLE
Connect with Eden API and map their data to the common structure

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#66]
After https://github.com/benetech/ServiceNet/issues/65 will be finished, there has to be created a special scheduler to get data from the Eden API. This data has to be mapped to the common structure and persisted after the scheduler collects the data.

**Comment by wojtekbu** [comment]
@oskarhinc 
"UX_REGULAR_SCHEDULE_SRVC_ID_INDEX_A ON PUBLIC.REGULAR_SCHEDULE(SRVC_ID) VALUES ('d3ad2c84-6da7-41aa-b269-181776933136', 1)"
It looks like the system is trying to insert REGULAR_SCHEDULE with the same SRVC_ID and the constraint is violated. It occurs during Eden scheduler data fetching.

**Comment by johnhbenetech** [comment]
please review #137 is light of new requirements from partners

**Comment by oskarhinc** [comment]
@wojtekbu it should work now

**Comment by wojtekbu** [comment]
Works as expected
