### ISSUE TITLE
Save new "search filter" should clear name textbox once saved

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#662]
When you click "Save Filter" to save the combination of filters as you currently have them set, the handy confirmation message does appear from the top left, but the text box retains whatever name you gave to the filter. Instead it should be cleared out after a successful save so the user can change the filters and save them with a new name.

**Comment by bognasoldev89** [comment]
Confirmed that "Filter Name" field in saving filters engine clears out after saving a new filter.

Example of how it works:
![662 working](https://user-images.githubusercontent.com/51324797/64941248-62f50780-d866-11e9-9bc9-b96c4ea19ce0.gif)
