### ISSUE TITLE
Saved Filters - need a way to delete from list

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#663]
Over time, a Saved Filters entry may become irrelevant or the list may get too big to be manageable. Please provide a way for the user to delete any of their Saved Filters. If possible I would recommend a red "x" to the right of the name, but spaced at least 10 pixels away from the text to reduce the likelihood of an accidental click there. 

When the X is clicked, please give the user a Javascript alert "Are you sure you want to delete this saved filters?" and only an OK choice proceeds with the deletion.

**Comment by bognasoldev89** [comment]
I confirm that deleting filters works just fine. After adding and deleting filters I was checking Activity filters entity for the presence of those filters and everything went as expected (saved filters were there, deleted not).

Here an example of issue working:

![663 working](https://user-images.githubusercontent.com/51324797/65044884-1260d580-d95e-11e9-912a-8dee5375e3fb.gif)


![663 working 2](https://user-images.githubusercontent.com/51324797/65044892-15f45c80-d95e-11e9-9a46-b5b1dcf6115c.gif)
