### ISSUE TITLE
Saved Filters list - sort alphabetically by name

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#664]
It appears the entries in the Saved Filters list are being sorted by creation date. Please sort them alphabetically by name instead. This will make them easier to find and allow users to cluster similar entries together.

**Comment by bognasoldev89** [comment]
I saved a few filters in random order and they are sorted alphabetically on the dropdown list. Saved filters from other tasks are sorted too.

Example from testing this issue:
![ServiceNet - Mozilla Firefox_003](https://user-images.githubusercontent.com/51324797/64030200-6427f400-cb46-11e9-89fa-d8a846ad58af.png)
