### ISSUE TITLE
Search - searches sometimes yield zero results, sometimes yield expected results just minutes later

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#670]
"Food Pantries" is one of the most commonly used taxonomy terms and is auto-suggested in the taxonomy filter. However when I do a search with no other filters in place, I get zero results. Unless those records were excluded from the exports provided by the 2-1-1's (UWBA and Eden), this sounds like a bug. This would be a common search in Service Net, especially combined with Discovery mode where you want to see Services of a certain type, in partner data sources.

I tried variations with "Only show matching" on and off, as well as searching at the Organization and at the Service record types. All yield zero results.

![Capture2](https://user-images.githubusercontent.com/52297301/63954945-cb578280-ca38-11e9-9c14-76ab876d3262.PNG)

**Comment by NeilMBenetech** [comment]
Note that "Food Pantry" is also auto-suggested and does return search results, but only from non-2-1-1 partners (SMC, ShelterTech) so that must be one of their category names. But there are no results showing from UWBA or Eden when searching either on "Food Pantry" or "Food Pantries", the latter being the one I would expect to return results for UWBA and Eden.

**Comment by NeilMBenetech** [comment]
There's something weird going on. 20 minutes later I do the same search and now I am getting results. 

I had the same problem this morning on a completely different search. Here's the search from this task, now working. What could be causing this?

![Capture](https://user-images.githubusercontent.com/52297301/63956715-d3fd8800-ca3b-11e9-81f4-8d514a309e53.PNG)

**Comment by NeilMBenetech** [comment]
Less than 5 minutes later, we're back to zero results.

![Capture](https://user-images.githubusercontent.com/52297301/63956987-6736bd80-ca3c-11e9-84f8-633e1723924e.PNG)

**Comment by bognasoldev89** [comment]
@NeilMBenetech @johnhbenetech I was not able to reproduce this issue, I always get results. I tried an example from this issue and I tried other filters and I never saw a situation with 0 results when I knew there's something there.
@NeilMBenetech are You still observing this issue?

**Comment by NeilMBenetech** [comment]
Thanks @bognasoldev89 . When I logged this issue it was happening on the production server. Did you try it there? @johnhbenetech did something behind the scenes that seemed to have corrected the issue at the time but I think he wasn't 100% sure that whatever he did would be a long-term solution.

**Comment by bognasoldev89** [comment]
@NeilMBenetech I tried production too and while trying example you provided I never hit zero results. Screenshots from today (both environments):

| | |
| --- | --- |
| ![Screenshot from 2019-10-01 15-05-45](https://user-images.githubusercontent.com/51324797/65964517-7060e300-e45d-11e9-8bbe-ac578ed27b97.png) | ![Screenshot from 2019-10-01 15-06-06](https://user-images.githubusercontent.com/51324797/65964538-78208780-e45d-11e9-9a03-6459ef7dc1b1.png) |
| ![Screenshot from 2019-10-01 15-07-19](https://user-images.githubusercontent.com/51324797/65964550-7f479580-e45d-11e9-830c-f11775d5f2f6.png) | ![Screenshot from 2019-10-01 15-07-32](https://user-images.githubusercontent.com/51324797/65964568-88d0fd80-e45d-11e9-9b71-8e8de07870d0.png) |

**Comment by NeilMBenetech** [comment]
Thanks @bognasoldev89 . I think the only other thing to try is do this several times but separated by 20-30 minutes. If it still works OK then we can close this item.

**Comment by bognasoldev89** [comment]
@NeilMBenetech I tried this as you suggested and I didn't hit zero results. I'll move this issue to done column but I'm going to have this in my mind during future testing.

**Comment by NeilMBenetech** [comment]
@bognasoldev89 Thanks - I'm adding priority tags to many of the items and since it sounds like you have this working I'll make it a C for now.
