### ISSUE TITLE
Health Leads should be written this way, not healthleads

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#671]
I've heard them ask for this correction several times. Please modify wherever it may appear, such as the search result page, the details view, the comparison view, etc.

![Capture](https://user-images.githubusercontent.com/52297301/63956164-c72c6480-ca3a-11e9-8894-ab54b9851cf9.PNG)

**Comment by johnhbenetech** [comment]
Should be good, just updated in prod
