### ISSUE TITLE
Visually differentiate the staging environment from production

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#672]
It can get confusing to keep track of which browser tab is production vs staging, since the only difference is the URL. A common practice I've seen is to add a banner or colored text to the top of a staging environment. Something like this in bold red : **Staging environment - for testing only**

**Comment by awalkowiak** [comment]
@NeilMBenetech JHipster has a built in feature for this. We can display a red ribbon with "Development" text in the top left hand corner for desired profiles. Here it is how it looks like by default: 
![Selection_128](https://user-images.githubusercontent.com/12113312/67094751-b5eb1300-f1b4-11e9-9d9e-59024dbdeea4.png)
Is this enough or you'd like to have something changed?

**Comment by NeilMBenetech** [comment]
@awalkowiak Yes indeed that would work.

**Comment by bognasoldev89** [comment]
I confirm that in staging environment red ribbon is added. I checked all users, About us page and several randomly chosen entities. In the production environment mentioned ribbon is not added.

Examples:
1. admin
![672 1](https://user-images.githubusercontent.com/51324797/67464073-f75f4080-f642-11e9-9d7b-1c8442058692.png)

2. regular user
![672 2](https://user-images.githubusercontent.com/51324797/67464086-0219d580-f643-11e9-8be7-0f2fca16f51e.png)

3. sacramento user
![672 3](https://user-images.githubusercontent.com/51324797/67464102-0940e380-f643-11e9-830d-4af4e6ae5bf8.png)
