### ISSUE TITLE
Search filter on "updated date" validate date range and include message

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#675]
As a follow-up to this item https://github.com/benetech/ServiceNet/issues/637 I would like to provide the user with message when the From date and Until date do not define a valid date range. Currently it just seems to clear out one of the erroneous dates. Instead please do the following.

When "Date Range is specified in the filter for Update Date and the Apply button is clicked, show an error message using our following convention with the red "flyout" banner on the top left corner:

1. If neither a From nor an Until date are specified, present an error message that says "Please specify a From and an Until date." Also please highlight the datepicker box for both the From and Until date with a yellow background.

2. If the From date is not specified, present an error message that says "Please specify a From date." Also please highlight the datepicker box for the From date with a yellow background.

3. If the Until date is not specified, present an error message that says "Please specify a Until date." Also please highlight the datepicker box for the Until date with a yellow background.

4. If the Until date is a date earlier than the From date, present an error message that says "Please specify a From date that is on or before the Until date." Also please highlight the datepicker box for both the From and Until date with a yellow background.

5. If either date specified is invalid (for example, either any date in the future or a month value greater than 12 or a day value greater than 31 or a year value that is more than 20 years in the past), please present an error message that says "Please specify valid From and Until dates." And highlight the datepicker box of the invalid date with a yellow background.

**Comment by bognasoldev89** [comment]
Maybe to be consistent it would be good to apply point 5 to dates too far in the future as well?
User can input dates like that and, of course, it is not applied, but toast is saying "Bad request" and date picker is not highlighted.

![Screenshot from 2019-09-19 15-29-21](https://user-images.githubusercontent.com/51324797/65248375-5edd1a00-daf2-11e9-9b11-3cae319fde6f.png)

**Comment by NeilMBenetech** [comment]
@bognasoldev89 I suppose future dates in the "Until" picker are not too harmful because the underlying data would never have a future date, but future dates in the "From" picker should yield an error message. I'm not sure if you are suggesting the toast should say "Bad request" or if that is just what is happening when you put in a future date? Either way, "Bad request" is not a desired message we want to show to users, so if that is happening because one or both pickers have a future date, then please enforce validation so that future dates ware not possible to enter.

**Comment by bognasoldev89** [comment]
@NeilMBenetech yes, I'm suggesting that toast should say to specify valid date, not "Bad request", that's all.

@jkondrat can you look into this? It happens when year value has more than 4 characters, so I think that's the core of this issue.
Can you also add "n" to the toast from point 3, so it would say "Please specify an Until date."?

**Comment by bognasoldev89** [comment]
It seems like all faulty possibilities are covered now. I was not able to set a date like 02/30/10000 and all points from the ticket are fulfilled.
Some examples of working functionality:

![675 working 1](https://user-images.githubusercontent.com/51324797/65868862-754c6680-e379-11e9-8b87-bdaf830f66f4.gif)

![675 working 2](https://user-images.githubusercontent.com/51324797/65868863-75e4fd00-e379-11e9-8a3f-0b1989b79329.gif)
