### ISSUE TITLE
Show more information about last updated

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#680]
When viewing your own record, whether or not you are comparing to a partner's "matched" record or not, please change the user interface. For any record that lacks one of these data elements, just put "unknown" as the value for items 1 through 4 below.

1. Organization records : For those data exports that are giving us valid data about the most recent "Complete Review" (in iCarol it is called "LastVerifiedOn and LastVerifiedBy"), please add a line above "Last updated" called "Last complete review " and put the corresponding date, time, person's name and source of information (if available - I don't think iCarol has this last field yet).

2. Organizational records: Rename "Last updated" to be "Last partial update". 

3. Service records and Location records: Please add "Last complete review" and "Last partial update"  to show, formatted the same way as specified in item 1 and 2 above.

4. Service Records: For those exports that have "usage" data (in iCarol it might be there called NumberOfReferrals), please for now add a line under item "Last partial update" that reads: "Number of times used in past 12 months : " and append the usage data. This will likely need some refinement in the future (for example to characterize as "low, medium or high for this data partner" but for now let's keep it simple.

5. Please let me know, for each partners' exports, which data elements above are currently available and which are not.

**Comment by johnhbenetech** [comment]
So @NeilMBenetech looking at the various data we have access to:

----

**LAAC:** Only field I see is a date field called "changed". All of those dates occur in the last 2 months so I'm not sure if this constitutes anything related to 'verification'.

**Recommended Action:** Pull nothing right now

---

**SMC:** No obvious data element present for verification/updates sent in the HSDS 

**Recommended Action:** Pull nothing right now

---

**HealthLeads:** No obvious data element present for verification/updates sent in the HSDS 

**Recommended Action:** Pull nothing right now

---

UWBA/EDEN (iCarol): 
 "lastVerifiedOn": present at Agency, Site, and Program level

@NeilMBenetech I don't see LastVerifiedBy within the API response. Looking through the API docs - is it possible it's only available via CSV export? I also dont see anything related to referral count or usage.

**Recommended Action:** Add and display LastVerifiedOn to Organization, Location, and Service as indicated by Neil above.


---

**ShelterTech**:

* Organization (368 Total)
** "certified" - 344 True, 24 False
** "verified_at" - 217 Blank, 43 in 2019, 99 in 2018, 9 in 2017
** "certified_at" - 221 Blank, 111 in 2019, 36 in 2018

* Services (1397 Total)
** "certified" - 1397 Blank
** "verified_at" - 1396 Blank, 1 in 2019
** "certified_at" - 1397 Blank

**Recommended Action:** Pull Organization 'certified_at' for those records which have 'certified' = true. Do not pull anything from Services level.


@NeilMBenetech Take a look and let me know if you disagree with any of the recommended actions

**Comment by NeilMBenetech** [comment]
@johnhbenetech Thanks for the analysis, I agree with everything you have proposed. There might have been a decision to exclude LastVerifiedBy from the iCarol API years ago but I can't recall the logic in that now.

I have not had any response to my email to partners specifying the new data in their exports - I'm hoping at least to get clarifying questions or loose timelines soon. I'm also hopeful that if/when they start seeing the "Most recent complete review" in those partners' records that will have it, it will be a reminder to them. I will also nudge them in the near future by email.

**Comment by bognasoldev89** [comment]
"Last complete review" and "Last partial update" are available in single and multi record view. For Eden and UWBA data, Last complete review dates can be set on every level (Organization, Locations and Services) and for ShelterTech data Last complete review can be set for Organization.

There's one thing I ask @jkondrat to look into: can you investigate updating Last complete review date after uploading a file? I was not able to update it.

Here examples of how it looks with and without dates:

![Screenshot from 2019-10-17 13-51-10](https://user-images.githubusercontent.com/51324797/67006510-a0f37e80-f0e5-11e9-8473-b542ec66ae30.png)
![Screenshot from 2019-10-17 13-51-29](https://user-images.githubusercontent.com/51324797/67006511-a0f37e80-f0e5-11e9-8300-eaa109458827.png)
![Screenshot from 2019-10-17 13-51-51](https://user-images.githubusercontent.com/51324797/67006512-a0f37e80-f0e5-11e9-90cd-86ae65725aee.png)

@NeilMBenetech you wrote: "For any record that lacks one of these data elements, just put "unknown" as the value for items 1 through 4 below." For now, I see that the place remains empty. Is it good enough or "unknown" should be implemented?

**Comment by NeilMBenetech** [comment]
@bognasoldev89 I think we should put "unknown" instead of blank, that will help distinguish the current state of things from this newly implemented capability.

**Comment by bognasoldev89** [comment]
I confirm that I was able to change Last complete review date after data upload. Also, lack of the date is signalized by "unknown".

Before:
![Screenshot from 2019-11-04 16-36-24](https://user-images.githubusercontent.com/51324797/68134331-439f6000-ff22-11e9-8498-cd725b4185e9.png)

And after:
![Screenshot from 2019-11-04 16-43-20](https://user-images.githubusercontent.com/51324797/68134467-747f9500-ff22-11e9-92af-af742cb1e881.png)

**Comment by NeilMBenetech** [comment]
@bognasoldev89 @johnhbenetech This seems to be working to me too.
