### ISSUE TITLE
Matching - show most recent "complete review" record first

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#681]
This is related to https://github.com/benetech/ServiceNet/issues/680 .

In the details view of an Organization, please sequence the partner's record who has the most recent "complete review" date to be the first one that appears, and if there are additional records those should be sequenced in descending order of "complete review" date. If any records do not have a "complete review" date, the sort them to appear after those that do, in descending order of "partial update" date.

**Comment by bognasoldev89** [comment]
@jkondrat can you look into Partial update order? I think it doesn't always is ordered correctly.

**Comment by bognasoldev89** [comment]
Matched organizations are ordered properly now, first by Last complete review, then by Last partial update.

Examples:
![681 1](https://user-images.githubusercontent.com/51324797/71970657-63485280-3209-11ea-89d6-ae97bf03cb21.gif)

![681 2](https://user-images.githubusercontent.com/51324797/71970659-63485280-3209-11ea-807b-9848694ee390.gif)

![681 3](https://user-images.githubusercontent.com/51324797/71970660-63e0e900-3209-11ea-9f0c-76c0ebb6172a.gif)

![681 4](https://user-images.githubusercontent.com/51324797/71970661-63e0e900-3209-11ea-80b9-10c0a108699e.gif)
