### ISSUE TITLE
Investigate "Dismiss date" in Organization Matches entity

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#686]
I noticed that in detail pages Dismiss date is present, even if match was not dismissed ("Dismissed" -> false). Moreover, it seems like it is the exact date and time of opening those pages.

![Screenshot from 2019-09-18 15-03-11](https://user-images.githubusercontent.com/51324797/65152938-2e7d7900-da29-11e9-90ad-da7618932dd3.png)

![Screenshot from 2019-09-18 15-29-48](https://user-images.githubusercontent.com/51324797/65152940-2f160f80-da29-11e9-912f-210200da325e.png)

**Comment by jkondrat** [comment]
@bognasoldev89 I also noticed that it was not possible to save dismissDate, so I fixed it

**Comment by bognasoldev89** [comment]
Hmm, now this works fine until organization is dismissed. I noticed that Dismissed remains as false and Dismiss date remains empty though I'm sure organization is dismissed.

@jkondrat can you check again?

**Comment by jkondrat** [comment]
@bognasoldev89 unfortunately, I couldn't reproduce this, I dismissed a match and it shows correctly on admin's view:
![Screenshot from 2019-10-17 11-10-12](https://user-images.githubusercontent.com/5969801/66995219-e789ae80-f0ce-11e9-8b05-48b80615fc04.png)

**Comment by bognasoldev89** [comment]
@jkondrat it seems like it works. For now, I'm going to close this ticket and I am going to check this issue carefully during regression.

![Screenshot from 2019-10-17 11-21-54](https://user-images.githubusercontent.com/51324797/66996264-b8743c80-f0d0-11e9-8338-3fd55314a200.png)
