### ISSUE TITLE
Add Wiki documentation about all of the cases for the updating Organization matches

### ISSUE THREAD

**Issue by kkaczmarczyk** [benetech/ServiceNet#688]
As per discussion #632, it would be helpful to document cases (what happens with Organization matches) when uploading updated organizations.

**Comment by bognasoldev89** [comment]
@johnhbenetech @NeilMBenetech what do you think?

https://github.com/benetech/ServiceNet/wiki/Updating-Organization-matches

**Comment by NeilMBenetech** [comment]
@bognasoldev89 I'll defer to @johnhbenetech on this as he's more familiar with the matching algorithm and how well this represents it.

**Comment by johnhbenetech** [comment]
Thanks @bognasoldev89. The only thing I would think about adding is work with the dev team to record a few more details:

1. Which fields are compared (and how)
2. The current weighting of those field similarities (and where that config is stored)
3. A short description of the match_similarity table that stores the similarity


Thanks and let me know if I can chip in on any of the above

**Comment by bognasoldev89** [comment]
@johnhbenetech I asked @jkondrat for help with requested details and here's the result: https://github.com/benetech/ServiceNet/wiki/Updating-Organization-matches

Can you review this document?

Moreover, I think this wiki page is outdated: https://github.com/benetech/ServiceNet/wiki/Matching-algorithm-approaches
Is it still needed?

**Comment by bognasoldev89** [comment]
Hi @johnhbenetech 
I took a liberty to copy some info from this old wiki page https://github.com/benetech/ServiceNet/wiki/Matching-algorithm-approaches to the one created by me and @jkondrat 

@johnhbenetech can you take a quick look if it looks good to you? https://github.com/benetech/ServiceNet/wiki/Updating-Organization-matches

**Comment by bognasoldev89** [comment]
@johnhbenetech I'll close this ticket for now. Of course, I'll reopen it if needed.
