### ISSUE TITLE
Investigate Location Match Similarity when the distance between organizations < 100m

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#689]
I noticed that location similarity for these two organizations was calculated as 0.36 and I'm sure that it is too distant for those coordinates. Something weird is going on.
Please, investigate this geocoding issue.

I'm attaching files that gave mentioned results:
https://drive.google.com/drive/folders/19vpWGpiNCRBvHs1wBS1bf-sNOiupmdQW?usp=sharing

**Comment by jkondrat** [comment]
@bognasoldev89 I couldn't reproduce this issue, the location similarity for these organizations is 0.9 - could you please verify?

**Comment by bognasoldev89** [comment]
I reproduced this issue today on a clean server and I got the right similarity too.

![Screenshot from 2019-10-21 13-37-41](https://user-images.githubusercontent.com/51324797/67202908-0f984b00-f40a-11e9-9c44-5d15f8899208.png)

@johnhbenetech what do you think? I suppose the best way is to close this issue now and check during regression again.

**Comment by bognasoldev89** [comment]
As regression testing is planned for Monday it would be good to resolve remaining issues. I suppose since Jakub and I cannot reproduce this issue anymore it should be closed and observed closely during regression.
@johnhbenetech can you confirm?

**Comment by johnhbenetech** [comment]
@bognasoldev89 yes you can close
