### ISSUE TITLE
Update the application to Java 11

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#7]
JHipster doesn't support creating an app with Java 11, so it has to be converted manually. This link should be helpful: https://gist.github.com/mraible/716f4d2ab205c0e747d51119fc5d9cd8#gistcomment-2598658

**Comment by pgesek** [comment]
@oskarhinc I verified this works, can we move to done?

**Comment by oskarhinc** [comment]
@pgesek sure, I'll move it
