### ISSUE TITLE
Show matching "metadata" when you are viewing your Organization's record

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#700]
Once we have implemented Location https://github.com/benetech/ServiceNet/issues/698 and Service https://github.com/benetech/ServiceNet/issues/699 matching, then for any of the current user's Organization records, display metadata about these matches, before clicking in to view any particular partner's Organization record.

Please show a list of clickable Organization names that match my own record. Below each, show how many Services and how many Locations match to my record. And this list should be sorted in descending order of total number of Location + Service matches, so the partner's Organization record with the most matches is at the top.

**Comment by johnhbenetech** [comment]
We don't have service matching done yet, but we can start this work for locations.

@NeilMBenetech can you comment on the following mockup and see if it was roughly what you were thinking:
![mockup showing matching details](https://user-images.githubusercontent.com/12927553/71008348-1364e880-20ae-11ea-9f52-e7eff0bfdd9f.png)

**Comment by NeilMcKechnie** [comment]
@johnhbenetech This looks good to me. I'm wondering if we should add Last Complete Update and Last Partial Update but that would probably get pretty messy given each major record type can have different/independent values for each of those.

Any creative ideas? Maybe some formula to calculate "freshness factor" (not sure I like the name)....something like: Total number of days since last Partial Update for all O+L+S records divided by total number of O+L+S records in the Organization.

**Comment by johnhbenetech** [comment]
@NeilMBenetech we can call it the mentos factor :)

We can explore that in a second iteration (once we have service matching). We had talked about a color-based indicator before (especially in the context of 'usage'). 

I'll think about it a bit more

**Comment by bognasoldev89** [comment]
I think for Locations this feature works quite well.

I found some UI issue though. While the organization has a few matches, it looks good:

![700 ui](https://user-images.githubusercontent.com/51324797/71975938-73fec580-3215-11ea-9024-fc3829143298.png)

But when it has much more it doesn't look good in my opinion:

![700 ui issue](https://user-images.githubusercontent.com/51324797/71976007-91339400-3215-11ea-923a-46f5736489b2.gif)

![700 ui issue 2](https://user-images.githubusercontent.com/51324797/71976009-91cc2a80-3215-11ea-9770-f0f0ba152a46.gif)

@johnhbenetech @NeilMBenetech should it stay that way?

**Comment by NeilMcKechnie** [comment]
@bognasoldev89 @johnhbenetech Good catch. What if we start by not showing the "0 match" entries?

**Comment by bognasoldev89** [comment]
@johnhbenetech @NeilMBenetech maybe a smarter scroll or page break would be a better option?

**Comment by johnhbenetech** [comment]
@NeilMBenetech Scroll or pagination seems like an okay option, what do you think?

**Comment by NeilMBenetech** [comment]
@johnhbenetech @bognasoldev89 Yes I suppose that would work too. Let's do scrolling.

**Comment by bognasoldev89** [comment]
@jkondrat can you look into it?

**Comment by bognasoldev89** [comment]
@jkondrat while going through testing records I noticed that sometimes organizations match on the right are doubled. I haven't found any doubled matches in "original" records" though. Can you look into that as well, just to make sure it won't be a problem?

![700 double 1](https://user-images.githubusercontent.com/51324797/72344370-57f59b00-36d1-11ea-94f5-de3fed8c8be4.png)

![700 double 2](https://user-images.githubusercontent.com/51324797/72344371-57f59b00-36d1-11ea-9c70-4b1f5b1724bc.png)

![700 double 3](https://user-images.githubusercontent.com/51324797/72344372-57f59b00-36d1-11ea-818e-8241b783ad5f.png)

**Comment by bognasoldev89** [comment]
Now the scroll works well in my opinion. I check it on Chrome v79.0.3945.117, Firefox v72.0.1, Edge v44.17763.1.0, and Safari v12.03.3.
Example of the scroll on Chrome:
![700 scroll](https://user-images.githubusercontent.com/51324797/72809197-76244380-3c5b-11ea-80ee-b6cd481ef15a.gif)

@johnhbenetech @jkondrat as of my comment from week before, I'll recheck this issue and create a ticket if needed.
