### ISSUE TITLE
Investigate open website issue

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#707]
On dev server:

* Search for Housing Authority of the County of Contra Costa (it's currently the top result default)

* in the side by side the right record has www.example.example or www.website.com

* click on the open URL button and those examples try to take you to 'https://benetechservicenet.org/www.website.com' which obviously fails

Looking quickly it seems that http:// and https:// urls work as expected

**Comment by bognasoldev89** [comment]
I confirm that URL in forms http://website, https://website, www.website, website and combined are redirected to indicated websites and work as supposed.

Examples:
![707 1](https://user-images.githubusercontent.com/51324797/67571738-fc042180-f734-11e9-8cf6-32cc6a7493a0.gif)

![707 2](https://user-images.githubusercontent.com/51324797/67571739-fc042180-f734-11e9-860a-cc9a869d6f8b.gif)
