### ISSUE TITLE
Add reports for data updates

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#71]
Uploading a data should produce a report, so it can be later reviewed. It can be displayed in a simple table, for example showing how much entities were updated, when the upload was done. Maybe info about how long it takes to persist the data or to compare it with other ones (looking for conflicts). What is most important for it to be easily extendible, as in the future more data might be reported. The report should be generated both in the scheduler while collecting the data with the API and when uploading data files manually.

**Comment by oskarhinc** [comment]
Additionally, when reports will be available, we should use them to specify properly dates when collecting data by the API, so it should be done as a part of this issue.

**Comment by wojtekbu** [comment]
It works fine, but there is no document's link for many files. We have to find out a way to group them. I have created an issue on the backlog https://github.com/benetech/ServiceNet/issues/133
