### ISSUE TITLE
Linked/Combined taxonomical terms may need to be digested in a different manner

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#711]
For iCarol services, the taxonomical terms are frequently of the format:

XX-NNN.NNNN

Occasionally you will see the following:
XX-NNN.NNNN*XX-NNN.NNNN

The asterisk denotes that two separate terms are being passed. I believe we currently just store this as a single term, thereby we are unable to pull taxonomy term name and other components.

We should refactor the import process to break/store these into separate terms. And possibly come up with a DML to retroactively break out previous records.

**Comment by jkondrat** [comment]
Hi John, unfortunately I couldn't find any taxonomy that's in this format, where exactly are these terms passed like this?

**Comment by johnhbenetech** [comment]
@jkondat this will give you some results on the dev DB:

```
SELECT id, name, vocabulary, parent_id, external_db_id, provider_name, details, taxonomy_id
	FROM public.taxonomy	
	where id in ('ac7d028b-e68f-4400-86c4-6ef9351c9113', '63eb2389-7531-4b41-b7f7-002e9ee44733','5069a9c9-3af3-4ace-955b-743daf4562d3')
```

**Comment by NeilMBenetech** [comment]
@johnhbenetech This task is well described for now. In the future though the linking is important. No action needed now, just a mental bookmark when the day comes for us to handle taxonomy and its many complexities in a more nuanced manner.

Note that when you have multiple such linked terms, the first one in the chain is the most important - it's known as the "base term".

**Comment by bognasoldev89** [comment]
I went through the whole "Taxonomy" entity on the staging server and didn't find any of the records with an asterisk. I confirm that this issue is resolved and I'm going to check it for sure during future regressions
