### ISSUE TITLE
'Your data' shows on left side even when you are viewing 'unmatched' records from a partner system

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#712]
When a user unclicks 'only show matching' and then views a partner's record, the record on the left still shows 'Your Data'

This should be changed to show the partner's name.

**Comment by bognasoldev89** [comment]
I confirm that the multi-record view reacts to providers now. When the user is going through his provider data he still sees the information "Your data":

![712 2](https://user-images.githubusercontent.com/51324797/68210871-c5e95c00-ffd6-11e9-8bdd-c000a2214840.png)

And while going through partner's records it is changed to the provider's name:

![712 1](https://user-images.githubusercontent.com/51324797/68211037-0d6fe800-ffd7-11e9-95f8-ae609794cc73.png)

I checked for all of the providers and this information was always accurate.
