### ISSUE TITLE
Develop logic for sorting importance of updates

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#72]
As we discussed on our call, the home page should display at most 3 lines of updates per record cluster.

For records that have greater than three updates, we should choose the three 'highest priority' updates to display in full and then display text indicating there are more, e.g. "There are 5 additional updates for this record"

The ranking for update type:

'Recommendations' are always higher priority than 'Updates'

'Updates' are always higher priority than 'Conflicts'

The ranking for fields:
1. Address
2. Phone
3. Name
4. Service Type
5. All other fields

Recommendations with a higher number of partners should outrank those with only a single matching partner. Same for Updates and Conflicts.

**Comment by oskarhinc** [comment]
As conflict types are currently not supported, I've created a separate issue for including them while sorting (https://github.com/benetech/ServiceNet/issues/126). For now, only the number of partners and field types should be considered.

**Comment by oskarhinc** [comment]
Additionally, I've created an issue to support Service types, so it won't be forgotten when we will support this - https://github.com/benetech/ServiceNet/issues/127

**Comment by kcissewski** [comment]
Tested with success.
