### ISSUE TITLE
Duplicate organization records appearing in search

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#734]
Seeing duplicate organization records. For example, "Safe & Sound" is appearing 3 times for ShelterTech in search results. In "Details" they all seem to have different GUIDs.

https://servicenet.benetech.org/#/single-record-view/a4340015-74de-4b67-a295-4c0058e02f50

https://servicenet.benetech.org/#/single-record-view/a988baa6-cb10-4960-9ee5-ae898de737f9

https://servicenet.benetech.org/#/single-record-view/f66a8a8a-73e6-4df4-8420-8d9dd012ec30

![1](https://user-images.githubusercontent.com/52297301/69161797-8aec2b80-0aa0-11ea-94f1-fda2d56c715b.PNG)

![2](https://user-images.githubusercontent.com/52297301/69161807-8de71c00-0aa0-11ea-8878-b2681c53ae05.PNG)

**Comment by johnhbenetech** [comment]
@NeilMBenetech Per Edward it appears these all exist, but two have a field "status = inactive". Do you think we should hide/delete all inactive records for Sheltertech?

**Comment by NeilMcKechnie** [comment]
@johnhbenetech Tough decision. There are all sorts of reason to make a record inactive. For example, seasonal services that are out-of-season, or services that are out of capacity (food bank no more food until next month). These are cases where you still want the record to be present.

Maybe we should ask Edward not to expose records to us that are duplicates of themselves for some reason....? I'm guessing in this case the Inactive one may be an earlier defunct version of the current/Active one.

**Comment by johnhbenetech** [comment]
ok, we won't plan any work on this until we hear otherwise

**Comment by NeilMBenetech** [comment]
I think we shouldn't infer anything like this from partners' data. it will get very specific to each partner in non-scalable ways and also may have unintended consequences. In other words, we should just accept whatever data they are sending us. Closing for now.
