### ISSUE TITLE
Comparison view - specify a subset of fields to view

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#735]
When comparing one record to another, often times SN users only are focused on a few fields, such as physical addresses or eligibility requirements. To make the screens easier to read and navigate, create user-customizable groups of fields the user can apply consistently in a session and when in "Comparison" view, only show those fields for both records in the comparison.

1. Give each user the option to specify and save sets of fields for every record type (Organization, Location, Service). All fields should be candidates to be included. The user should be able to name each set, and each name needs to be unique from all other names saved at the user's agency. The UI does not need to be fancy. A list of all fields by major record type on the left, the list of included fields on the right, the ability to drag&drop fields in both directions, a text box to give the set of fields a name, and a Save button. Also allow users to delete previously saved sets of fields.

2. In the Comparison view, allow the user to select one of the groups of fields from above and apply them to the view. Doing so removes all fields from both records that are not included in the saved group. There should also be the option to reset and show "all fields".

3. The user's choice should be retained/remembered for all subsequent comparison views in that session. It should revert to "all fields" at the end of that user's session.

**Comment by awalkowiak** [comment]
Hi @NeilMBenetech one quick question popped out, should user see only his saved field set settings or all saved field set setting from his agency?

**Comment by NeilMBenetech** [comment]
@awalkowiak I think it should be for all users at that Agency.

**Comment by johnhbenetech** [comment]
Hi @NeilMBenetech. The current iteration of this task manifests as a dropdown at the top of the comparison view. By default it shows you all fields and you need to choose your alternate preset each time you open a new organization match set.

Would you like a setting that allows you to replace your default with one of your created presets? if so should that be at the user or agency level?

We can split this into a second task if needed.

**Comment by awalkowiak** [comment]
@johnhbenetech My current setting model has relation to User who created it and this User has direct relation to agency (system account). Having this information we should have possibility to easily sort out settings.

@NeilMBenetech here is a preview:
![Selection_076](https://user-images.githubusercontent.com/12113312/73467783-1a0c9e00-4384-11ea-8140-5f3d1126fdcc.png)
the select field on top and "cogs" are visible only on this page. Clicking on cogs you can enter page with settings update option.

and here is page with option to create/edit/delete settings:
![Selection_077](https://user-images.githubusercontent.com/12113312/73467882-40cad480-4384-11ea-83c3-547eb4a88bce.png)

I want to give possibility to users to view all settings from his agency on multi record view (as requested in this issue), but on "update settings page" he will have option to manipulate with setting that he has created. For now I am using there selectors that are already used in our project (further improvements can be done later once this feature is up and running)

If you have any requests regarding this feature, let me know.

**Comment by johnhbenetech** [comment]
@awalkowiak one thing i see is that this doesnt appear on the 'view all matches page' only on the single side by side view. It should be on both

**Comment by awalkowiak** [comment]
@johnhbenetech i missed that part. I'll fix that with all other feedback from @bognasoldev89

**Comment by bognasoldev89** [comment]
@awalkowiak, in general, this feature works nice but I have some remarks.

1. I was able to save a few sets with the same name. It shouldn't be possible.
2. The first position on dropdown - one that shows just all of the fields - shouldn't be maybe named? At this moment there's no indication, what is it. cc @NeilMBenetech @johnhbenetech 
3. While setting Physical and Postal Address fields, it should be set in Location Fields accordingly (see screenshot) and it's highly unintuitive. Can it be simplified in any way? Or at least indicitaed in any way, that Location field should be set as well? cc @johnhbenetech 

![735 1](https://user-images.githubusercontent.com/51324797/73836835-76524080-4810-11ea-9600-24739ba662e3.png)

![735 2](https://user-images.githubusercontent.com/51324797/73836836-76ead700-4810-11ea-9bd5-b43e9e72a8ec.png)

**Comment by awalkowiak** [comment]
@NeilMBenetech @johnhbenetech @bognasoldev89 
I fixed this feature on all records view (mentioned by @johnhbenetech). I fixed following points from @bognasoldev89 comment:
1. Now you cant create setting with name which already exists in your system account (agency)
2. The first position on dropdown is now: 'All fields'
4. After deleting a setting the page is properly cleared.
5. Now on comparison (or all records) view user see all setting from his system account (agency) and on settings management panel user can see only his settings.

Reg. 4th point from @bognasoldev89 comment, here are my possible solutions for this:
1. It stays the same (no changes applied) and we believe that user will know and remember about this behavior.
2. When user selects something from physical address without having it selected in Location then there will be displayed red text above field, which will inform him about requirement of adding it also to other related setting (Location in this case)
3. When user selects something from physical address without having it selected in Location then this field will be automatically added in related setting (Location in this case)
4. Physical address field is disabled until user selects it in related setting.
5. Physical address fields is hidden until user selects it in related setting.

Personally I think either 2nd or 4th are the best options. 
3rd might provide some edge cases which may result in some sort of user confusion.

What do you @NeilMBenetech @johnhbenetech  think about that one?

**Comment by johnhbenetech** [comment]
@NeilMBenetech would lvoe your input on this.

I think i'm leaning towards # 3 but could be convinced otherwise.

I would imagine if any address field is added, that parent address entity is automatically added to the Location section. If the parent address entity is removed from the Location section, it should wipe out any previously selected fields from the related child address entity.


I think # 4 could also work, but im worried it wont be clear how to 'enable' the address entities. At a minimum there would need to be a hint when disabled like - 'please add physical address to Location section to choose these fields' or something

**Comment by NeilMBenetech** [comment]
@johnhbenetech @awalkowiak I think I like #3 as well, which I think boils down to "If any address field is selected, automatically included all address fields."

**Comment by bognasoldev89** [comment]
> I fixed this feature on all records view (mentioned by @johnhbenetech).

Done:
![735 1](https://user-images.githubusercontent.com/51324797/74637732-d9c26380-516a-11ea-88c1-a45d788ec47e.png)

> Now you cant create setting with name which already exists in your system account (agency)

Done (exemplary gif is for the same user, but it works for the whole agency. I was not able to save fields set as a user within the same agency).
![735 2](https://user-images.githubusercontent.com/51324797/74638105-94526600-516b-11ea-8439-5560c6320b10.gif)

> After deleting a setting the page is properly cleared.

Almost done. In general, it works fine:
![735 3](https://user-images.githubusercontent.com/51324797/74638223-ccf23f80-516b-11ea-8aae-7dd8eb6f16f5.gif)

Unless you delete fields set with locations. In that case, Location Fields are not cleared:
![735 5](https://user-images.githubusercontent.com/51324797/74639008-56eed800-516d-11ea-955f-525b0f2a4b81.gif)

> Now on comparison (or all records) view user see all setting from his system account (agency) and on settings management panel user can see only his settings.

Done, but I'm not sure if this should work this way.

> When user selects something from physical address without having it selected in Location then this field will be automatically added in related setting (Location in this case)

Done:
![735 4](https://user-images.githubusercontent.com/51324797/74638752-d29c5500-516c-11ea-8790-0925e89c50d4.gif)


@johnhbenetech @NeilMBenetech can you please clarify, if those two bullets work as expected now? Because I'm not sure about this:

1. Now you cant create setting with name which already exists in your system account (agency)
2. Now on comparison (or all records) view user see all setting from his system account (agency) and on settings management panel user can see only his settings.

**Comment by awalkowiak** [comment]
@bognasoldev89 The first bullet point is included in first point of initial description. Regarding your second point: I asked if user should have option to choose set from someone else from his agency and the answer was that he should see all from his agency. User can choose any setting from his agency on multi record view (or all record view). However I didn't give option to see or delete settings on "management" page if user is not the direct owner of a given setting (which i think is proper approach in this case)

**Comment by bognasoldev89** [comment]
@johnhbenetech @awalkowiak as agreed on meeting, I'm moving this issue to done
