### ISSUE TITLE
Comparison view - compare more than one partner record at a time

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#736]
Currently in Comparison view, a user can only compare the base record on the left to one record on the right.

Please add the ability for the user to compare all matching partner records. The base record will remain on the left. Matching records will "stack" horizontally to the right. 

Please include a horizontal scroll bar so the user can slide between the compared-to records on the right, but leaving the base record firmly in place on the left (not scrolled). 

The sequence of compared records from left-to-right should reflect the new preferences established in these items:

https://github.com/benetech/ServiceNet/issues/701

https://github.com/benetech/ServiceNet/issues/681

The fields across all records need to align vertically to aid in the comparison.

The "subset of fields" capability expressed in this item should also be available. https://github.com/benetech/ServiceNet/issues/735

This would not work well on a mobile device so assume the user is using a wide desktop monitor.

**Comment by bognasoldev89** [comment]
In general, it works - I was able to view all matches at once, expand and collapse sections and compare them.

I found some issues though.
1. with UI: it looks different than multi-record view where 2 organizations are compared.

Mult-record:
![736 multi](https://user-images.githubusercontent.com/51324797/73435010-1c510700-4348-11ea-880c-3c8c20172277.png)

All-record:
![736 all](https://user-images.githubusercontent.com/51324797/73435020-22df7e80-4348-11ea-82fb-5c6b659eefbb.png)

@johnhbenetech @NeilMBenetech I'll leave it to you how to proceed with that.

2. Performance.
I found Organization with 15 matches and it looks like it's too much - all record view couldn't load.

![736 many matches](https://user-images.githubusercontent.com/51324797/73435167-6c2fce00-4348-11ea-841e-44482dada61f.gif)

@jkondrat can you please look into this?

**Comment by kkaczmarczyk** [comment]
@jkondrat I've merged the timeout increase, however, this is a temporary solution. As discussed let's revisit the performance in the #826 ticket that you created.

**Comment by bognasoldev89** [comment]
As mentioned in #826 performance is improved.
All record view with 62 matches:

![826 62 matched records](https://user-images.githubusercontent.com/51324797/74322546-5ed10580-4d84-11ea-8a54-0abd71fcfce1.gif)

As for UI, this strange comma is removed and displaying match similarity is OK - regarding differences in displaying matched organizations in multi and all records views.
