### ISSUE TITLE
"Unexpected error" after dismissing mismatched organization

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#740]
As I mentioned in #309 I noticed unexpected behavior while dismissing some of the organizations an unexpected error occurs.

For example CALL Primrose organization as hluser on staging server caused this:
![unexpected error](https://user-images.githubusercontent.com/51324797/69646632-6d9efa80-1068-11ea-81f7-268316908497.gif)

And I managed to get this on local server for test organization:
![Screenshot from 2019-11-26 15-20-40](https://user-images.githubusercontent.com/51324797/69646678-86a7ab80-1068-11ea-85b0-6412e76eb3f0.png)

**Comment by kkaczmarczyk** [comment]
@bognasoldev89 I think that this may be fixed by now - could you re-test this scenario?

**Comment by bognasoldev89** [comment]
@kkaczmarczyk @johnhbenetech seems like it works now!

![740](https://user-images.githubusercontent.com/51324797/70247870-623f8380-177a-11ea-8ec9-dff5dda8fce4.gif)

I'm going to close it and I'll include it to the regression, just to be sure
