### ISSUE TITLE
Investigate why one of UWBA organization is not restricted (but should be)

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#741]
As was said in #496 Locations at San Benito and Santa Cruz are supposed to be restricted.
ENCOMPASS COMMUNITY SERVICES from UWBA shows locations at Santa Cruz in both single and multi record view though.

**Comment by awalkowiak** [comment]
@johnhbenetech my guess here is that we exclude Region, not City in Location Exclustion here:
![Selection_018](https://user-images.githubusercontent.com/12113312/70534750-faaf7c80-1b5b-11ea-825d-a22fc8a50191.png)
and looking into both locations related to Santa Cruz in organization we have:
![Selection_019](https://user-images.githubusercontent.com/12113312/70534830-2e8aa200-1b5c-11ea-9851-cd4a42e0daa1.png)

If this is not the case, then it will need some further investigation

**Comment by awalkowiak** [comment]
@bognasoldev89 please change location exclusions and recheck this issue.

**Comment by bognasoldev89** [comment]
@awalkowiak yeah, seems accurate, I'll include this in test case. Thanks for noticing this!
