### ISSUE TITLE
Update date filter doesn't work properly when "Only show matching" is unchecked

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#742]
When "Update date" is set to Last 7 days and "Obly show matching" is unchecked, records are not filtered properly.

Screen from 26.11.2019:
![last 7 days](https://user-images.githubusercontent.com/51324797/69651391-4b10df80-1070-11ea-86d2-b1d36cce3b21.png)

Also when date range was set from 11/12/2019 - 11/26/2019 I got hits with 11/08/2019 date.

The issue works fine when "Only show matching" is checked

**Comment by awalkowiak** [comment]
@bognasoldev89 I also found issue, that datepicker dates were inconsistent when i had changed timezones. Example: when i changed my timezone to PT, when I was selecting 1st of December i got records starting from 30th of November. When you will be testing this issue please also test this behavior.

**Comment by bognasoldev89** [comment]
@awalkowiak it seems fine now, timezone case too

![Screenshot from 2019-12-13 17-13-38](https://user-images.githubusercontent.com/51324797/70814524-f1c4e200-1dcb-11ea-8bc9-0801037b50ca.png)
