### ISSUE TITLE
Handle the case when physical address is null to prevent error on organization detail page

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#746]
see #698

**Comment by jkondrat** [comment]
It turns out that there are 42 records with empty physical_address; I have changed the UI to skip this section for these records, and display postal address in the dropdown instead.
> "Seniors EyeCare Program (SEP)"
> "BART"
> "Crystal Springs Trail County Park"
> "James V. Fitzgerald Marine Reserve"
> "Wunderlich Park"
> "RecycleWorks"
> "Overeaters Anonymous of the Mid-Peninsula"
> "Northern California Gamblers Anonymous"
> "Transgender Care Clinic for Trans Youth"
> "Healthy Homes"
> "Daybreak"
> "Child & Adolescent Hotline & Prevention Program"
> "Crisis Intervention and Suicide Prevention Center"
> "Crisis Hotline"
> "Alcohol and Drug Helpline"
> "Bay Area Legal Aid - Marin Regional Office - Location"
> "Children and Adults with Attention Deficit/Hyperactivity Disorder"
> "Healthy Homes"
> "Daybreak"
> "Child & Adolescent Hotline & Prevention Program"
> "Crisis Intervention and Suicide Prevention Center"
> "Crisis Hotline"
> "Alcohol and Drug Helpline"
> "Community Health., Mobile Clinic"
> "Explorers' Program"
> "Healthy Homes"
> "Daybreak"
> "Child & Adolescent Hotline & Prevention Program"
> "Crisis Intervention and Suicide Prevention Center"
> "Crisis Hotline"
> "Alcohol and Drug Helpline"
> "Healthy Homes"
> "Daybreak"
> "Child & Adolescent Hotline & Prevention Program"
> "Crisis Intervention and Suicide Prevention Center"
> "Crisis Hotline"
> "Alcohol and Drug Helpline"
> "Community Service Center"
> "California Youth Crisis Line"
> "Bay Area Legal Aid - Marin Regional Office - Location"
> "BART"
> "Compassionate Friends"
>

**Comment by bognasoldev89** [comment]
I checked those cases and error does not occur anymore and it seems to be working just fine now. For example:

![746](https://user-images.githubusercontent.com/51324797/70043508-e6e6a200-15c0-11ea-9cde-5833a5eda10b.png)

@johnhbenetech  @NeilMBenetech could you check if that's ok? Here comparison of UI for the modified record and a regular one:

![746 2](https://user-images.githubusercontent.com/51324797/70044027-d2ef7000-15c1-11ea-92a9-e44a61537e92.png)


@jkondrat I just want to make sure of one matter - you changed UI with the thought of future records with that issues, not only those listed by you?

**Comment by bognasoldev89** [comment]
Hi @johnhbenetech what's your opinion on this solution? I would like to include this test case in regression

**Comment by johnhbenetech** [comment]
@NeilMBenetech What do you think? In the case where a location does not have a physical address at all, should we simply not show the physical address section (this is what we have done in this task)?

Would you prefer a different UX - showing a blank section or a small note?

**Comment by NeilMBenetech** [comment]
@johnhbenetech I think it is a little better UX to show the fields but with nothing in them. Relatedly on the "Location dropdown picker" we should probably list the Location as "No physical address provided" instead of blank.

**Comment by bognasoldev89** [comment]
@jkondrat can you look into that?

**Comment by bognasoldev89** [comment]
I confirm that on Locations dropdown "No physical address provided" is visible for mentioned locations, fields are displayed but empty and no error occurs.

See an example:
![746 working](https://user-images.githubusercontent.com/51324797/71171935-45697c80-225f-11ea-9178-d2e1b6b17753.gif)
