### ISSUE TITLE
Refactor 'last partial update' functionality

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#755]
There seems to be some inconsistencies in how we populate 'last partial update' across organization, service, and location records after #680. Talking a bit  with @awalkowiak I was hoping we could explore the following:

* Review organization 'last partial update' field. We believe it actually looks at the last time organizationmatch was updated. Can we confirm that this actually reflects the last date ANY field in the entity was updated? Why don't we populate organization.updated_at during data imports whenever a entity field changes?

* For location and service, why aren't we using/populating location.updated_at and service.updated_at during data imports whenever a entity field changes?

Once the import logic is adjusted to start writing these updated_at fields during import jobs, I will run one time SQL jobs to back populate the missing data for historical records based on the metadata table.

something like:
SELECT max(last_action_date)
FROM public.metadata
where resource_class='Service'
and last_action_type = 'UPDATE'
and resource_id = [id of entity]

**Comment by awalkowiak** [comment]
@johnhbenetech I fixed the timestamps saving. Now we need to populate the missing data after deployment with the following:
>UPDATE organization o SET updated_at = (SELECT max(last_action_date) FROM metadata m where m.resource_id = o.id and m.last_action_type IN ('CREATE', 'UPDATE'));

>UPDATE service s SET updated_at = (SELECT max(last_action_date) FROM metadata m where m.resource_id = s.id and m.last_action_type IN ('CREATE', 'UPDATE'));

>UPDATE location l SET updated_at = (SELECT max(last_action_date) FROM metadata m where m.resource_id = l.id and m.last_action_type IN ('CREATE', 'UPDATE'));

**Comment by awalkowiak** [comment]
Seems like our current deepEquals on organisation update is not working properly. When I was uploding same file it was always validated as changed data and updated to database. After fixing this issue our timestamps should work properly

**Comment by awalkowiak** [comment]
@johnhbenetech all work related to this issue is done. We can run the mentioned queries. I can do it on staging, but prod will need to be updated by you.

**Comment by bognasoldev89** [comment]
@awalkowiak for healthleads, SMCConnect and ShelterTech it works, but after uploading LAAC, UWBA  and Eden data with changes for example only in Location, all "Last partial update" dates are changed. Can you look into that?

**Comment by bognasoldev89** [comment]
So I checked all of the providers again and now the "Last partial update" date is showed correctly for all of them.
