### ISSUE TITLE
Fix weird signs depicting apostrophes after csv files upload

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#763]
I noticed that after uploading csv files (for healthleads, SMC and LAAC) apostrophes are replaced by weird signs. Json files work OK.
I looked for older healthleads records and I found out that apostrophes were displayed correctly earlier.

Examples:

![Screenshot from 2019-12-17 13-09-06](https://user-images.githubusercontent.com/51324797/70994431-85e5c080-20ce-11ea-9787-701f03d01b0e.png)

![Screenshot from 2019-12-17 12-57-26](https://user-images.githubusercontent.com/51324797/70994489-a9a90680-20ce-11ea-842a-e20b588ca86c.png)

**Comment by jkondrat** [comment]
@bognasoldev89 : Could you please share the CSV files? I tried uploading a sample organization with apostrophes and it worked fine:
![Screenshot from 2019-12-17 17-13-52](https://user-images.githubusercontent.com/5969801/71013225-a1fa5980-20f0-11ea-8377-073c987257b7.png)

**Comment by bognasoldev89** [comment]
@jkondrat sure: https://drive.google.com/drive/folders/1J-f7L6fMgLoXI-0ZkbqO9FdZ7GnarxFE?usp=sharing

**Comment by jkondrat** [comment]
@bognasoldev89 : It looks that the file is corrupted, it shows me these weird signs when I opened it with utf-8 encoding

**Comment by bognasoldev89** [comment]
@jkondrat @johnhbenetech seems like it was my file editor's fault. I edited a file in notepad, uploaded and got apostrophes right:
![Screenshot from 2019-12-19 14-30-17](https://user-images.githubusercontent.com/51324797/71177340-160d3c80-226c-11ea-923c-0a70c3496b43.png)

But I think it would be good to keep this issue in mind for the future.
