### ISSUE TITLE
Recommend approach for architectural changes for upcoming API work

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#771]
As we've discussed on calls we will have some upcoming work around enabling API access to core data flows in ServiceNet. The main consumers of these APIs will be other vendor software that wishes to display serviceNet data/matches directly in their tool. Additionally they may use an additional API to directly send us updated records from their systems in real time so we will no longer have to rely on weekly jobs.

In preparation for this work I want the team to review our architectural approach and make any recommendations they see necessary to scale.

**Comment by johnhbenetech** [comment]
Some ideas I had which we may consider:

* Separate the front end from the back end application. Currently our jhipster approach does all data operations AND serves the frontend in one container. Taking a quick read through the j hipster documentation I see some details around peeling off the front end. In other projects, we simply have the build process output a static version of the front end which we then host separately from the backend. 

* Come up with a way to host the API gateway separately from the back end container. I think it's easy to say that we could just use some built-in AWS service, but in that this project is meant to be open source I'd like to hear if there are any other elegant solutions. Can we come up with an architectural approach that can be used by any person hosting on any platform?

* Review the current backend operations for any opportunities to increase performance, robustness, and speed. 

I'm not saying we have to do any or all of the above, just some of my thoughts. My hope is that by moving towards a more microservices approach we can avoid issues taking out all functionality

**Comment by kkaczmarczyk** [comment]
> Separate the front end from the back end application. Currently our jhipster approach does all data operations AND serves the frontend in one container. Taking a quick read through the j hipster documentation I see some details around peeling off the front end. In other projects, we simply have the build process output a static version of the front end which we then host separately from the backend.

I think as well that we can use the jHipster bells and whistles to handle that. @jkondrat can you explain how are you doing the separation? The front end / back end split affects things like the deployment process and CI builds.

> Come up with a way to host the API gateway separately from the back end container. I think it's easy to say that we could just use some built-in AWS service, but in that this project is meant to be open source I'd like to hear if there are any other elegant solutions. Can we come up with an architectural approach that can be used by any person hosting on any platform?

@jkondrat I am curious about the architectural approach here - could you explain how do you want to achieve this?

**Comment by jkondrat** [comment]
@kkaczmarczyk : I'm generating a backend and gateway microservices using the newest JHipster and moving our existing back- and frontend code there. We will probably need to run docker containers like consul for development, I'll add docker-compose configurations and scripts to the repo that will ease the process
Regarding the API gateway, JHipster has a dedicated service type that uses Zuul proxy. The frontend will be also served there. 
I propose that we create a new repo for gateway + ui. Another option would be to put it in a separate directory

**Comment by jkondrat** [comment]
It might also be a good idea to create a separate microservice for authentication and add oauth2 there
