### ISSUE TITLE
Investigate disappearing taxonomies for LAAC, ShelterTech, and healthleads providers

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#778]
I noticed that for LAAC, ShelterTech and healthleads providers all of the taxonomies disappeared and are no longer available while browsing organizations. It also makes difficult filtering by Taxonomy filter.

**Comment by johnhbenetech** [comment]
Thanks @bognasoldev89 

I forgot where we wound up with this. I think it was possibly that we were pulling tax name vs tax details? We should try to find the best strategy for each partner, or at least have a null fall back.

**Comment by awalkowiak** [comment]
@johnhbenetech, is there anything else for me to investigate/do beside what was already discovered and shared on slack/meeting?

**Comment by johnhbenetech** [comment]
Maybe if you and @bognasoldev89 can recheck Staging and make sure the approach seems to have fixed it as expected. Then I believe this will be complete.

**Comment by bognasoldev89** [comment]
@johnhbenetech @awalkowiak in my opinion this bug is fixed. I got hits for mentioned providers for every randomly chosen taxonomies:

![778 hl](https://user-images.githubusercontent.com/51324797/72966822-1c895980-3dc0-11ea-8f9f-915256e46fbf.gif)

![778 laac](https://user-images.githubusercontent.com/51324797/72966823-1d21f000-3dc0-11ea-9434-1bdcff8d1f26.gif)

![778 st](https://user-images.githubusercontent.com/51324797/72966825-1d21f000-3dc0-11ea-9d80-a5978e62cee8.gif)

Just to be sure I check other providers and it's well:

![778 eden](https://user-images.githubusercontent.com/51324797/72966904-46db1700-3dc0-11ea-9ad8-06cf3aadff3d.gif)

![778 smc](https://user-images.githubusercontent.com/51324797/72966905-46db1700-3dc0-11ea-9e58-5bcc1ca61fa4.gif)

![778 uwba](https://user-images.githubusercontent.com/51324797/72966907-46db1700-3dc0-11ea-8738-6dd0ae847270.gif)

**Comment by awalkowiak** [comment]
Ok, so for future if this will occur once again. Look into table service_taxonomy and if it will have lot of nulls in taxonomy_id, then: reupload data or if there is access to db snapshot with these value, then copy ids to places where it is missing. This might be helpful:
