### ISSUE TITLE
Show "freshness" metadata when you are viewing one of your Organization records

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#779]
As a follow-on to https://github.com/benetech/ServiceNet/issues/700 , we also want to display the "freshness" of records to more seamlessly help users decide which of various different possible partner matching records have the most recent updates and hence which one the user might want to look at first.

I propose that just under the "matching" metadata added from the task noted above (example: "3 services / 1 match"), we also indicate a "freshness" value there too. 

To make this value easy to interpret, I propose that we sum the total number of days since each record was updated (the parent Organization plus all child Location and Service records to that Org) and divide by the sum of records (Org + Services + Locations) to yield an "average number of days since last updated" or "freshness". If a "complete review" date is available for all records of the Organization record, use that. If not, then use the "partial update" date for the records.

Example: For partner "Health Leads", their Organization "Bob's Services" was updated 200 days ago. It has one Location that was updated 100 days ago and two Services that were updated 300 and 400 days ago, respectively. So the total number of days since each record was updated is 1,000, and there are 4 records (1 O, 1 L, 2 S) = 1,000 / 4 = 250 days on average since last updated = "freshness".

**Comment by johnhbenetech** [comment]
@NeilMBenetech just to double check, in your example we would display '250 days' or do you want to afford some different language to the user?

**Comment by NeilMBenetech** [comment]
@johnhbenetech Good question. I think we want a succinct way to express the concept. How about "250 days on average since last updated" with a tooltip/title attribute to explain the math when you hover over that prose: "We take the total number of days it has been since this Organization and all of its Service and Location records have most recently been updated, and divide by the total number of records, to calculate the average number of days since these records have been updated."

**Comment by bognasoldev89** [comment]
@jkondrat I calculated a different amounts of average days for some matched organizations. Can you please investigate?

**Comment by bognasoldev89** [comment]
My calculations fit displayed the average amount of days counted on the app now.
I also confirm that last complete review date is taken for calculations if available, and if not, last partial update date is counted.
It's all clear now.
