### ISSUE TITLE
Allow users to express record matches manually at the Service and Location level

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#780]
When a user is comparing their own record to partner records, they might spend considerable time deciding which partners' Service records actually match to their own Service records. Once they have done that work, it should be retained so they don't have to do that again in the future, for those records.

So please enable users to manually mark their own Service to be a match to 0, 1 or many partner Service records and when they are viewing their own Service record, they can quickly navigate to the partner Service records they had previously marked as "matches". 

This "quick navigation" might be a hyperlink listed in their own Service record that, when clicked, brings the corresponding comparison Service record to the right-hand column. The text for the hyperlink should be [Partner Name] + [Matching Service Name] so for example: "Health Leads - Larry's Food Pantry" which should be sufficient for this and not require more information (such as the Service's parent Organization record name).

Any manual match saved by a user should be available to all other users from that partner. Users should also be able to delete these manual matches.

The data generated from these manual matches could also be used by us to help us check and tune our automated Service-level matching laid out here : https://github.com/benetech/ServiceNet/issues/699

**Comment by johnhbenetech** [comment]
@NeilMBenetech we will need a UI suggestion for this. Is that something you'd like to handle?

**Comment by kdondziak** [comment]
@johnhbenetech @NeilMBenetech In the description is mentioned that #699 should be done first. Am I right? Also what about UI suggestion?

**Comment by NeilMBenetech** [comment]
Hi @kdondziak actually I think this one should be done before #699 so that data from this one could feed the algorithm used there. 

@johnhbenetech  As for UI, I think the original write-up of this addresses how to navigate to the manually-matched records, but you're probably looking for a UI suggestion for how to mark the matches, manually, in the first place.

I recommend that when you are viewing your own record's detail in the left column and have a partner's record in comparison in the right column, there is a button below the Service name that reads something like "Matches my Service record". If the shown partner record had already been marked as a match, the button would change to say "Unmatch this record".

The same would apply for Location records as originally specified in this item.

In thinking further about this, I think it makes sense to allow for this matching to happen at the Organization level too. So, all three levels would be able to be indicated as a match, independently. That's because, while the partner's Organization might match my own (and I want to manually confirm that), every child Service and Location may or may not match to my own.

Further, I anticipate some filters on the main Search page (in a later Github task) where users can go directly to just records they had previously designated as Matched.

**Comment by abaranowska1** [comment]
@kdondziak I checked this functionality and I saw that users can manually mark their own Service as matching 0, 1 or many partner Service records and when they are viewing their own Service record, they can quickly navigate to the partner Service records they had previously marked as "matches", but I found two things that can be investigated: 

1. In my opinion, after clicking the hyperlink in section "Matches", the page should back to the top 
2. Please check why this "See another match" ![image](https://user-images.githubusercontent.com/61964176/76519676-b769f000-6461-11ea-9bea-ca59b175cc38.png) always have the same value, for example (3/5) even if I changed the partner's organizations via hyperlink 

Steps: 

- Log in to the app as Admin
- Go to the organization with conflicting data for example (HOUSING AUTHORITY OF THE COUNTY OF Commoncounty (ABCD) siala)
- Open all partners record view
- Click "Match my location record" for example in 1 and 3 organization 
- Go to "Matches" section and click the second hyperlink - you see that "See another match" display 3/5)
-Go to "Matches" section and click the first hyperlink - you see that "See another match" display the same value 
![sam](https://user-images.githubusercontent.com/61964176/76521177-9525a180-6464-11ea-8aad-3ccf90bfb4c1.gif)

**Comment by kdondziak** [comment]
@johnhbenetech What do you think about Alicia's idea "In my opinion, after clicking the hyperlink in section "Matches", the page should back to the top" ?

**Comment by johnhbenetech** [comment]
@NeilMBenetech feel free to chime in here.

I wonder if it's possible to not only go to top, but also expand the location section and switch right to the matching location? Do we have a time estimate on how long that interaction would take?

**Comment by kdondziak** [comment]
@johnhbenetech If you mean scroll to the top and collapse related location? Or Scroll to location dropdown and open right one?

**Comment by johnhbenetech** [comment]
sorry, scroll to location and open right one (matching one)

**Comment by kdondziak** [comment]
I think it would take 1d

**Comment by johnhbenetech** [comment]
cool, lets go for it then.

@abaranowska1 number 2 should be investigated as well

**Comment by abaranowska1** [comment]
Retested and confirmed that after fix the manual record matches functionality works without any issue. 
After clicking the hyperlink the page is scrolled to the right matching location/services. The second issue with "See another match" is also fixed.
