### ISSUE TITLE
API: Request matching records

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#783]
Create an an endpoint that only responds to authenticated and authorized API requests (see this related task : https://github.com/benetech/ServiceNet/issues/782 ).

Both the request and the response should be in well-structured JSON. The request should specify the native unique identifier of any Organization, Service or Location record in their own database. 

The response should include an array of matching records of the same record type as the request (O, S, L) with the following attributes:
-Service Net unique identifier (so it can be subsequently requested)
-Native unique identifier (in the owner's database)
-HSDS record type (Organization, Service, Location)
-Record name as present in the partner's datbase (for example "Bob's Food bank")
-Name of the SN partner agency that owns the matching record

In the future we may add "matching" metadata to the response object, but for now we will start with these basic attributes.

**Comment by kdondziak** [comment]
@johnhbenetech I have a question about details of the endpoint. 
1. Should there be one endpoint for (organization, location, services) or one for each of them?
2. Should it accept one id or array of ids?

**Comment by johnhbenetech** [comment]
1. I think we should just start with organizations alone right now. This is the biggest use case by far and I'd rather wait on building anything out for locations or services. 

2. Let's just keep it to a single ID

So essentially there is a get organization matches endpoint

It takes in:
* an organization ID (either a ServiceNet ID or one from their system (external_db_id)
* an optional threshold for similarity (suggestions on what the default should be?) 

It provides back an array of orgs we believe to be matches. each includes
* SN org ID
* SN org Name
* SN org's system account name
* Similarity


Open to suggestions or if you feel im missing anything obvious

**Comment by kdondziak** [comment]
Note for QA:
Test for this issue consists of 2 parts:

1. Creating, reading, updating and deleting client -> see admin menu client management.
2. Getting information from api via postman: 
- Create client in mentioned above client management
- Using credentials get auth token just like #782 
- Using token prepare request:
* Post: https://benetechservicenet.org//services/servicenet/partner-api/records
headers section:
Content-Type: application/json
Cookie: access_token="here paste token"
body section: 
{
    "id": "id of organizatinon from same provider as client e.g. sheltertech 6a5cc3c9-6181-4c6d-ae30-bde10f3a4660",
    "similarity": 0.1
}

**Comment by abaranowska1** [comment]
Following by @kdondziak  instruction I checked:

1. Creating, reading, updating, and deleting external client, and here I found one small issue : 
![ise](https://user-images.githubusercontent.com/61964176/80707308-06d7ae80-8aea-11ea-9b17-26b9e75f88dd.gif)
Internal Server Error is thrown after I want to create a client with the same id 
2. Getting information from API via postman - here all works fine, I can send POST requests and use organization external id in different forms ( with letters, only numbers or with "-"), response body shows correct information and I've always had status code 200 when I put proper data 
![image](https://user-images.githubusercontent.com/61964176/80707735-c167b100-8aea-11ea-9db8-91b5b2b60b74.png)
![image](https://user-images.githubusercontent.com/61964176/80707777-cd537300-8aea-11ea-9fee-72a1a197b74d.png)
![image](https://user-images.githubusercontent.com/61964176/80707803-de03e900-8aea-11ea-959a-c7a471c4d1c8.png)

**Comment by abaranowska1** [comment]
**Tested with success**
Internal Server Error is not thrown after I want to create a client with the same id 

![test](https://user-images.githubusercontent.com/61964176/81400500-8d653f00-912d-11ea-9d06-276ce31fd500.gif)

Also getting information from API via postman works fine, I can send POST requests and use organization external id in different forms ( with letters, only numbers or with "-"), response body shows correct information and I've always had status code 200 when I put proper data
