### ISSUE TITLE
API: Request and response logging

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#785]
As these tasks are being coded as well as all future API-related tasks:
https://github.com/benetech/ServiceNet/issues/782
https://github.com/benetech/ServiceNet/issues/783
https://github.com/benetech/ServiceNet/issues/784

Please log every request and response, including the bearer token used, requesting IP address, the request URL and body, the response HTTP code, URL and Body. This will be useful for us to track usage, potentially enable throttling, and debug any bugs or issues we see over time.

**Comment by awalkowiak** [comment]
Note: The feature is finished, but needs to be moved to ServiceNetGateway service. It will be done when we split db schemas for services #873.

**Comment by awalkowiak** [comment]
@jkondrat Could you confirm that this is working. (excluding the 0x00 issue, which will be resolved in  separate issue)
