### ISSUE TITLE
Adjust the database schema to include multiple locations for organizations

### ISSUE THREAD

**Issue by oskarhinc** [benetech/ServiceNet#79]
Some organizations might have multiple locations - it should be included in the database schema. When it'll be available, some data adapters should be adjusted too - e. g. data from iCarol contains multiple locations for an organization, so all of them should be persisted.

**Comment by johnhbenetech** [comment]
I think this is fixed? I see multiple locations for some iCarol records. QA to confirm

**Comment by kkrawczyk123** [comment]
Confirmed that I can see multiple locations for iCarol and other records.
