### ISSUE TITLE
Fix displaying Location and Services section

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#795]
I found an interesting UI bug:
1. Open multirecord view for Organization with more than one matches (Note: different number of Locations and/or Services)
2. Choose the last Location/Service from the match with the biggest number of them.
3. Check other matched organizations.

Actual result:
4. Locations/Services are hidden while the app tries to show always the same "position" -> the first, the second

Expected result:
4. Locations/Services should be always available

Exemplary gif:
![showing Locations bug](https://user-images.githubusercontent.com/51324797/73343860-979bb580-4281-11ea-9d40-7db4f79675fa.gif)

**Comment by bognasoldev89** [comment]
I confirm that bug is fixed. Chosen sections don't disappear anymore, it just goes back to the first one from the list.

Examples for Locations and Services:
![795 services working](https://user-images.githubusercontent.com/51324797/73832194-02139f00-4808-11ea-9473-9563518de218.gif)

![795 locations working](https://user-images.githubusercontent.com/51324797/73832198-0344cc00-4808-11ea-83da-24d1ce2ce13a.gif)

**Comment by abaranowska1** [comment]
During regression testing after re-architecture, I met the same issue once again. Locations are hidden during changing the records and partners organizations 
![reopen](https://user-images.githubusercontent.com/61964176/78014426-35763400-7348-11ea-8b87-c60758e83756.gif)
Organization from testing: Mission Neighborhood Health Center (MNHC)

**Comment by abaranowska1** [comment]
**Tested with success**

![loc2](https://user-images.githubusercontent.com/61964176/78872633-df8d4480-7a49-11ea-8634-a5410962cd5b.gif)

I confirm that the bug is fixed. Chosen sections don't disappear anymore.
