### ISSUE TITLE
Fix errors during data upload

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#796]
I have issues with uploading data on staging and local servers.
On staging data from UWBA, Eden and ShelterTech are not uploaded, on local data from all of the providers give back this error message:

> During the import, the following problems occurs: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : org.benetech.servicenet.domain.PhysicalAddress.location -> org.benetech.servicenet.domain.Location; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : org.benetech.servicenet.domain.PhysicalAddress.location -> org.benetech.servicenet.domain.Location

**Comment by awalkowiak** [comment]
Dev note: @kdondziak suggested that adding cascade all might help

**Comment by kdondziak** [comment]
To PhysicalAdress's location field to be precise.

**Comment by bognasoldev89** [comment]
I confirm that bug is fixed and data can be uploaded again. There's no error message in Import Data Report and I have confirmation from developers that uploaded Organizations are in db.
