### ISSUE TITLE
Investigate issues with geography filters

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#802]
While testing #661 issue I found an organization placed in Oakland and Hayward, but this record is not displayed after applying filters with those cities. If needed I probably can provide more examples for this issue.

Link to the organization: https://benetechservicenet.org/#/single-record-view/0d62edae-e06a-4b32-bc19-5659fbf31739

**Comment by kdondziak** [comment]
@bognasoldev89 @johnhbenetech 
I investigated the issue and here is what I've found:
Filter 'City' in home page is looking for 'locality' field in geocoding table in the database. What Bogna saw was City in Physical address. Usually cities in geocodin_result and in physical address are the same, but about 20% of geocoding records in Eden organizations have nulls on most of the fields. #661 fixed issue with saving geolocation but some data is corrupted. 
cc @awalkowiak

**Comment by kdondziak** [comment]
@johnhbenetech You asked me about what was causing this issue. I believe it was mentioned above #661 and this issue won't happen again.

**Comment by bognasoldev89** [comment]
**Tested with success**

Tested on Chrome 79.0.3945.130 

Test cases checked:
- Filtering Oakland in City filter and looking for LINCOLN Organization as edenuser
- Filtering Hayward in City filter and looking for LINCOLN Organization as edenuser
- Checking Locations for randomly chosen Organizations, filtering checked cities/counties and checking if Organizations are displayed on the homepage

I filtered a few randomly chosen Organizations by Locations I knew and I found them on the homepage after applying filters. I consider this issue finished.
