### ISSUE TITLE
User with no admin role has access to entities pages.

### ISSUE THREAD

**Issue by kdondziak** [benetech/ServiceNet#810]
User has access to entities pages and can view, edit, delete entities.

Step to reproduce: 
1. Login as user with ROLE_USER e.g. stuser
2. Go to entity page e.g. https://benetechservicenet.org/#/entity/service

Expected result: User has no access to that page.
Current result: User can see, edit, delete entities.

**Comment by bognasoldev89** [comment]
I confirm that I had no access to entities pages as regular user and sacramento user. I checked upload, administration and sessions pages too, with the same result.

Examples:
![810 1](https://user-images.githubusercontent.com/51324797/73841212-650e3180-481a-11ea-94af-97517563d906.png)

![810 2](https://user-images.githubusercontent.com/51324797/73841214-65a6c800-481a-11ea-83ad-c137b54d44b9.png)

![810 3](https://user-images.githubusercontent.com/51324797/73841217-663f5e80-481a-11ea-9670-0ad5946df931.png)

![810 4](https://user-images.githubusercontent.com/51324797/73841218-663f5e80-481a-11ea-8aef-2ebb2b0b27f0.png)
