### ISSUE TITLE
Improve the performance of fetching ActivityRecordDto

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#826]
It takes a couple of seconds to fetch activity dto, when there are lots of matches the multi- and all- record views can take really long time to load

**Comment by bognasoldev89** [comment]
I can confirm that the performance improved a lot.

Organization with 27 matches:
![826 27 matched records](https://user-images.githubusercontent.com/51324797/74320938-c89be000-4d81-11ea-8d27-2f5c6b07153a.gif)

Organization with 62 matches:
![826 62 matched records](https://user-images.githubusercontent.com/51324797/74320964-d0f41b00-4d81-11ea-9e4a-cc5a9252bb53.gif)

I went through staging, not only on multi and all orgs views and performance really seems to be better.
