### ISSUE TITLE
When comparing to multiple records, scroll bar is inconvenient

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#827]
Here's an example in the production system logged in as uwbauser

https://servicenet.benetech.org/#/all-records-view/01f03ca9-b597-425a-b3ec-2cbb65ebee3f

There are 4 comparison records for the 1 base record in the uwba system. In order to scroll to the right to see them all, I first have to scroll ALL the way down to the very bottom of the page.

Instead, could the "scroll right" bar be always visible please? Screen shots below.

![CaptureA](https://user-images.githubusercontent.com/52297301/74120461-54422080-4b78-11ea-985b-39569d036ea4.PNG)
![CaptureB](https://user-images.githubusercontent.com/52297301/74120464-560be400-4b78-11ea-8141-4b9670aa3150.PNG)

**Comment by bognasoldev89** [comment]
Scrollbar works smoothly right now! Example:

![827 working](https://user-images.githubusercontent.com/51324797/74348906-b8045d80-4db3-11ea-9d2c-da0597d79dc5.gif)
