### ISSUE TITLE
Match percentage shows as 0.00% even though there are 4 matching records

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#828]
In the production system logged in as uwbauser, I'm looking at this record and 4 matching records in "multi" view. 

You would think each of the matching records would have some non-zero matching score, but all of them have 0.00%, which must be an error (or the matches should not be showing). Please investigate. Screen shots below.

https://servicenet.benetech.org/#/all-records-view/01f03ca9-b597-425a-b3ec-2cbb65ebee3f

![CaptureA](https://user-images.githubusercontent.com/52297301/74120638-e77b5600-4b78-11ea-921a-8c8aea5c3418.PNG)
![CaptureB](https://user-images.githubusercontent.com/52297301/74120640-e9451980-4b78-11ea-92f2-5907d7d9d827.PNG)
![CaptureC](https://user-images.githubusercontent.com/52297301/74120643-eb0edd00-4b78-11ea-84f9-21bb62d5f4bf.PNG)
![CaptureD](https://user-images.githubusercontent.com/52297301/74120645-ed713700-4b78-11ea-98bf-f87727eca6f1.PNG)

**Comment by awalkowiak** [comment]
@jkondrat is it possible, that your most recent improvement for similarity count will fix this issue?

**Comment by jkondrat** [comment]
@awalkowiak : No, it wouldn't remove any existing matches, we will probably need to add a migration that cleans them up

**Comment by johnhbenetech** [comment]
@NeilMBenetech I believe this was just catching it while our match update script was running. Can you recheck and see if you still are seeing this issue?

**Comment by NeilMBenetech** [comment]
@johnhbenetech I saw this morning that it is working now, thanks!
