### ISSUE TITLE
Custom record views - need a UI tweak

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#829]
Now that I see the "custom record views" that allows me to dictate the visible fields (love it) I have a small request to make the capability a little more obvious.

How about to the left of the gear/cog icon we have the prose: "Show less fields" to make it more obvious that is what it is there for?

![CaptureA](https://user-images.githubusercontent.com/52297301/74120807-bb140980-4b79-11ea-88c5-0a92c1c8e7d1.PNG)

**Comment by bognasoldev89** [comment]
I checked this feature and it looks nice in my opinion. I rechecked if it works OK and I haven't found anything wrong.

Design:
![829](https://user-images.githubusercontent.com/51324797/75986851-1aea9f80-5eef-11ea-9f3a-c660eb5446d6.png)

Exemplary usage:
![829 working](https://user-images.githubusercontent.com/51324797/75986884-2b027f00-5eef-11ea-9b28-651239b4da99.gif)

**Comment by NeilMBenetech** [comment]
Yes indeed, looks good, thanks @bognasoldev89
