### ISSUE TITLE
Security issue: Backend is not secured

### ISSUE THREAD

**Issue by kdondziak** [benetech/ServiceNet#830]
Any user can make request to backend api. I was managed to do so with postman.
Steps to reproduce:
1. Log as any non admin user.
2. Open browser console.
3. Copy Cookie and X-XSRF-TOKEN and create request headers with them.
3. Create POST request to '/api/organizations' with proper body: e.g.
{
    "active": true,
    "name": "fakeName1",
    "alternateName": "fakeAltName",
    "description": "decs",
    "email": "fakes@gmail.com",
    "url": "www.fake.pl",
    "taxStatus": "",
    "taxId": "",
    "yearIncorporated": "2020-01-02",
    "legalStatus": "",
    "updatedAt": null,
    "replacedById": "",
    "sourceDocumentId": "",
    "accountId": "4d1df6b9-12f5-491e-b7bb-dd3d73888579",
    "externalDbId": "fakeId",
    "providerName": ""
}
Expected result: Request should fail with 403
Result: Request passed

**Comment by kdondziak** [comment]
This issue affects all api endpoints except: system account, data upload, jobs, user, data import report

**Comment by bognasoldev89** [comment]
I tried to access a few entities through Postman and I got access denied info because lack of authorization.

For example, I tried to add funding:
![830](https://user-images.githubusercontent.com/51324797/74646184-a1765180-5179-11ea-8c38-bfd7968cdd88.png)
