### ISSUE TITLE
"Bad request" indicator after dismissing record from multi/all record view

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#846]
I noticed this issue while testing #339 

Reproduction:
* go to record with at least one match
* open multi/all record view
* dismiss record via "yes, remove this record" button
* click "View previously removed records"
* go back

Expected results:
* no "Bad request" indicator should appear

Actual results:
* "Bad request" indicator appears

Note: This issue has no impact on this functionality - If clicking reinstate button, organization is actually reinstated.

![reinstate bad request](https://user-images.githubusercontent.com/51324797/75159605-c2f6b080-5718-11ea-910e-98d2c2899888.gif)

![reinstate bad request 2](https://user-images.githubusercontent.com/51324797/75159610-c427dd80-5718-11ea-8f7b-d5071a61e120.gif)

**Comment by abaranowska1** [comment]
The issue still exist, but now we cannot reinstate the organization after click reinstate button 

Steps: 
- Log in to the app as Admin
- Go to record with at least one match
- Open all record view ( click Show all matches )
- Dismiss record via "yes, remove this record" button
- Click "View previously removed records"
- Click reinstate button 

Actual result: Error occurred when reinstating record pop - up is thrown 
Expected result: Organization should be reinstated.

Also, there is a difference when we go to record with at least one match, open multi record view and dismiss record via "yes, remove this record" button - app crashes and the user should log in again 

Steps:
- Log in to the app as Admin
- Go to record with at least one match
- Open multi record view ( open only one organization to compare )
- Dismiss record via "yes, remove this record" button

Actual result: User is logged out, and should log in again 
Expected result: It should be possible to dismiss record properly 

Tested on Chrome Browser Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by abaranowska1** [comment]
**Tested with success**
Dismissing and reinstating record works fine now. 

- we can reinstate the organization after click reinstate button
- it is possible to dismiss record properly

Tested on Chrome Browser Version 80.0.3987.132 (Official Build) (64-bit)
