### ISSUE TITLE
Fix time-out issue and google resources

### ISSUE THREAD

**Issue by kdondziak** [benetech/ServiceNet#853]
The goal of this ticket is to fix time-out after making long request and failing request for google resources (fonts, map scripts).

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on Firefox 73.0.1

Verified cases:
- Browsing login page with console open
- Logging in as an admin and browsing the homepage with console open
- Logging in as a regular user and browsing the homepage with console open
- Logging in as a sacramentouser and browsing the shelter view with console open
- Provoking long requests - showing all records view for 60 matches

**Summary**
I checked the app with console and focused on pages with google elements and long requests for all types of users and I haven't noticed time-out in any situation.

**Exemplary screenshots**

![853 2](https://user-images.githubusercontent.com/51324797/76401285-ee68d480-6381-11ea-8aa1-7eac793b83c8.png)

![853 4](https://user-images.githubusercontent.com/51324797/76401289-ef9a0180-6381-11ea-90c5-2a25811519cc.png)

![853 5](https://user-images.githubusercontent.com/51324797/76401370-0fc9c080-6382-11ea-992c-e0d02b93e3a8.png)
