### ISSUE TITLE
"Active" Checkbox on record view

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#857]

**Comment by NeilMBenetech** [comment]
@johnhbenetech you had created this item but it was for some reason not an "Issue" in Github, so I converted it. Do you recall what this was? If not feel free to close it and remove from the Product Board.

**Comment by johnhbenetech** [comment]
@NeilMBenetech I forget exactly :)

I think it was that having a checkbox is weird UI since it's an input normally.

Some partners don't have this concept at all, some have non binary (active, temporary pause, not active)

So maybe there's a better UI to surface this
