### ISSUE TITLE
Add missing front end tests for single, multi and all records components.

### ISSUE THREAD

**Issue by awalkowiak** [benetech/ServiceNet#861]
This is related to service: ServiceNetGateway.

Add missing jest tests for SingleRecordView, MultipleRecordView, AllRecordsView components.

**Comment by kdondziak** [comment]
@johnhbenetech It is related to old view. Should we create task for new views?

**Comment by johnhbenetech** [comment]
@kdondziak yes please do

**Comment by johnhbenetech** [comment]
Is #1151 a duplicate of this? If so feel free to close it.
