### ISSUE TITLE
Hide unused administration pages

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#864]
After migrating to microservice architecture, some of administration pages stopped working. Investigate which endpoints are present in the backend service and switch urls on the front to these. If an endpoint is not available, hide the menu item.

**Comment by bognasoldev89** [comment]
@jkondrat I checked which ones stopped working and which ones seem fine.

Fine:
- User Management
- Health
- Configuration
- Scheduler
- Logs
- API

Not available anymore:
- Metrics
- Audits
- Gateway (is not clickable anymore)

**Comment by abaranowska1** [comment]
**Tested with success**
I checked all Administration Pages and now all of them work. Correct endpoints are present in the URLs on the front side.
![Peek 2020-08-05 14-07](https://user-images.githubusercontent.com/61964176/89412793-f443c580-d727-11ea-8384-c699de42b64a.gif)
