### ISSUE TITLE
Hide "View Hidden Records" option for Sacramento user

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#868]
"View Hidden Records" option can be hidden for Sacramento user because this user is not authorized to access this page.
![viewHiddenRecords](https://user-images.githubusercontent.com/61964176/76307259-cb2e1e80-62c8-11ea-9dac-5d4245ef5df8.png)

**Comment by jkondrat** [comment]
PR: https://github.com/benetech/ServiceNetGateway/pull/41

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified on** 

- Google Chrome Version 80.0.3987.149 

**Verified cases:**

-  "View Hidden Records" option should be hidden from dropdown for Sacramento user
![Selection_125](https://user-images.githubusercontent.com/61964176/79211538-aa686400-7e46-11ea-96c9-ec285c791e38.png)
