### ISSUE TITLE
Investigate performance issue.

### ISSUE THREAD

**Issue by kdondziak** [benetech/ServiceNet#869]
QA testers have spotted that app has really bad performance and works really slow after re architecture. The goal is to investigate this issue, find possible cause of it and fix the issue if it is not complex.

**Comment by kdondziak** [comment]
Updated dependencies in https://github.com/benetech/ServiceNetGateway/commit/25a3d92dae5bed3b1dbb3a0c99b2a2b9c617f808

**Comment by abaranowska1** [comment]
I confirm that application performance has increased. It's better now and faster.
