### ISSUE TITLE
User Registration no longer displaying error when email/username already in use

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#874]
tested on staging, try to register a user with same email as existing user or same username as existing user. Registration fails silently, console log:

register/CREATE_ACCOUNT_PENDING
warning.js:33 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method `preventDefault` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist(). 
...
POST https://benetechservicenet.org/services/servicenet/api/register 400
....
logger-middleware.ts:5 register/CREATE_ACCOUNT_REJECTED
....
error-middleware.ts:28 register/CREATE_ACCOUNT caught at middleware with reason: "string.match is not a function".

**Comment by abaranowska1** [comment]
**Tested with success**

- Confirmed that error message is displayed when email/username is already in use
- Verified on: Google Chrome Version 80.0.3987.149 Browser

![user](https://user-images.githubusercontent.com/61964176/77150186-9887e100-6a93-11ea-9524-88c954cb49f0.gif)
