### ISSUE TITLE
Create an Authentication service

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#877]
* create an OAuth2 authorization service
* modify all the existing microservices to authorize requests using the auth service
* migrate existing users

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on staging env

**Verified cases**
- Logging in and out as
-- admin
-- regular user
-- Sacramento user
- Checking user management page

**Summary**
I was able to log in and out as any kind of user without any obstacles. Users seem to be migrated correctly.
