### ISSUE TITLE
Prepare a step-by-step instruction for deploying ServiceNet on production

### ISSUE THREAD

**Issue by wojtekbu** [benetech/ServiceNet#88]
TODO:
* check if mongo DB container works fine with the app,
* check if PostgreSQL container works fine with the app,
* Prepare a step-by-step instruction for deploying ServiceNet on production,
* make sure that it is clear how to add env variables e.g. partners' API keys.

**Comment by oskarhinc** [comment]
I've created a wiki page with detailed instructions:
https://github.com/benetech/ServiceNet/wiki/Production-environment
