### ISSUE TITLE
Add CI build to SN Gateway and SN Auth repos

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#884]
Add CI build to ServiceNetGateway repo. Consider using Travis or Github Actions

**Comment by kkaczmarczyk** [comment]
extended the scope to include SN auth repo CI

**Comment by kkaczmarczyk** [comment]
@johnhbenetech Hi, could you enable TravisCI to run jobs for the Auth and Gateway repos?

https://travis-ci.com/github/benetech/ServiceNetAuth
https://travis-ci.com/github/benetech/ServiceNetGateway

**Comment by kkaczmarczyk** [comment]
Closing as done - there were no issues with the builds for quite some time.
