### ISSUE TITLE
The alerts and pagination on user management page are broken

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#891]
After saving or deleting a user, an error message pops up stating that "string.match is not a function"
The pagination on that screen doesn't show the total number of pages and allows to indefinitely hit the "next page" button

**Comment by abaranowska1** [comment]
**Tested with success**

Verified on: Google Chrome Version 80.0.3987.149

Verified cases: The alerts and pagination on the user management page work fine now. There is no blank page and no error message.
