### ISSUE TITLE
Checkbox 'Active/Inactive' is broken

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#897]
Checkbox 'Active/Inactive' is broken. I cannot click the checkbox.
![checkbox gif](https://user-images.githubusercontent.com/61964176/78022638-95bfa280-7355-11ea-9a2f-b920d89c3f77.gif)

Steps:

1. Log in to the app as Admin
2. Go to random Organization
3. Try to click 'Active' checkbox

Actual result: Checkbox is broken 
Expected result: It should be a chance to check the checkbox.

**Comment by abaranowska1** [comment]
@johnhbenetech 
Checkbox 'Active/Inactive' is still broken.

**Comment by johnhbenetech** [comment]
@abaranowska1 this is more of a design error than a bug. It is meant to be a visual indicator of if the partner's data says that the record is active/inactive (not a user input).

I'm gonna close this and we can revisit if we update the old views
