### ISSUE TITLE
An unexpected error has occurred after going to Sessions page

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#898]
An unexpected error has occurred after going to the Sessions page

![Screenshot from 2020-04-01 09-12-35](https://user-images.githubusercontent.com/61964176/78110603-88f58a00-73fb-11ea-98e5-33a943ea797c.png)

Actual result: An unexpected error has occurred
![image](https://user-images.githubusercontent.com/61964176/78110716-c5c18100-73fb-11ea-8fad-ebd0892ef787.png)

**Comment by awalkowiak** [comment]
This view is no longer supproted after authorization changes. I'll remove it. cc @jkondrat

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on Staging environment.

**Verified cases**
- Checking users dropdowns for Sessions
-- admin
-- regular user
-- sacramento user

**Summary**
Sessions are not available for all of the users. 

**Attachments**
- Admin view
![898 1](https://user-images.githubusercontent.com/51324797/78869878-8d4a2480-7a45-11ea-9051-aafac65e96d2.png)

- Regular user view
![898 2](https://user-images.githubusercontent.com/51324797/78869897-92a76f00-7a45-11ea-9583-e93a053d3a05.png)

- Sacramento user
![898 3](https://user-images.githubusercontent.com/51324797/78869931-9a671380-7a45-11ea-8799-fddaa4b0160f.png)
