### ISSUE TITLE
Introduce a Bootstrap theme

### ISSUE THREAD

**Issue by pgesek** [benetech/ServiceNet#9]
Select an existing, free Bootstrap theme and introduce it to the site in order to change the default bland JHipster look.

**Comment by pgesek** [comment]
@oskarhinc  can you replace the orange on the home/login page with something more neutral?

**Comment by oskarhinc** [comment]
Sure, how about blue?
![screenshot from 2018-11-13 07-54-34](https://user-images.githubusercontent.com/19305104/48396049-7650b700-e719-11e8-89bc-6f4b909acbf2.png)

**Comment by pgesek** [comment]
I think it looks fine for now

**Comment by pgesek** [comment]
Moving to done
