### ISSUE TITLE
Locations are not rotated when matched

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#901]
After re-architecture an issue with Locations not rotating to each others when matched came back.

**Reproduction**
- Go to Organization (it should have match with matched Location, for example: CALIFORNIA STATE DEPARTMENT OF SOCIAL SERVICES, COMMUNITY CARE LICENSING DIVISION (CCLD))
- Expand Locations section
- Check checkbox with chain icon

**Expected results**
- Matched Locations should rotate to each other

**Actual results**
- Locations are not rotated

**Attachments**
![locations match not working](https://user-images.githubusercontent.com/51324797/78134956-4cd52000-7421-11ea-8c52-9e8f73042caa.gif)

**Linked issues**
- #698 
- #780

**Comment by bognasoldev89** [comment]
Verified on Staging env

**Verified cases**
- Choosing matched and not matched Locations with checkbox chosen

**Summary**
I checked it on a few Organizations with Location matches and, in general, it works as expected:
- while checkbox is unchecked it doesn't rotate
- while checkbox is checked - it does
I found Location match that is not rotated exactly as it is expected from user's perspective. While there's Location with exact the same address, it's rotated to different Location.

@kdondziak can you please look into this case?

**Attachments**
- Proper behavior
![901 fine](https://user-images.githubusercontent.com/51324797/78879654-78c15880-7a54-11ea-8fb3-100b825d281b.gif)

- Improper behavior
![901 not well](https://user-images.githubusercontent.com/51324797/78879676-824ac080-7a54-11ea-967b-3e56d9f965a9.gif)

**Comment by kdondziak** [comment]
@johnhbenetech  @NeilMBenetech Bogna is suggesting that if there are more than 1 location that matches then dropdown should rotate to location with higher similarity. Now it's undefined which should chose. Correct me if I am wrong.  
cc @bognasoldev89

**Comment by johnhbenetech** [comment]
@kdondziak that sounds like the right approach

**Comment by kdondziak** [comment]
@johnhbenetech I've noticed that on all-record-view rotating mechanism works only for left side organization and first on the right organization and not for the rest. Should it work for all the other organizations?

**Comment by bognasoldev89** [comment]
@kdondziak I still have doubts about Locations rotating in the example mentioned by me earlier. Can you please review it again?

Example: https://benetechservicenet.org/#/multi-record-view/dd1b118d-610f-4265-b0fa-1908c0782d13/45a27296-95e8-466a-be01-ce4ff0e8b880
Episcopal Community Services (healthleads) matched with EPISCOPAL COMMUNITY SERVICES OF SAN FRANCISCO (UWBA)

**Comment by kdondziak** [comment]
@bognasoldev89  I investigated the your doubts. For some reason algorithm counting location similarity gives to both locations 100% similarity. Please see this example:
https://benetechservicenet.org/#/multi-record-view/4902236d-6ccd-4ef7-84c9-f364cc979a4e/0618f647-8ecb-4689-9d35-6f690c062bb3
Matrix measuring similarity for "536 Central Avenue San Francisco"
location name -> similarity
536 Central Avenue - San Francisco (CA) -> 1
6324 Geary Boulevard - San Francisco (CA) -> 0
134 Golden Gate Avenue - San Francisco (CA) -> 0
869 Ellis Street - San Francisco (CA) -> 0
1317 Height Street - San Francisco (CA) -> 0.8

**Comment by kkaczmarczyk** [comment]
@kdondziak thanks for the investigation. That look strange - could you try to debug it?

**Comment by kdondziak** [comment]
@kkaczmarczyk I investigated it and I know why Bogna is confused. Algorithm counting location similarity looks for geocoding results which are not visible to the user. Latitude/longitude visible on compare page are only used when geocoding results are broken/missing. In case Bogna is reporting geocoding result that seems to be not similar at all the distance between them is 58 meters which gives 100% similarity ratio.

**Comment by kdondziak** [comment]
@johnhbenetech With team we were discussing that counting similarity using geocoding results that are not visible to the user may be confusing. Can you consider adding task that shows/informs user about which geocoding was used to determine match's similarity? Jakub suggested hidden section with the geocoding.

**Comment by bognasoldev89** [comment]
**Verified with success**

Verified on staging env

**Verified cases**
- Choosing matched and not matched Locations with checkbox is chosen

**Summary***
I checked it on a few Organizations with Location matches and, in general, it works as expected:
- while checkbox is unchecked it doesn't rotate
- while checkbox is checked - it does

Confusing edge cases will be left for later consideration - how to indicate them for regular users.
