### ISSUE TITLE
Bring back "View previously removed records" option

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#906]
Bring back "View previously removed records" option 
![70247870-623f8380-177a-11ea-8ec9-dff5dda8fce4](https://user-images.githubusercontent.com/61964176/78245183-50cb7580-74e7-11ea-94fb-166661b53f00.gif)

Now, this option is disabled and the user cannot reinstate match when all records are dismissed.
![Peek 2020-04-02 13-37](https://user-images.githubusercontent.com/61964176/78245255-76587f00-74e7-11ea-8983-3794b790108e.gif)

**Acceptance criteria:** 
- "View previously removed records" option is restored

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on Staging env

**Verified cases**
- Dismissing records from all records view
-- one by one
-- all of them
- Dismissing records from multi records view
-- one by one
-- all of them

**Summary**
View previously removed records is displayed where it should be.

**Attachment**
- Exemplary views
![906 working](https://user-images.githubusercontent.com/51324797/78872575-c7b5c080-7a49-11ea-8d93-7abceba7a916.gif)
