### ISSUE TITLE
Spike: Investigate the feasibility of automated unity/integration testing to cover some of the regressions

### ISSUE THREAD

**Issue by kkaczmarczyk** [benetech/ServiceNet#921]
After recent microservice re-architecture effort there were several regressions popping up. There was a discussion in which we concluded that some of these issues may be covered with automated tests. This way we will be able to catch such regressions on the CI build level.

- Look at the recent regression tests report.
- Try to group the issues 
- Investigate which groups/issues can be covered with either unit or integration tests

Acceptance Criteria:
* A report of which issues can be covered with which type of tests
* Include the complexity/effort factor for the implementation of tests

**Comment by awalkowiak** [comment]
@kkaczmarczyk @jkondrat @johnhbenetech 
I shared result spreadsheet on the slack channel. In my opinion if we want to cover test cases from regressions (to take some load off of @abaranowska1 and @bognasoldev89), then the most suiting approach would be the use of end to end testing. Recently I added protractor (selenium based framework, made for angular, but usable with react without any issues) to the gateway service. The majority of test cases that could be done as end-to-end. Couple of tests could be done as frontend snapshot tests on frontend side and couple as unit and/or integration tests on the backend side.

For the end-to-end testing these are potential obstacles:
- in some test cases the usage of reference database with initial users and records could be very helpful,
- choosing options on select fields (https://stackoverflow.com/a/20308276 or just simple value setting could be enough),
- choosing dates in datepickers (https://stackoverflow.com/a/35946919 or just simple value setting could be enough),
- hoverovers (https://stackoverflow.com/a/28301469),

Usage of other browsers than chrome is just a config change:
- firefox (https://www.protractortest.org/#/browser-setup#adding-firefox-specific-options),
- there should be support for edge (https://github.com/angular/protractor/issues/3016),
- responsive view (`--window-size=800,600` browser config option),
- there is also option to use multiple browsers in the same test (https://www.protractortest.org/#/browser-setup#using-multiple-browsers-in-the-same-test)

**Comment by kkaczmarczyk** [comment]
LGTM, let's move the doc to the general QA folder @awalkowiak 

@jkondrat any thoughts about it?

**Comment by jkondrat** [comment]
@kkaczmarczyk Nothing to add, looks good
