### ISSUE TITLE
Push docker images to dockerhub

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#932]
So just a note that I set up the following:
https://hub.docker.com/r/johnhbenetech/servicenet
https://hub.docker.com/r/johnhbenetech/servicenetauth
https://hub.docker.com/r/johnhbenetech/servicenetgateway

I tied each of them to commits to dev branch. I tried to put the dockerfile location as 'ServiceNet/src/main/docker/app.yml' but i guess it doesnt do the yml formatted configs and actually wants the standard DockerFile. Let me know if you all have a chance to poke around and let me know if you figure out the right approach for which file to point docker hub at

**Comment by kkaczmarczyk** [comment]
I have added Github Action for all 3 services. It builds, tags and pushes the Docker images to Docker Hub. It was tested and it works, so let me close this ticket.
