### ISSUE TITLE
Security: PreAuthorize is not checking authorities

### ISSUE THREAD

**Issue by kdondziak** [benetech/ServiceNet#936]
PreAuthorize is not checking authorities so all users have access to resources that should be limited.
Reproduction steps: 
1. Login as user with Sacramento authority.
2. Open browser console -> network tab
3. Copy cookie and XSRF-TOKEN
4. Make valid request to resource available to admin in postman e.g. (POST: https://localhost:8080/services/servicenet/api/services) 
Body: {
"name": "ServiceName1233"
}
![image](https://user-images.githubusercontent.com/52406204/79557467-e6980080-80a2-11ea-99d5-4a8e78e4059a.png)

Expected result: Unauthorized
Actual result: Request passed.

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:** 
- It has been checked if the sacramento user can send a valid request to a resource only accessible to the admin
![Selection_149](https://user-images.githubusercontent.com/61964176/79738213-c19eca00-82fc-11ea-9857-c6dbc7055016.png)
![Selection_148](https://user-images.githubusercontent.com/61964176/79738218-c2cff700-82fc-11ea-8591-bc504ff6c494.png)
- It has been checked if the sacramento user can send a valid request to a resource accessible to the sacramento
![Selection_147](https://user-images.githubusercontent.com/61964176/79738221-c3688d80-82fc-11ea-838d-d4baff8f121b.png)
