### ISSUE TITLE
When e-mail lacks @ sign Organization is not compared

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#938]
I noticed, that conflict is not detected for the Organizations that lack @ sign in e-mail field.

**Reproduction**
- Upload data with string without @ sign in the e-mail field
- Organization should have match

**Expected result**
- Fields should be compared for matches and conflicts

**Actual result**
- Fields are not compared for matches and conflicts

**Comment by abaranowska1** [comment]
**Tested with success**

- Fields are compared for matches and conflicts after upload data with string without @ sign in the e-mail field

- Fields are compared for matches and conflicts after upload data with @ sign in the e-mail field

![image](https://user-images.githubusercontent.com/61964176/80212218-62f88980-8637-11ea-96f0-f044ae701b34.png)
![image](https://user-images.githubusercontent.com/61964176/80212237-6a1f9780-8637-11ea-96fc-fc0b56810013.png)
![image](https://user-images.githubusercontent.com/61964176/80212273-773c8680-8637-11ea-9cd3-698c0b2daffb.png)
