### ISSUE TITLE
Map pin based filtering doesn't appear to work anymore

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#942]
Steps:

Log in as UWBA

Expand Filter and go to location tab

Put map pin in Africa set distance to 1 mile

Go back to filter tab and hit apply

Result:
Number of results remains unchanged

**Comment by kdondziak** [comment]
@johnhbenetech Have you checked this checkbox?
![image](https://user-images.githubusercontent.com/52406204/79970910-ec6f5680-8493-11ea-8ec8-4992ac125fd7.png)

**Comment by johnhbenetech** [comment]
Ah yes, that's the problem. I'll close this for now and think about how we might improve the UX there
