### ISSUE TITLE
Create new landing page for Service Providers

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#943]
This is the first task to create the skeleton structure for the new landing page. I'm not sure on the route naming right now, so we can put it at /serviceprovider for now.

I will attempt to break things out into sub-tasks, but feel free to split/combine as you see fit.

The total design will look like:
![fullhome](https://user-images.githubusercontent.com/12927553/79926322-390a5180-8402-11ea-92c2-b1c1a04a6eee.jpg)

This task will be for the skeleton structure focusing on the navbar and hero header
![image](https://user-images.githubusercontent.com/12927553/79926368-5b9c6a80-8402-11ea-8ad3-02fb2bacb2ff.png)

We can exclude the search bar and notification bell from this task.

For avatar, we can use the first letter of their username in a colored circle using something like:
https://material-ui.com/components/avatars/

The header background will be shared elsewhere

**Comment by johnhbenetech** [comment]
Font is Open Sans

**Comment by johnhbenetech** [comment]
@kdondziak Sorry, I'm gonna change my previous comment. 

Font should be Muli:
https://fonts.google.com/specimen/Muli

**Comment by kdondziak** [comment]
@johnhbenetech Can you give advice/mock-up how mobile header bar would look like? And also what should be visible on menu if menu is necessary?

**Comment by johnhbenetech** [comment]
What do you all think of this?

![image](https://user-images.githubusercontent.com/12927553/80635847-17245680-8a22-11ea-80ae-7d3282cd783f.png)


![image](https://user-images.githubusercontent.com/12927553/80636060-708c8580-8a22-11ea-8cdb-d21a938e5b87.png)

The other option:

![image](https://user-images.githubusercontent.com/12927553/80636739-88183e00-8a23-11ea-9255-f6d729663433.png)

We could then use the three dot for like sort/filtering stuff - basically the main screen on mobile would only be cards

**Comment by kdondziak** [comment]
It looks good to me

**Comment by abaranowska1** [comment]
@kdondziak minor issues: 
WEB : 
1. When I set zoom browser for example for 90% or less, something weird happens with the carousel. 
![homepage](https://user-images.githubusercontent.com/61964176/81548391-83d21600-937d-11ea-91db-d7af706ec427.gif)

- Card: "Have more data to contribute?" is not in the center, and the middle card is also not centered 
![image](https://user-images.githubusercontent.com/61964176/81549511-276ff600-937f-11ea-9b6e-6f39295fa7bb.png)

![image](https://user-images.githubusercontent.com/61964176/81549693-7584f980-937f-11ea-98fa-d192301ff1de.png)

- The cards are out of the page 
![Screenshot from 2020-05-11 12-01-55](https://user-images.githubusercontent.com/61964176/81549593-42426a80-937f-11ea-9946-90379afed7c9.png)

- The background is not width enough 
a) zoom 90% ![image](https://user-images.githubusercontent.com/61964176/81549644-5c7c4880-937f-11ea-8db0-64476691dbe1.png)

b) zoom 100% 
![image](https://user-images.githubusercontent.com/61964176/81549775-91889b00-937f-11ea-9073-22f8a1d88a16.png)

2. Blue border in the searcher, could we change it? 
![image](https://user-images.githubusercontent.com/61964176/81549870-b8df6800-937f-11ea-84dc-4fd51646d20d.png)

3. Avatar - When a user doesn't have a photo this first letter is not the same size, in my opinion, "P" in the right corner is too big 
![image](https://user-images.githubusercontent.com/61964176/81550256-4458f900-9380-11ea-8ed2-135b8d87e723.png)

MOBILE:

1. Plz add Sign Out option 
![image](https://user-images.githubusercontent.com/61964176/81550379-65b9e500-9380-11ea-95ab-e2338712f5e0.png)

2. Avatar - could you check if the avatar in the right corner is a circle or ellipse? It looks a little different 
![image](https://user-images.githubusercontent.com/61964176/81550488-98fc7400-9380-11ea-938a-c7e9998d51e9.png)

3. Hamburger button, @johnhbenetech @kdondziak maybe we should use the same hamburger button as on our normal homepage, in my opinion, it looks better 
![image](https://user-images.githubusercontent.com/61964176/81550704-eb3d9500-9380-11ea-8b5d-f6f5eadd7eca.png)

**Comment by kdondziak** [comment]
@abaranowska1 I fixed bugs you have found.

**Comment by abaranowska1** [comment]
**Tested with success**

Verified on

- Chrome (v.81.0.4044.92) 
- Mozilla Firefox (v 75.0) Browsers 
- Mobile Device iPhone X ( 1125x2436) and emulator 360x640

Following by issues from the previous comment now: 

- The background and the carousel looks fine on 100%,90%,110%, and all zoom browser, 
- Blue border in the searcher disappeared
- Avatar view was fixed
- Sign Out option was added to mobile 
- Avatar is a circle not an ellipse 
- The page looks better on the horizontal view

![image](https://user-images.githubusercontent.com/61964176/81811035-48be1700-9524-11ea-8e75-de03351dc783.png)
![image](https://user-images.githubusercontent.com/61964176/81811073-583d6000-9524-11ea-89dc-8ee1dd823719.png)
