### ISSUE TITLE
Implement card design for record view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#944]
Our central object representing an Organization Entity. This task is to begin to create the skeleton of the object on the home page. Full design:
![image](https://user-images.githubusercontent.com/12927553/79926664-17f63080-8403-11ea-9536-8148235f1b40.png)

Details are as follows:
![image](https://user-images.githubusercontent.com/12927553/79927022-16793800-8404-11ea-86e8-4ec35c1e22d6.png)

Note the taxonomy icon will be handled in a separate task

**Comment by jkondrat** [comment]
The card will be added to the new homepage in a separate ticket

**Comment by kdondziak** [comment]
Ticket mentioned above: https://github.com/benetech/ServiceNet/issues/958

**Comment by awalkowiak** [comment]
Since it was non-QA and is in done for 22 days, I'm closing this one.
