### ISSUE TITLE
Display all  records from Service Providers

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#945]
As part of full design: 
![fullhome](https://user-images.githubusercontent.com/12927553/79927299-f0a06300-8404-11ea-890a-cfc6e5af1f9d.jpg)

This task will cover the bottom "all records" section

It will have a record count similar to the classic design.

Card design will be responsive with max three columns, and min width of 1 card with padding.

Sorting/Filtering/row view will be broken out in separate tasks

![image](https://user-images.githubusercontent.com/12927553/79927410-4b39bf00-8405-11ea-92cf-0fb8100deee6.png)

**Comment by awalkowiak** [comment]
@johnhbenetech you want to have here the "Load more" button or the infinite loader like on current home page?

**Comment by johnhbenetech** [comment]
@awalkowiak Let's go with 'Load More'

**Comment by kdondziak** [comment]
@johnhbenetech Should be on the same page as 'user orgs' (mobile)? Or should it be on separate page?

**Comment by johnhbenetech** [comment]
@kdondziak Same page

**Comment by kdondziak** [comment]
@johnhbenetech It should be carousel too? Or scrollable list?

**Comment by johnhbenetech** [comment]
@kdondziak scrollable list with load more

**Comment by kdondziak** [comment]
@johnhbenetech Should all records contain 'users records'?

**Comment by johnhbenetech** [comment]
@kdondziak it's not a house difference either way. My initial thought is no they shouldn't since they will already be showing above, but let me know if that's technically difficult

**Comment by johnhbenetech** [comment]
@kdondziak Sorry this is my fault in the original spec. Can we limit the records displayed to only the 'Service Provider' records. Hopefully this makes sense.

Basically we should ONLY show those records that were created in the new flow and NOT the records from the previous partners (UWBA,Eden, LAAC, healthleads, sheltertech).

I think in the future we may open it up, but we'll start with the limited records

**Comment by bognasoldev89** [comment]
@kdondziak I took a quick look at this and I have one remark:
can you please make the cursor consistent while hovering over clickable elements?

![Peek 2020-05-15 12-12](https://user-images.githubusercontent.com/51324797/82039751-c3fb0680-96a5-11ea-9f6d-e58bb6ca5ba1.gif)

@johnhbenetech at this moment 6 cards appear after clicking "Load more" button. It seems fine to me but maybe you have some thought on this?

**Comment by johnhbenetech** [comment]
6 at a time is good for me

**Comment by bognasoldev89** [comment]
@kdondziak I looked at this feature and I think one improvement would be great:

after reaching the end of records by "load more" button, it would be good to deactivate it.

![945 load more button](https://user-images.githubusercontent.com/51324797/82066295-7dba9d00-96cf-11ea-8c6a-6643d644b5f1.gif)

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on staging  env.

**Verified cases**
- Logging in as a provider users
- Checking if other organizations are from other providers accounts
- Loading more records on the homepage

**Summary**
This feature works correctly
- available records come from the other provider users
- cards load properly
- progress bar reacts properly
- "Load more" button deactivates while reaching the end of records

**Attachment**
![sn 945 working](https://user-images.githubusercontent.com/51324797/82202614-75967380-9902-11ea-8009-c387e2575460.gif)
