### ISSUE TITLE
Add sorting to all record section

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#946]
On the all record view, add preliminary sorting control
![image](https://user-images.githubusercontent.com/12927553/79927436-5f7dbc00-8405-11ea-97b9-6670274a9412.png)

Options should be recently updated, and alphabetical. Recently updated is default sort

**Comment by kdondziak** [comment]
@johnhbenetech How should it look when sort is clicked. I suggest to add expand section on desktop and modal on mobile.

**Comment by johnhbenetech** [comment]
@kdondziak that works for me

**Comment by abaranowska1** [comment]
**Tested with success**
**Verified cases:** 

- Sorting works without any problems on web and mobile devices.
- It is possible to sort data ascending and descending
- Options are recently updated, and alphabetical 
- Recently updated is the default sort
![Peek 2020-05-18 16-05](https://user-images.githubusercontent.com/61964176/82223303-c5853280-9922-11ea-8d09-9399d41ec855.gif)
![Peek 2020-05-18 16-03](https://user-images.githubusercontent.com/61964176/82223312-c74ef600-9922-11ea-9cab-dce676675e80.gif)
