### ISSUE TITLE
Add Sentry.io configuration for live error notifications

### ISSUE THREAD

**Issue by kkaczmarczyk** [benetech/ServiceNet#947]
Consider adding a free monitoring&alert tool such as Sentry.io. It would send an alert with a stack trace whenever unexpected error happens. It also enables live browsing through the issues, and see trenda about these.

Acceptance Criterias:
- Sentry.io configuration is added and it sends alerts whenever unexpected errors occur on staging/prod

**Comment by johnhbenetech** [comment]
Would we do this for both react and Java?

Maybe you can test on an independent account and when ready i can provide the appropriate key (this should probably be an env var)

**Comment by kkaczmarczyk** [comment]
Ideally we do it both for the React and Java.
