### ISSUE TITLE
Add avatar image to UserProfile

### ISSUE THREAD

**Issue by awalkowiak** [benetech/ServiceNet#950]
On user profile page should be option to choose avatar image (consider redesign of the profile page).

- img field in UserProfile entity
- img selector
- it should be square size (find 'cutting image' library)
- if avatar image is added it should be displayed in avatar placeholder added in #943

**Comment by abaranowska1** [comment]
@jkondrat If you can please change these buttons to the pills buttons 
![image](https://user-images.githubusercontent.com/61964176/101616544-c640fb80-3a0f-11eb-9faf-313c4ac13386.png)

**Comment by jkondrat** [comment]
@abaranowska1 I'm going to break this into a separate task since the page is reused on classic view #1460
