### ISSUE TITLE
Create data entry Page for new record creation

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#954]
When a user clicks the 'add a record' option, they will enter into a workflow to collect a reduced set of fields from our full data standard. It will walk them through first adding org details, then locations, then service information.

One new thing is the ability to attach services to locations. We can discuss this in more detail, but refer to: https://openreferral.readthedocs.io/en/latest/hsds/reference/#service_at_location

The entered data will be saved to a new record with the logged in user set as owner.

![image](https://user-images.githubusercontent.com/12927553/80433425-82541880-88bc-11ea-9359-f3b86465b2a1.png)

![image](https://user-images.githubusercontent.com/12927553/80433444-8e3fda80-88bc-11ea-960a-693b150cf29c.png)

![image](https://user-images.githubusercontent.com/12927553/80433461-9b5cc980-88bc-11ea-8948-9e51a306d2df.png)

**Comment by kkaczmarczyk** [comment]
@johnhbenetech are there any mockups/guidelines/suggestions about how this screen may look on the mobile screens/resolutions? Or should it be more-or-less similar?

**Comment by johnhbenetech** [comment]
1. I'll work on that now. It should be largely the same - the only thing im considering is if the go back/add/finished options would move to a static bottom nav bar. I'm trying to go for a vaguely material design approach.

2. It would be fed from the 'taxonomy' entities. All "Service Provider" records will have the same taxonomy options. I'll provide the list shortly, but it will be ~20 options and would be 1 to many.

3. Yes. This is what I'm currently thinking. It would be a multiselect dropdown listing like: "Address 1, City" for each location entered on previous step.

**Comment by johnhbenetech** [comment]
![image](https://user-images.githubusercontent.com/12927553/80535090-dcf57f00-8965-11ea-949d-618834a98aa3.png)

**Comment by jkondrat** [comment]
Hi @johnhbenetech, I have a few questions regarding the inputs:
1. Where should we pull the service types from?
2. What should we put in the 'CA' select?
2. Which location field should be used as a label in the 'Where Is This Service Offered' select?
4. Once another location or service is added, should it be possible to remove it?

**Comment by johnhbenetech** [comment]
1. We should make a new taxonomy set for the "Service Provider" system account. For now it can copy the ShelterTech values. This should be a mutiselect that hopefully has the type to filter interaction we currently have on our taxonomy filter.

2. This should be the 50 US state abbreviations. These are the USPS column here: https://en.wikipedia.org/wiki/List_of_U.S._state_abbreviations but dont include the blue highlighted rows for the territories. It should always be prepopulated to CA for california since that's where we expect 99% of the resources to be located.

3. lets do concatenated "Address 1, Address 2, City"

4. That's a good point. I can work on a mockup, but we can put a grey  remove button at the same level as the add button. remove left aligned, add right aligned.

For the 1st record, hitting that button will just clear all values but still display the blank form. For any latter record it will remove that record but keep the remaining records in place

**Comment by bognasoldev89** [comment]
Verified on staging env

**Verified cases**
- Creating new Organizations via provider
-- on browser
-- on mobile emulators

1. I was able to create a new Organization with needed information

2. Validation is correct
![954 2](https://user-images.githubusercontent.com/51324797/81549756-87669c80-937f-11ea-88db-42d3b91ace15.gif)

3. "Remove" button removes the last entry on Locations and Services pages. Should user have a possibility to choose which entry is to remove? @johnhbenetech what do you think?
![954 1](https://user-images.githubusercontent.com/51324797/81549716-7c137100-937f-11ea-9902-1f280e668dff.png)

4. I created 2 Locations, added the second one to created Service, went back, removed chosen Location. Should this be removed?
![954 4](https://user-images.githubusercontent.com/51324797/81550661-deb93c80-9380-11ea-9748-264387d84bda.png)

5. I tried to save the Organization from point 4 and got "Internal server error". I removed this empty element and tried to save the Organization and got "Bad request". I had to add existing Location to save the Organization, but this field is not validated.
![954 5](https://user-images.githubusercontent.com/51324797/81551133-9f3f2000-9381-11ea-970d-af9ec5b73ec5.gif)

6. Locations are counted from 1 on Locations page and from 0 on Services page.

7. Mobile UI issues:
7.1. Fields are not even placed:
![954 6](https://user-images.githubusercontent.com/51324797/81551802-bf231380-9382-11ea-84fd-d3b59f9ae7a0.png)
![954 7](https://user-images.githubusercontent.com/51324797/81551829-c6e2b800-9382-11ea-9a88-f223686b06a4.png)

7.2. "Add another" button is not even placed:
![954 7](https://user-images.githubusercontent.com/51324797/81552210-643dec00-9383-11ea-8dea-000850416bb6.png)
![954 8](https://user-images.githubusercontent.com/51324797/81552211-64d68280-9383-11ea-9da5-346e28e0a527.png)

**Comment by bognasoldev89** [comment]
I rechecked this issue and all of the raised issues are fixed but one:

> Locations are counted from 1 on Locations page and from 0 on Services page.

![locations counting](https://user-images.githubusercontent.com/51324797/81936058-e3d0f280-95f1-11ea-970e-5ff047350be2.png)

@jkondrat can you look into that?

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on staging env
Used resolutions:
- 1920 x 1080
- 360 x 640

**Verified cases**
- Creating new Organizations via provider
-- on browser
-- on mobile emulators

**Summary**
All of the issues are resolved, this feature works correctly and elements look as expected.

**Attachment**
Fixed Locations count on Services page:
![locations counting 2](https://user-images.githubusercontent.com/51324797/82449077-f42e1500-9aaa-11ea-9d71-59e8b6499ea5.png)
