### ISSUE TITLE
Integrate Card with carousel

### ISSUE THREAD

**Issue by kdondziak** [benetech/ServiceNet#958]
Integrate Card from this issue: https://github.com/benetech/ServiceNet/issues/944, and carousel from this: https://github.com/benetech/ServiceNet/issues/943
Consider adding separate endpoint and mapper method for this

**Comment by abaranowska1** [comment]
**Tested with success**

Verified on staging env

**Verified cases**

Cards are integrated with the carousel
![image](https://user-images.githubusercontent.com/61964176/81556778-2e9d0100-938b-11ea-935c-b359caea2bdc.png)
