### ISSUE TITLE
Single record view page

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#959]
The following views represent the page after a user clicks on a single record. The mobile version should be pretty straightforward from this design but let me know if there are questions.

Note: For the services section, you are first brought to the card view, clicking an individual card opens the detail view which gives you previous, next service option as well as an 'X' which brings you back to the services card view

**Comment by johnhbenetech** [comment]
Single Record initial View:
![covidsingleorg](https://user-images.githubusercontent.com/12927553/80655994-b1e25c80-8a45-11ea-8a46-4429188b2df7.jpg)

Single record location expanded:
![covidsingleloc](https://user-images.githubusercontent.com/12927553/80656001-b6a71080-8a45-11ea-85f1-fbf03565261b.jpg)

Single record All Services expanded:
![covidsinglesrvs](https://user-images.githubusercontent.com/12927553/80656036-cd4d6780-8a45-11ea-850f-e6d8f9cbd922.jpg)

Single Record Service Drill down:
![expandovidsinglesrvs](https://user-images.githubusercontent.com/12927553/80656052-d76f6600-8a45-11ea-9782-15dfbb3dd313.jpg)

**Comment by awalkowiak** [comment]
@abaranowska1 @bognasoldev89 
You can start the QA on that one, but there are couple of things that are missing:
1. Currently, there's missing specific Service Detail (the part with arrow navigation).
2. When there're a bigger amount of services or location, then all are displayed => no collapsing with "+ remaining elements count" or "load more".

**Comment by abaranowska1** [comment]
@awalkowiak Plz look at these points :

1. Services without Name and Type could be displayed for example as "No service name provided" and 'Untyped"
![image](https://user-images.githubusercontent.com/61964176/82058149-a38e7480-96c4-11ea-9ba5-8c002fdbf7fc.png)
2. Plz add some space at the bottom of the page, under Services table 
![image](https://user-images.githubusercontent.com/61964176/82058645-4fd05b00-96c5-11ea-86c6-ac97f6a5b838.png)
3. We can bold these main sections of the Organization 
![image](https://user-images.githubusercontent.com/61964176/82059054-d422de00-96c5-11ea-9128-f3446ba7162a.png)
4. Mobile device: In my opinion, cards should have smaller padding and bigger font 
![image](https://user-images.githubusercontent.com/61964176/82059292-1d732d80-96c6-11ea-8bc6-a3521385bc7f.png)
5. As @jkondrat we could add an Edit button which will move to the edit page

**Comment by abaranowska1** [comment]
@awalkowiak Everything works fine, but if you can plz change the font for a little smaller. It will be great if it is the same as in Jakub's edit view
![image](https://user-images.githubusercontent.com/61964176/82212772-64099780-9913-11ea-82bc-ec1d98b3fdd8.png)
![image](https://user-images.githubusercontent.com/61964176/82212784-68ce4b80-9913-11ea-804b-36ab1f4a2de1.png)

**Comment by abaranowska1** [comment]
Now it looks good :+1: 
![image](https://user-images.githubusercontent.com/61964176/82221264-0e87b780-9920-11ea-94f5-ad23291e786c.png)
![image](https://user-images.githubusercontent.com/61964176/82221274-12b3d500-9920-11ea-99f0-ce360710139a.png)

**Comment by awalkowiak** [comment]
@abaranowska1 thanks, let's not close it yet because I am still working on the service details. I'll let you know once it can be tested.

**Comment by awalkowiak** [comment]
@abaranowska1 I added Service Details after clicking on specific service and I added Autosizer on header card (the most top one) for service pills and locations.

**Comment by abaranowska1** [comment]
**Tested with success**

Verified on:

- Chrome Browser v.81.0.4044.92
- Firefox Browser v.75.0
- Mobile Device 360x640 and iPhone X 

Verified cases:

- Single Record initial View:
![image](https://user-images.githubusercontent.com/61964176/82336952-7bb44f00-99eb-11ea-91ba-93a06f9d90d9.png)

- Single record location expanded:
![image](https://user-images.githubusercontent.com/61964176/82336993-8969d480-99eb-11ea-89e3-1c3f8c6702e9.png)

- Single record All Services expanded:
![image](https://user-images.githubusercontent.com/61964176/82337529-29276280-99ec-11ea-94ec-054177f713c3.png)

- Single Record Service Drill down:
![image](https://user-images.githubusercontent.com/61964176/82337593-3e9c8c80-99ec-11ea-8e6e-06fb2a74faaf.png)

- Single Record Mobile View:
![Peek 2020-05-19 16-18](https://user-images.githubusercontent.com/61964176/82337806-73a8df00-99ec-11ea-9c76-3ab596824a25.gif)
