### ISSUE TITLE
Allow owner to edit their record

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#961]
When a user clicks one of their owned records on the main page they will be brought to a page to edit the existing data in the record.

Org Detail Edits
![baseorgedit](https://user-images.githubusercontent.com/12927553/81006522-4ae1f080-8e15-11ea-85c9-9f021bcfd322.jpg)

All Locations
![covideditlocations](https://user-images.githubusercontent.com/12927553/81006563-5c2afd00-8e15-11ea-832a-105b3892de87.jpg)

Single Location
![covideditsingle location](https://user-images.githubusercontent.com/12927553/81006580-60efb100-8e15-11ea-8a11-364b52ce4f01.jpg)

All Services
![covideditservices](https://user-images.githubusercontent.com/12927553/81006602-66e59200-8e15-11ea-9426-74d2f73cec94.jpg)

Single Service
![covideditsingleservice](https://user-images.githubusercontent.com/12927553/81006615-6baa4600-8e15-11ea-8783-5855d61b4b9e.jpg)

**Comment by awalkowiak** [comment]
Backend and Frontend will be handled in separate PRs (or at least commits).

**Comment by jkondrat** [comment]
@johnhbenetech : How should the daily update field work? Would it create a new entity every time or or update existing one? Should it show the previously entered value? How about expiry date?

**Comment by johnhbenetech** [comment]
@jkondrat initially it should be populated with the existing value and display the date it was last updated. 

If the user changes or updates it, when they hit save:

1. Create a new daily update with the new value and a created date of the current datetime

2. Set the expiry of the old value to the current datetime

In this manner, anywhere daily update is displayed should show the most recent non-expired daily update (if one exists)

**Comment by abaranowska1** [comment]
@jkondrat 
During testing I found a few issues: 

1. I added a new record using "Add a new record" button from Service Provider Homepage and then I go to this Organization. When I want to add some changes and save or deactivate this record, error message: "You are not allowed to edit this shelter" was thrown.

![Peek 2020-05-19 10-30](https://user-images.githubusercontent.com/61964176/82304474-ae931e80-99bc-11ea-8fee-30eb2e674716.gif)

![image](https://user-images.githubusercontent.com/61964176/82304143-36c4f400-99bc-11ea-9297-e5197be9a4a6.png)

2. When we have more types of services we should use "+2, +5" option as in the rest of Service Provider View 
![image](https://user-images.githubusercontent.com/61964176/82304537-c4a0df00-99bc-11ea-93aa-82c8ec20a55e.png)

3. In my opinion, it would be better to start from 1. not 0. 
![image](https://user-images.githubusercontent.com/61964176/82304766-0c276b00-99bd-11ea-9322-d205134b6dee.png)

4. Once during the deactivating process, I met "An unexpected error has occurred", but I cannot reproduce it, so I will let you know if I will meet it again

**Comment by abaranowska1** [comment]
**Tested with success**

Verified on:

- Chrome Browser v.81.0.4044.92
- Firefox Browser v.75.0
- Mobile Device 360x640 and iPhone X

Verified cases:

- All four issues from the previous comment were fixed
- When a user clicks one of their owned records on the main page they will be brought to a page to edit the existing data in the record
- Org Detail Edits:
![image](https://user-images.githubusercontent.com/61964176/82340977-229aea00-99f0-11ea-9314-89b37706d409.png)
- All Locations:
![image](https://user-images.githubusercontent.com/61964176/82341038-347c8d00-99f0-11ea-9a66-5df9cf50476a.png)
- Single Location:
![image](https://user-images.githubusercontent.com/61964176/82341068-42caa900-99f0-11ea-833e-d9ba037c1a91.png)
- All Services:
![image](https://user-images.githubusercontent.com/61964176/82341137-54ac4c00-99f0-11ea-8fff-b3af29f88e07.png)
- Single Service:
![image](https://user-images.githubusercontent.com/61964176/82341199-6392fe80-99f0-11ea-882a-455b8e6968a0.png)
- Mobile View:
![image](https://user-images.githubusercontent.com/61964176/82341225-6d1c6680-99f0-11ea-9ff0-cc602fc971f4.png)
- The deactivated function also works fine
