### ISSUE TITLE
Add 'Daily Update' Entity attached to Organizations

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#963]
Create a new Entity 'Daily Update' that can attach to an organziation.

The would be a free text value. It will also need a Created datetime as well as a column for 'expiry' datetime

**Comment by abaranowska1** [comment]
@jkondrat During testing, I found a few minor issues:
1. Could you check which Organizations should display in the dropdown list - I see only a few and I'm not sure if it is correct. 
2. Please change "Create or edit a DailyUpdate" to "Create or edit a Daily Update" in the title ( space is missing)
3. I guess that Expiry placeholder should display only mm/dd/yyyy, without time section 
4. The expiry date is not saved after click Save button, it is also empty after click on Edit button
5. In my opinion this "Showing 1 - 1 of 1 items." is unnecessary
![image](https://user-images.githubusercontent.com/61964176/81931834-fdbb0700-95ea-11ea-93ac-af194390388b.png)
![image](https://user-images.githubusercontent.com/61964176/81931843-027fbb00-95eb-11ea-88c0-8b814085989f.png)

**Comment by jkondrat** [comment]
@abaranowska1 
1. Done, showing all organizations. 
2. Done
3. The expiry is a datetime so it should show both sections. It will be automatically populated once a new daily update is added through provider's edit record form, no need for convenience here
4. It's only saved if both date and time are present

**Comment by abaranowska1** [comment]
**Tested with success** 

- New Entity - 'Daily Updated' was added 
- After a daily meeting, we decided that only Service Provider's  Organizations should be displayed in Organization dropdown list  
- Title is fixed
- All dates are saved
- All updates from the Service Provider Hompage are saved in new entity

![image](https://user-images.githubusercontent.com/61964176/82441932-06a25180-9a9f-11ea-85ab-a6ee688ba565.png)
![image](https://user-images.githubusercontent.com/61964176/82441941-0a35d880-9a9f-11ea-9cef-07d11adc85bc.png)
