### ISSUE TITLE
UI issue with displaying checkboxes on filtering feature for Shelters view

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#966]
On Shelters view for sacramento users, checkboxes on filtering feature are displayed not even, especially "Only show beds currently available" one. It's more visible after changing size of the browser.

**Reproduction**
- Open ServiceNet app
- Log in as a sacramento user
- Click "Filter" button

**Expected result**
- Filtering options are displayed in a similar way

**Actual result**
- "Only show beds currently available" checkbox is placed in a different way

**Attachments**
- Overview of filtering feature

![Screenshot from 2020-05-06 09-29-13](https://user-images.githubusercontent.com/51324797/81152353-29524780-8f82-11ea-9460-1a35fe23f2c9.png)

**Verified on**
- Chrome v80.0.3987.149
- Firefox v76.0

**Acceptance criteria**
- Checkboxes on filtering feature are displayed in a similar way

**Comment by abaranowska1** [comment]
**Tested with success**
**Verified cases:**
- Checkboxes on filtering feature are displayed in a similar way
![image](https://user-images.githubusercontent.com/61964176/82996545-68197180-a005-11ea-872d-01f1ea31bb89.png)
![image](https://user-images.githubusercontent.com/61964176/82996556-6b146200-a005-11ea-958f-c28f8231249c.png)
