### ISSUE TITLE
UI issue with removing record dialog

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#969]
After clicking "Yes, remove this record" on multi/all record view, confirming dialog appears. Hovering over "Yes, remove this" causes skipping the dialog.

**Reproduction**
- Open ServiceNet app and log in
- Open record view for Organization with matches
- Open multi/all record view
- Click "Yes, remove this record" button below chosen Organization
- Hover over "Yes, remove this" button on dialog

**Expected result**
- The dialog is still

**Actual result**
- The dialog skips

**Acceptance criteria**
- The dialog is still while hovering over it

**Attachment**

![Peek 2020-05-06 11-48](https://user-images.githubusercontent.com/51324797/81167213-2745b400-8f95-11ea-9ece-eb637480b20d.gif)

**Comment by kdondziak** [comment]
QA note: These changes have impact on all buttons across the app

**Comment by abaranowska1** [comment]
@kdondziak I found some places with button issues : 
![buttons10](https://user-images.githubusercontent.com/61964176/83648807-ca9ae080-a5b6-11ea-952a-ba526752ddca.gif)
![buttons9](https://user-images.githubusercontent.com/61964176/83648813-cb337700-a5b6-11ea-95a1-73bbedc8a394.gif)
![buttons8](https://user-images.githubusercontent.com/61964176/83648818-cc64a400-a5b6-11ea-9335-b8eee005ee30.gif)
![buttons7](https://user-images.githubusercontent.com/61964176/83648820-cc64a400-a5b6-11ea-8ec2-418016cc900b.gif)
![buttons6](https://user-images.githubusercontent.com/61964176/83648823-ccfd3a80-a5b6-11ea-8748-afc89335e125.gif)
![buttons4](https://user-images.githubusercontent.com/61964176/83648827-cd95d100-a5b6-11ea-8a40-06fcfd8ad68d.gif)
![buttons3](https://user-images.githubusercontent.com/61964176/83648830-ce2e6780-a5b6-11ea-98be-8eda018d48da.gif)
![buttons2](https://user-images.githubusercontent.com/61964176/83648833-cec6fe00-a5b6-11ea-8267-b452419a7966.gif)
![buttons](https://user-images.githubusercontent.com/61964176/83648834-cf5f9480-a5b6-11ea-8507-8f9172190f8e.gif)
![buttons5](https://user-images.githubusercontent.com/61964176/83648837-cff82b00-a5b6-11ea-911e-30e06f43ae80.gif)

**Comment by abaranowska1** [comment]
**Tested with success**
I checked all places with buttons that I listed above and now after fix buttons don't "jump"
Example : 
![Peek 2020-06-05 13-35](https://user-images.githubusercontent.com/61964176/83872028-7e27e000-a731-11ea-89fb-2d641fd9d5c8.gif)
![Peek 2020-06-05 13-33](https://user-images.githubusercontent.com/61964176/83872032-7ff1a380-a731-11ea-8578-1fdb69ef88ca.gif)
