### ISSUE TITLE
Tags, Languages and Defined Coverage Areas stays after creating a new Shelter

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#973]
Tags, Languages and Defined Coverage Areas data stays after creating a new Shelter.
![Peek 2020-05-06 16-35](https://user-images.githubusercontent.com/61964176/81190770-879a1d00-8fb8-11ea-94a8-c608f93e303d.gif)

**Steps:**

1. Log in as Admin
2. Go to Entities and click Create a New Shelter
3. Fill all fields ( Tags, Languages and Defined Coverage Areas too) and Save
4. Click Create a New Shelter once again 

**Actual result:** 
Previously picked Tags, Languages and Defined Coverage Areas are already picked

**Expected result:**
All fields should be clear during creation mode

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on staging env

**Verified cases**
- creating a new shelter
- creating another shelter with looking up mentioned fields

**Summary**
Values provided for the previous shelter are not available for the next shelter.

**Attachment**
![sn 973](https://user-images.githubusercontent.com/51324797/83118842-2f45cf00-a0cf-11ea-87ad-2f56bc4d574b.gif)
