### ISSUE TITLE
Make data entry page responsive and integrate it into the homepage

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#974]
Once the homepage is added, we can reuse its styles to make data entry responsive and add missing images (background, headers). We will also need to integrate it into the main view

The mockups can be found here: https://github.com/benetech/ServiceNet/issues/954

**Comment by jkondrat** [comment]
Hi @johnhbenetech : where can I get the background and heading images from?

**Comment by johnhbenetech** [comment]
@jkondrat sent on slack

**Comment by bognasoldev89** [comment]
This issue is tested in the scope of #954 and will be visited again after #954 gets back to QA column.

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified in the scope of #954 issue.

**Summary**
The data entry page is responsive and integrated into the homepage. It was open on different resolutions and every element was presented as expected.
