### ISSUE TITLE
"Cannot read property 'length' of null" pop-up message is thrown after reset filters on Sacramento homepage

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#976]
"Cannot read property 'length' of null" pop-up message is thrown after reset filters on Sacramento homepage

![image](https://user-images.githubusercontent.com/61964176/81273616-6df7e480-904f-11ea-96f5-619bd810d679.png)

![Peek 2020-05-07 10-40](https://user-images.githubusercontent.com/61964176/81273622-705a3e80-904f-11ea-8b71-7d61317b3f6e.gif)

**Steps:**

1. Log in as Sacramento User
2. Click the Filter button and add some filter 
3. Click Apply
4. Click Reset button
5. Click Reset button once again
6. Click Reset button once again

**Actual result:** 
"Cannot read property 'length' of null" pop-up message is thrown 

**Expected result:**
Filters should reset properly after click Reset button 

The issue occurs also on Chrome v81.0.4044.92 and Mozilla v75.0 browser

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on staging env

**Verified cases**
- Reseting filters as a sacramentouser

**Summary**
The issue doesn't occur anymore.

**Attachment**
![976](https://user-images.githubusercontent.com/51324797/81555997-dd404200-9389-11ea-8e36-104228f39ca6.gif)
