### ISSUE TITLE
Provider homepage doesn't load after changing provider accounts

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#982]
Provider homepage is not fully loaded after changing accounts between providers.

**Reproduction**
- Log in as a 1. provider
- Log out
- Log in as a 2. provider

**Expected result**
- Provider homepage is fully loaded

**Actual result**
- Not all of the homepage elements are loaded, user has to refresh page to gain a full access

**Attachment**
![982 bug](https://user-images.githubusercontent.com/51324797/81657037-d839cc00-9437-11ea-9b86-d999a0babe10.png)

**Comment by kdondziak** [comment]
@bognasoldev89 Can you confirm that issue is still there since https://github.com/benetech/ServiceNet/issues/1000 is solved?

**Comment by bognasoldev89** [comment]
@kdondziak I confirm that this issue doesn't occur anymore. I tried logging in and out numerous times to different provider accounts and always got full provider view.
